import type { ProjectModule } from "../../contracts/project-module";

const kittyRun: ProjectModule = {
  id: "kitty-run",
  title: "Cat Runner",
  tag: "game",
  eyebrow: "A candy-goth endless runner",
  description:
    "A candy-goth endless runner with a bullet-time dash, a ghostly wisp of your best run racing beside you, and a moonlit plum world where every wish glows. Run with vesper — the sweetest little thief in the dark.",
  technologies: [
    "React Three Fiber",
    "Three.js",
    "TypeScript",
    "Procedural vector art",
    "WebAudio",
    "Deterministic simulation",
  ],
  status: "available",
  accent: "pink",
  presentation: {
    className: "presentation-kitty-run",
    motion: "terrain",
    centerLabel: "",
    centerMark: "kitty",
    note: "Moonlit circuit",
    motionLabel: "the night rolls by",
    instruction: "Jump with Space, dash with Shift; Esc slips you back here.",
    parts: [
      {
        id: "hills",
        label: "Parallax hills",
        className: "presentation-part-terrain",
        anchorX: -18,
        anchorY: -8,
        mark: "contours",
        scatterX: -84,
        scatterY: -44,
        scatterZ: 76,
        baseZ: 14,
        rotation: -5,
      },
      {
        id: "combo",
        label: "Heart combo",
        className: "presentation-part-pin",
        anchorX: 34,
        anchorY: 26,
        mark: "pin",
        scatterX: 80,
        scatterY: -28,
        scatterZ: 54,
        baseZ: 26,
        rotation: 6,
      },
      {
        id: "dash",
        label: "Dash trail",
        className: "presentation-part-branches",
        anchorX: 78,
        anchorY: -34,
        mark: "branches",
        scatterX: 62,
        scatterY: 80,
        scatterZ: 92,
        baseZ: 44,
        rotation: 4,
      },
      {
        id: "rig",
        label: "Vector rig",
        className: "presentation-part-nodes",
        anchorX: -78,
        anchorY: 42,
        mark: "nodes",
        scatterX: -102,
        scatterY: 70,
        scatterZ: 64,
        baseZ: 32,
        rotation: -9,
      },
    ],
  },
  loadPage: () => import("./web/KittyRunPage"),
};

export default kittyRun;
