import type { ProjectModule } from "../../contracts/project-module";

const planckToNow: ProjectModule = {
  id: "planck-to-now",
  title: "Planck to Now",
  tag: "sim",
  eyebrow: "A log-time cosmology simulation",
  description: "Watch 13.8 billion years unfold in a GPU-accelerated WebGL simulation, from the Planck epoch to the present day.",
  technologies: ["TypeScript", "Three.js", "WebGL"],
  status: "available",
  accent: "amber",
  links: [
    {
      label: "GitHub repository",
      href: "https://github.com/vasyapym/vasyapym.github.io/tree/main/portfolio/projects/planck-to-now",
      external: true,
    },
    {
      label: "Open standalone view",
      href: "/planck-to-now/",
    },
  ],
  presentation: {
    className: "presentation-planck-to-now",
    motion: "network",
    centerLabel: "B / B",
    centerMark: "generic",
    note: "Cosmic timeline",
    motionLabel: "the universe expands",
    instruction: "Follow the timeline from the first hot particles to the cosmic web.",
    parts: [
      {
        id: "cosmic-field",
        label: "Cosmic field",
        className: "presentation-part-cosmic-field",
        anchorX: -18,
        anchorY: -6,
        mark: "contours",
        scatterX: -82,
        scatterY: -42,
        scatterZ: 76,
        baseZ: 14,
        rotation: -4,
      },
      {
        id: "timeline",
        label: "Log-time timeline",
        className: "presentation-part-timeline",
        anchorX: 34,
        anchorY: 28,
        mark: "route",
        scatterX: 82,
        scatterY: -28,
        scatterZ: 54,
        baseZ: 30,
        rotation: 6,
      },
      {
        id: "present-day",
        label: "Present day",
        className: "presentation-part-present-day",
        anchorX: 84,
        anchorY: -34,
        mark: "type",
        markLabel: "now",
        scatterX: 66,
        scatterY: 76,
        scatterZ: 94,
        baseZ: 48,
        rotation: 5,
      },
      {
        id: "first-light",
        label: "First light",
        className: "presentation-part-first-light",
        anchorX: -84,
        anchorY: 44,
        mark: "pin",
        scatterX: -104,
        scatterY: 70,
        scatterZ: 66,
        baseZ: 36,
        rotation: -8,
      },
    ],
  },
  loadPage: () => import("./web/PlanckToNowPage"),
};

export default planckToNow;
