import type { ProjectModule } from "../../contracts/project-module";

const explosionLuna: ProjectModule = {
  id: "explosion",
  title: "Explosion",
  tag: "physics",
  eyebrow: "Real-time demolition lab",
  description:
    "Shell a whole voxel monument district and watch a Rust → WebAssembly core reroute its load paths in real time — carve the supports away and everything above comes down, in x-ray and bullet time.",
  technologies: ["Rust → WebAssembly", "three.js instancing", "structural solvers", "WebAudio"],
  status: "available",
  accent: "red",
  presentation: {
    className: "presentation-explosion-luna",
    motion: "stack",
    centerLabel: "L / X",
    centerMark: "blast",
    note: "demolition lab",
    motionLabel: "the monument falls",
    instruction: "Open the demolition lab and shoot the monument until it falls.",
    parts: [
      {
        id: "luna-shell",
        label: "Shell",
        className: "presentation-part-luna-shell",
        anchorX: -50,
        anchorY: -18,
        mark: "contours",
        scatterX: -92,
        scatterY: -48,
        scatterZ: 80,
        baseZ: 18,
        rotation: -8,
      },
      {
        id: "luna-shards",
        label: "Shard constellation",
        className: "presentation-part-luna-shards",
        anchorX: 52,
        anchorY: -28,
        mark: "nodes",
        scatterX: 94,
        scatterY: -42,
        scatterZ: 62,
        baseZ: 30,
        rotation: 7,
      },
      {
        id: "luna-ring",
        label: "Impact ring",
        className: "presentation-part-luna-ring",
        anchorX: 18,
        anchorY: 34,
        mark: "route",
        scatterX: 34,
        scatterY: 86,
        scatterZ: 94,
        baseZ: 42,
        rotation: -5,
      },
      {
        id: "luna-core",
        label: "Core",
        className: "presentation-part-luna-core",
        anchorX: -82,
        anchorY: 42,
        mark: "type",
        markLabel: "LX",
        scatterX: -116,
        scatterY: 74,
        scatterZ: 70,
        baseZ: 38,
        rotation: 12,
      },
    ],
  },
  loadPage: () => import("./web/ExplosionLunaPage"),
};

export default explosionLuna;
