import type { ProjectModule } from "../../contracts/project-module";

const practiceMap: ProjectModule = {
  id: "practice-map",
  title: "Practice Map",
  eyebrow: "A working map for technical practice",
  description: "Keep concepts, small exercises, and useful things to revisit in one quiet place.",
  technologies: ["React", "TypeScript", "Local state"],
  status: "available",
  accent: "blue",
  presentation: {
    className: "presentation-practice-map",
    motion: "terrain",
    centerLabel: "P / M",
    centerMark: "compass",
    note: "Practice route",
    motionLabel: "the route unfolds",
    instruction: "Follow a route, mark a place, and leave a note for the next pass.",
    parts: [
      {
        id: "terrain",
        label: "Practice terrain",
        className: "presentation-part-terrain",
        anchorX: -18,
        anchorY: -8,
        mark: "contours",
        scatterX: -82,
        scatterY: -42,
        scatterZ: 78,
        baseZ: 12,
        rotation: -6,
      },
      {
        id: "route",
        label: "Practice route",
        className: "presentation-part-route",
        anchorX: 32,
        anchorY: 22,
        mark: "route",
        scatterX: 82,
        scatterY: -30,
        scatterZ: 52,
        baseZ: 28,
        rotation: 7,
      },
      {
        id: "waypoint",
        label: "Next waypoint",
        className: "presentation-part-pin",
        anchorX: 84,
        anchorY: -34,
        mark: "pin",
        scatterX: 64,
        scatterY: 78,
        scatterZ: 94,
        baseZ: 48,
        rotation: 4,
      },
      {
        id: "compass",
        label: "Direction dial",
        className: "presentation-part-compass",
        anchorX: -82,
        anchorY: 46,
        mark: "compass",
        scatterX: -104,
        scatterY: 68,
        scatterZ: 66,
        baseZ: 34,
        rotation: -10,
      },
    ],
  },
  loadPage: () => import("./web/PracticeMapPage"),
};

export default practiceMap;
