import type { LessonSection } from "../curriculum";

export const sections: readonly LessonSection[] = [
  {
    heading: "Part I: Two Definitions",
    blocks: [
      {"kind":"p","text":"**AI-proof** is a slightly dishonest phrase, so let's fix it before we start. Almost no skill is permanently immune to automation. The frontier of what machines can do moves every few months, and anyone who tells you \"AI will never do X\" is making a bet, not stating a fact. A better term is **AI-resilient**: a skill whose value holds up, or even *rises*, as AI gets better. Economists call this the difference between a **substitute** and a **complement**. A substitute competes with the machine: the better the machine gets, the less you're worth. A complement works with the machine: the better the machine gets, the more you're worth, the way cheap spreadsheets made good financial analysts more valuable rather than less."},
      {"kind":"p","text":"**Recursive** is the more interesting word. In computer science, a recursive function calls itself. A more useful image here is the **bootstrapping compiler**: a compiler written in its own language, which can compile better versions of itself. Each version builds a stronger successor. A recursive skill works the same way. Practicing it improves your ability to practice it, and often your ability to learn *other* skills too. Its output feeds back into its input."},
      {"kind":"p","text":"Put these together and you get the subject of this lesson: **skills that compound, and that become more valuable as AI becomes more capable.** These are the highest-leverage things a person can invest in right now, because they pay interest on themselves, and the interest rate is going up."},
    ],
  },
  {
    heading: "Part II: Why Recursion Matters More Than Content",
    blocks: [
      {"kind":"p","text":"Consider two kinds of knowledge. The first is **content**: the syntax of a programming language, the rules of tax law, the steps of a lab protocol. Content is valuable, but it is exactly what large language models absorb best, because it exists in text, in bulk, on the internet. Content also *depreciates*. Frameworks change, laws are amended, protocols are replaced."},
      {"kind":"p","text":"The second kind is **process**: how you figure things out, how you decide what matters, how you tell good work from bad. Process is harder to write down, harder to train a model on, and it doesn't expire when the content changes. A person with strong process can pick up new content quickly. A person with only content is stranded when it changes."},
      {"kind":"p","text":"Recursive skills are process skills with a feedback loop. They behave like **compound interest** rather than a salary. A salary pays you the same amount each month. Compound interest pays you on what you've already earned. Over one year the difference is small. Over twenty years it is enormous. This is why the most important career decisions are rarely about *what* to learn next. They're about which *loops* to install."},
    ],
  },
  {
    heading: "Part III: The Core Recursive Skills",
    blocks: [
      {"kind":"p","text":"**1. Learning How to Learn (Meta-Learning)**"},
      {"kind":"p","text":"This is the root loop, the one all the others run on. Meta-learning means understanding how your own learning works: which methods actually build lasting knowledge (spaced repetition, retrieval practice, interleaving, building things) versus which ones just *feel* productive (rereading, highlighting, passively watching tutorials)."},
      {"kind":"p","text":"The recursion is direct. Every time you learn something, you can also learn something about *how you learned it*: what worked, where you got stuck, what you'd do differently. That makes the next thing faster, which gives you more cycles, which teaches you more about learning. In machine learning terms, you aren't just training a model. You're tuning the optimizer."},
      {"kind":"p","text":"In an AI-rich world this is critical, because the half-life of specific skills is shrinking. The person who can get competent in a new domain in three weeks instead of six months has a durable edge over any fixed body of knowledge."},
      {"kind":"p","text":"**2. Problem Formulation**"},
      {"kind":"p","text":"Charles Kettering, the engineer who ran research at General Motors, said that \"a problem well stated is a problem half solved.\" AI has made this truer than he could have imagined. Modern AI systems are extraordinary at solving well-specified problems. They are much weaker at figuring out *which* problem is worth solving, what the real constraints are, and what the person asking actually needs, which often differs from what they asked for."},
      {"kind":"p","text":"Problem formulation is the skill of turning a vague situation (\"sales are down,\" \"the code feels slow,\" \"my team seems unhappy\") into a precise question that can be investigated. It involves separating symptoms from causes, spotting hidden assumptions, and choosing the right level of abstraction."},
      {"kind":"p","text":"The recursion: every well-framed problem you solve gives you a template, a pattern you can recognize in future situations. Over time you build a library of problem *shapes*. Experienced engineers, doctors, and investors don't think faster than novices. They recognize the shape of a problem sooner, so they search a much smaller space."},
      {"kind":"p","text":"This is also the skill that sets the ceiling on how useful AI is to you. Your prompts can only be as good as your understanding of the problem."},
      {"kind":"p","text":"**3. Judgment, Verification, and Taste**"},
      {"kind":"p","text":"Here is a useful asymmetry borrowed loosely from complexity theory: for many problems, **checking a solution is much easier than generating one**. Verifying a proof is easier than discovering it, and spotting a bad paragraph is easier than writing a great one. AI has flipped the economics of generation. Drafts, code, designs, and analyses are now nearly free. What stays scarce is the ability to tell which outputs are correct, which are subtly wrong, and which are merely plausible."},
      {"kind":"p","text":"Geeks will recognize this as the architecture of a **GAN** (generative adversarial network). One network generates; another discriminates. Increasingly, AI is the generator and *you* are the discriminator. The quality of the whole system is capped by the quality of the discriminator."},
      {"kind":"p","text":"Judgment is recursive because each evaluation, especially each one you get *wrong* and then learn from, sharpens the next. **Taste** is judgment that has been trained so thoroughly it runs fast and mostly below conscious awareness: the senior developer who glances at a pull request and says \"something's off here\" before she can say what."},
      {"kind":"p","text":"A warning: taste can't be built without **ground truth**. You need feedback from reality (the code ran or crashed, the product sold or didn't, the prediction came true or failed). Judgment trained only on opinions drifts. Judgment trained on outcomes compounds."},
      {"kind":"p","text":"**4. Calibration**"},
      {"kind":"p","text":"Calibration means your confidence matches your accuracy. If you say you're 90% sure about things, you should be right about 90% of the time. Most people are badly overconfident, and the problem gets worse in an age of fluent machines, because AI outputs *sound* equally confident whether they're right or wrong."},
      {"kind":"p","text":"Calibration is a skill you can measure and train. Forecasters track it with tools like the **Brier score**, which grades probabilistic predictions against outcomes. The practice is simple: make explicit predictions with probabilities, write them down, check them later, and adjust."},
      {"kind":"p","text":"The recursion is that calibration applies to itself. Once you know you tend to be overconfident about timelines but well calibrated about technical feasibility, you can correct for that bias, which improves every future estimate. You're building an accurate model of your own mind's error patterns. That self-model can't be outsourced, because no one else has access to the data."},
      {"kind":"p","text":"**5. Model-Building and Abstraction**"},
      {"kind":"p","text":"A mental model is a compressed representation of how something works: supply and demand, feedback loops, the CAP theorem, natural selection, opportunity cost. Expertise is largely the possession of good models and the sense to know which one applies."},
      {"kind":"p","text":"The deep insight here comes from cognitive science's concept of **chunking**. Experts don't hold more items in working memory than novices; they hold *bigger* items. A chess master sees \"a kingside attack structure\" where a beginner sees twelve individual pieces. Each chunk you build becomes a single building block for larger chunks. That is recursion in its purest form: abstractions built from abstractions, like functions composed of functions."},
      {"kind":"p","text":"This matters for AI resilience because models let you *reason across domains*. AI can retrieve a model if you ask for it. Knowing that a supply-chain problem is secretly a queueing theory problem, or that an organizational conflict has the structure of a prisoner's dilemma, requires seeing the connection first. Cross-domain synthesis remains one of the places human insight adds the most value."},
      {"kind":"p","text":"**6. Explanation and Teaching**"},
      {"kind":"p","text":"Richard Feynman's test for understanding was whether you could explain an idea simply. The act of explaining exposes gaps you didn't know you had. You reach for the next step in the argument and find nothing there."},
      {"kind":"p","text":"This loop is doubly recursive. Teaching improves your understanding, which improves your teaching. Clear explanation also builds **reputation and trust**, which bring you better problems, collaborators, and opportunities, and those in turn give you more to understand and explain."},
      {"kind":"p","text":"In an AI world, explanation takes on a new role. Organizations are drowning in machine-generated content. The person who can translate complexity into clarity, who can stand in a room and make a decision *legible* to the people who have to live with it, is doing something a generated summary cannot fully replace, because the explanation carries their credibility with it."},
      {"kind":"p","text":"**7. Accountability, Trust, and Relationships**"},
      {"kind":"p","text":"A 1979 IBM training slide put it bluntly: *\"A computer can never be held accountable, therefore a computer must never make a management decision.\"* Whatever you think of the second half, the first half points at something structural. Societies run on **someone being responsible**. Contracts, medical decisions, engineering sign-offs, and leadership calls all need a person who has something at stake and can be held to account."},
      {"kind":"p","text":"Trust is the most obviously recursive asset there is. Reliability earns trust; trust earns responsibility; responsibility, handled well, earns more trust. It compounds slowly and can collapse quickly, which is exactly why it's valuable. It's also deeply *local*. It lives in specific relationships with specific people, and it can't be downloaded."},
      {"kind":"p","text":"**8. Agency and Problem Selection**"},
      {"kind":"p","text":"The mathematician Richard Hamming, in his famous talk *You and Your Research*, asked colleagues at Bell Labs a pointed question: \"What are the most important problems in your field, and why aren't you working on them?\" His observation was that the difference between good and great careers often came down less to ability than to *choosing what to work on*."},
      {"kind":"p","text":"As execution gets cheaper, direction becomes the bottleneck. AI can multiply your output tenfold, but multiplying effort aimed at the wrong target just gets you lost faster. **Agency** is the disposition to decide what should exist and then pursue it, rather than waiting for a task to be assigned. It's recursive because every self-directed project teaches you more about what you're good at, what the world rewards, and where the unexplored opportunities are. That improves your next choice of project."},
    ],
  },
  {
    heading: "Part IV: A Three-Question Test",
    blocks: [
      {"kind":"p","text":"When evaluating any skill, ask:"},
      {"kind":"list","ordered":true,"items":["**Does it compound?** Does practicing it make future practice more effective, or make other skills easier to learn? (Recursion test.)","**Does AI make it more valuable?** When AI gets better, does this skill become a bottleneck or become redundant? (Complement test.)","**Is it anchored in something AI lacks?** Stakes, accountability, embodied experience, local context, relationships, or personal preferences about what *should* happen? (Anchor test.)"]},
      {"kind":"p","text":"A skill that passes all three is a strong investment. Memorizing API syntax fails all three. Debugging intuition, built from years of tracing real failures, passes all three."},
    ],
  },
  {
    heading: "Part V: The Trap of Outsourced Recursion",
    blocks: [
      {"kind":"p","text":"Here is the subtle danger. AI can quietly *break* your recursive loops while appearing to help."},
      {"kind":"p","text":"If an AI writes all your code, you never develop debugging intuition. If it drafts all your arguments, you never develop the ability to structure thought. If it evaluates your options, your judgment never gets trained on outcomes. Researchers call this **cognitive offloading**, and while it's useful for routine work, applied to your core skills it amounts to paying someone to go to the gym for you. The work gets done, but you don't get stronger."},
      {"kind":"p","text":"The practical principle: **use AI to extend your loops, not to replace them.** Some concrete patterns:"},
      {"kind":"list","items":["**Attempt first, then compare.** Solve the problem yourself, *then* ask the AI. The gap between your answer and its answer is where learning happens.","**Use AI as an adversary.** Ask it to find the flaws in your reasoning, argue the opposite side, or generate test cases that break your code. This trains your discriminator.","**Demand explanations you can verify.** Don't accept outputs you couldn't check. If you can't evaluate it, you're not using a tool; you're trusting an oracle.","**Keep a prediction log.** Before asking AI or running an experiment, write down what you expect. Compare afterward. This builds calibration almost automatically.","**Teach what you learn.** Write a short explanation of anything important the AI helped you with. If you can't explain it, you haven't absorbed it."]},
    ],
  },
  {
    heading: "Part VI: The Big Picture",
    blocks: [
      {"kind":"p","text":"There's an idea from software engineering called the **Lindy effect**: the longer something has survived, the longer it's likely to keep surviving. Programming languages from the 1970s outlive frameworks from last year. The same applies to skills. Learning, framing problems, judging quality, knowing your own uncertainty, building models, explaining clearly, earning trust, and choosing direction have been valuable for as long as civilization has existed. They survived the printing press, industrialization, and the computer. They are likely to survive this transition too, not because machines can't touch them, but because each wave of automation has made them *more* central."},
      {"kind":"p","text":"The summary of this lesson fits in one sentence: **invest in the loops, not just the outputs.** Content is what AI can hand you. Loops are what let you get better at everything, including using AI. The first depreciates; the second compounds. In a world where generation is nearly free, the scarce resource is the mind that knows what to generate, how to judge it, and how to keep improving at both."},
      {"kind":"p","text":"**Exercise for this week:** Pick one recursive skill from Part III. Design a tiny daily loop for it that takes ten minutes or less and includes a feedback mechanism from reality: a prediction you check, a solution you compare, an explanation you test on someone else. Run it for seven days, then ask the meta-question: *what did I learn about how I learn this?*"},
    ],
  },
];;
