import type { LessonSection } from "../curriculum";

export const sections: readonly LessonSection[] = [
  {
    heading: "What \"cloud-native\" actually means",
    blocks: [
      {"kind":"p","text":"The phrase is abused so often that it is worth pinning down. A system is cloud-native not because it runs on someone else's computers but because it is *designed around the assumptions of the cloud*: that infrastructure is ephemeral and programmable, that failure is normal rather than exceptional, that capacity is elastic and metered, and that the unit of deployment is small and independently replaceable. The Cloud Native Computing Foundation (CNCF) formalizes this as systems that are containerized, dynamically orchestrated, and microservice-oriented, but the deeper intellectual shift is from treating servers as pets (named, nursed, irreplaceable) to treating them as cattle (numbered, interchangeable, culled without ceremony). Everything else in this vocabulary follows from that shift."},
      {"kind":"p","text":"A useful mental ladder is the service model spectrum. Infrastructure as a Service (IaaS) hands you virtual machines, disks, and networks and leaves the operating system upward to you. Platform as a Service (PaaS) takes the OS and runtime off your plate and asks only for code. Function as a Service (FaaS), or serverless, goes further and bills you per invocation with no persistent process at all. Software as a Service (SaaS) is the finished product. The cloud-native practitioner moves fluidly across this ladder, choosing the highest rung that still permits the control the problem demands, because each rung upward trades flexibility for reduced operational toil. The governing contract across all of them is the **shared responsibility model**: the provider secures the cloud (physical facilities, hypervisors, the managed service's internals) while you secure what is *in* the cloud (your data, identities, configuration, and code). Most breaches in cloud environments arise from misunderstanding where that line sits, not from provider failure."},
    ],
  },
  {
    heading: "Physical geography and the failure domains it defines",
    blocks: [
      {"kind":"p","text":"All three hyperscalers organize the planet into **regions**, geographically separate clusters of data centers, each subdivided into **availability zones** (AZs), which are physically isolated facilities with independent power, cooling, and networking but connected by low-latency links. AWS calls them regions and Availability Zones, Google Cloud calls them regions and zones, and Azure calls them regions and Availability Zones, with Azure additionally pairing regions for disaster recovery. The architectural significance is that an AZ is the smallest blast radius you should design around: a well-built system spreads replicas across at least three zones so that losing one does not reduce you below quorum. A **multi-region** architecture extends the same principle to continental failures, at the cost of grappling with the speed of light, which imposes a floor of tens of milliseconds between distant regions and therefore forces you to confront consistency trade-offs that single-region designs can ignore."},
      {"kind":"p","text":"Beyond regions, each provider operates **edge locations** or points of presence, used by content delivery networks (CloudFront, Cloud CDN, Azure Front Door) and increasingly by edge compute (Lambda@Edge, Cloudflare-style workers in Google's and Azure's ecosystems) to execute logic within a few milliseconds of the user. The term **blast radius** itself is central vocabulary: it describes the scope of impact when a component fails or a change goes wrong, and reducing it is the recurring motive behind zones, cells, canaries, and most of the other patterns below."},
    ],
  },
  {
    heading: "Compute: the evolving unit of work",
    blocks: [
      {"kind":"p","text":"The foundational compute abstraction is the **virtual machine** (EC2, Compute Engine, Azure Virtual Machines). VMs come in families optimized for general purpose, compute, memory, storage, or accelerators, and they introduce the pricing vocabulary of **on-demand**, **reserved** or **committed-use** discounts, and **spot** or **preemptible** instances, the latter being spare capacity sold at steep discount with the caveat that the provider can reclaim it on short notice. Spot capacity is a cornerstone of cost-efficient cloud-native design precisely because cloud-native workloads are supposed to tolerate instance loss gracefully."},
    ],
  },
  {
    heading: "Containers",
    blocks: [
      {"kind":"p","text":"**Containers** package an application with its dependencies into an immutable image that runs identically on any host with a compatible kernel. The image is built in layers, stored in a **registry** (ECR, Artifact Registry, Azure Container Registry), and instantiated as a process isolated by Linux namespaces and cgroups rather than by a full guest operating system, which is why containers start in milliseconds where VMs take tens of seconds. The container alone solves packaging; it does not solve scheduling, networking, scaling, or self-healing across a fleet. That is the job of an **orchestrator**, and the industry has converged overwhelmingly on **Kubernetes**."},
      {"kind":"p","text":"Kubernetes deserves its own vocabulary because it has become the lingua franca of cloud-native infrastructure. A **cluster** consists of a control plane and worker **nodes**. The smallest schedulable unit is the **pod**, one or more tightly coupled containers sharing a network namespace. Pods are rarely created directly; instead you declare a **Deployment** (for stateless replicas), a **StatefulSet** (for ordered, identity-preserving workloads like databases), a **DaemonSet** (one pod per node, for agents), or a **Job**. A **Service** provides a stable virtual IP and DNS name in front of an ephemeral set of pods, and an **Ingress** or the newer **Gateway API** routes external HTTP traffic in. Configuration is injected through **ConfigMaps** and **Secrets**, persistent storage through **PersistentVolumeClaims** backed by cloud disks via the Container Storage Interface (CSI), and networking is pluggable through the Container Network Interface (CNI). The deeper idea underneath all of this is the **reconciliation loop**: you declare desired state in YAML, and controllers continuously compare actual state to desired state and act to close the gap. The **Operator pattern** extends this by letting you write custom controllers over **Custom Resource Definitions** (CRDs), effectively teaching Kubernetes to manage a Postgres cluster or a Kafka deployment the same way it manages pods. Managed offerings (EKS, GKE, AKS) run the control plane for you; GKE Autopilot, EKS Fargate, and AKS virtual nodes go further and abstract away the nodes themselves."},
    ],
  },
  {
    heading: "Serverless compute",
    blocks: [
      {"kind":"p","text":"**Serverless compute** inverts the operational model entirely. With AWS Lambda, Google Cloud Functions and Cloud Run, and Azure Functions, you supply code or a container, the platform provisions execution environments on demand in response to events, scales to zero when idle, and bills per request and per unit of memory-time. The characteristic trade-offs are **cold starts** (the latency of initializing a fresh environment, mitigated by provisioned concurrency or minimum instances), execution time limits, and a strong architectural push toward statelessness and event-driven decomposition. Cloud Run and Azure Container Apps occupy a sweet spot sometimes called *serverless containers*, where you get the request-based scaling of FaaS with the packaging freedom of containers, and under the hood both draw on **Knative**, the Kubernetes-based serverless layer."},
    ],
  },
  {
    heading: "Networking: the software-defined fabric",
    blocks: [
      {"kind":"p","text":"Every cloud-native system lives inside a **virtual private cloud** (VPC on AWS and GCP, Virtual Network or VNet on Azure), a logically isolated software-defined network with its own private IP address space carved into **subnets**. The classic design places internet-facing load balancers in public subnets and everything else in private subnets that reach the internet only through a **NAT gateway**. **Security groups** (AWS, Azure's Network Security Groups, GCP firewall rules) act as stateful virtual firewalls at the instance or subnet level. Connecting VPCs to each other and to on-premises networks introduces **peering**, **transit gateways** or hub-and-spoke topologies, **VPN** tunnels, and dedicated circuits (Direct Connect, Cloud Interconnect, ExpressRoute). **Private endpoints** or **PrivateLink** allow you to consume managed services over the private network without traversing the public internet, which is now considered table stakes for regulated workloads."},
    ],
  },
  {
    heading: "Load balancers",
    blocks: [
      {"kind":"p","text":"**Load balancers** distribute traffic and come in layers: Layer 4 (TCP/UDP) balancers are fast and protocol-agnostic, while Layer 7 (HTTP) balancers can route on path, header, or hostname and terminate TLS. AWS offers the Network Load Balancer and Application Load Balancer, GCP offers a globally anycast load balancer that is unusually powerful because a single IP serves users worldwide from the nearest region, and Azure offers Load Balancer, Application Gateway, and Front Door. An **API gateway** sits above these for API-specific concerns: authentication, rate limiting, request transformation, and versioning."},
      {"kind":"p","text":"Within a microservice architecture, east-west traffic (service to service) often dwarfs north-south traffic (client to service), and that is where the **service mesh** enters. Istio, Linkerd, and the managed variants (AWS App Mesh, Anthos Service Mesh, Open Service Mesh) inject a **sidecar proxy** (typically Envoy) beside each pod, transparently handling mutual TLS, retries, timeouts, circuit breaking, traffic splitting, and telemetry without changing application code. The newer **ambient** or sidecar-less meshes and **eBPF**-based networking (Cilium) push this logic into the kernel to reduce the resource and latency overhead that sidecars impose. Service meshes are powerful but heavy; the honest advice is to adopt one when you have a concrete problem it solves, not as a default."},
    ],
  },
  {
    heading: "Storage and the three shapes of data at rest",
    blocks: [
      {"kind":"p","text":"Cloud storage divides into three fundamental types, each with a distinct consistency and access model. **Object storage** (S3, Cloud Storage, Azure Blob Storage) stores immutable blobs addressed by key in a flat namespace, offers effectively unlimited capacity and eleven-nines durability through erasure coding across zones, and is accessed over HTTP rather than mounted. It is the default home for backups, media, data lakes, and static sites, and its **storage classes** (standard, infrequent access, archive, deep archive) encode a cost-versus-retrieval-latency trade-off managed through **lifecycle policies**. **Block storage** (EBS, Persistent Disk, Azure Managed Disks) presents raw volumes that a single VM mounts as a disk, with IOPS and throughput as the key performance dimensions. **File storage** (EFS, Filestore, Azure Files) provides shared POSIX or SMB file systems mountable by many clients simultaneously. The cloud-native instinct is to minimize block and file storage, which bind state to specific machines, and to push state either into object storage or into managed databases."},
    ],
  },
  {
    heading: "Databases: managed, distributed, and purpose-built",
    blocks: [
      {"kind":"p","text":"The relational tier is dominated by managed services (RDS and Aurora, Cloud SQL and AlloyDB, Azure SQL and Database for PostgreSQL) that automate backups, patching, failover, and read replicas. Aurora and AlloyDB are architecturally notable because they decouple compute from a distributed, log-structured storage layer that replicates across zones, allowing failover in seconds and read scaling without traditional replication lag."},
      {"kind":"p","text":"The **NoSQL** family trades relational expressiveness for horizontal scalability. **Key-value and wide-column** stores such as DynamoDB, Bigtable, and Cosmos DB partition data by a **partition key** (also called a shard key) and deliver single-digit-millisecond latency at any scale, provided you design your access patterns around the key up front. The cardinal sin here is the **hot partition**, where skewed keys concentrate load on one shard. **Document** stores (DocumentDB, Firestore, Cosmos DB's Mongo API) store JSON-like records. **In-memory** stores (ElastiCache, Memorystore, Azure Cache for Redis) serve as caches and ephemeral state. **Graph**, **time-series**, and **search** engines (Neptune, Timestream, OpenSearch and their equivalents) round out the purpose-built catalog, and the architectural principle is **polyglot persistence**: each service owns its data and chooses the store that fits its access pattern rather than forcing everything into one database."},
      {"kind":"p","text":"The frontier is the **globally distributed, strongly consistent** database. Google Spanner pioneered the use of atomic clocks and GPS (the **TrueTime** API) to bound clock uncertainty and thereby provide externally consistent transactions across continents; Cosmos DB exposes five tunable consistency levels from strong to eventual; Aurora Global Database and DynamoDB Global Tables take different points in the same design space. To reason about these you need the **CAP theorem**, which states that under a network partition a system must choose between consistency and availability, and its refinement **PACELC**, which observes that even without partitions there is a trade-off between latency and consistency. You also need the vocabulary of **consensus** (Paxos, Raft), **quorum** reads and writes, **linearizability** versus **eventual consistency**, and **idempotency**, the property that lets you safely retry an operation, which turns out to be the single most important property in any distributed system that retries."},
    ],
  },
  {
    heading: "Messaging and event-driven architecture",
    blocks: [
      {"kind":"p","text":"Decoupling services in time is as important as decoupling them in space, and messaging infrastructure accomplishes this. A **queue** (SQS, Cloud Tasks, Azure Queue Storage or Service Bus queues) delivers each message to one consumer and smooths bursts into steady processing. A **publish-subscribe topic** (SNS, Pub/Sub, Azure Service Bus topics or Event Grid) fans a message out to many subscribers. A **log-based stream** (Kinesis, Pub/Sub in its ordered mode, Event Hubs, and managed Kafka on all three) retains an ordered, replayable record partitioned for parallel consumption, which enables stream processing and event sourcing. The essential vocabulary includes **at-least-once** versus **exactly-once** delivery semantics (the latter is really at-least-once plus idempotent consumers), **dead-letter queues** for poison messages, **backpressure**, **consumer groups**, and **ordering guarantees**, which in almost every system hold only within a partition."},
    ],
  },
  {
    heading: "Event-driven architecture",
    blocks: [
      {"kind":"p","text":"**Event-driven architecture** (EDA) builds whole systems around these primitives: services emit domain events describing facts that have happened, and other services react. **Event sourcing** stores the sequence of events as the system of record and derives current state by replaying them. **CQRS** (Command Query Responsibility Segregation) separates the write model from one or more read models optimized for queries, frequently fed by those same events. The **transactional outbox** pattern solves the dual-write problem of updating a database and publishing an event atomically, and **change data capture** (CDC, with Debezium as the archetype) turns database transaction logs into event streams. Distributed transactions across services are handled not with two-phase commit, which couples availability, but with the **saga pattern**, a sequence of local transactions with compensating actions for rollback, orchestrated either centrally (Step Functions, Workflows, Durable Functions, or Temporal) or through choreography."},
    ],
  },
  {
    heading: "Identity, security, and zero trust",
  },
  {
    heading: "Identity and Access Management",
    blocks: [
      {"kind":"p","text":"**Identity and Access Management** (IAM) is the control plane for everything. All three providers model it as principals (users, groups, roles or service accounts), policies that grant permissions on resources, and a resource hierarchy (AWS Organizations and accounts, GCP organizations, folders, and projects, Azure management groups, subscriptions, and resource groups) along which policies inherit. The guiding principle is **least privilege**, and the cloud-native implementation of it is **workload identity**: rather than embedding long-lived credentials in applications, a pod or function assumes a short-lived role (IAM Roles for Service Accounts, GKE Workload Identity, Azure Managed Identity) and receives temporary tokens automatically. Secrets that genuinely must exist live in a **secrets manager** (Secrets Manager, Secret Manager, Key Vault) and are encrypted by keys in a **key management service** (KMS, Cloud KMS, Key Vault keys), with **envelope encryption** meaning data is encrypted by a data key that is itself encrypted by a master key held in a hardware security module."},
    ],
  },
  {
    heading: "Zero trust",
    blocks: [
      {"kind":"p","text":"**Zero trust** replaces the perimeter model, where being inside the network implied trust, with continuous verification of every request based on identity, device, and context. In practice this means mutual TLS everywhere, identity-aware proxies (Google's BeyondCorp lineage), fine-grained authorization, and treating the internal network as hostile. Supporting vocabulary includes **policy as code** (OPA, Gatekeeper, Kyverno, Sentinel) for enforcing guardrails declaratively, **software supply chain security** (signed images via Sigstore, Software Bills of Materials, SLSA levels), **cloud security posture management** (Security Hub, Security Command Center, Defender for Cloud), and the **landing zone**, a pre-configured multi-account scaffold with networking, logging, and guardrails baked in, which is how mature organizations onboard new teams safely."},
    ],
  },
  {
    heading: "Observability: seeing inside the system",
    blocks: [
      {"kind":"p","text":"Monitoring tells you whether known failure modes are occurring; **observability** is the property of being able to ask arbitrary new questions about system behavior from the outside. Its three canonical signals are **metrics** (numeric time series, cheap and aggregable), **logs** (discrete structured events, rich and expensive), and **traces** (causal records of a request's path across services, built from spans with propagated context). **OpenTelemetry** has become the vendor-neutral standard for instrumenting and exporting all three, feeding into CloudWatch and X-Ray, Cloud Operations (formerly Stackdriver), Azure Monitor and Application Insights, or third parties like Datadog, Grafana, and Honeycomb. The site reliability engineering vocabulary layered on top matters enormously: **Service Level Indicators** (SLIs) are the measurements that matter to users, **Service Level Objectives** (SLOs) are targets for those indicators, and the **error budget**, the gap between the SLO and perfection, becomes the currency that governs how fast you may ship. **Cardinality** is the technical constraint underneath all this: high-cardinality dimensions like user ID make metrics explode in cost, which is why tracing and structured logging exist. Continuous profiling and **eBPF**-based auto-instrumentation represent the current edge."},
    ],
  },
  {
    heading: "Infrastructure as code, delivery, and GitOps",
    blocks: [
      {"kind":"p","text":"In a cloud-native system, infrastructure is defined in version-controlled, reviewable, reproducible code. **Declarative** tools (Terraform and OpenTofu, CloudFormation, Deployment Manager, Bicep and ARM templates) describe the desired end state and compute a plan to reach it; **imperative-flavored** general-purpose-language tools (CDK, Pulumi) generate that declarative state from TypeScript or Python. Key concepts include **state** (the record of what the tool believes exists), **drift** (divergence between declared and actual state, usually caused by manual console changes), **modules** for reuse, and **immutable infrastructure**, in which you never patch a running server but replace it with a new image, often baked in advance with tools like Packer."},
    ],
  },
  {
    heading: "Continuous integration",
    blocks: [
      {"kind":"p","text":"**Continuous integration** builds and tests every commit; **continuous delivery** makes every passing build deployable; **continuous deployment** actually ships it. Progressive delivery strategies limit blast radius: **blue-green** runs two full environments and flips traffic, **canary** sends a small percentage of traffic to the new version and watches SLIs before widening, **rolling** updates replace instances incrementally, and **feature flags** decouple deployment from release entirely. **GitOps** (Argo CD, Flux) takes the reconciliation-loop idea and applies it to delivery: the Git repository is the single source of truth for cluster state, and an agent inside the cluster continuously pulls and applies it, which yields auditability, easy rollback, and no need for CI systems to hold cluster credentials."},
    ],
  },
  {
    heading: "Design patterns and the philosophy of resilience",
    blocks: [
      {"kind":"p","text":"The **twelve-factor app** methodology remains the clearest statement of cloud-native application hygiene: configuration in the environment, stateless processes, backing services as attached resources, logs as event streams, disposability, and dev/prod parity. On top of it sit the microservice patterns. **Bounded contexts** from domain-driven design define service boundaries along business capabilities. The **strangler fig** incrementally replaces a monolith by routing slices of traffic to new services. **Backends for frontends** tailor APIs per client type. The **sidecar**, **ambassador**, and **adapter** patterns place helper containers beside the main one. For resilience, **timeouts**, **retries with exponential backoff and jitter**, **circuit breakers** (which stop calling a failing dependency so it can recover and so you fail fast), **bulkheads** (which isolate resource pools so one failing dependency cannot exhaust everything), **load shedding**, and **graceful degradation** form the standard toolkit. The counter-intuitive but essential insight is that naive retries amplify outages, so retries must be budgeted and jittered, and the system must distinguish retryable from non-retryable failures."},
      {"kind":"p","text":"At architectural scale, **cell-based architecture** partitions an entire service into independent, identically shaped cells, each serving a subset of customers with no shared dependencies, so that a bad deployment or a poison request affects only one cell. **Static stability** means a system continues to operate correctly during a dependency failure without needing to make control-plane calls, which is why well-designed systems pre-provision capacity across zones rather than relying on autoscaling to react during an AZ loss. **Chaos engineering** (AWS Fault Injection Simulator, Chaos Mesh, Gremlin) is the discipline of deliberately injecting failures in production to validate these properties empirically rather than assuming them. **Autoscaling** vocabulary includes horizontal versus vertical scaling, the Kubernetes Horizontal Pod Autoscaler and the event-driven **KEDA**, cluster autoscalers such as Karpenter, and the distinction between reactive, predictive, and scheduled scaling. Disaster recovery is quantified by **Recovery Time Objective** (how long until service is restored) and **Recovery Point Objective** (how much data loss is tolerable), which together determine whether you need backup-and-restore, pilot light, warm standby, or multi-region active-active."},
    ],
  },
  {
    heading: "Data platforms, cost, and the organizational layer",
    blocks: [
      {"kind":"p","text":"Modern analytical architecture converges on the **lakehouse**: raw data lands in object storage in open columnar formats (Parquet) with table formats (Apache Iceberg, Delta Lake, Hudi) that add ACID transactions and schema evolution, queried by serverless engines (Athena, BigQuery, Synapse and Fabric) and processed by Spark (EMR, Dataproc, Databricks) or streaming engines (Flink, Dataflow). **Data mesh** applies microservice thinking to data, treating datasets as products owned by domain teams. **Feature stores**, **vector databases**, and managed model serving (SageMaker, Vertex AI, Azure ML and Azure OpenAI) increasingly sit alongside, and the integration of large language models through retrieval-augmented generation is pushing vector search into mainstream database offerings."},
    ],
  },
  {
    heading: "FinOps",
    blocks: [
      {"kind":"p","text":"**FinOps** is the practice of making cost a first-class engineering concern, with vocabulary around tagging and allocation, rightsizing, commitment coverage, unit economics (cost per request or per customer), and the critical observation that in cloud architecture, cost is a proxy for efficiency and often the clearest signal of design flaws. Finally, **platform engineering** has emerged as the organizational response to cloud-native complexity: rather than expecting every product team to master Kubernetes, IAM, and observability, a platform team builds an **internal developer platform** with golden paths, self-service provisioning, and paved roads that make the right thing the easy thing. The CNCF landscape, with its hundreds of projects, is navigable only with this kind of curation, and the mark of mature cloud-native practice is not using the most tools but choosing the fewest that let teams ship reliably, observe honestly, and recover quickly."},
    ],
  },
];;
