import type { LessonSection } from "../curriculum";

export const sections: readonly LessonSection[] = [
  {
    heading: "The Premise, and Why It's a Trap",
    blocks: [
      {"kind":"p","text":"Terry Pratchett's Discworld series (41 novels, 1983–2015) begins with a deliberately absurd cosmology: a flat, circular world resting on the backs of four elephants, which in turn stand on the shell of Great A'Tuin, a turtle of planetary scale swimming through space. If you stop there, you've been successfully misdirected. The silly cosmology is a Trojan horse. What Pratchett actually built is one of the most sustained philosophical projects in modern fiction — an investigation of belief, power, justice, death, and narrative itself, conducted through the medium of comic fantasy because comedy lowers the reader's defenses."},
      {"kind":"p","text":"The useful comparison is not Tolkien but Swift. Discworld is satire wearing fantasy's clothes, and the fantasy elements are almost always instruments for examining *us*. The dwarfs are about immigration and cultural identity. The golems are about labor, personhood, and free will. The vampires who swear off blood are about addiction and recovery. Pratchett called fantasy \"an exercise bicycle for the mind: it might not take you anywhere, but it tones up the muscles that can.\""},
    ],
  },
  {
    heading: "The Core Physics: Narrativium",
    blocks: [
      {"kind":"p","text":"The single most important Discworld concept is **narrativium** — the idea that on the Disc, stories are a fundamental force, like gravity. Things happen because narrative demands it. The third son of a king *will* succeed at the quest his brothers failed. Million-to-one chances crop up nine times out of ten — but *only* if they are exactly a million to one, which characters sometimes attempt to engineer."},
      {"kind":"p","text":"This is not just a joke about genre conventions. It's a serious claim about human cognition, one Pratchett developed explicitly in *The Science of Discworld* books (co-written with mathematician Ian Stewart and biologist Jack Cohen): humans are not *Homo sapiens* so much as ***Pan narrans***, the storytelling ape. We understand the world through narrative, and we are therefore vulnerable to it. Much of Discworld's dramatic tension comes from characters who *know* they're inside a story-shaped universe and must decide whether to ride the story or fight it. Granny Weatherwax, the series' most formidable witch, treats stories as parasitic entities that feed on people — and her heroism consists largely of refusing the roles stories assign."},
      {"kind":"p","text":"The corollary concept is **Belief**. On the Disc, gods exist because people believe in them, and their power waxes and wanes with their congregations (*Small Gods* is the definitive treatment — a \"Great God\" reduced to a one-eyed tortoise because his church grew mighty while actual belief in *him* withered into belief in the institution). Death, the Hogfather (a Santa Claus analogue), the Tooth Fairy — all are anthropomorphic personifications sustained by human imagination. In *Hogfather*, Death argues that humans must practice believing \"the little lies\" — fantasy figures — as training for believing the big necessary ones: justice, mercy, duty. \"Take the universe and grind it down to the finest powder and sieve it through the finest sieve and then *show me one atom of justice, one molecule of mercy.*\" Yet we must act as if they exist, or they never will. That's the philosophical spine of the whole series: meaning is not discovered but *made*, and making it is a moral duty."},
    ],
  },
  {
    heading: "The Geography of Ideas",
    blocks: [
      {"kind":"p","text":"**Ankh-Morpork** is the great city, a composite of Renaissance Florence, Dickensian London, and modern New York, ruled by the Patrician, **Lord Vetinari** — a benevolent(ish) tyrant and one of fiction's great political minds. Vetinari's genius is that he has weaponized systems thinking: he legalized and unionized the Thieves' Guild (crime becomes predictable, taxable, and self-limiting), and he governs on the principle that people fundamentally want tomorrow to be roughly like today. He is Machiavelli's Prince written by someone who read Machiavelli *sympathetically*. Watching Vetinari operate is a graduate seminar in institutional design."},
      {"kind":"p","text":"**Unseen University** houses the wizards — academia satirized with love and precision. Anyone who has worked in a university will recognize the committee politics, the territorial faculty, the administration's relationship with lunch. The wizards study magic but mostly avoid using it, having discovered that the primary purpose of concentrating wizards in a university is to keep them from doing magic at scale. (There's a real argument here about institutions as containment vessels for dangerous ambition.) Magic itself is treated with something like scientific rigor: it's a form of energy (measured in *thaums*), it has costs and conservation laws, and its practitioners include **Hex**, a semi-sentient thinking engine driven by an ant colony — Pratchett's running commentary on computing, complete with an \"Anthill Inside\" sticker."},
      {"kind":"p","text":"**L-space** deserves special mention for the professionally geeky: the theory that all libraries are connected through a higher-dimensional space, because books bend reality — \"knowledge equals power equals energy equals matter equals mass,\" and a large library therefore distorts spacetime. The Librarian of Unseen University, an orangutan (transformed in a magical accident, and violently uninterested in being changed back), navigates L-space professionally. It's a joke, and it's also a genuinely elegant metaphor for intertextuality."},
    ],
  },
  {
    heading: "The Major Threads",
    blocks: [
      {"kind":"p","text":"The series isn't strictly sequential; it braids several sub-series, each with its own thematic territory. This matters for how you approach it."},
      {"kind":"p","text":"**Death** (*Mort*, *Reaper Man*, *Hogfather*) — The anthropomorphic personification himself, WHO SPEAKS IN SMALL CAPS, and who has developed a fascination with humanity: he adopts a daughter, takes an apprentice, tries curry. Death is the series' most beloved character precisely because he is the outsider through whom Pratchett examines what it means to be human. These books are the philosophical core."},
      {"kind":"p","text":"**The Witches** (*Wyrd Sisters*, *Witches Abroad*, *Lords and Ladies*) — Granny Weatherwax, Nanny Ogg, and their coven in the rural kingdom of Lancre. The key concept here is **headology**: the recognition that most \"magic\" is actually applied psychology. People don't need spells; they need to believe things, and a witch's real power is understanding what people are, expecting the worst, and helping anyway. Granny Weatherwax's ethics can be compressed into one line, arguably the moral center of all 41 books: *\"Sin is when you treat people as things. Including yourself. That's what sin is.\"* The witch books are also Pratchett's deepest engagement with folklore, Shakespeare, and the mechanics of story."},
      {"kind":"p","text":"**The City Watch** (*Guards! Guards!*, *Men at Arms*, *Night Watch*) — The arc of Sam Vimes, a drunk night-watchman who rises to command a police force in a city that never had a real one, is the series' study of power, law, class, and institutional justice. It contains Pratchett's most famous piece of economic theory, the **Vimes \"Boots\" Theory of Socioeconomic Unfairness**: the rich man buys fifty-dollar boots that last a decade; the poor man buys ten-dollar boots that last a season, and thus spends more money over time and still has wet feet. Being poor is *expensive* — a point economists now cite by name. *Night Watch* (2002), in which Vimes is thrown back in time to mentor his younger self during a revolution, is widely considered the series' masterpiece and works as a standalone meditation on why revolutions eat their children and why decent policing matters anyway."},
      {"kind":"p","text":"**The Industrial Revolution / Moist von Lipwig** (*Going Postal*, *Making Money*) — Late-series books about a conman conscripted by Vetinari to run failing public institutions: the post office, the mint. These are startlingly sharp about semaphore networks-as-internet (the \"clacks\"), financial systems, fiat currency, and the fact that a reformed fraudster understands trust — the actual substance of money — better than any banker."},
      {"kind":"p","text":"**Tiffany Aching** (*The Wee Free Men* onward) — Nominally YA, actually Pratchett distilled: a young witch on the chalk downlands learning that witchcraft means doing the unglamorous necessary work — sitting with the dying, cutting toenails for the elderly — because \"we are the people who do the things that need doing.\""},
    ],
  },
  {
    heading: "Why It Rewards Intelligence",
    blocks: [
      {"kind":"p","text":"Pratchett's prose operates on layers. The surface is jokes — puns, footnotes (the footnotes are load-bearing), running gags. Underneath is a density of allusion spanning Shakespeare, Leibniz, phantom-of-the-opera, Chinese history, thermodynamics, and Australian folk songs, none of which is required but all of which pays off. And beneath *that* is a consistent moral philosophy: broadly humanist, deeply suspicious of anyone who treats people as things, furious at cruelty, and convinced that evil begins not with monsters but with ordinary people who stop paying attention. Pratchett's anger — and he was, by his own account, an angry writer — is always aimed upward, at power, never downward."},
    ],
  },
  {
    heading: "Where to Start",
    blocks: [
      {"kind":"p","text":"Do **not** start with *The Colour of Magic* (book one); it's a parody of 1980s fantasy tropes and unrepresentative of the mature series. The standard advice, which is correct:"},
      {"kind":"list","items":["*Mort* (Death sub-series) or *Guards! Guards!* (Watch) for classic entry points","*Small Gods* — fully standalone, and the best single-volume argument for the whole enterprise","*Going Postal* — if you're a technologist or came for the systems thinking","*Wyrd Sisters* — if you want the Shakespeare-and-folklore register"]},
      {"kind":"p","text":"Read one. If Pratchett's sentences work on you — and they either do immediately or don't — you have forty more waiting, written by a man who, even as early-onset Alzheimer's took him apart, kept insisting on the discipline his entire fictional universe is built upon: that the story you tell about the world is a choice, and you are responsible for it."},
    ],
  },
];;
