import type { LessonSection } from "../curriculum";

export const sections: readonly LessonSection[] = [
  {
    heading: null,
    blocks: [
      {"kind":"p","text":"*A lesson in two systems that were never really separate*"},
    ],
  },
  {
    heading: "Why these two words belong in the same sentence",
    blocks: [
      {"kind":"p","text":"Dopamine, in the popular imagination, is the molecule of pleasure, motivation, and doomscrolling. Irritable bowel syndrome (IBS) is a disorder of cramping, bloating, and unpredictable bowels. Putting them together sounds like a wellness-blog category error."},
      {"kind":"p","text":"It isn't, for three reasons. First, roughly half of the dopamine your body makes on any given day is made in the gut, not the brain. Second, IBS is formally defined as a *disorder of gut–brain interaction*, and dopamine is a major signaling currency on both sides of that hyphen. Third, dopamine touches nearly every mechanism thought to matter in IBS: motility, secretion, immune tone, pain processing, stress, and expectation."},
      {"kind":"p","text":"One caveat before anything else. The dopamine–IBS literature is thin compared with serotonin's, which has been the gut's celebrity neurotransmitter for decades. What follows is partly established physiology, partly suggestive human data, partly rodent work, and partly a way of thinking. I will try to flag which is which, because the ability to tell them apart is the actual skill being taught here."},
    ],
  },
  {
    heading: "1. IBS, defined properly",
    blocks: [
      {"kind":"p","text":"For the beginner: IBS is diagnosed by pattern, not by a test. Under the current Rome IV criteria, it means recurrent abdominal pain on average at least one day a week over the past three months, linked to defecation or to a change in how often or in what form stool appears. Subtypes are assigned by stool consistency: IBS-D (diarrhea-predominant), IBS-C (constipation-predominant), IBS-M (mixed), and IBS-U (unclassified). About 4% of the world's population meets Rome IV criteria; older, looser criteria gave figures closer to 10%. The defining feature is that nothing is structurally wrong on endoscopy or biopsy, which for most of the twentieth century earned IBS the label \"functional,\" a word patients correctly heard as \"imaginary.\""},
      {"kind":"p","text":"For the geek: the modern mechanistic picture is a list of dysregulated settings rather than a lesion. *Visceral hypersensitivity* — a lowered threshold for pain from gut distension, measurable by inflating a balloon (a barostat) in the rectum — is the most reproducible finding. Add altered motility and transit; low-grade mucosal immune activation, with mast cells sitting suspiciously close to nerve endings; increased epithelial permeability; shifts in the microbiota, including the roughly one in ten cases that begin after an infectious gastroenteritis; altered central pain processing in the anterior cingulate, insula, amygdala, and prefrontal cortex, along with hypervigilance to bodily signals; and overactive stress signaling through corticotropin-releasing factor (CRF) and the hypothalamic–pituitary–adrenal axis. The classical neurochemical story is serotonin (5-HT): most of the body's serotonin lives in gut enterochromaffin cells, and drugs acting on 5-HT3 and 5-HT4 receptors were the first mechanism-based IBS therapies."},
      {"kind":"p","text":"The concept to carry forward: IBS is a disorder of a loop. The gut sends signals up; the brain predicts, interprets, and sends instructions down; the two calibrate each other continuously. In IBS the calibration is off. The pathology is in the *gains and thresholds*, not in the tissue."},
    ],
  },
  {
    heading: "2. Dopamine, defined properly",
    blocks: [
      {"kind":"p","text":"For the beginner: dopamine is a small molecule made from the amino acid tyrosine in two enzymatic steps. Tyrosine hydroxylase (TH), the slow, rate-limiting step, adds a hydroxyl group to make L-DOPA; it needs oxygen, iron, and a cofactor called tetrahydrobiopterin (BH4), a detail that will matter later. Aromatic L-amino acid decarboxylase (AADC), which needs vitamin B6, then removes a carboxyl group to yield dopamine. Add one more enzyme, dopamine β-hydroxylase (DBH), and you get norepinephrine; one more still and you get epinephrine. Dopamine is thus also the parent of the stress catecholamines. It is cleared from wherever it acts by reuptake through the dopamine transporter (DAT) and lower-affinity organic cation transporters, then dismantled by monoamine oxidase (MAO) and catechol-O-methyltransferase (COMT) into metabolites like DOPAC and homovanillic acid."},
      {"kind":"p","text":"For the geek: five receptors, all G-protein-coupled, in two families. D1-like receptors (D1, D5) couple to Gs and raise cyclic AMP. D2-like receptors (D2, D3, D4) couple to Gi/o, lower cAMP, open potassium channels, and inhibit calcium channels; D2 also functions as a presynaptic autoreceptor that tells the releasing neuron to stop. Same molecule, opposite cellular effects depending on which receptor is listening. Hold onto that, because the gut uses exactly this trick."},
      {"kind":"p","text":"In the brain, four pathways matter. Nigrostriatal (substantia nigra to dorsal striatum) governs movement and is what dies in Parkinson's disease. Mesolimbic (ventral tegmental area to nucleus accumbens) handles motivation and reward learning. Mesocortical (VTA to prefrontal cortex) supports working memory and effortful cognition. Tuberoinfundibular (hypothalamus to pituitary) restrains prolactin, which is why drugs that block D2 receptors can cause milk secretion. The modern computational view is that phasic dopamine bursts encode *reward prediction error* — the gap between what you expected and what you got — while tonic dopamine levels set motivational vigor. More broadly, dopamine signals *salience*: what deserves attention, learning, and action, including threatening and painful things. It is not the pleasure molecule. It is the \"this matters, update your model\" molecule."},
      {"kind":"p","text":"The single most important fact for this lesson: dopamine does not cross the blood–brain barrier. L-DOPA does; dopamine does not. So the body has two dopamine compartments — brain and periphery — that do not exchange the molecule itself. They communicate through nerves (the vagus, spinal afferents, sympathetic fibers), immune messengers, hormones, and, as we'll see, microbes."},
    ],
  },
  {
    heading: "3. The gut's dopamine economy",
    blocks: [
      {"kind":"p","text":"In 1997, Graeme Eisenhofer and colleagues measured catecholamines in blood entering and leaving the mesenteric organs of human volunteers and concluded that the gut accounts for roughly half of the body's dopamine production. Where does it come from?"},
      {"kind":"p","text":"The enteric nervous system, first. The ENS is the gut's own network of two to six hundred million neurons, embedded in the intestinal wall in two layers (the myenteric plexus between the muscle layers, the submucosal plexus beneath the lining), and it can run peristalsis, secretion, and local blood flow without any input from the brain — hence the \"second brain\" nickname. Michael Gershon's laboratory showed in 2004 that a small fraction of these neurons are genuinely dopaminergic: they express TH and AADC, they express DAT, and they lack DBH, meaning dopamine is their final product rather than a way-station to norepinephrine. They are intrinsic, born late in development, and survive if the gut is disconnected from the sympathetic supply."},
      {"kind":"p","text":"The epithelium, second, and in bulk. Enterocytes, the absorptive cells lining the intestine, contain abundant AADC and some TH, and they manufacture dopamine as a local, paracrine regulator of their own transport and defense. Much of Eisenhofer's \"half\" is probably this non-neuronal, epithelial dopamine. Sympathetic nerve terminals contribute a little as a co-transmitter; immune cells such as T lymphocytes and dendritic cells can synthesize and store it; and gut bacteria — certain *Bacillus*, *Escherichia*, *Proteus*, and *Serratia* strains in culture, and *Enterococcus* species via tyrosine decarboxylase — produce it too."},
      {"kind":"p","text":"Its fate is instructive. Most gut dopamine is rapidly sulfated by the enzyme SULT1A3, which is heavily expressed in intestinal tissue, into dopamine sulfate, which cannot activate receptors. Plasma dopamine sulfate runs about a hundred times higher than free dopamine and rises after meals. Bananas and avocados contain milligram quantities of dopamine, which is why \"dopamine foods\" articles are half right: you absorb it, you sulfate it, you excrete it, and your brain never hears about it. A second inactivation route is glucuronidation, and here microbes re-enter the story. Asano and colleagues showed in 2012 that in germ-free mice, most dopamine in the gut lumen is conjugated and inert, whereas in normally colonized mice it is largely free and active, because bacterial β-glucuronidases strip the conjugate off. Bacteria do not merely make dopamine; they switch it on."},
    ],
  },
  {
    heading: "4. What dopamine does to a gut",
    blocks: [
      {"kind":"p","text":"Motility comes first, and the headline is that dopamine is a brake. Acting through D2 receptors on cholinergic motor neurons of the ENS, it suppresses acetylcholine release, which means less smooth-muscle contraction, slower gastric emptying, reduced lower esophageal sphincter tone, and slower colonic transit. D1 receptors on smooth muscle add direct relaxation in some segments. Gershon's group demonstrated the physiological reality of this in 2006: mice lacking the D2 receptor move contents through the gut faster than normal mice. Remove the brake, and things speed up."},
      {"kind":"p","text":"This single fact explains an entire drug class. *Prokinetics* — drugs that promote gut movement — are largely D2 antagonists. Metoclopramide blocks D2 receptors and stimulates 5-HT4 receptors; it crosses into the brain, which is why chronic use carries a black-box warning for tardive dyskinesia, a movement disorder born of striatal D2 blockade. Domperidone blocks D2 receptors but stays outside the brain; it still relieves nausea because the brain's vomiting trigger, the area postrema, sits outside the blood–brain barrier and is thick with D2 receptors. (This is also why dopamine agonists like apomorphine provoke vomiting, why levodopa causes nausea, and why levodopa is co-formulated with carbidopa, an AADC inhibitor that stops dopamine being made in the periphery.) Itopride and levosulpiride round out the class and are used, mostly outside the United States, for functional dyspepsia — the stomach's counterpart to IBS."},
      {"kind":"p","text":"Dopamine also protects and regulates the lining. Through D1 receptors it stimulates duodenal bicarbonate secretion, the mucosa's first defense against gastric acid; in animal models it protects against gastric and duodenal ulceration, which generated a \"dopamine hypothesis\" of ulcer disease in the 1980s and 1990s. Epithelial dopamine tunes sodium pumps and ion transport in receptor-subtype-specific directions, and D1 receptors on mesenteric vessels dilate them, increasing splanchnic blood flow."},
      {"kind":"p","text":"Finally, dopamine is an immune modulator. Macrophages, dendritic cells, and T cells carry dopamine receptors. In a 2015 *Cell* paper, Yan and colleagues showed that dopamine acting on D1 receptors triggers ubiquitination and degradation of the NLRP3 inflammasome, the intracellular sensor that drives interleukin-1β production — a mechanism by which dopamine restrains systemic inflammation. In inflamed mucosa from patients with inflammatory bowel disease, dopamine is depleted (Magro and colleagues, 2002), and in colitis models restoring dopaminergic tone often reduces inflammation, though the direction depends on receptor subtype and cell type, and there are settings in which D1 signaling on T cells is pro-inflammatory."},
      {"kind":"p","text":"If you want one sentence: in the gut, dopamine is predominantly a restraining signal. It slows, it shields, and it dampens."},
    ],
  },
  {
    heading: "5. Where dopamine meets the mechanisms of IBS",
    blocks: [
      {"kind":"p","text":"**Motility, and the Parkinson's connection**"},
      {"kind":"p","text":"If dopamine is a brake, the arithmetic is easy: too much braking should resemble constipation, too little should resemble hurry. The natural experiment is Parkinson's disease, a dopamine-deficiency disorder in which constipation typically precedes tremor by years, sometimes decades. Heiko Braak's staging hypothesis places the earliest α-synuclein pathology in the enteric nervous system and olfactory bulb, spreading upward via the vagus; people who underwent truncal vagotomy decades ago have a lower Parkinson's risk. In 1995 Singaram and colleagues reported loss of dopaminergic myenteric neurons in the colons of constipated Parkinson's patients, though later careful counts (Annerino and colleagues, 2012) found no generalized loss of enteric neurons, so the enteric side of this remains contested."},
      {"kind":"p","text":"Epidemiology then supplied a tantalizing link: cohort studies in Taiwan (Lai and colleagues, 2014), Finland, and Sweden found that a diagnosis of IBS is followed by a modestly elevated risk of Parkinson's, on the order of one and a half times. The lesson here is in causal reasoning. The excess risk concentrates in the first few years after the IBS label is applied, which is what you would expect if some \"IBS\" is actually prodromal Parkinson's — constipation and abdominal discomfort from early enteric synuclein pathology — being misfiled. IBS probably does not cause Parkinson's. But the two share a substrate: dopaminergic wiring in the gut wall that, when disturbed, produces the symptoms clinicians call irritable."},
      {"kind":"p","text":"**Pain**"},
      {"kind":"p","text":"Visceral hypersensitivity is the core of IBS, and dopamine is, by disposition, analgesic. In humans, the availability of striatal D2 receptors on PET imaging predicts pain thresholds. A descending dopaminergic pathway from the hypothalamic A11 nucleus to the spinal dorsal horn suppresses nociceptive transmission through D2 receptors. In rodents, D2 agonists such as quinpirole tend to dampen the reflexive abdominal contractions elicited by colorectal balloon distension — the animal proxy for visceral pain — while D2 antagonists heighten them. Fibromyalgia, which overlaps with IBS in roughly a third of patients, shows blunted striatal dopamine release in response to painful stimulation (Wood and colleagues, 2007). And in a landmark 2012 study, Baliki and Apkarian showed that the strength of functional connectivity between the nucleus accumbens and medial prefrontal cortex — the heart of the mesolimbic system — predicted which people with new back pain would still have it a year later. The circuit that assigns value and salience is the circuit that decides which pains become chronic. IBS pain, on this view, can be a dopaminergic-circuit phenomenon in the brain regardless of what gut dopamine is doing."},
      {"kind":"p","text":"Genetics adds a wrinkle. COMT, the dopamine-clearing enzyme, has a common variant, Val158Met: the Met form is three- to four-fold less active, leaving more dopamine in prefrontal synapses. Met/Met individuals are, on average, more pain-sensitive and mount weaker endogenous opioid responses to pain (Zubieta and colleagues, 2003). A Swedish case–control study (Karling and colleagues, 2011) reported the opposite, high-activity Val/Val genotype over-represented among IBS patients — a finding from the small-sample, candidate-gene era that should be held loosely. Far more interesting is what came next."},
      {"kind":"p","text":"**Expectation, salience, and the placebo problem**"},
      {"kind":"p","text":"In IBS trials, roughly 40% of patients improve on placebo. Even placebo given openly, with patients told it is inert, works (Kaptchuk and colleagues, 2010). In 2012, Hall and colleagues genotyped participants from a trial that compared no treatment, sham acupuncture, and sham acupuncture delivered by a warm, attentive clinician. COMT genotype predicted response: Met/Met patients improved most in the augmented arm, forming a dose–response relationship between genotype and the intensity of the therapeutic ritual. Placebo analgesia in healthy volunteers, meanwhile, releases dopamine in the nucleus accumbens, and nocebo does the reverse (Scott and colleagues, 2007 and 2008)."},
      {"kind":"p","text":"Why should this be? Because the brain's job in interoception — the sensing of the body's interior — is not passive reception but prediction. It generates expectations about gut signals and weights the discrepancies, and dopamine is a leading candidate for the signal that sets those weights, what computational neuroscientists call *precision*. In this framework, IBS is a state in which the brain assigns high precision and high salience to gut sensations: visceral hypervigilance made mechanistic. The machinery that generates symptoms is therefore the same machinery that placebo, gut-directed hypnotherapy, and cognitive behavioral therapy act on. The geek's reframing is that the notorious IBS placebo rate is not statistical noise to be designed away. It is a readout of the disorder's mechanism."},
      {"kind":"p","text":"**Stress and inflammation**"},
      {"kind":"p","text":"CRF, released in the amygdala and hypothalamus, is the best-established stress mediator in IBS: it accelerates colonic motility and lowers pain thresholds in animals and humans alike. CRF neurons project onto dopamine neurons in the VTA, and chronic or early-life stress — the maternal separation model in rats reliably produces adult visceral hypersensitivity — durably remodels the mesolimbic system toward blunted reward signaling and heightened threat salience."},
      {"kind":"p","text":"Inflammation adds a second route. Cytokines oxidize BH4, the cofactor TH cannot work without, and reduce dopamine synthesis and release in the striatum; this is the Felger–Miller model of inflammation-induced anhedonia, fatigue, and psychomotor slowing, worked out in patients receiving interferon therapy. The immune activation in IBS is low-grade, but it is a coherent pathway to the fatigue and lack of drive that so many IBS patients report and that clinics rarely ask about."},
      {"kind":"p","text":"**Microbes**"},
      {"kind":"p","text":"Mark Lyte's field of *microbial endocrinology* established that bacteria sense host catecholamines. Norepinephrine and dopamine pry iron loose from the host proteins lactoferrin and transferrin, and *E. coli*, *Salmonella*, and *Yersinia* respond with faster growth and increased virulence gene expression. Microbes generate free dopamine in the lumen (Asano); microbes shape host dopamine turnover in the striatum, since germ-free mice have altered striatal dopamine metabolism (Diaz Heijtz and colleagues, 2011); and microbes run serious catecholamine chemistry of their own — *Enterococcus faecalis* converts levodopa to dopamine and *Eggerthella lenta* then strips a hydroxyl off, a two-species pathway that measurably reduces levodopa delivery in Parkinson's patients (Maini Rekdal and colleagues, 2019). In IBS, altered microbiota and small-intestinal bacterial overgrowth are common. Whether their dopamine chemistry matters is untested, but the circuit is complete on paper: stress pushes sympathetic catecholamines toward the lumen, catecholamines alter microbial growth, microbes alter mucosal immune tone, and immune tone alters what the afferent nerves report upward."},
      {"kind":"p","text":"**The comorbidity cluster**"},
      {"kind":"p","text":"IBS travels in company. It overlaps with functional dyspepsia in a third or more of patients, with fibromyalgia in about a third, with migraine, with restless legs syndrome (found in roughly a quarter to a third of IBS patients in some series), and, in population data, with ADHD. Each companion has dopamine in its biology. Restless legs responds to dopamine agonists and implicates the very A11 pathway that gates spinal pain. Migraine's premonitory yawning and nausea are dopaminergic, and D2 antagonists such as metoclopramide and prochlorperazine abort attacks. ADHD is a dopamine–norepinephrine disorder treated with reuptake inhibitors. IBS is also one and a half to two times more common in women, and estrogen modulates striatal dopamine release and D2 receptor density. No single item here proves anything. Together they form a pattern that a curious scientist should not ignore."},
    ],
  },
  {
    heading: "6. Pharmacology at the intersection",
    blocks: [
      {"kind":"p","text":"The peripheral D2 antagonists — metoclopramide, domperidone, itopride, levosulpiride — are used mainly for the dyspepsia and nausea that so often accompany IBS; levosulpiride has small, older trials in IBS itself. Sulpiride and amisulpride illustrate a pharmacological paradox worth knowing: at low doses they preferentially block presynaptic D2 autoreceptors, which *increases* dopamine release and produces an antidepressant, activating effect, while higher doses block postsynaptic receptors and behave as antipsychotics. The 2018 Rome Foundation report on neuromodulators lists atypical antipsychotics such as quetiapine, olanzapine, and aripiprazole as augmentation options for refractory central pain, anxiety, and sleep disturbance in disorders of gut–brain interaction, though their benefit likely owes more to serotonin, histamine, and adrenergic receptor effects than to D2 blockade. Bupropion, which inhibits dopamine and norepinephrine reuptake, is sometimes chosen for IBS patients with fatigue and low mood precisely because it does not constipate and lacks sexual side effects, though it does little for pain."},
      {"kind":"p","text":"Two humbling counterpoints. Tricyclic antidepressants like amitriptyline, the best-evidenced neuromodulators for IBS pain, barely touch dopamine directly. And the antipsychotics that block D2 most heavily, such as clozapine, cause gut *hypomotility*, largely through anticholinergic and serotonergic actions — a reminder that no drug is a clean probe of one system. Nothing in current practice is a \"dopamine treatment for IBS.\" There isn't one, and it is not obvious there should be."},
    ],
  },
  {
    heading: "7. How to read claims about dopamine and IBS",
    blocks: [
      {"kind":"p","text":"The measurement problems are real. Plasma dopamine reflects sympathetic and gut sources indiscriminately, and unless a study separates free from sulfated dopamine it is measuring lunch. There is no imaging ligand for gut dopamine, and brain PET studies of dopamine in IBS are essentially absent. Genetic associations come from small candidate-gene studies with a poor replication record. Rodent models measure visceromotor reflexes, not pain. No randomized trial has ever used a dopaminergic drug as a deliberate mechanism test in IBS."},
      {"kind":"p","text":"What good evidence would look like: PET measurement of striatal D2 availability and pain-evoked dopamine release in IBS patients stratified by subtype; prospective replication of genotype-by-ritual placebo effects; quantification of dopamine, DAT, and D2 in colonic biopsies correlated with transit and pain thresholds; and characterization of microbial catecholamine chemistry in IBS stool linked to symptoms. None of this is exotic. All of it is undone."},
      {"kind":"p","text":"And a word on the cultural noise. \"Dopamine detox,\" \"boosting your dopamine,\" \"dopamine foods\" — none of it maps onto the physiology above. Eating tyrosine will not fix your colon. Gut dopamine cannot reach your brain. Brain dopamine is not a fuel tank that empties and refills; it is a teaching signal."},
    ],
  },
  {
    heading: "8. The mental model to keep",
    blocks: [
      {"kind":"p","text":"Think of dopamine as a setter of gains and thresholds. In the gut, it is a brake on movement, a shield for the mucosa, and a damper on inflammation. In the brain, it is a weight on what matters, including how much a sensation from the gut is allowed to matter. IBS, mechanistically, is a disorder of mis-set gains and mis-weighted predictions across the gut–brain loop. Serotonin, CRF, mast-cell mediators, and dopamine are among the knobs."},
      {"kind":"p","text":"Dopamine's peculiarity — that it sits at both ends of the loop while never crossing between them — makes it an unusually good teacher of the whole subject. The gut and the brain do not share molecules. They share logic."},
      {"kind":"p","text":"Three sentences to keep: the gut makes about half your dopamine and mostly uses it to slow, protect, and calm; the brain's dopamine decides how loud the gut is allowed to be; and the proof that any of this is decisive in IBS is still mostly circumstantial, which is a research opportunity rather than a reason to look away."},
      {"kind":"p","text":"*For readers who want primary sources:* Eisenhofer et al., *J Clin Endocrinol Metab* 1997 (gut dopamine production); Li et al., *J Neurosci* 2004 and 2006 (enteric dopaminergic neurons, D2-knockout transit); Asano et al., *Am J Physiol* 2012 (microbial deconjugation of luminal catecholamines); Yan et al., *Cell* 2015 (dopamine and NLRP3); Hall et al., *PLoS One* 2012 (COMT and placebo in IBS); Scott et al., *Neuron* 2007 and *Arch Gen Psychiatry* 2008 (placebo and striatal dopamine); Baliki et al., *Nat Neurosci* 2012 (corticostriatal prediction of chronic pain); Wood et al., *Eur J Neurosci* 2007 (fibromyalgia dopamine PET); Maini Rekdal et al., *Science* 2019 (microbial levodopa metabolism); Drossman et al., *Gastroenterology* 2018 (Rome Foundation neuromodulator report)."},
    ],
  },
];;
