import type { LessonSection } from "../curriculum";

export const sections: readonly LessonSection[] = [
  {
    heading: "What an embedding actually is",
    blocks: [
      {"kind":"p","text":"An embedding is a learned function that maps some piece of data—a sentence, an image, a product, a user, a protein—into a list of numbers, a point in a high-dimensional space, such that geometric closeness in that space corresponds to semantic similarity in the original domain. That is the whole idea, and everything else is engineering around it. When you hear \"the embedding of this paragraph is a 1536-dimensional vector,\" it means a neural network has digested the paragraph and emitted 1536 floating-point numbers, and those numbers were trained so that paragraphs about similar things land near each other and paragraphs about unrelated things land far apart."},
      {"kind":"p","text":"The reason this works is not magic but optimization. Modern embedding models are typically trained with contrastive objectives: show the model pairs of things that should be close (a question and its answer, a caption and its image, two paraphrases) and things that should be far (random unrelated samples, or better, \"hard negatives\" that look superficially similar but mean something different), and adjust the weights so the dot product or cosine of the positive pair goes up and the negatives go down. The InfoNCE loss, the engine of CLIP and most sentence-embedding models, is essentially a softmax over similarity scores in a batch. The geometry the model learns is therefore a direct artifact of what pairs it was trained on. An embedding model trained on question–answer pairs will think a question and its answer are \"similar\" even though they share few words; a model trained purely on paraphrase will not. This is why choosing an embedding model is a modeling decision, not a commodity purchase, and why benchmark suites like MTEB exist to compare them across retrieval, clustering, classification, and semantic textual similarity tasks."},
      {"kind":"p","text":"The vocabulary distinguishes **dense** embeddings—every dimension is a real number, nearly all nonzero, meaning is distributed and uninterpretable—from **sparse** vectors, where the dimensions correspond to vocabulary terms and most entries are zero. Classical lexical search (TF-IDF, BM25) lives in sparse space; a document is a bag of weighted words. Learned sparse models like SPLADE blur the line: a transformer predicts which vocabulary terms a document \"should\" activate, including terms it never literally contains, producing an expanded sparse vector that keeps the exact-match precision of keyword search while gaining some of the semantics of dense retrieval. **Multi-vector** representations, exemplified by ColBERT, go the other way: instead of compressing a document into one vector, they keep one vector per token and score query–document pairs by \"late interaction\"—for each query token, find its maximum similarity against any document token, then sum. This is more expressive than a single vector and more expensive to store and search, which is exactly the trade-off vector databases must negotiate."},
      {"kind":"p","text":"Dimensionality matters more than beginners expect. Common sizes range from 384 (small sentence transformers) to 768, 1024, 1536, 3072, and beyond. Higher dimensions can encode more distinctions but cost linearly more memory and compute per comparison, and the geometry gets strange: in high dimensions, distances concentrate, meaning the ratio between the nearest and farthest neighbor shrinks, which is one face of the \"curse of dimensionality.\" A recent trick, **Matryoshka Representation Learning**, trains the model so that the first k dimensions of the vector are themselves a good embedding, letting you truncate a 3072-dimensional vector to 256 dimensions at query time with graceful rather than catastrophic quality loss. This is why some APIs let you request an output dimension."},
    ],
  },
  {
    heading: "Measuring closeness",
    blocks: [
      {"kind":"p","text":"Once data are points, similarity is distance, and three metrics dominate. **Euclidean (L2) distance** is the straight-line distance you learned in school. **Dot product** (inner product) multiplies corresponding components and sums; it rewards both direction and magnitude. **Cosine similarity** is the dot product of the vectors after normalizing each to unit length, so it measures only the angle between them and ignores magnitude. For most text embedding models, which are trained with cosine or produce normalized outputs, these three are interchangeable up to monotone transformations—if all vectors have length one, cosine equals dot product, and L2 distance is a simple function of it. The practical rule is: use the metric the model was trained with, normalize if in doubt, and understand that a database's \"cosine index\" is often just a dot-product index over pre-normalized vectors. There are also specialized metrics—Hamming distance for binary vectors, Jaccard for sets—that appear once you start quantizing."},
    ],
  },
  {
    heading: "The core problem: nearest neighbor search at scale",
    blocks: [
      {"kind":"p","text":"The query a vector database answers is k-nearest-neighbor (kNN) search: given a query vector, return the k stored vectors closest to it. The naive algorithm, called a **flat** or brute-force index, compares the query against every stored vector. This is exact, embarrassingly simple, and perfectly fine up to perhaps a few hundred thousand vectors, especially on a GPU. The entire reason vector databases exist is that brute force scales linearly, and at ten million or a billion vectors with sub-100-millisecond latency requirements, linear is unacceptable."},
      {"kind":"p","text":"The escape is **approximate nearest neighbor (ANN)** search: trade a small, controllable amount of accuracy for orders of magnitude in speed. Accuracy here is measured as **recall@k**—of the true k nearest neighbors, what fraction did the approximate index return? A recall of 0.95 means you missed one in twenty true neighbors, usually replaced by something only marginally farther. The fundamental dial in every vector database is the recall–latency–memory triangle, and every index family is a different way of carving it up."},
    ],
  },
  {
    heading: "Index families",
    blocks: [
      {"kind":"p","text":"**Inverted file (IVF)** indexes borrow from clustering. Run k-means on the stored vectors to find, say, 4096 centroids; assign every vector to its nearest centroid, producing 4096 buckets (the \"inverted lists\"). At query time, find the nprobe closest centroids to the query and only scan vectors in those buckets. If nprobe is 1, you scan a 4096th of the data and recall suffers; raise it to 64 and recall improves while latency grows. IVF is simple, memory-light, and the backbone of many FAISS deployments and of pgvector's `ivfflat`. Its weakness is that it is built from a snapshot of the data; heavy inserts drift the clusters, and vectors near a Voronoi boundary are easily missed."},
      {"kind":"p","text":"**Graph-based indexes**, above all **HNSW (Hierarchical Navigable Small World)**, are the current workhorse. Imagine every vector as a node connected to a handful of its near neighbors, forming a proximity graph. To search, start at an entry point, look at its neighbors, move greedily toward whichever is closest to the query, and repeat until no neighbor improves. Flat proximity graphs can get stuck or take long walks, so HNSW stacks layers: the top layer contains a sparse sample of nodes with long-range links for coarse navigation, each layer below is denser, and the bottom layer holds everything. Search descends like a skip list—coarse hops at the top, fine hops at the bottom. The construction parameter M sets how many links each node keeps; `ef_construction` sets how exhaustively neighbors are sought during building; `ef_search` (or `ef`) sets the size of the candidate beam at query time and is the knob you turn to trade latency for recall. HNSW delivers excellent recall at low latency but holds the whole graph in RAM, costs real time to build, and handles deletions awkwardly—most implementations mark nodes as tombstones and periodically rebuild rather than truly removing them, because ripping a node out can disconnect the graph."},
      {"kind":"p","text":"**DiskANN** (and its Vamana graph) adapts the graph idea to SSDs by storing the full-precision graph on disk and keeping only compressed vectors in memory to guide the walk, enabling billion-scale search on a single machine at a fraction of the RAM. **ScaNN** from Google combines partitioning with an anisotropic quantization scheme that is particularly careful about preserving inner-product rankings. **Locality-sensitive hashing (LSH)** is the older theoretical approach—hash functions where similar vectors collide with high probability—and while elegant and well-analyzed, it is largely outperformed in practice by graphs and IVF."},
    ],
  },
  {
    heading: "Compression: quantization",
    blocks: [
      {"kind":"p","text":"A million 1536-dimensional float32 vectors occupy about 6 gigabytes before any index overhead; a billion occupy 6 terabytes. Quantization shrinks this. **Scalar quantization** maps each float32 to an int8, cutting memory fourfold with modest recall loss. **Binary quantization** keeps only the sign of each dimension, a 32x reduction, and uses Hamming distance via hardware popcount; it works surprisingly well for high-dimensional embeddings from models that were trained to tolerate it, and is often paired with a **rescoring** step where the top candidates found in binary space are re-ranked using full-precision vectors. **Product quantization (PQ)** is the sophisticated option: split each vector into m sub-vectors, run k-means separately on each sub-space to learn 256 centroids, and store each sub-vector as a one-byte centroid ID. A 1536-dimensional vector becomes, say, 96 bytes. Distances are computed from precomputed lookup tables, which is fast but introduces approximation error; this is why IVF-PQ indexes commonly refine their results with exact distances on a shortlist. Vocabulary you will see: \"IVF_PQ,\" \"HNSW_SQ,\" \"coarse quantizer,\" \"codebook,\" \"asymmetric distance computation.\""},
    ],
  },
  {
    heading: "Filtering, the quiet hard problem",
    blocks: [
      {"kind":"p","text":"Real queries are rarely pure similarity. You want the nearest documents *where tenant_id = 42 and date > 2024*. **Post-filtering** runs the vector search for k results, then applies the filter, and frequently returns fewer than k or nothing at all when the filter is selective. **Pre-filtering** applies the filter first to get the allowed set, then searches only within it—exact but potentially slow, and it degrades to brute force if you cannot exploit the index. The hard research problem is **filtered ANN** or in-index filtering: modifying the graph traversal so that it skips disallowed nodes without losing connectivity, or building separate indexes per filter value, or using bitset intersection during IVF list scanning. How gracefully a database handles highly selective filters is one of the sharpest differentiators among products, and the terms \"metadata filtering,\" \"payload filtering,\" and \"attribute filtering\" all refer to this."},
    ],
  },
  {
    heading: "Hybrid search and reranking",
    blocks: [
      {"kind":"p","text":"Dense retrieval is excellent at paraphrase and intent and poor at exact strings—part numbers, names, rare jargon, a specific error code. Lexical search is the mirror image. **Hybrid search** runs both and merges them, most commonly with **Reciprocal Rank Fusion (RRF)**, which scores each document by the sum over systems of 1/(k + rank), sidestepping the problem that BM25 scores and cosine scores live on incomparable scales. Alternatively, a weighted convex combination of normalized scores, exposed as an \"alpha\" parameter in systems like Weaviate."},
      {"kind":"p","text":"Above retrieval sits **reranking**. The first stage—whatever index you use—is a **bi-encoder** setup: query and documents are embedded independently, which is what makes the search precomputable and fast. A **cross-encoder** reranker instead feeds the query and a candidate document together through a transformer and outputs a relevance score, attending across both. It is far more accurate and far too slow to run over a corpus, so the pattern is retrieve 100 with ANN, rerank with a cross-encoder, return 10. This two-stage retrieve-then-rerank architecture is the default in serious systems."},
    ],
  },
  {
    heading: "The data model of a vector database",
    blocks: [
      {"kind":"p","text":"Beyond the index, a vector database is a database. Records (often called points, objects, or documents) consist of an ID, one or more vectors, and metadata (a \"payload\" or \"properties\"). They are grouped into **collections**, **indexes**, or **classes** depending on the vendor, and often partitioned into **namespaces** or **tenants** for isolation—multi-tenancy is a first-class concern because the typical SaaS use case is thousands of customers' data that must never cross-contaminate. Writes are usually **upserts**, insert-or-update by ID. Many systems distinguish an in-memory write buffer from sealed, immutable **segments** that are indexed and periodically **compacted**, a design inherited from LSM-tree storage engines; this is why you will see terms like \"freshness layer,\" \"segment,\" \"flush,\" and why a freshly inserted vector may be searchable by brute force before it is incorporated into the ANN structure. **Sharding** distributes a collection across nodes by hashing IDs; queries fan out to all shards and merge results, a scatter-gather pattern. **Replication** provides availability and read throughput. Consistency guarantees vary enormously and are worth reading closely—\"eventually searchable\" is common."},
    ],
  },
  {
    heading: "The landscape",
    blocks: [
      {"kind":"p","text":"**FAISS** is not a database but Meta's foundational library of index implementations; most of the vocabulary above was popularized through its code. **pgvector** adds a vector type and `ivfflat` and `hnsw` indexes to PostgreSQL, with the enormous advantage that your vectors live next to your relational data, under the same transactions, joins, and access controls; its limits appear at very large scale and in filtered-search performance, which extensions like pgvectorscale and alternative Postgres indexes attempt to address. **Pinecone** is a fully managed, serverless-oriented service that hides index internals entirely; you get namespaces, metadata filtering, sparse-dense hybrid, and pay for storage and operations. **Weaviate** is an open-source database with a rich object model, built-in vectorizer modules that embed data on ingest, GraphQL and REST APIs, and strong hybrid search. **Milvus** (and its managed form, Zilliz) is designed for very large scale with a disaggregated architecture of separate query, data, and index nodes and a wide menu of index types including GPU indexes. **Qdrant** is a Rust-based engine known for sophisticated filtered search and payload indexing and for binary and scalar quantization options. **Chroma** targets developer ergonomics for small and medium applications. **Elasticsearch/OpenSearch** and **Vespa** come from the search-engine tradition and offer dense, sparse, and hybrid retrieval inside mature, battle-tested platforms; Vespa in particular supports tensor-level computation and multi-vector ranking natively. **Redis**, **MongoDB Atlas**, **Cassandra/DataStax**, **ClickHouse**, **DuckDB**, and others have all added vector indexes, reflecting the thesis that vector search is becoming a feature rather than a category."},
    ],
  },
  {
    heading: "Retrieval-augmented generation and the ingestion pipeline",
    blocks: [
      {"kind":"p","text":"The dominant application is **RAG**: embed a corpus, retrieve relevant chunks for a user's question, place them in a language model's context window, and generate a grounded answer. The pipeline introduces its own vocabulary. **Chunking** splits long documents into embeddable pieces, and the size and overlap of chunks are consequential: too large and a chunk's embedding becomes a blurry average of multiple topics; too small and it loses context. Strategies range from fixed token windows to recursive splitting on structure, to **semantic chunking** that breaks where embedding similarity between consecutive sentences drops, to **late chunking**, which embeds the full document with long-context models and then pools token embeddings per chunk so each chunk's vector retains global context. **Contextual retrieval** prepends a model-generated summary of the document to each chunk before embedding. **Query transformation** techniques—HyDE (embed a hypothetical answer rather than the question), multi-query expansion, step-back prompting—address the mismatch between how people ask and how documents are written. **Parent-document retrieval** indexes small chunks for precision but returns the enclosing section for context."},
    ],
  },
  {
    heading: "Evaluation and operations",
    blocks: [
      {"kind":"p","text":"Offline, retrieval quality is measured with recall@k, precision@k, **mean reciprocal rank (MRR)**, and **normalized discounted cumulative gain (NDCG)**, which rewards placing relevant results near the top. ANN index quality is measured as recall against brute-force ground truth at a fixed latency or queries-per-second, which is what the ann-benchmarks project standardizes. The most common failure in production is not the index but the embedding: **embedding drift** when you change or upgrade the model means every stored vector must be re-embedded, because vectors from different models (or even different versions) live in incompatible spaces and cannot be compared. Version your embedding model as rigorously as a schema. Watch out for **the mismatch between training distribution and your domain**—a general-purpose model may cluster all your legal documents into a tiny region where fine distinctions are lost, which is the motivation for fine-tuning embeddings on in-domain pairs. Monitor **tail latency**, which graph indexes can spike under memory pressure; **index build time** and its impact on deployment; and the memory footprint of HNSW, which is typically 1.5 to 2 times the raw vector size before quantization."},
    ],
  },
  {
    heading: "Where the field is going",
    blocks: [
      {"kind":"p","text":"Several threads are converging. Long-context language models have not eliminated retrieval, because cost, latency, and freshness still favor fetching only what is needed. Multimodal embeddings (CLIP, SigLIP, and their successors, plus unified text-image-audio models) place different media in a shared space, making \"search images with text\" a single cosine query. Late-interaction and multi-vector methods are being made cheap enough to deploy, with token pruning and PLAID-style indexing. Learned sparse retrieval keeps closing the gap to dense while retaining interpretability and inverted-index infrastructure. Filtered ANN and streaming updates to graph indexes remain active research. And the architectural question—dedicated vector database versus vector capability inside your existing database—is being decided, as these things usually are, by workload: billions of vectors with heavy throughput and complex filtering still justify a specialized engine, while the large majority of applications are well served by pgvector or an equivalent bolted onto whatever already holds the data."},
      {"kind":"p","text":"The mental model to keep: embeddings turn meaning into geometry, trained contrastively so that proximity encodes relatedness as defined by the training pairs; vector databases make nearest-neighbor search over that geometry fast by trading exactness for structure—clusters, graphs, compressed codes—while wrapping the result in the durability, filtering, and multi-tenancy that any database needs; and the quality of the whole system is bounded far more often by the embedding model, the chunking, and the evaluation discipline than by the choice of index."},
    ],
  },
];;
