import type { LessonSection } from "../curriculum";

export const sections: readonly LessonSection[] = [
  {
    heading: null,
    blocks: [
      {"kind":"p","text":"*An essay-length introduction for newcomers, and a map for the devoted.*"},
    ],
  },
  {
    heading: "How to Read This",
    blocks: [
      {"kind":"p","text":"This guide works in layers. Each section opens with the essentials, then goes deeper. If you're new, read the bolded ideas and the listening guide at the end. If you already know which J Dilla drum pattern lives under \"Didn't Cha Know,\" the later paragraphs in each section are for you."},
    ],
  },
  {
    heading: "I. The Short Version",
    blocks: [
      {"kind":"p","text":"**Erykah Badu (born Erica Abi Wright, February 26, 1971, Dallas, Texas) is a singer, songwriter, producer, and conceptual artist. She helped define the late-1990s movement the industry called \"neo-soul,\" then spent the rest of her career slipping out of that label.**"},
      {"kind":"p","text":"Her 1997 debut, *Baduizm*, won two Grammys and made her an instant icon: the headwrap, the ankh, the burning incense, the voice that sounded like Billie Holiday had studied hip-hop cadence. Journalists called her a revivalist. She was actually doing something stranger. She fused jazz phrasing, hip-hop production, Black nationalist and metaphysical thought, and a sly, deadpan humor into a persona that was part priestess, part trickster, and part stand-up philosopher."},
      {"kind":"p","text":"She has four Grammys. Her album catalog is small, but her cultural footprint is enormous. She has worked as a birth doula and an end-of-life doula, run a community arts nonprofit in South Dallas, DJed under the alias \"Lo Down Loretta Brown,\" acted in films like *The Cider House Rules*, and stripped naked in Dealey Plaza for a music video."},
      {"kind":"p","text":"The key to understanding her is this: **Badu treats identity as a work of art, something you author, revise, and perform on purpose.** Nearly everything else follows from that."},
    ],
  },
  {
    heading: "II. The Name as Manifesto",
    blocks: [
      {"kind":"p","text":"Before the music, there was the renaming, and it is the Rosetta Stone for her entire project."},
      {"kind":"p","text":"Badu has explained that she came to see \"Erica\" as a slave name, a name imposed rather than chosen. She changed the spelling to \"Erykah,\" with \"kah\" nodding to the Kemetic (ancient Egyptian) concept of the *ka*, the vital essence or inner self. \"Badu\" came from a jazz scat syllable she loved to sing, a sound she improvised often enough that it became her signature."},
      {"kind":"p","text":"Look at what that combination does:"},
      {"kind":"list","items":["**\"Erykah\"** reaches back to an imagined African antiquity, part of a long Afrocentric tradition of reclaiming Egypt (Kemet) as Black heritage.","**\"Badu\"** reaches toward Black American music, specifically jazz improvisation, where identity is spontaneous and sonic."]},
      {"kind":"p","text":"So the name holds two sources of selfhood: *ancestral cosmology* and *improvised sound*. One is mythic and ancient, the other is in-the-moment and American. Her whole career moves between those two poles."},
      {"kind":"callout","variant":"key","title":"For the geeks:","text":"This fits a lineage of Black self-naming as political and spiritual practice, from Malcolm Little becoming Malcolm X, to the Nation of Islam's \"X,\" to the Five Percent Nation's attributes, to Sun Ra renouncing \"Herman Blount\" for a cosmic identity. Badu's version is distinctive because it is *playful*. Half her name is a nonsense syllable. The sacred and the goofy are fused from the start."},
    ],
  },
  {
    heading: "III. Formation: Dallas, Theater, and the Hip-Hop Cipher",
    blocks: [
      {"kind":"p","text":"Badu grew up in South Dallas, raised largely by her mother, Kolleen Wright, an actress, along with her grandmother. She attended Booker T. Washington High School for the Performing and Visual Arts (whose alumni also include Norah Jones and Roy Hargrove), then studied theater at Grambling State University before leaving in 1993 to pursue music."},
      {"kind":"p","text":"**Three formative threads matter:**"},
      {"kind":"list","ordered":true,"items":["**Theater.** Badu is a performer in the dramaturgical sense. She builds characters, stages scenes, and understands costume as meaning. Her stage persona and her videos are closer to performance art than to conventional R&B showmanship."]},
      {"kind":"list","ordered":true,"items":["**Hip-hop.** She came up rapping and performing in the Dallas scene. For a while she worked with her cousin Robert \"Free\" Bradford under the name Erykah Free. Hip-hop shaped her rhythmic sense, the way she places words against a beat, and her sense of herself as part of a *cipher* (the circle of MCs, and a Five Percent term)."]},
      {"kind":"list","ordered":true,"items":["**Teaching and community.** She worked as a drama teacher for children. The pedagogical impulse, the artist as someone who instructs, heals, and raises consciousness, runs through her later work (\"Master Teacher,\" \"The Healer\")."]},
      {"kind":"p","text":"The break came when she opened for D'Angelo in Fort Worth in 1994. His manager, Kedar Massenburg, signed her. Massenburg is also widely credited with coining **\"neo-soul\"** as a marketing category. Hold onto that fact. It means the genre label attached to Badu was, from day one, partly a sales pitch."},
    ],
  },
  {
    heading: "IV. The Records: A Guided Tour",
    blocks: [
      {"kind":"p","text":"***Baduizm* (1997): The Oracle Arrives**"},
      {"kind":"p","text":"**Essential tracks:** \"On & On,\" \"Next Lifetime,\" \"Appletree,\" \"Otherside of the Game,\" \"Sometimes\""},
      {"kind":"p","text":"*Baduizm* sounds unhurried and smoky: upright bass, dusty drums, Rhodes piano, and a voice that sits *behind* the beat like a jazz singer's. People compared her to Billie Holiday immediately, and the comparison is fair on timbre (that nasal, reedy, slightly pinched tone) and phrasing (lagging, conversational, weary-wise). But the album's structure is hip-hop. Grooves loop rather than develop, and the drums are programmed and sampled with a producer's ear."},
      {"kind":"p","text":"**\"On & On\"** is the thesis. Its lyrics are dense with the vocabulary of the **Five Percent Nation (Nation of Gods and Earths)**, a Harlem-born offshoot of the Nation of Islam whose teachings deeply shaped East Coast hip-hop (Rakim, Wu-Tang Clan, Brand Nubian). You hear the \"cipher,\" references to knowledge and mathematics, and the line \"If we were made in His image, then call us by our names,\" which ties back to the renaming."},
      {"kind":"p","text":"The Five Percent idea at the root is that Black people are divine, that God is not a mystery god in the sky but the self in knowledge of itself. Badu adopted that language as a woman, singing about her own sovereign consciousness. That was significant, because the Five Percent framework traditionally casts men as \"Gods\" and women as \"Earths.\""},
      {"kind":"p","text":"**\"Otherside of the Game\"**, made with members of The Roots, is a small masterpiece of moral ambiguity. The narrator is pregnant and in love with a man who hustles. She doesn't condemn him and doesn't romanticize him. She just sits inside the contradiction. That refusal to moralize is very Badu."},
      {"kind":"p","text":"*Baduizm* won **Best R&B Album**, and \"On & On\" won **Best Female R&B Vocal Performance**."},
      {"kind":"p","text":"***Live* (1997): The Improviser Revealed**"},
      {"kind":"p","text":"Recorded while she was pregnant with her son Seven (whose father is André 3000 of OutKast), *Live* showed that the studio persona was no studio trick. Badu is a formidable stage performer, loose and funny and responsive."},
      {"kind":"p","text":"It also gave us **\"Tyrone,\"** a new song introduced on the album. It is a comic kiss-off to a freeloading boyfriend: \"You better call Tyrone... but you can't use my phone.\" It became one of her most beloved songs and a cultural catchphrase. \"Tyrone\" matters because it showed her **humor**, which critics fixated on the mystical headwrap image kept missing. Badu is a trickster as much as a sage."},
      {"kind":"p","text":"**The Soulquarian Years and *Mama's Gun* (2000): The Masterpiece**"},
      {"kind":"p","text":"**Essential tracks:** \"Bag Lady,\" \"Didn't Cha Know,\" \"Green Eyes,\" \"Orange Moon,\" \"Cleva,\" \"A.D. 2000,\" \"Penitentiary Philosophy,\" \"My Life,\" \"…& On\""},
      {"kind":"p","text":"Here we enter one of the most important creative collectives in modern Black music: **the Soulquarians**. Centered on Questlove (The Roots), J Dilla, James Poyser, D'Angelo, Common, Q-Tip, Talib Kweli, Mos Def, Bilal, and others, the loose collective worked largely out of **Electric Lady Studios** in New York, the studio Jimi Hendrix built. Over roughly 1998 to 2002 they produced a cluster of landmark albums: D'Angelo's *Voodoo*, Common's *Like Water for Chocolate*, and Badu's *Mama's Gun*."},
      {"kind":"p","text":"(Also in this period: Badu sang the hook on **The Roots' \"You Got Me\"** (1999), a chorus originally written by Jill Scott. It won Badu her third Grammy.)"},
      {"kind":"p","text":"*Mama's Gun* is more organic, more live-band, more rock- and funk-inflected, and far more emotionally exposed than *Baduizm*. If *Baduizm* was the oracle speaking from on high, *Mama's Gun* is the oracle being human: jealous, heartbroken, self-critical, funny."},
      {"kind":"list","items":["**\"Bag Lady\"** is a gentle sermon about emotional baggage: \"Bag lady, you gon' hurt your back / dragging all them bags like that.\" Its message, *let it go*, became a kind of self-care anthem before \"self-care\" was a hashtag. The groove is built on a sample drawing from the same Isaac Hayes source as Dr. Dre's \"Xxplosive,\" which is hip-hop lineage folded into a healing song."]},
      {"kind":"list","items":["**\"Didn't Cha Know,\"** produced by **J Dilla**, is the key text for musicians. Built on a sample of Tarika Blue's \"Dreamflower,\" it has Dilla's famously \"drunk\" feel, with drums that seem to stagger slightly out of grid alignment and yet feel more human for it (more on this in the Sound section)."]},
      {"kind":"list","items":["**\"Green Eyes\"** is a ten-minute suite about jealousy and the end of a relationship. It moves through distinct sections, commonly described as denial, relapse, and acceptance, and shifts styles as the emotional state shifts, from torchy jazz ballad to something more unsettled. It is widely understood to concern her relationship with André 3000. Musically and emotionally it is one of her most ambitious works."]},
      {"kind":"list","items":["**\"A.D. 2000\"** is a quiet elegy for **Amadou Diallo**, the Guinean immigrant killed by New York police in 1999 after officers fired 41 shots. It anticipates the protest songs of the Black Lives Matter era by more than a decade."]},
      {"kind":"list","items":["**\"Penitentiary Philosophy\"** opens the album with rock distortion and anger, a deliberate announcement that this would not be *Baduizm 2*."]},
      {"kind":"callout","variant":"key","title":"Critical thesis:","text":"*Mama's Gun* is where Badu's two poles (the cosmic and the improvisatory, the priestess and the person) come into full balance. Many critics and musicians consider it her greatest album and one of the essential records of its era."},
      {"kind":"p","text":"**\"Love of My Life (An Ode to Hip-Hop)\" (2002)**"},
      {"kind":"p","text":"This duet with Common, then her partner, was recorded for the *Brown Sugar* soundtrack. It works as an extended metaphor, with hip-hop personified as a lover, and it won her fourth Grammy (**Best R&B Song**)."},
      {"kind":"p","text":"***Worldwide Underground* (2003): The Jam**"},
      {"kind":"p","text":"**Essential tracks:** \"Danger,\" \"Back in the Day (Puff),\" \"Love of My Life Worldwide,\" \"Bump It\""},
      {"kind":"p","text":"Loose, groove-oriented, and deliberately unfinished-sounding, *Worldwide Underground* was built with her band **Freakquency**. It feels like a jam session or an extended vamp. Some critics found it slight. Others hear it as a transitional record where Badu loosens song structure in preparation for the experiments to come. \"Love of My Life Worldwide\" features Queen Latifah, Angie Stone, and Bahamadia, a small summit of Black women in hip-hop and soul."},
      {"kind":"p","text":"A long gap followed. During this time J Dilla died in February 2006, of complications from TTP and lupus, a loss that reverberated through the whole Soulquarian community and through Badu's next work."},
      {"kind":"p","text":"***New Amerykah Part One (4th World War)* (2008): The Prophet Goes Electric**"},
      {"kind":"p","text":"**Essential tracks:** \"The Healer,\" \"Master Teacher,\" \"Soldier,\" \"Me,\" \"Telephone,\" \"The Cell,\" \"Twinkle,\" \"Amerykahn Promise,\" \"Honey\""},
      {"kind":"p","text":"**This is Badu's most radical album, and for many devotees her most important.**"},
      {"kind":"p","text":"Released on her 37th birthday, it abandons the warm live-band sound for something darker, denser, more electronic, and more collage-like. Her collaborators came from the experimental edge of hip-hop and beat culture: **Madlib, 9th Wonder, Sa-Ra Creative Partners, Shafiq Husayn, Karriem Riggins**, and longtime allies Questlove and James Poyser. The cover art by the poster artist **Emek** depicts Badu's afro as a teeming universe of symbols, politics, and cosmology, a literal visualization of the album's crowded mind."},
      {"kind":"p","text":"The album is explicitly political and diagnostic. It surveys poverty, addiction, state violence, religion, mental health, and the psychic toll of being Black in America."},
      {"kind":"list","items":["**\"The Healer\"** (produced by Madlib) proclaims that hip-hop is \"bigger than religion... bigger than the government.\" It argues that hip-hop functions as a kind of spiritual practice or folk religion for its community. That is a serious claim, and scholars of Black religion have made versions of it too."]},
      {"kind":"list","items":["**\"Master Teacher\"** contains the repeated phrase **\"I stay woke.\"** Badu didn't coin \"woke.\" The idea of staying awake to injustice runs back through Black vernacular at least to Lead Belly's 1938 commentary on the Scottsboro Boys. But her song is widely credited with **popularizing the phrase for a new generation**. It later fed directly into Black Lives Matter-era language, then passed into mainstream and eventually weaponized political discourse. When Merriam-Webster discussed the word's history, Badu's song was part of the story. (The song credits Georgia Anne Muldrow and Shafiq Husayn, whose earlier work it grows from.)"]},
      {"kind":"list","items":["**\"Telephone\"** is an elegy for J Dilla. It draws on accounts of his final days, with Ol' Dirty Bastard (who died in 2004) appearing as a kind of spirit guide calling to lead him home. It is one of the most moving songs in her catalog, and it introduces the **telephone** as a recurring Badu symbol: a device for connection across distance, even across death."]},
      {"kind":"list","items":["**\"Me\"** is a disarmingly frank self-portrait about aging, her body, her children and their different fathers, and her refusal to apologize for any of it."]},
      {"kind":"list","items":["**\"Soldier\"** and **\"The Cell\"** confront systemic violence and drug addiction head-on."]},
      {"kind":"list","items":["**\"Honey,\"** the hidden bonus track produced by 9th Wonder, has a famous video in which Badu recreates classic album covers in a record store. It is a love letter to Black music history."]},
      {"kind":"callout","variant":"key","title":"Why it matters:","text":"*New Amerykah Part One* anticipates the 2010s turn toward politically explicit, sonically experimental Black music: Kendrick Lamar's *To Pimp a Butterfly*, Solange's *A Seat at the Table*, Flying Lotus, Thundercat, the Brainfeeder aesthetic. It pulled the beat-scene avant-garde into the orbit of a major-label soul star."},
      {"kind":"p","text":"***New Amerykah Part Two (Return of the Ankh)* (2010): The Heart Side**"},
      {"kind":"p","text":"**Essential tracks:** \"Window Seat,\" \"Turn Me Away (Get MuNNY),\" \"Out My Mind, Just in Time,\" \"Gone Baby, Don't Be Long,\" \"Umm Hmm,\" \"Agitation\""},
      {"kind":"p","text":"If *Part One* was the mind and the world, *Part Two* is the heart. It is warmer, more analog, and largely about love. \"Return of the Ankh\" signals a return to her original iconography, but matured."},
      {"kind":"p","text":"**\"Out My Mind, Just in Time,\"** a ten-minute closer she produced herself, contains one of her great self-descriptions: \"I'm a recovering undercover over-lover.\" Love here is treated as something close to an addiction, a pattern to recover from, which ties the love songs back to *Part One*'s concern with compulsion and healing."},
      {"kind":"p","text":"**The \"Window Seat\" video** is her most famous (and infamous) piece of performance art. Badu walks through **Dealey Plaza in Dallas**, the site of John F. Kennedy's assassination, and removes her clothes piece by piece, filmed guerrilla-style in public. When she is fully nude, a gunshot rings out and she falls. Blue liquid spills from her head and forms the word **\"GROUPTHINK.\"** In a closing monologue she describes how people are quick to \"assassinate\" what they don't understand."},
      {"kind":"p","text":"The meaning is layered:"},
      {"kind":"list","items":["**Nudity as vulnerability**: stripping away persona, fashion, and armor.","**The assassination site**: linking her exposure to the violent destruction of public figures, and to Dallas's own history. It is her hometown's wound.","**Groupthink**: a critique of conformity and of how societies punish difference, especially in Black women's bodies."]},
      {"kind":"p","text":"She was charged with disorderly conduct and paid a fine. She credited the indie duo Matt and Kim's video \"Lessons Learned\" as an inspiration."},
      {"kind":"p","text":"The *New Amerykah* series was conceived as more than two parts. Further installments have been discussed over the years but never delivered as such."},
      {"kind":"p","text":"***But You Caint Use My Phone* (2015): The Mixtape Conceptualist**"},
      {"kind":"p","text":"**Essential tracks:** \"Cel U Lar Device,\" \"Phone Down,\" \"Hello\" (with André 3000), \"U Don't Have to Call,\" \"Mr. Telephone Man\""},
      {"kind":"p","text":"Released as a mixtape, this is a playful, cohesive, and underrated concept project built entirely around **the telephone**. It started as a response to Drake's \"Hotline Bling,\" which she remade as \"Cel U Lar Device.\""},
      {"kind":"p","text":"The title calls back to \"Tyrone\" (\"you can't use my phone\"). The project reimagines phone songs from across Black music history: New Edition's \"Mr. Telephone Man,\" Usher's \"U Don't Have to Call,\" and a reworking of \"Hello It's Me\" (Todd Rundgren, famously covered by the Isley Brothers) as a duet with **André 3000**, her former partner and the father of her son."},
      {"kind":"callout","variant":"key","title":"Thematic note:","text":"The phone runs through her catalog, from \"Tyrone\" to \"Telephone\" to this mixtape. It carries her abiding question about **connection and mediation**: how we reach each other, who gets access to us, how technology shapes intimacy, and, in \"Telephone,\" how the living and the dead stay in touch."},
      {"kind":"p","text":"**Since 2015**"},
      {"kind":"p","text":"Badu has been more active as a performer, host, curator, and provocateur than as a releaser of albums. She hosted the **Soul Train Awards** in 2015 and 2016. She collaborated widely, including Janelle Monáe's \"Q.U.E.E.N.\" (2013) and Flying Lotus's \"See Thru to U\" (2012), and a long-promised new album has been perpetually on the horizon. (For the latest releases, check current sources; announcements may have come after my knowledge.)"},
      {"kind":"p","text":"During the 2020 pandemic, she built **her own livestream concert platform** and sold tickets for a dollar. It was an early, savvy move toward artist-owned distribution while much of the industry scrambled. She also made headlines by selling incense marketed as smelling like her own vagina. It sold out almost immediately, and it was simultaneously a joke, a commentary on commodified female sexuality, and a masterclass in provocation-as-marketing."},
    ],
  },
  {
    heading: "V. The Sound: What Musicians Hear",
    blocks: [
      {"kind":"p","text":"**The Voice**"},
      {"kind":"p","text":"**Beginner version:** Badu's voice is thin-ish, reedy, and nasal. She doesn't belt like Whitney Houston or Aretha Franklin. Her power comes from *phrasing*, meaning where she puts the words, rather than volume."},
      {"kind":"p","text":"**Deeper:**"},
      {"kind":"list","items":["**Timbre:** a bright, slightly pinched upper-register tone, with a jazz singer's control over breath and attack. The Billie Holiday comparison is about *character* more than imitation: an intimate voice with deliberate \"flaws\" that make it human.","**Behind-the-beat phrasing:** she routinely places syllables slightly late, which creates a relaxed, conversational, almost lazy feel that is actually highly controlled. This is a jazz trait, and it pairs perfectly with the Soulquarian rhythmic aesthetic.","**Rhythmic speech-song:** her hip-hop background shows in how she treats lyrics as rhythm, sometimes approaching rap cadence, often halfway between singing and talking.","**Minimal melisma:** unlike the gospel-rooted R&B runs dominant in the 1990s, Badu uses ornamentation sparingly. The restraint was part of her distinctiveness.","**Scat and vocables:** the \"Badu\" in her name is literally a scat syllable, and she improvises nonverbal vocal lines as texture."]},
      {"kind":"p","text":"**Dilla Time and the Soulquarian Feel**"},
      {"kind":"p","text":"This is where serious music nerds light up."},
      {"kind":"p","text":"**J Dilla** (James Dewitt Yancey, 1974–2006) pioneered a rhythmic approach, programmed on the Akai MPC with quantization turned off or manipulated, in which drum hits land *slightly off the grid*. Kicks might rush a hair while snares drag, so that different rhythmic \"clocks\" coexist in a single groove. The effect is a tipsy, swaying, deeply human feel, sometimes described as \"drunk\" drumming."},
      {"kind":"p","text":"The journalist **Dan Charnas**, in *Dilla Time* (2022), argues this was a genuine rhythmic innovation: a third feel beyond \"straight\" and \"swung\" time, which blends and tensions the two. Live drummers like **Questlove** and **Chris Dave** then learned to *play* that programmed feel on acoustic kits, and a whole generation of musicians internalized it."},
      {"kind":"p","text":"Badu's behind-the-beat vocals are ideal for this. On \"Didn't Cha Know\" and throughout *Mama's Gun*, voice and groove occupy the same slightly-off, elastic time space. That shared microtiming is a large part of why the Soulquarian records feel the way they do."},
      {"kind":"p","text":"**Harmony and Texture**"},
      {"kind":"list","items":["**Rhodes piano and extended jazz chords** (9ths, 11ths, 13ths), especially via James Poyser.","**Upright or warm electric bass**, often Pino Palladino in the Soulquarian era, playing melodically and behind the beat.","**Analog warmth**: tape, vintage gear, and room sound. Badu has long favored an \"analog\" aesthetic even in her electronic phases.","**Collage and sampling** on the *New Amerykah* records, where the approach becomes more fragmented and layered, closer to beat-tape culture and musique concrète than to conventional soul arranging."]},
      {"kind":"p","text":"**Badu as Producer and Auteur**"},
      {"kind":"p","text":"It's easy to credit her famous collaborators and miss this: **Badu is a producer and conceptual director of her own work.** She co-produced much of her catalog, produced \"Out My Mind, Just in Time\" herself, and sets the vision across albums, visuals, and live shows. She is best understood as an **auteur** in the film-theory sense. The work bears one governing sensibility across its many collaborators."},
    ],
  },
  {
    heading: "VI. The Big Ideas",
    blocks: [
      {"kind":"p","text":"**1. Self-Authorship and Sovereign Identity**"},
      {"kind":"p","text":"From the renaming onward, Badu insists that the self is something you *create*. She has taken on multiple names and personas (Erykah Badu, Lo Down Loretta Brown, Sarah Bellum), each a facet of self-construction. This connects to the Five Percent teaching of self-knowledge as divinity, and to broader Black traditions of self-fashioning under conditions that tried to deny Black personhood."},
      {"kind":"p","text":"**2. Metaphysics: Five Percent, Kemet, Numerology, and the Cosmos**"},
      {"kind":"p","text":"Badu's spiritual vocabulary is **syncretic**, a blend of traditions rather than loyalty to one:"},
      {"kind":"list","items":["**Five Percent / Supreme Mathematics** language, especially early on","**Kemetic (ancient Egyptian) symbolism**: the ankh (life) and the *ka*","**Numerology and astrology**: she speaks fluently in these idioms","**Afrofuturism**: the cosmic imagery of *New Amerykah* connects her to Sun Ra, George Clinton's Parliament-Funkadelic mothership mythology, and Octavia Butler"]},
      {"kind":"callout","variant":"key","title":"Scholarly framing:","text":"Afrofuturism, a term coined by Mark Dery in 1993 and developed by thinkers like Kodwo Eshun and Alondra Nelson, describes Black artists' use of science fiction, technology, and cosmic myth to imagine Black futures and reinterpret Black pasts. Badu's work, especially the *New Amerykah* era, sits squarely in this tradition. She pairs an imagined ancient African past (Kemet) with a cosmic future to escape the confines of an American present that has been hostile to Black life."},
      {"kind":"p","text":"**3. Healing: The Doula as Artistic Model**"},
      {"kind":"p","text":"Badu is a trained **birth doula** and has also practiced as a **death doula**, supporting people through the end of life. This is not a side hobby. It is arguably the master metaphor for her art."},
      {"kind":"p","text":"A doula doesn't deliver the baby or cure the disease. A doula *accompanies* and *holds space* through a threshold. Badu's music often works this way. \"Bag Lady\" doesn't fix your trauma, it sits with you and encourages release. \"Telephone\" doesn't resurrect Dilla, it accompanies his passage. \"The Healer\" frames hip-hop as communal medicine."},
      {"kind":"p","text":"**She conceives of the artist as someone who presides at thresholds: birth, death, heartbreak, awakening.**"},
      {"kind":"p","text":"**4. Love as Recovery**"},
      {"kind":"p","text":"Across *Mama's Gun* and *Part Two*, romantic love appears as something close to addiction: compulsive, cyclical, and in need of recovery (\"recovering undercover over-lover\"). This is more psychologically sophisticated than standard R&B love songs. She treats relationships as patterns to understand and outgrow, not just fates to celebrate or mourn."},
      {"kind":"p","text":"Her publicly discussed relationships and co-parenting with the fathers of her three children (André 3000, The D.O.C., and Jay Electronica) are often framed by her as extended family rather than failure. That is a quiet challenge to the nuclear-family script, and she speaks about it openly in songs like \"Me.\""},
      {"kind":"p","text":"**5. Political Consciousness: \"Stay Woke\"**"},
      {"kind":"p","text":"From \"A.D. 2000\" to *New Amerykah Part One*, Badu has made explicitly political art about police violence, poverty, addiction, and systemic racism. Her popularization of **\"stay woke\"** is among her most consequential cultural contributions, though the phrase's later journey (from Black vernacular to protest slogan to partisan pejorative) is a case study in how Black language gets absorbed and distorted by mainstream discourse."},
      {"kind":"p","text":"**6. The Black Woman's Body as Contested Site**"},
      {"kind":"p","text":"The \"Window Seat\" nudity, \"Me\" and its frank talk about her body and aging, and the incense stunt all use provocation to confront how Black women's bodies are looked at, judged, sexualized, and policed. Badu seizes control of the gaze by staging her own exposure, on her own terms."},
      {"kind":"p","text":"**7. Humor and the Trickster**"},
      {"kind":"p","text":"This is the most underrated dimension. \"Tyrone.\" The incense. The deadpan interviews. The oversized hats. Badu is **funny**, and the humor is structural, not incidental. In West African and African American folklore, the **trickster** (Anansi, Esu/Eshu, Br'er Rabbit) disrupts order, speaks truth sideways, and survives through wit. Badu's persona draws heavily on this archetype. Her seriousness is always slightly winking, and her jokes are always slightly serious. Missing the humor means misreading her entirely."},
    ],
  },
  {
    heading: "VII. On \"Neo-Soul\": The Label and the Escape",
    blocks: [
      {"kind":"p","text":"**Beginner version:** \"Neo-soul\" describes a late-1990s wave of R&B artists (D'Angelo, Erykah Badu, Lauryn Hill, Maxwell, Jill Scott, Musiq Soulchild, India.Arie) who drew on 1970s soul, jazz, and hip-hop, in contrast to the slicker, more pop-driven R&B of the time."},
      {"kind":"p","text":"**Deeper:** The term was coined as a marketing category, largely credited to Kedar Massenburg, Badu's own label boss. It helped sell records by giving critics and retailers a frame. But it also:"},
      {"kind":"list","items":["**flattened** very different artists into one aesthetic of headwraps, incense, and \"real instruments\"","**implied authenticity politics**, positioning this music as more \"real\" or \"conscious\" than mainstream R&B, a hierarchy that could be condescending to other Black popular music","**suggested revivalism**, when artists like Badu were forward-looking"]},
      {"kind":"p","text":"Badu has expressed discomfort with the label over the years, and her career trajectory is essentially an escape from it. *New Amerykah* sounds nothing like the neo-soul template. Scholars like Mark Anthony Neal (*Songs in the Key of Black Life*) and Emily Lordi (*The Meaning of Soul*) have written thoughtfully about how \"soul\" operates as both aesthetic and ideology, a useful frame for thinking about what the neo-soul label did and didn't capture."},
    ],
  },
  {
    heading: "VIII. Visual Language and Fashion",
    blocks: [
      {"kind":"list","items":["**The headwrap era (1997–2000):** towering, sculptural headwraps became her signature, evoking African diasporic tradition, Afrocentric consciousness, and regal self-possession. The look was so iconic it became shorthand for \"neo-soul\" itself.","**The hats:** later, famously enormous hats, a playful escalation of the headwrap's architecture.","**High fashion:** she fronted a **Givenchy** campaign under Riccardo Tisci (2014) and remains a reference point for designers and stylists.","**Iconography:** ankhs, crystals, incense, cosmic symbols. Her visual world is as carefully built as her sonic one."]},
      {"kind":"p","text":"Badu treats fashion as **semiotic**: clothing as a system of signs communicating identity, lineage, and mood. It is costume in the theatrical sense. That makes sense for a theater-trained artist."},
    ],
  },
  {
    heading: "IX. Complications and Controversies",
    blocks: [
      {"kind":"p","text":"A serious account can't be purely celebratory. Badu has drawn significant criticism:"},
      {"kind":"list","items":["**2018 remarks:** in a *Vulture* interview she said she saw \"something good\" in Hitler, framing it as her belief in seeing good in everyone, and she also made comments seen as sympathetic toward R. Kelly. Both drew widespread backlash.","**2016 comments** about schoolgirls' skirt lengths were criticized as victim-blaming, and she pushed back on that reading.","**The Flaming Lips dispute (2012):** a collaborative cover of \"The First Time Ever I Saw Your Face\" produced a video, featuring her sister, that Badu said was released without her approval of the final cut, leading to a public falling-out with Wayne Coyne."]},
      {"kind":"p","text":"**How to hold this:** Badu's philosophy of radical nonjudgment, provocation, and contrarian spirituality is part of what makes her art powerful. It can also produce statements that are careless, harmful, or that shield bad actors. Her trickster persona does not exempt her from accountability. A mature reading acknowledges both: the same impulses that produced \"Window Seat\" also produced some of her worst public moments."},
    ],
  },
  {
    heading: "X. Legacy and Influence",
    blocks: [
      {"kind":"list","items":["**On artists:** her fingerprints are on Solange, SZA, Jhené Aiko, Janelle Monáe, H.E.R., Little Simz, and much of the alternative R&B wave of the 2010s. The permission to be weird, cosmic, political, and funny inside R&B traces substantially back to her.","**On sound:** *New Amerykah Part One* helped bridge major-label soul and the experimental beat scene (Madlib, Flying Lotus, Sa-Ra), prefiguring the sound of *To Pimp a Butterfly* and the Brainfeeder era.","**On language:** \"Stay woke.\"","**On the model of the artist:** Badu showed that a Black woman in R&B could be an **auteur**, **conceptual artist**, and **public intellectual**, not only a voice for hire. She owns her persona, directs her visuals, and builds platforms.","**On community:** she founded **B.L.I.N.D.** (Beneficial Life In Neighborhood Development), a nonprofit supporting arts and community development in South Dallas, and she remains rooted in her hometown."]},
    ],
  },
  {
    heading: "XI. Listening Guide",
    blocks: [
      {"kind":"p","text":"**For Beginners: Ten Songs, in Order**"},
      {"kind":"list","ordered":true,"items":["**\"On & On\"** (1997): the thesis statement","**\"Next Lifetime\"** (1997): the dreamy, romantic side","**\"Tyrone\"** (1997, *Live*): the humor","**\"You Got Me\"** (The Roots feat. Erykah Badu, 1999): the hip-hop crossover","**\"Bag Lady\"** (2000): the healer","**\"Didn't Cha Know\"** (2000): the Dilla groove","**\"Love of My Life (An Ode to Hip-Hop)\"** (with Common, 2002): the love letter","**\"Honey\"** (2008): the joy, and watch the video","**\"Window Seat\"** (2010): the provocateur, and watch the video","**\"Hello\"** (with André 3000, 2015): the full-circle moment"]},
      {"kind":"p","text":"**Then: Albums in This Order**"},
      {"kind":"p","text":"*Baduizm* → *Mama's Gun* → *New Amerykah Part One* → *New Amerykah Part Two* → *Live* → *But You Caint Use My Phone* → *Worldwide Underground*"},
      {"kind":"p","text":"**For the Geeks: Deep Cuts and Study Pieces**"},
      {"kind":"list","items":["**\"Green Eyes\"**: study the suite form and how the arrangement tracks emotional stages","**\"Otherside of the Game\"**: moral ambiguity, plus The Roots' live-hip-hop feel","**\"A.D. 2000\"**: a protest song a decade ahead of its time","**\"The Healer\"**: Madlib's production and the hip-hop-as-religion argument","**\"Telephone\"**: elegy, Dilla lore, and the phone motif","**\"Master Teacher\"**: \"stay woke\" at the source, and its Georgia Anne Muldrow lineage","**\"Out My Mind, Just in Time\"**: Badu as producer, and love as addiction","**\"Cleva\"** (with Roy Ayers): jazz-soul lineage made explicit","**\"The Cell\"**: addiction and the prison-industrial complex"]},
    ],
  },
  {
    heading: "XII. Quick Reference",
    blocks: [
      {"kind":"list","items":["**Birth name** — Erica Abi Wright","**Born** — February 26, 1971, Dallas, Texas","**Education** — Booker T. Washington HS for the Performing & Visual Arts; Grambling State University (theater)","**Grammys (4)** — Best R&B Album (*Baduizm*); Best Female R&B Vocal Performance (\"On & On\"); Best Rap Performance by a Duo or Group (\"You Got Me,\" with The Roots); Best R&B Song (\"Love of My Life\")","**Children** — Seven (b. 1997, with André 3000); Puma (b. 2004, with The D.O.C.); Mars (b. 2009, with Jay Electronica)","**Collectives** — Soulquarians; bands Freakquency and The Cannabinoids","**Aliases** — Lo Down Loretta Brown (DJ), Sarah Bellum","**Other roles** — Birth and death doula, actress, DJ, activist, founder of B.L.I.N.D."]},
    ],
  },
  {
    heading: "XIII. Further Reading",
    blocks: [
      {"kind":"list","items":["**Dan Charnas, *Dilla Time* (2022)**: the essential study of J Dilla's rhythmic innovation and the Soulquarian world","**Questlove, *Mo' Meta Blues* (2013)**: insider perspective on the Soulquarian era","**Emily J. Lordi, *The Meaning of Soul* (2020)**: soul as aesthetic and philosophy","**Mark Anthony Neal, *Songs in the Key of Black Life* (2003)**: cultural criticism of Black popular music including the neo-soul era","**Ytasha Womack, *Afrofuturism* (2013)**: an accessible introduction to the tradition Badu works within"]},
    ],
  },
  {
    heading: "Coda: The Unifying Idea",
    blocks: [
      {"kind":"p","text":"If you remember one thing, make it this: **Erykah Badu turns the self into a ceremony.** She names herself and renames herself. She dresses as meaning. She treats love as recovery, music as medicine, the phone as a line to the dead, and her own naked body as an argument. She moves between ancient Kemet and outer space, between the pulpit and the punchline, always slightly behind the beat, where the groove feels most human."},
      {"kind":"p","text":"She is an analog priestess who never stopped being a trickster. The best way to understand her is the way she understands everything else: don't just listen, stay woke."},
    ],
  },
];;
