import type { LessonSection } from "../curriculum";

export const sections: readonly LessonSection[] = [
  {
    heading: null,
    blocks: [
      {"kind":"p","text":"Start with the simplest possible picture. In a request-driven system, one component asks another to do something and waits for the answer: \"charge this card, tell me when you're done.\" In an event-driven system, a component instead announces that something has happened—\"an order was placed\"—and goes back to its business without knowing or caring who is listening. That shift, from *commanding* to *announcing*, is the whole idea. Everything else—brokers, partitions, consumer groups, idempotency, the outbox pattern—is machinery for making that idea reliable at scale."},
    ],
  },
  {
    heading: "Events, Commands, Messages",
    blocks: [
      {"kind":"p","text":"Vocabulary matters here because the words encode design decisions. An *event* is an immutable fact about the past, named in the past tense: `OrderPlaced`, `PaymentFailed`. It has already happened; nobody can veto it. A *command* is a request for something to happen in the future: `PlaceOrder`, `ChargeCard`. It has one intended recipient and can be rejected. A *message* is the generic envelope that carries either. People sloppily say \"events\" for everything flowing through a broker, but the distinction is load-bearing: events decouple, commands couple. If your \"events\" are secretly instructions to a specific downstream service, you have a request-driven system wearing a costume, with all the coupling and none of the simplicity."},
      {"kind":"p","text":"Events come in flavors too. A *notification event* carries just enough to say \"something changed, come look\" (an ID and a type). A *state-transfer event* carries the full relevant state so consumers never have to call back. The first keeps payloads small but reintroduces synchronous coupling through the callback; the second trades bandwidth and schema discipline for genuine autonomy. A *domain event* is a business-meaningful fact from your bounded context's own language; an *integration event* is the deliberately stable, versioned version of that fact you publish for other teams. Conflating the two means your internal refactors break strangers."},
    ],
  },
  {
    heading: "Producers, Consumers, Brokers, Topics",
    blocks: [
      {"kind":"p","text":"A *producer* (or publisher) emits messages. A *consumer* (or subscriber) receives them. Between them sits a *broker*—Kafka, NATS, RabbitMQ, Pulsar, SQS—whose job is to accept messages, store them for some duration, and hand them to interested parties. Messages are organized into named channels: *topics* in Kafka, *subjects* in NATS, *exchanges* and *queues* in RabbitMQ. The broker is what turns point-to-point coupling into a hub, and its durability characteristics are what determine whether your architecture survives a consumer being down for an hour."},
      {"kind":"p","text":"Two fundamental delivery topologies exist. In a *queue* (point-to-point), each message is consumed by exactly one of possibly many competing workers—this is how you scale out processing. In *publish-subscribe*, each message is delivered to every interested subscriber—this is how you fan out a fact to independent concerns like billing, analytics, and notifications. Modern systems blend these: Kafka's consumer groups give you pub-sub *across* groups and queue semantics *within* a group."},
    ],
  },
  {
    heading: "Kafka's Mental Model: The Log",
    blocks: [
      {"kind":"p","text":"Kafka is best understood not as a message queue but as a distributed, append-only, replicated *commit log*. A topic is split into *partitions*; each partition is an ordered, immutable sequence of records, each identified by a monotonically increasing *offset*. Producers append; consumers read by offset. Crucially, consuming does not delete—records stay until a retention policy (time- or size-based) removes them, or indefinitely with *log compaction*, which retains only the latest record per key, turning a topic into a changelog that can rebuild a table from scratch."},
      {"kind":"p","text":"Ordering is guaranteed only *within a partition*. A producer chooses the partition, typically by hashing a *key*: all events for `customer-42` land on the same partition and are therefore totally ordered relative to each other. Across partitions there is no ordering at all. This is the single most important fact about Kafka, and the source of most subtle bugs. If you need `OrderPlaced` to precede `OrderShipped` for the same order, they must share a key. If you later increase the partition count, the hash mapping changes and ordering across the resize boundary breaks—so partition counts are decided carefully and early."},
      {"kind":"p","text":"A *consumer group* is a set of consumer instances sharing a group ID; Kafka assigns each partition to exactly one member of the group, so parallelism is bounded by partition count. When members join or leave, a *rebalance* reassigns partitions—historically a stop-the-world event, now mitigated by cooperative/incremental rebalancing and static membership. Each group tracks its own *committed offsets* (stored in an internal `__consumer_offsets` topic), which is how two independent groups can read the same topic at different speeds. *Consumer lag*—the gap between the latest offset and the committed offset—is the primary health metric of any Kafka system."},
      {"kind":"p","text":"Replication works via a *leader* and *followers* per partition. Followers that are caught up form the *in-sync replica set* (ISR). The producer's `acks` setting defines durability: `acks=0` fire-and-forget, `acks=1` leader-only, `acks=all` wait for the ISR. Paired with `min.insync.replicas`, this gives you a tunable guarantee: with replication factor 3 and `min.insync.replicas=2`, you can lose one broker without losing acknowledged data. The *idempotent producer* adds sequence numbers so broker-side retries don't duplicate records, and *transactions* let a producer atomically write to multiple partitions and commit consumer offsets in the same unit—the foundation of Kafka's \"exactly-once\" semantics, which really means exactly-once *within the Kafka ecosystem*, not between Kafka and your database."},
      {"kind":"p","text":"Around the core sit *Kafka Connect* (declarative source/sink connectors), *Kafka Streams* and *ksqlDB* (stream processing as a library or SQL), and the *Schema Registry* (Avro/Protobuf/JSON Schema with compatibility enforcement). Older clusters depended on ZooKeeper for metadata; *KRaft* replaces it with a built-in Raft quorum."},
    ],
  },
  {
    heading: "NATS's Mental Model: The Subject Space",
    blocks: [
      {"kind":"p","text":"NATS starts from the opposite philosophy: radical simplicity and low latency. Core NATS is a fire-and-forget pub-sub fabric with no persistence—if no subscriber is listening when a message is published, the message is gone. Messages flow on *subjects*, hierarchical dot-separated strings like `orders.eu.created`, and subscribers use wildcards: `*` matches one token, `>` matches the rest. This makes routing a function of naming rather than configuration, which is powerful: you don't provision topics, you just publish. *Queue groups* give load-balanced delivery among competing subscribers. *Request-reply* is a first-class pattern built on ephemeral inbox subjects, making NATS a credible RPC substrate, not just an event bus."},
      {"kind":"p","text":"*JetStream* is the persistence layer added on top. A *stream* captures messages from one or more subjects and stores them with configurable retention (limits-based, interest-based, or work-queue), replication (Raft, up to 5 replicas), and storage (file or memory). *Consumers* in JetStream are server-side cursors over a stream, either *push* (server delivers) or *pull* (client fetches batches, now the recommended mode). Consumers can be *durable* (position survives disconnects) or *ephemeral*. Acknowledgment is per message, with *ack*, *nak*, *in-progress*, and *term* semantics, plus automatic redelivery after an ack wait—closer to a classic queue than Kafka's offset-commit model, and far more forgiving for heterogeneous processing times. JetStream also provides *Key-Value* and *Object Store* abstractions built on streams, and deduplication via a message-ID header within a window."},
      {"kind":"p","text":"The practical contrast: Kafka optimizes for enormous throughput, long retention, replayable history, and stream processing, at the cost of operational weight and a partition-centric model you must design around. NATS optimizes for latency, simplicity, edge and multi-tenant deployments (leaf nodes, superclusters, accounts), and flexible subject-based routing, with persistence as an opt-in layer rather than the core identity. Neither is \"better\"; they answer different questions."},
    ],
  },
  {
    heading: "Delivery Guarantees and the Impossibility at the Heart of It",
    blocks: [
      {"kind":"p","text":"Every broker advertises a delivery guarantee: *at-most-once* (may lose, never duplicates), *at-least-once* (never loses, may duplicate), or *exactly-once*. The honest truth is that exactly-once delivery across a network boundary is impossible in general—the Two Generals problem guarantees that an acknowledgment can always be lost, forcing a choice between retry (duplicate) or give up (loss). What systems actually deliver is *at-least-once delivery plus idempotent processing*, which produces *effectively-once* outcomes. Idempotency means processing the same message twice yields the same state as once. You achieve it with natural idempotent operations (set balance to X rather than add 10), deduplication tables keyed by message ID, conditional writes with version numbers, or by folding the deduplication into the state itself. Every serious consumer must be written assuming redelivery. This is not a corner case; it is the normal operating condition during rebalances, restarts, and timeouts."},
      {"kind":"p","text":"Ordering interacts with this. *Head-of-line blocking* occurs when one unprocessable message holds up everything behind it in a partition. The standard remedy is a *dead-letter queue* (DLQ): park the poison message elsewhere, alert, and move on—accepting that you've now broken strict ordering for that key. Retry strategies with *exponential backoff and jitter*, and *retry topics* with escalating delays, sit between naive retry and DLQ."},
    ],
  },
  {
    heading: "The Dual-Write Problem and the Outbox Pattern",
    blocks: [
      {"kind":"p","text":"Here is the bug that every team eventually discovers. A service handles a request: it writes a row to its database, then publishes an event to the broker. If the database commit succeeds and the publish fails, downstream systems never learn about the change. If you publish first and the commit fails, downstream systems learn about something that didn't happen. Wrapping both in a try/catch does not help; the process can crash between the two operations. This is the *dual-write problem*, and it cannot be solved by ordering the two writes cleverly, because there is no distributed transaction spanning a database and a broker (two-phase commit exists in theory and is avoided in practice for good reasons)."},
      {"kind":"p","text":"The *transactional outbox pattern* solves it by refusing to do two writes. Inside the same local database transaction that modifies business state, the service also inserts a row into an `outbox` table containing the event to be published—payload, headers, destination, a unique ID. Both succeed or both fail atomically, because they're one transaction in one database. A separate process, the *relay* or *message relay*, then reads unpublished outbox rows and publishes them to the broker, marking them sent. If the relay crashes after publishing but before marking, it will republish—so the pattern yields at-least-once, and consumers must be idempotent (the outbox row's ID becomes the deduplication key)."},
      {"kind":"p","text":"The relay can be implemented two ways. *Polling* simply queries the outbox table periodically; it is simple and portable but adds latency and database load, and requires care to avoid two relay instances publishing the same rows (use `SELECT ... FOR UPDATE SKIP LOCKED` or a single leader). *Change Data Capture* (CDC) instead tails the database's write-ahead log or binlog—Debezium is the canonical tool—and streams every committed row change into Kafka with no polling and minimal latency. Pointing CDC at the outbox table gives you the *outbox with CDC* pattern, which is the de facto standard for serious systems: Debezium's outbox event router even unwraps the row into a clean event with the right topic and key. The outbox table itself is append-and-delete; rows are purged after successful publication, or the CDC approach lets you delete immediately after insert in the same transaction, since the log change is what matters."},
      {"kind":"p","text":"The mirror image is the *inbox pattern* (or idempotent consumer): a consumer records each processed message ID in a table within the same transaction as its own state change, and skips any ID already present. Outbox on the producing side and inbox on the consuming side together give end-to-end effectively-once semantics with nothing but local ACID transactions."},
      {"kind":"p","text":"Related but distinct: the *listen-to-yourself* pattern publishes first and lets the service itself consume the event to update its own database, which makes the broker the source of truth and the database a projection. And the *saga* pattern coordinates multi-service workflows through sequences of local transactions and compensating actions, either by *choreography* (each service reacts to events and emits its own) or *orchestration* (a central coordinator sends commands and tracks state). Choreography is loosely coupled but hard to observe; orchestration is explicit but concentrates logic."},
    ],
  },
  {
    heading: "Event Sourcing and CQRS",
    blocks: [
      {"kind":"p","text":"Push the log idea to its conclusion and you arrive at *event sourcing*: rather than storing current state and emitting events as a side effect, you store *only* the events and derive state by replaying them. The event stream is the system of record. This gives perfect audit trails, temporal queries (\"what did this account look like last Tuesday\"), and the ability to build new read models retroactively. It costs you: schema evolution becomes a forever problem (old events never go away), replays need *snapshots* to stay fast, and querying across aggregates is awkward—which is why event sourcing is almost always paired with *CQRS* (Command Query Responsibility Segregation), where writes go through the event-sourced model and reads go through separately maintained *projections* optimized for each query. Note that Kafka, despite its log nature, is a poor event store for per-aggregate loads because it cannot efficiently read \"all events for aggregate 42\" without scanning a partition; purpose-built stores (EventStoreDB, or a database table) do that better, with Kafka as the distribution fabric."},
    ],
  },
  {
    heading: "Schemas, Evolution, and Contracts",
    blocks: [
      {"kind":"p","text":"Because events outlive the code that wrote them, the schema is the contract. *Backward compatibility* means new consumers can read old events; *forward compatibility* means old consumers can read new events; *full* means both. The practical rules: only add optional fields, never rename or change types, never repurpose a field's meaning. A schema registry enforces this at publish time. Events should carry an *envelope* with metadata—event ID, type, version, timestamp, *correlation ID* (tying together everything caused by one originating request) and *causation ID* (the immediate parent event)—because distributed tracing across asynchronous hops is otherwise hopeless. CloudEvents is a vendor-neutral standard for this envelope."},
    ],
  },
  {
    heading: "Consistency, Time, and Backpressure",
    blocks: [
      {"kind":"p","text":"Event-driven systems are *eventually consistent*: after an event, different services agree *eventually*, not instantly. A user who places an order and immediately refreshes may not see it in a projection updated asynchronously. Mitigations include *read-your-writes* via the write path, optimistic UI, or routing the user's read to the service that owns the write. Understand that this is not a flaw to be eliminated but a property to be designed around; the alternative is global locking, which doesn't scale."},
      {"kind":"p","text":"Time itself fragments. *Event time* (when it happened) differs from *processing time* (when a consumer handled it), and events arrive out of order across partitions and sources. Stream processors handle this with *watermarks* (a heuristic claim that no events older than T will arrive) and *windows* (tumbling, sliding, session) with *allowed lateness*. If your aggregation logic ignores this distinction, your dashboards are quietly wrong."},
      {"kind":"p","text":"*Backpressure* is what happens when producers outrun consumers. Pull-based models (Kafka, JetStream pull consumers) naturally handle it—the consumer takes what it can. Push-based models need explicit flow control or they overwhelm slow receivers. Unbounded queues don't solve backpressure; they defer it until memory or disk runs out."},
    ],
  },
  {
    heading: "When Not To",
    blocks: [
      {"kind":"p","text":"Finally, the uncomfortable part. Event-driven architecture buys decoupling, resilience, scalability, and auditability. It charges for them in debuggability (where did this state come from?), operational complexity (a broker is a stateful distributed system you now own), cognitive load (every developer must understand idempotency, ordering, and eventual consistency), and the seductive ease of adding one more consumer until the event graph is an unreadable tangle nobody can change. A monolith with a well-structured domain and a synchronous call is frequently the right answer. Reach for events when you have genuinely independent consumers of a fact, when temporal decoupling matters (the consumer may be down, or slow, or not yet written), when you need replay or audit, or when the throughput demands it. Reach for the outbox the moment you find yourself writing to a database and a broker in the same handler—which is to say, almost immediately."},
    ],
  },
];;
