import type { LessonSection } from "../curriculum";

export const sections: readonly LessonSection[] = [
  {
    heading: "Introduction: Why Think About the Future at All?",
    blocks: [
      {"kind":"p","text":"The future cannot be studied the way the past can, because it has left no fossils, documents, or data. Yet serious thinkers have built a discipline around it, variously called *futures studies*, *foresight*, or *long-term thinking*. Its goal is not prophecy. The honest futurist does not ask \"what *will* happen?\" but \"what *could* happen, what is *likely*, and what do we *want*?\""},
      {"kind":"p","text":"A useful mental model is the **futures cone**, popularized by the foresight researcher Joseph Voros. Imagine standing at the tip of a cone that widens as it extends forward in time. The widest region holds *possible* futures, anything not forbidden by physics. Inside that sits a narrower band of *plausible* futures, consistent with what we know about how societies and technologies behave. Inside that is the *probable*, the default trajectory if current trends continue. Somewhere in the cone, not necessarily overlapping the probable, lies the *preferable*: the futures we would actually choose. Much of the intellectual action in this field is about closing the gap between the probable and the preferable."},
      {"kind":"p","text":"This lesson covers the major concepts in that conversation: the scale of time involved, the tools for reasoning about change, the risks that could end the story early, the technologies that could rewrite it, and the ethical questions about what we owe to people who do not yet exist."},
    ],
  },
  {
    heading: "Part I: Thinking Tools, or How Not to Be Wrong About Tomorrow",
    blocks: [
      {"kind":"p","text":"Before looking at specific scenarios, it helps to understand the cognitive traps that make forecasting hard."},
      {"kind":"p","text":"The first is the **linear intuition problem**. Human brains evolved to extrapolate in straight lines: the gazelle runs at a steady speed, the seasons repeat. Many of the forces shaping modernity are instead *exponential*. For roughly half a century, the number of transistors on a chip doubled about every two years, a pattern known as **Moore's Law**. Thirty doublings is not thirty times larger; it is about a billion times larger. When people underestimate technological change, they are usually thinking linearly about an exponential process."},
      {"kind":"p","text":"The opposite error is just as common. Almost no real-world exponential continues forever. Growth typically follows an **S-curve** (a logistic curve): slow at first, explosive in the middle, then flattening as it hits physical or economic limits. Passenger aircraft speeds rose dramatically from 1903 to the 1960s and then plateaued; the Concorde was retired in 2003, and today's airliners fly no faster than those of 1970. The hard part of forecasting is telling whether you are standing at the bottom of an S-curve, where the exponential is about to take off, or near the top, where it is about to stall."},
      {"kind":"p","text":"These two errors combine in what is called **Amara's Law**, after the researcher Roy Amara: *we tend to overestimate the effect of a technology in the short run and underestimate it in the long run.* The internet was overhyped in 1999, when the dot-com bubble burst, and underhyped relative to what it had become by 2019."},
      {"kind":"p","text":"A third tool is **base-rate reasoning**. Before asking whether a particular new technology will transform society, ask how often technologies that looked this promising actually did. Most confident predictions of flying cars, fusion \"within twenty years,\" and the imminent end of work have missed. That does not mean transformative change is impossible. It means extraordinary claims deserve calibrated skepticism. The research of Philip Tetlock on \"superforecasters\" shows that the best predictors think probabilistically, update frequently, and avoid grand ideological narratives."},
    ],
  },
  {
    heading: "Part II: Deep Time, or How Much Future Is There?",
    blocks: [
      {"kind":"p","text":"To appreciate what is at stake, consider the timescales. *Homo sapiens* has existed for roughly 300,000 years. Agriculture is about 12,000 years old, writing about 5,000, and industrial civilization about 250. On a cosmic calendar, all of recorded history is a rounding error."},
      {"kind":"p","text":"Now look forward. The typical mammalian species survives about one million years. If humanity merely achieves an average lifespan for a mammal, we are perhaps a third of the way through our story. Earth itself will remain habitable for complex life for something like another *billion* years, until the Sun's slowly increasing brightness drives a runaway loss of the oceans. And if our descendants ever leave the solar system, the relevant timescale becomes the lifespan of stars: red dwarfs will continue burning for trillions of years."},
      {"kind":"p","text":"This is not idle stargazing. The sheer quantity of potential future is the foundation of an entire ethical framework, discussed in Part VII. If the future could contain vastly more people than have ever lived, then decisions made in our century, particularly decisions that could end that future, carry disproportionate weight."},
    ],
  },
  {
    heading: "Part III: Energy and the Kardashev Scale",
    blocks: [
      {"kind":"p","text":"One of the most elegant frameworks for thinking about civilizational progress comes from the Soviet astrophysicist Nikolai Kardashev, who in 1964 proposed classifying civilizations by the energy they command."},
      {"kind":"p","text":"A **Type I** civilization harnesses energy on the scale of its entire planet, roughly the total sunlight reaching Earth, on the order of 10¹⁷ watts. A **Type II** civilization captures the full output of its star, about 4 × 10²⁶ watts for our Sun. A **Type III** civilization commands the energy of an entire galaxy, around 10³⁷ watts."},
      {"kind":"p","text":"Where are we? Carl Sagan proposed a formula that interpolates between the types, and by that measure humanity, which consumes roughly 19 to 20 terawatts, sits at about **Type 0.73**. We are not yet a planetary-scale civilization."},
      {"kind":"p","text":"The Kardashev scale is a convenient shorthand in science fiction and in the search for extraterrestrial intelligence. The physicist Freeman Dyson suggested in 1960 that an advanced civilization might surround its star with orbiting collectors, now called a **Dyson sphere** or *Dyson swarm*, to capture its energy. Such a structure would glow in the infrared as waste heat, which gives astronomers something concrete to search for."},
      {"kind":"p","text":"The scale has a quiet assumption built in: that more energy use is what advancement looks like. Critics point out that a civilization might grow more capable while becoming *more efficient* rather than more energy-hungry, much as a modern smartphone outperforms a 1970s room-sized computer on a tiny fraction of the power. The Kardashev scale is best understood as one axis of progress, not the whole story."},
    ],
  },
  {
    heading: "Part IV: The Great Silence, from Fermi to the Great Filter",
    blocks: [
      {"kind":"p","text":"In 1950, over lunch at Los Alamos, the physicist Enrico Fermi reportedly asked a deceptively simple question: *\"Where is everybody?\"*"},
      {"kind":"p","text":"The reasoning behind the **Fermi Paradox** runs as follows. The Milky Way contains hundreds of billions of stars, many of them billions of years older than the Sun. Surveys by the Kepler space telescope suggest that planets are common and that a substantial fraction lie in habitable zones. Even at slow sub-light speeds, a spacefaring civilization could colonize the entire galaxy in a few million years, which is short compared with the galaxy's age. So if intelligent life is even moderately common, someone should have been here already. Yet we see no convincing evidence of anyone."},
      {"kind":"p","text":"In 1961, the astronomer Frank Drake organized the problem into the **Drake Equation**, which multiplies a chain of factors: the rate of star formation, the fraction of stars with planets, the number of habitable planets per system, and then the fractions on which life arises, becomes intelligent, and develops detectable technology, all multiplied by how long such civilizations last. The equation is less a calculator than a structured list of our ignorance. Several of its terms are uncertain by many orders of magnitude."},
      {"kind":"p","text":"The economist Robin Hanson sharpened the paradox in 1996 with the concept of the **Great Filter**. Somewhere along the path from dead chemistry to galaxy-spanning civilization, there must be at least one step that is extraordinarily improbable. The unsettling question is *where that filter lies*."},
      {"kind":"p","text":"If it lies **behind us**, for instance if the origin of life, or the jump to complex cells, or the emergence of intelligence is astronomically rare, then we are lucky survivors, and the road ahead may be relatively open. If it lies **ahead of us**, then something tends to destroy technological civilizations before they spread. That something could be self-inflicted war, runaway technology, or ecological collapse. This is why some thinkers have said, only half-jokingly, that finding simple fossilized life on Mars would be *bad* news. It would suggest that life arises easily, which pushes the filter forward in time, toward us."},
      {"kind":"p","text":"Other proposed resolutions include the **Rare Earth hypothesis** (complex life needs an improbable combination of planetary conditions), the **zoo hypothesis** (advanced civilizations deliberately avoid contact), and the observation that our search has barely begun. Pointing radio telescopes at a tiny fraction of the sky for a few decades is like dipping a glass into the ocean and concluding there are no fish."},
    ],
  },
  {
    heading: "Part V: Existential Risk and the Precipice",
    blocks: [
      {"kind":"p","text":"The Great Filter leads naturally to one of the most influential concepts in modern futures thinking: **existential risk**. The philosopher Nick Bostrom, writing in 2002, defined it as a risk that threatens either the extinction of Earth-originating intelligent life or the permanent and drastic curtailment of its potential."},
      {"kind":"p","text":"The distinction between a *catastrophe* and an *existential catastrophe* is crucial. A war that kills 90% of humanity is an unimaginable horror, but the survivors could, over centuries, rebuild. An event that kills 100%, or that locks civilization permanently into a dystopia, forecloses the entire future. The difference between 90% and 100% is not 10%. It is the difference between a wound and a death."},
      {"kind":"p","text":"In *The Precipice* (2020), the Oxford philosopher Toby Ord attempted to put rough numbers on these risks. His estimates are explicitly subjective, but they illustrate a key insight. **Natural risks** such as asteroid impacts and supervolcanoes are comparatively small, on the order of 1 in 10,000 per century. We know this partly because our species has survived about 3,000 centuries of them. **Anthropogenic risks**, those created by humans, are far larger. Ord estimated the risk from nuclear war and from climate change each at around 1 in 1,000 for existential outcomes specifically, engineered pandemics at 1 in 30, and unaligned artificial intelligence at 1 in 10. His overall estimate for existential catastrophe this century was about **1 in 6**, the odds of Russian roulette. He describes our era as \"the Precipice\": a period in which our power to destroy ourselves has outpaced our wisdom to avoid doing so."},
      {"kind":"p","text":"Bostrom later offered a vivid thought experiment called the **Vulnerable World Hypothesis**. Imagine human invention as drawing balls from an urn. Most balls are white (beneficial) or grey (mixed). What if somewhere in the urn is a *black ball*, a technology so cheap and destructive that its discovery almost inevitably destroys the civilization that finds it? Imagine, for example, if building a nuclear weapon required only household materials. We have not drawn a black ball yet, but we have no mechanism to put balls back once they are drawn."},
      {"kind":"p","text":"A related governance puzzle is the **Collingridge Dilemma**, named after the scholar David Collingridge. Early in a technology's development, it is easy to control but hard to know what harms it will cause. Once its impacts become clear, it is so entrenched that control is difficult. Social media is a textbook case."},
    ],
  },
  {
    heading: "Part VI: Transformative Technologies",
    blocks: [
      {"kind":"p","text":"**Artificial Intelligence and the Singularity**"},
      {"kind":"p","text":"In 1965, the statistician I. J. Good, who had worked with Alan Turing at Bletchley Park, described an **intelligence explosion**. An \"ultraintelligent machine\" could design even better machines, which would design better ones still, triggering runaway recursive improvement. Good concluded that such a machine would be \"the last invention that man need ever make, provided that the machine is docile enough to tell us how to keep it under control.\""},
      {"kind":"p","text":"The mathematician and science-fiction author Vernor Vinge called this the **Technological Singularity** in a 1993 essay, borrowing the physics term for a point beyond which our models break down, as at the center of a black hole. Ray Kurzweil popularized the idea further, famously forecasting 2045 as a date. The core claim is not about any particular year. It is that beyond a certain threshold of machine intelligence, the future becomes fundamentally unpredictable to unaugmented human minds."},
      {"kind":"p","text":"That final clause of Good's, about keeping the machine under control, has become a research field in its own right: **AI alignment**, the problem of ensuring that highly capable AI systems pursue goals that are actually beneficial to humans. The difficulty is subtler than evil robots. It is closer to the old folk tale of the genie that grants wishes too literally. A system optimizing hard for an imperfectly specified objective may pursue it in ways its designers never intended. Researchers call this *specification gaming* or *reward hacking*, and it already appears in simple machine-learning systems. Bostrom's **orthogonality thesis** adds that intelligence and goals are independent: a system can be arbitrarily smart while pursuing arbitrarily strange ends. His related concept of **instrumental convergence** holds that nearly any goal is better served by acquiring resources and avoiding being switched off, which makes those behaviors worth worrying about regardless of the system's ultimate purpose."},
      {"kind":"p","text":"Views on how soon, and how dangerous, advanced AI will be vary enormously among serious researchers. That variance is itself important information. It signals deep uncertainty, not settled consensus in either direction."},
      {"kind":"p","text":"**Biotechnology and Transhumanism**"},
      {"kind":"p","text":"**Transhumanism** is the view that humans can and should use technology to transcend current biological limitations: extending healthy lifespan, enhancing cognition, and perhaps eventually merging with machines or uploading minds to computers. Tools like CRISPR gene editing, which earned Jennifer Doudna and Emmanuelle Charpentier the 2020 Nobel Prize in Chemistry, have moved some of these conversations from speculation to policy."},
      {"kind":"p","text":"Critics raise concerns about inequality, since enhancement could become available only to the wealthy, and about the erosion of a shared human nature. Some bioethicists, such as Michael Sandel, argue that aspiring to engineer ourselves reflects a troubling drive for mastery. The debate often turns on where to draw the line between *therapy* (curing disease) and *enhancement* (exceeding normal function), a line that turns out to be surprisingly blurry."},
      {"kind":"p","text":"The same biotechnology that promises cures also feeds the engineered-pandemic risk discussed in Part V. The technologies of the future are almost universally **dual-use**."},
    ],
  },
  {
    heading: "Part VII: The Humans Themselves, Demographics and Values",
    blocks: [
      {"kind":"p","text":"**The Population Turn**"},
      {"kind":"p","text":"For most of the twentieth century, the dominant fear was *overpopulation*. Paul Ehrlich's 1968 bestseller *The Population Bomb* predicted mass famines in the 1970s and 1980s. These largely did not materialize, thanks in part to the agricultural **Green Revolution**. Ehrlich's famous 1980 bet with the economist Julian Simon, over whether the prices of five metals would rise over the following decade, ended in Simon's favor. The episode became emblematic of a debate between resource pessimists and innovation optimists that continues today."},
      {"kind":"p","text":"The emerging demographic story is almost the reverse. Nearly every society that industrializes goes through the **demographic transition**: death rates fall first, then birth rates follow. The global total fertility rate has fallen from about 5 children per woman in 1960 to roughly 2.3 today. Many nations are now far below the replacement level of about 2.1; South Korea's rate dropped to about 0.72 in 2023, the lowest ever recorded for a country. The United Nations projects world population will peak at around 10.3 billion in the mid-2080s and then begin to decline."},
      {"kind":"p","text":"A shrinking, aging population raises new questions. Who will care for the elderly? Can economies grow with fewer workers? Will automation fill the gap? Does a smaller population mean fewer innovators, and therefore slower progress? Demography is slow-moving but nearly unstoppable, which makes it one of the most reliable tools a futurist has."},
      {"kind":"p","text":"**Longtermism and Its Critics**"},
      {"kind":"p","text":"The observation that the future could be vast has given rise to **longtermism**, articulated in works such as William MacAskill's *What We Owe the Future* (2022). Its central claims are that future people matter morally, that there could be enormous numbers of them, and that we can meaningfully affect their lives, especially by reducing existential risks and by avoiding the **lock-in** of bad values or institutions that could persist for millennia."},
      {"kind":"p","text":"Longtermism has attracted substantial criticism. Some argue that our ability to predict the long-term consequences of actions is so poor that we should focus on present, tractable suffering. Others worry that multiplying tiny probabilities by astronomically large numbers produces conclusions that can justify almost anything, a problem philosophers call **fanaticism** or \"Pascal's mugging.\" Still others argue that the framework can be used to deprioritize the urgent needs of the world's poorest people today. These critiques are worth taking seriously. The concepts of existential risk and intergenerational responsibility can be valuable without accepting every conclusion of the strongest versions of the view."},
      {"kind":"p","text":"A gentler, related idea is **moral circle expansion**: the historical observation that humanity has gradually extended moral concern outward, from kin to tribe, nation, all humans, and increasingly to animals. Some thinkers ask whether the circle will eventually include future generations, ecosystems, or even digital minds, and whether the shape of that circle is one of the most important things we could influence."},
    ],
  },
  {
    heading: "Part VIII: The Very Long Run",
    blocks: [
      {"kind":"p","text":"Even in the best case, where humanity avoids catastrophe and flourishes, physics sets the ultimate horizon."},
      {"kind":"p","text":"In about a billion years, the brightening Sun will make Earth uninhabitable without large-scale engineering. In about five billion years, the Sun will swell into a red giant. Beyond our solar system, the universe's accelerating expansion, driven by what cosmologists call dark energy, will eventually push distant galaxies beyond reach. This means any civilization's accessible territory is shrinking over time, an argument some use for expanding sooner rather than later. Star formation will wind down over roughly a hundred trillion years, the end of what cosmologists call the *Stelliferous Era*. Over unimaginably longer timescales, the universe trends toward **heat death**, a state of maximum entropy in which no usable energy gradients remain and nothing further can happen."},
      {"kind":"p","text":"Some physicists and philosophers have speculated about how intelligence might persist as long as possible in such a universe, for example by thinking ever more slowly and efficiently as the cosmos cools. These ideas are deeply speculative, but they illustrate a profound point: the future, however long, is not infinite, and the resources available to any civilization are finite. That finiteness makes the choices of each era count."},
    ],
  },
  {
    heading: "Conclusion: The Hinge of History?",
    blocks: [
      {"kind":"p","text":"Some philosophers have asked whether we are living at the **hinge of history**, a uniquely pivotal moment when decisions carry outsized influence over the long-term future. The argument for this view is that we are the first generation with the technological power to end our species, and possibly among the last to be able to shape which values guide the transformative technologies ahead. The argument against it is that nearly every generation has believed itself uniquely important, and base rates should make us humble."},
      {"kind":"p","text":"Either way, the tools in this lesson let you engage with that question rigorously rather than through hype or despair: exponentials and S-curves, the Kardashev scale, the Great Filter, existential risk, alignment, demographic transition, and longtermism. The future is not a destination we arrive at but a place we build, and the first step in building well is thinking clearly."},
    ],
  },
  {
    heading: "Key Concepts at a Glance",
    blocks: [
      {"kind":"list","items":["**Futures cone**: The framework of possible, plausible, probable, and preferable futures.","**S-curve**: The pattern of slow start, rapid growth, and plateau typical of real-world technologies.","**Amara's Law**: We overestimate technology's short-term effects and underestimate its long-term ones.","**Kardashev scale**: Civilizations ranked by energy use; humanity is at roughly Type 0.73.","**Fermi Paradox / Great Filter**: Why we see no aliens, and whether the barrier lies behind or ahead of us.","**Existential risk**: A threat to humanity's entire long-term potential, not merely a large disaster.","**Vulnerable World Hypothesis**: The possibility that some future discovery is a civilization-ending \"black ball.\"","**Technological Singularity / intelligence explosion**: Recursive AI self-improvement beyond which prediction fails.","**AI alignment**: Ensuring capable AI systems pursue genuinely beneficial goals.","**Demographic transition**: The shift from high to low birth and death rates as societies develop.","**Longtermism**: The view that positively influencing the long-term future is a key moral priority.","**Heat death**: The ultimate thermodynamic end state of the universe."]},
    ],
  },
  {
    heading: "Suggested Further Reading",
    blocks: [
      {"kind":"p","text":"Toby Ord, *The Precipice* (2020); Nick Bostrom, *Superintelligence* (2014); William MacAskill, *What We Owe the Future* (2022); Philip Tetlock and Dan Gardner, *Superforecasting* (2015); Stephen Webb, *If the Universe Is Teeming with Aliens… Where Is Everybody?* (2nd ed., 2015); Stewart Brand, *The Clock of the Long Now* (1999)."},
    ],
  },
];;
