import type { LessonSection } from "../curriculum";

export const sections: readonly LessonSection[] = [
  {
    heading: null,
    blocks: [
      {"kind":"p","text":"*A layered guide to the concepts and vocabulary of the Go programming language. Each section starts simple and ends deep, so beginners can read the first half of a section and move on, while experienced readers can dig into the internals.*"},
    ],
  },
  {
    heading: "1. The Philosophy: Why Go Looks the Way It Does",
    blocks: [
      {"kind":"p","text":"Go was designed at Google around 2007 by Robert Griesemer, Rob Pike, and Ken Thompson. It was released publicly in 2009 and reached version 1.0 in 2012. To understand Go, you have to understand what it was reacting against: slow C++ builds, sprawling class hierarchies, and the difficulty of writing concurrent network servers at scale. Go's designers did not try to invent new ideas. They selected old, proven ideas and removed almost everything else."},
      {"kind":"p","text":"The central value is **simplicity**, which in Go does not mean \"easy for the language designer.\" It means that the language is small enough to hold in your head. The whole specification can be read in an afternoon. The deliberate omissions include classical inheritance, exceptions, operator overloading, implicit numeric conversions, default arguments, and (until 2022) generics. Each omission is a trade-off: a little more typing in exchange for code whose behavior is obvious to anyone reading it. The Go community often puts it this way: code is read far more often than it is written, so optimize for the reader."},
      {"kind":"p","text":"Three intellectual lineages meet in Go. From **C** it takes its syntax, its value semantics, and its \"close to the machine\" mindset. From **Pascal, Modula, and Oberon** (Griesemer's heritage) it takes packages, declaration syntax that reads left to right, and fast single-pass compilation. From **Tony Hoare's Communicating Sequential Processes (CSP)**, filtered through Pike's earlier languages Newsqueak, Alef, and Limbo, it takes goroutines and channels."},
      {"kind":"p","text":"Two social contracts matter as much as the technical design. The first is the **Go 1 compatibility promise**: code written for Go 1.0 should still compile and run under every later Go 1.x release. This promise is why Go codebases age unusually well. The second is **gofmt**, the canonical formatter. There is exactly one accepted layout for Go code, so debates about formatting simply do not happen. Pike's proverb sums it up: \"Gofmt's style is no one's favorite, yet gofmt is everyone's favorite.\""},
    ],
  },
  {
    heading: "2. Programs, Packages, and Modules",
    blocks: [
      {"kind":"p","text":"A Go program is built from **packages**. A package is a directory of `.go` files that all begin with the same `package name` clause. Files in the same package share a single namespace, so a function defined in one file is visible in the others without any import."},
      {"kind":"p","text":"An executable program must contain a package named `main` with a function `func main()`. Execution proceeds in this order:"},
      {"kind":"list","ordered":true,"items":["Imported packages are initialized, recursively and in dependency order.","Within each package, package-level variables are initialized.","Each package's `init()` functions run. A package may have several, and they take no arguments.","Finally, `main` runs."]},
      {"kind":"p","text":"When `main` returns, the program exits immediately. It does not wait for other goroutines to finish, which surprises almost every beginner."},
      {"kind":"p","text":"**Visibility** is controlled by capitalization, not by keywords. An identifier that begins with an uppercase letter (`Println`, `Reader`) is **exported**, meaning visible outside its package. A lowercase identifier (`buffer`, `parse`) is **unexported**, meaning private to the package. There is no `public`, `private`, or `protected`. The unit of encapsulation is the package, not the type. A related convention reinforces this: a directory named `internal` can only be imported by code rooted at the parent of that directory. This gives library authors a way to share code between their own packages without exposing it as public API."},
      {"kind":"p","text":"A **module** is a collection of packages versioned together. It is defined by a `go.mod` file declaring the module path (for example `github.com/alice/tool`), the minimum Go version, and its dependencies. The companion file `go.sum` records cryptographic hashes of dependency contents so builds are verifiable and reproducible. Modules replaced the older **GOPATH** workspace model. They arrived in Go 1.11 and became the default in 1.16."},
      {"kind":"p","text":"Under the hood, Go resolves dependency versions with **Minimal Version Selection (MVS)**, an algorithm designed by Russ Cox. Most package managers pick the *newest* version that satisfies all constraints. MVS instead picks the *oldest* version that satisfies every stated minimum. The result is deterministic and requires no SAT solver, and your build doesn't silently change just because someone published a new release. MVS relies on **semantic import versioning**: a breaking major version must change the import path, so v2 and later live at paths like `example.com/lib/v2`. This lets v1 and v2 coexist in a single build. Downloads go through a module proxy (by default `proxy.golang.org`) and are checked against a global transparency log called the checksum database (`sum.golang.org`). Newer features include **workspaces** (`go.work`, 1.18) for developing several modules together, the **toolchain directive** (1.21), which lets a module request a specific Go toolchain that the `go` command can fetch automatically, and the **tool directive** (1.24), which tracks developer tools as module dependencies."},
    ],
  },
  {
    heading: "3. Values, Types, and Declarations",
    blocks: [
      {"kind":"p","text":"Go is **statically typed**: every expression has a type known at compile time. It is also **strongly typed** in the sense that there are no implicit conversions between distinct types. Even `int` and `int64` cannot be mixed without an explicit conversion, `int64(x)`. This feels pedantic at first, but it eliminates an entire family of subtle bugs."},
      {"kind":"p","text":"**Declaring variables**"},
      {"kind":"p","text":"You can declare variables with `var`:"},
      {"kind":"p","text":"Inside functions, you can use the **short variable declaration**:"},
      {"kind":"p","text":"The `:=` form declares *and* initializes, and the compiler infers the type. It only works inside functions. It has a subtle rule: in a multi-variable form like `a, err := f()`, at least one variable on the left must be new, and any existing ones in the *same scope* are simply assigned. If you use `:=` inside a nested block, you create a *new* variable that **shadows** the outer one. Accidental shadowing of `err` is a classic source of bugs."},
      {"kind":"p","text":"**Zero values**"},
      {"kind":"p","text":"Every type has a **zero value**, and every variable is always initialized:"},
      {"kind":"list","items":["Numbers — `0`","Booleans — `false`","Strings — `\"\"`","Pointers, slices, maps, channels, functions, interfaces — `nil`","Structs — every field set to its own zero value"]},
      {"kind":"p","text":"This is more than a safety feature. It is a design principle. Idiomatic Go types are designed so their zero value is immediately useful. For example, a `sync.Mutex` or a `bytes.Buffer` works without any constructor. The proverb is \"Make the zero value useful.\""},
      {"kind":"p","text":"**Basic types**"},
      {"kind":"list","items":["**Booleans:** `bool`.","**Strings:** `string`.","**Sized integers:** `int8` through `int64` and `uint8` through `uint64`.","**Platform-sized integers:** `int` and `uint` are 64 bits on 64-bit platforms. `uintptr` is an integer large enough to hold a pointer.","**Floats:** `float32` and `float64`.","**Complex numbers:** `complex64` and `complex128`.","**Aliases:** `byte` is an alias for `uint8`, and `rune` is an alias for `int32`. A rune represents a Unicode code point."]},
      {"kind":"p","text":"**Constants and iota**"},
      {"kind":"p","text":"**Constants** are declared with `const`, and Go's treatment of them is quietly sophisticated. Constants are frequently **untyped**. The literal `1 << 100` is a perfectly valid constant expression, because the compiler represents untyped constants with arbitrary precision (the spec requires at least 256 bits for integers). An untyped constant takes on a concrete type only when it is used in a context that demands one. That is why `const big = 1 << 100; fmt.Println(big >> 98)` compiles and prints 4. Untyped constants give you the convenience of implicit conversion without the dangers of implicit conversion between variables."},
      {"kind":"p","text":"**iota** is a counter usable in constant declarations. It starts at 0 in each `const` block and increments on each line, which makes it the idiomatic way to create enumerations and bit flags:"},
      {"kind":"p","text":"**Defined types vs aliases**"},
      {"kind":"p","text":"These two declarations look almost identical but mean very different things."},
      {"kind":"p","text":"A **type definition** creates a brand-new, distinct type:"},
      {"kind":"p","text":"`Celsius` shares its **underlying type** with `float64` but is not interchangeable with it. You cannot add a `Celsius` to a `Fahrenheit` by accident, and you can attach methods to `Celsius`."},
      {"kind":"p","text":"A **type alias** creates another name for the *same* type:"},
      {"kind":"p","text":"Aliases exist mainly to support gradual code migration across packages."},
      {"kind":"p","text":"The distinction between a type and its underlying type becomes central once you get to generics."},
    ],
    examples: [
      {"title":"Declaring with var","code":"var count int\nvar name = \"gopher\"","explanation":"var declares a variable with an explicit or inferred type; at package scope it also sets initialization order."},
      {"title":"Short declaration inside functions","code":"n := 42","explanation":":= declares and initializes with an inferred type, and only works inside functions; redeclare-or-assign rules apply in multi-variable forms."},
      {"title":"Enumerations and bit flags with iota","code":"type Weekday int\n\nconst (\n    Sunday Weekday = iota // 0\n    Monday                // 1\n    Tuesday               // 2\n)\n\nconst (\n    FlagA = 1 << iota // 1\n    FlagB             // 2\n    FlagC             // 4\n)","explanation":"iota counts lines within a const block starting at 0, so one expression plus blank repetitions builds enums and 1<<iota flags."},
      {"title":"Type definition: a new, distinct type","code":"type Celsius float64","explanation":"Celsius shares float64's underlying type but is not interchangeable with it — and methods can attach to it."},
      {"title":"Type alias: another name for the same type","code":"type MyFloat = float64","explanation":"The = form adds a second name to one existing type, mainly for gradual code migration across packages."},
    ],
  },
  {
    heading: "4. Composite Types: Arrays, Slices, Maps, Strings, Structs",
    blocks: [
      {"kind":"p","text":"**Arrays**"},
      {"kind":"p","text":"An **array** has a fixed length that is part of its type. `[4]int` and `[5]int` are different, incompatible types. Arrays are **values**: assigning one array to another, or passing it to a function, copies every element. For this reason, arrays are rarely used directly. Their main role is to serve as the storage underneath slices."},
      {"kind":"p","text":"**Slices**"},
      {"kind":"p","text":"A **slice** is Go's workhorse sequence type, and understanding it precisely separates novices from experts."},
      {"kind":"p","text":"A slice is a small descriptor, often called the **slice header**, with three fields:"},
      {"kind":"list","ordered":true,"items":["a pointer to an element in an underlying array,","a **length** (how many elements are currently visible), and","a **capacity** (how many elements exist from the pointer to the end of the underlying array)."]},
      {"kind":"p","text":"The header is passed by value, but the array it points to is shared. Slicing an existing slice or array with `s[low:high]` creates a new header over the *same* memory, with no copying involved."},
      {"kind":"p","text":"The built-in `append` adds elements. If there is spare capacity, `append` writes into the existing array and returns a header with a larger length. If there isn't, it allocates a new, larger array, copies the elements over, and returns a header pointing to the new array. Growth is roughly doubling for small slices, tapering toward about 1.25× for large ones. Because the new header may or may not point to the same array, you must always use the result: `s = append(s, x)`."},
      {"kind":"p","text":"This design produces the famous **aliasing gotcha**. Two slices can share an array, so appending to one can silently overwrite data visible through the other, but only when spare capacity existed. The **full slice expression** `s[low:high:max]` limits capacity so that a later append is forced to copy. Experts reach for it when handing sub-slices to code they don't control."},
      {"kind":"p","text":"Slices are created with a composite literal (`[]int{1, 2, 3}`), by slicing, or with `make([]T, length, capacity)`. A **nil slice** has no underlying array. It is fully usable: its length is zero, you can range over it, and you can append to it."},
      {"kind":"p","text":"**Maps**"},
      {"kind":"p","text":"A **map** (`map[K]V`) is a built-in hash table. Keys must be **comparable**, meaning they support `==`. Slices, maps, and functions are not comparable, so they cannot be keys."},
      {"kind":"p","text":"Reading a missing key returns the zero value. The **comma-ok idiom**, `v, ok := m[k]`, distinguishes \"absent\" from \"present with the zero value.\""},
      {"kind":"p","text":"Map iteration order is **deliberately randomized**, so programs cannot accidentally depend on it. A **nil map** can be read from, but writing to it panics, so initialize maps with `make` or a literal."},
      {"kind":"p","text":"Maps are **not safe for concurrent writes**. The runtime detects many such races and kills the program with a fatal error that cannot be recovered. Since Go 1.24, maps are implemented with a Swiss-table design, an open-addressing scheme that probes groups of slots using compact metadata bytes."},
      {"kind":"p","text":"**Strings**"},
      {"kind":"p","text":"A **string** is an immutable sequence of bytes. It is conventionally, but not necessarily, UTF-8 text. Internally, a string is a two-word header: a pointer and a length. Slicing a string is therefore cheap, and the substring shares memory with the original."},
      {"kind":"p","text":"Because strings are bytes, `len(s)` counts **bytes, not characters**. Indexing `s[i]` yields a byte. But `for i, r := range s` *decodes* UTF-8, yielding each rune along with its starting byte offset. Invalid encodings produce the replacement character U+FFFD. Converting between `string` and `[]byte` normally copies, because strings must stay immutable, although the compiler optimizes away many such copies. For efficient concatenation in a loop, use `strings.Builder`."},
      {"kind":"p","text":"**Structs**"},
      {"kind":"p","text":"A **struct** is a typed collection of named fields. Structs are values, and assignment copies them. Several details matter:"},
      {"kind":"list","items":["**Field order affects memory layout.** Fields are aligned according to their types, which can introduce padding. Ordering fields from largest to smallest can shrink a struct.","**Struct tags** are string metadata attached to fields, such as `` `json:\"name,omitempty\"` ``. Packages like `encoding/json` read them through reflection.","**Anonymous structs** are useful for one-off groupings, especially in tests.","**The empty struct** `struct{}` occupies zero bytes. Idiomatic Go uses it for sets (`map[string]struct{}`) and for pure signaling channels (`chan struct{}`)."]},
    ],
  },
  {
    heading: "5. Pointers, Memory, and Value Semantics",
    blocks: [
      {"kind":"p","text":"A **pointer** holds the address of a value. `&x` takes the address of `x`, and `*p` dereferences `p`. Unlike C, Go has **no pointer arithmetic** outside the `unsafe` package, and the garbage collector manages memory, so dangling pointers are impossible in safe code. It is perfectly legal, and idiomatic, to return a pointer to a local variable. The compiler notices that the value outlives the function and places it on the heap."},
      {"kind":"p","text":"That decision is made by **escape analysis**. At compile time, the compiler determines whether each value's lifetime is provably confined to its function. If it is, the value lives on the goroutine's stack, where it is essentially free. If it \"escapes\" (by being returned via pointer, stored in a longer-lived structure, captured by certain closures, or passed through an interface in ways the compiler can't see through), it is heap-allocated and later collected. You can inspect these decisions with `go build -gcflags=-m`. Performance-oriented Go is largely the art of avoiding unnecessary escapes."},
      {"kind":"p","text":"The cardinal rule is that **Go passes everything by value**. Assignment, function arguments, and method receivers all make copies. What varies is *what* gets copied:"},
      {"kind":"list","items":["Copying an `int` or a struct copies the data itself.","Copying a slice, map, channel, function, or interface copies a small header or reference, so the copy shares the underlying data."]},
      {"kind":"p","text":"People sometimes loosely call these \"reference types,\" but the precise statement is that they are values that *contain* pointers. Holding this model firmly resolves most confusion about when a function can modify its arguments."},
      {"kind":"p","text":"Two built-ins allocate memory:"},
      {"kind":"list","items":["**`new(T)`** allocates a zeroed `T` and returns a `*T`.","**`make`** initializes the internal structure of slices, maps, and channels and returns the value itself, not a pointer."]},
      {"kind":"p","text":"In practice, composite literals like `&Config{Port: 80}` are more common than `new`."},
    ],
  },
  {
    heading: "6. Functions, Closures, Defer, Panic, and Recover",
    blocks: [
      {"kind":"p","text":"Functions are first-class values. They can be assigned to variables, passed as arguments, and returned from other functions. Functions can return **multiple values**, which is the foundation of Go's error handling: `result, err := doThing()`. Results can be **named**, in which case they act as pre-declared variables and a bare `return` returns their current values. Use this sparingly, because bare returns hurt readability in long functions. **Variadic** functions accept a variable number of trailing arguments (`func sum(nums ...int)`). You can spread a slice into them with `sum(values...)`."},
      {"kind":"p","text":"A **closure** is a function literal that captures variables from its surrounding scope *by reference*: the closure and the enclosing function share the same variable. For over a decade, this interacted badly with loops. The loop variable was a single variable reused across iterations, so goroutines or closures launched inside a loop often all saw its final value. Go 1.22 changed the semantics so that each iteration of a `for` loop has its own fresh variable, for modules declaring `go 1.22` or later. Older codebases still contain the defensive idiom `v := v` from before the fix."},
      {"kind":"p","text":"**defer** schedules a function call to run when the surrounding function returns, whether it returns normally or by panic. Deferred calls execute in **LIFO order**. Their **arguments are evaluated immediately** at the `defer` statement, even though the call happens later. The canonical use is cleanup placed right next to acquisition:"},
      {"kind":"p","text":"Deferred closures can read and modify named results, which enables patterns like annotating errors on the way out."},
      {"kind":"p","text":"Historically, `defer` carried measurable overhead. Since Go 1.14, most defers are **open-coded**, meaning the compiler inlines them at function exits, which makes them nearly free. Deferring inside a long loop is still a mistake, though, because nothing runs until the *function* returns."},
      {"kind":"p","text":"**panic** stops normal execution, runs deferred calls up the stack, and crashes the program with a stack trace unless something recovers. **recover**, called *directly* inside a deferred function, stops the panic and returns the panic value. Go's philosophy is that panics are for truly unrecoverable conditions and programmer errors: nil dereferences, out-of-range indices, impossible states. They are *not* a substitute for exceptions in ordinary control flow. The idiomatic use of `recover` is at boundaries. For example, an HTTP server recovers panics in a handler so one bad request doesn't kill the process."},
    ],
    examples: [
      {"title":"Acquire, then defer cleanup","code":"f, err := os.Open(path)\nif err != nil {\n    return err\n}\ndefer f.Close()","explanation":"defer schedules Close at return (LIFO); its arguments are evaluated at the defer statement, so state is captured where you can see it."},
    ],
  },
  {
    heading: "7. Methods and Receivers",
    blocks: [
      {"kind":"p","text":"A **method** is a function with a **receiver**, a special parameter that binds it to a type: `func (c Celsius) String() string`. You can define methods on any named type declared in the same package, not just on structs. That includes named slices, maps, and function types."},
      {"kind":"p","text":"Receivers come in two forms:"},
      {"kind":"list","items":["A **value receiver** (`func (t T) M()`) operates on a copy.","A **pointer receiver** (`func (t *T) M()`) can modify the original and avoids copying large structs."]},
      {"kind":"p","text":"The common guidance is to use pointer receivers when a method mutates its receiver, when the struct is large, or when the type contains something that must not be copied, such as a mutex. Also be consistent: if some methods need pointer receivers, give all of them pointer receivers."},
      {"kind":"p","text":"Go smooths over the syntax. If `v` is **addressable** (a variable, not a temporary), `v.M()` automatically becomes `(&v).M()` for pointer methods. Likewise, pointers automatically dereference for value methods."},
      {"kind":"p","text":"This convenience hides a rigorous concept, the **method set**, which becomes decisive when interfaces enter the picture:"},
      {"kind":"list","items":["The method set of type `T` contains only its value-receiver methods.","The method set of `*T` contains both value-receiver and pointer-receiver methods."]},
      {"kind":"p","text":"The reasoning: a value stored inside an interface is not addressable, so the language cannot silently take its address to call a pointer method."},
    ],
  },
  {
    heading: "8. Interfaces: The Heart of Go's Design",
    blocks: [
      {"kind":"p","text":"An **interface** is a type defined by a set of method signatures:"},
      {"kind":"p","text":"The revolutionary part is that satisfaction is **implicit**. A type implements an interface simply by having the right methods. There is no `implements` keyword. This is **structural typing**, checked at compile time. It is sometimes compared to duck typing, but unlike duck typing, it is statically verified."},
      {"kind":"p","text":"The consequences are profound. Interfaces can be defined by the *consumer* of a behavior rather than the producer, and a type can satisfy interfaces its author never imagined. This decoupling is why Go tends to have small interfaces defined next to the code that uses them. The proverb is \"The bigger the interface, the weaker the abstraction.\" The standard library's most successful abstractions are tiny:"},
      {"kind":"list","items":["`io.Reader` and `io.Writer`, one method each, underpin files, network connections, compressors, hashers, and HTTP bodies alike.","`fmt.Stringer` controls how a value prints.","`error` is the universal error type.","`sort.Interface` makes a collection sortable."]},
      {"kind":"p","text":"A related maxim is **\"accept interfaces, return structs.\"** Functions should ask for the minimal behavior they need and return concrete types that callers can use fully."},
      {"kind":"p","text":"**Composition and the empty interface**"},
      {"kind":"p","text":"Interfaces compose by **embedding**. `io.ReadWriter` is simply `Reader` and `Writer` combined. The **empty interface** `interface{}` has no methods, so every type satisfies it. Since Go 1.18 it has had the alias **`any`**. It is Go's escape hatch for truly heterogeneous data, at the cost of static type safety."},
      {"kind":"p","text":"**Type assertions and type switches**"},
      {"kind":"p","text":"To recover a concrete type from an interface, use a **type assertion**. `v := x.(T)` panics if `x` doesn't hold a `T`, while the comma-ok form `v, ok := x.(T)` does not. A **type switch** dispatches on the dynamic type:"},
      {"kind":"p","text":"Assertions can also target *interfaces*, which lets you check for optional capabilities. For example, `if wt, ok := r.(io.Writer); ok { ... }` is how `io.Copy` opportunistically uses fast paths."},
      {"kind":"p","text":"**What an interface value really is**"},
      {"kind":"p","text":"An interface value is a **two-word pair: (dynamic type, dynamic value)**. For non-empty interfaces, the type word points to an **itab** — a runtime structure caching the concrete type's method pointers for that interface, built lazily per (interface, concrete type) pair, much like a C++ vtable. Empty-interface values use a simpler two-word form (`eface`) holding the type descriptor and the data pointer."},
      {"kind":"p","text":"This representation explains Go's most notorious gotcha, the **nil interface versus interface holding a nil pointer**. An interface is `nil` only when *both* words are nil. If a function returns a `*MyError` that happens to be nil, but its declared return type is `error`, the caller receives an interface whose type word is `*MyError` and whose value word is nil. That interface is **not** equal to `nil`, so `err != nil` evaluates to true. The rule of thumb: return a literal `nil` for \"no error,\" never a typed nil pointer."},
      {"kind":"p","text":"A small idiom lets you assert at compile time that a type satisfies an interface:"},
    ],
    examples: [
      {"title":"An interface is a set of methods","code":"type Reader interface {\n    Read(p []byte) (n int, err error)\n}","explanation":"Satisfaction is implicit and structurally checked at compile time — no implements keyword, tiny interfaces like this underpin the stdlib."},
      {"title":"Dispatching on the dynamic type","code":"switch v := x.(type) {\ncase int:\n    // v is an int here\ncase string:\n    // v is a string here\n}","explanation":"A type switch selects on the concrete type stored in the interface, binding v to that type inside each case."},
      {"title":"Compile-time interface assertion","code":"var _ io.Writer = (*MyWriter)(nil)","explanation":"Assigning a typed nil to the blank identifier forces a method-set check at build time without running anything."},
    ],
  },
  {
    heading: "9. Embedding: Composition Instead of Inheritance",
    blocks: [
      {"kind":"p","text":"Go has no classes and no inheritance. It offers **embedding**: declare a field with a type but no name, and the embedded type's fields and methods are **promoted** to the outer type."},
      {"kind":"p","text":"With this, `s.Log(\"hi\")` works on a `Server`. Promotion also means `Server` satisfies any interface that `*Logger` satisfies, which is a powerful way to build types out of parts."},
      {"kind":"p","text":"The crucial difference from inheritance is that **there is no virtual dispatch back into the outer type**. When a promoted method runs, its receiver is the embedded value, not the outer struct. If `Logger.Log` calls `l.Format()`, it calls `Logger`'s `Format`, even if `Server` defines its own `Format`. The outer type can **shadow** a promoted method by defining its own, but the inner type never knows. This is delegation with syntactic sugar, not subtype polymorphism. For polymorphism, Go uses interfaces, and the two mechanisms are kept cleanly separate."},
    ],
    examples: [
      {"title":"Embedding promotes fields and methods","code":"type Logger struct{ /* ... */ }\n\nfunc (l *Logger) Log(msg string) { /* ... */ }\n\ntype Server struct {\n    *Logger\n    addr string\n}","explanation":"Server gains Logger's fields and methods — and its interfaces — but there is no virtual dispatch back into the outer type."},
    ],
  },
  {
    heading: "10. Errors Are Values",
    blocks: [
      {"kind":"p","text":"Go has no exceptions. A function that can fail returns an `error` as its last result. `error` is just a built-in interface with one method, `Error() string`. The caller checks it immediately:"},
      {"kind":"p","text":"Critics call this verbose. Proponents argue it makes every failure path explicit and visible in the code, with no invisible control flow jumping across stack frames. Pike's essay \"Errors are values\" makes the deeper point: because errors are ordinary values, you can program with them. You can store them, aggregate them, and design APIs, like `bufio.Scanner`, that defer error checks until the end."},
      {"kind":"p","text":"Errors come in several vocabulary-defining flavors:"},
      {"kind":"list","items":["**Sentinel errors** are package-level variables compared by identity, such as `io.EOF` and `sql.ErrNoRows`.","**Custom error types** are structs that implement `Error()` and carry structured data, such as `*os.PathError`.","**Wrapped errors** carry context while preserving the original cause."]},
      {"kind":"p","text":"Since Go 1.13, the `%w` verb in `fmt.Errorf` wraps an error. Two functions then inspect the resulting **error chain**:"},
      {"kind":"list","items":["`errors.Is(err, target)` searches the chain for a matching value.","`errors.As(err, &target)` searches for a matching type and extracts it."]},
      {"kind":"p","text":"Go 1.20 added `errors.Join` and support for multiple `%w` verbs, so an error chain became an error *tree*. A good discipline is to wrap errors with context at each layer (\"reading config: opening file: permission denied\") and to decide deliberately whether a wrapped error is part of your API. Wrapping exposes the underlying cause to callers, which is a compatibility commitment."},
    ],
    examples: [
      {"title":"Errors are returned, then wrapped","code":"data, err := os.ReadFile(path)\nif err != nil {\n    return fmt.Errorf(\"loading config: %w\", err)\n}","explanation":"The %w verb preserves the cause while adding context; errors.Is and errors.As inspect the resulting chain."},
    ],
  },
  {
    heading: "11. Control Flow",
    blocks: [
      {"kind":"p","text":"Go has exactly one loop keyword, **`for`**, which covers all the usual shapes:"},
      {"kind":"list","items":["the C-style form: `for i := 0; i < n; i++`","the while-style form: `for cond`","the infinite form: `for`","the **range** form: `for i, v := range collection`"]},
      {"kind":"p","text":"Range works over arrays, slices, strings (decoding runes), maps (in random order), and channels (until closed). Since Go 1.22 it also works over integers (`for i := range 10`). Since Go 1.23 it works over **iterator functions**, which is covered in the generics section below. One detail matters: in `for _, v := range s`, the variable `v` is a *copy* of each element. Modifying `v` does not modify the slice. Use the index instead (`s[i].field = x`)."},
      {"kind":"p","text":"**`if`** and **`switch`** accept an optional init statement whose variables are scoped to the construct, as in `if err := f(); err != nil { ... }`. Switch cases do **not fall through** by default, which is the opposite of C. The explicit `fallthrough` keyword exists but is rare. A switch with no condition is a clean replacement for if-else chains. **Labels** allow `break` and `continue` to target outer loops, and `goto` exists with restrictions that keep it from jumping over declarations or into blocks."},
    ],
  },
  {
    heading: "12. Generics: Type Parameters",
    blocks: [
      {"kind":"p","text":"After more than a decade of debate, Go 1.18 (2022) added **type parameters**. Functions and types can now be parameterized over types:"},
      {"kind":"p","text":"**Constraints and type sets**"},
      {"kind":"p","text":"Each type parameter has a **constraint**, and constraints are simply interfaces, which unifies two concepts elegantly. The key to this unification is a reframing in the spec: an interface now defines a **type set**, the set of all types that satisfy it."},
      {"kind":"list","items":["A traditional method-only interface has the type set \"all types with these methods.\"","Interfaces used as constraints may also contain **union elements** such as `int | float64 | string`, which restrict the type set explicitly.","The **tilde** operator `~T` means \"any type whose *underlying* type is `T`.\" So `~int` admits both `int` and your own `type UserID int`.","The predeclared constraint **`comparable`** admits types supporting `==`.","The package `cmp` provides `cmp.Ordered` for types supporting `<`."]},
      {"kind":"p","text":"Interfaces containing unions or `comparable` can only be used as constraints, not as ordinary variable types."},
      {"kind":"p","text":"**Inference and limitations**"},
      {"kind":"p","text":"**Type inference** usually lets callers omit type arguments, so `Map(nums, strconv.Itoa)` just works. The design is intentionally conservative:"},
      {"kind":"list","items":["Methods cannot declare their own type parameters. Only functions and types can.","There is no specialization.","There is no metaprogramming in the C++ template sense."]},
      {"kind":"p","text":"Generic type aliases were fully enabled in Go 1.24."},
      {"kind":"p","text":"**How generics are implemented**"},
      {"kind":"p","text":"Implementation strategies for generics usually sit between two poles. **Full monomorphization**, as in C++ and Rust, generates a separate copy of the code for each type argument: fast at runtime, but heavy on binary size and compile time. **Uniform boxing**, as in Java, uses one copy of the code for everything: compact, but it adds indirection. Go chose a hybrid called **GC shape stenciling with dictionaries**. Types that share a \"GC shape\" (roughly, the same underlying memory layout; all pointer types share a single shape) share one compiled instantiation. A hidden **dictionary** argument supplies type-specific information such as method pointers and type descriptors. The consequence for performance-minded engineers is that generic code calling methods on pointer-shaped type parameters may be *slower* than hand-specialized code, or even interface-based code, because of the dictionary indirection. Generics in Go are chiefly a tool for type-safe reuse, not a performance feature."},
      {"kind":"p","text":"**What generics enabled**"},
      {"kind":"p","text":"Generics unlocked several standard library additions:"},
      {"kind":"list","items":["**`slices`** and **`maps`** packages (1.21), with functions like `slices.Sort`, `slices.Contains`, and `maps.Keys`.","The built-ins **`min`**, **`max`**, and **`clear`** (1.21).","**Range-over-func iterators** (1.23), standardized as `iter.Seq[V]` and `iter.Seq2[K, V]`."]},
      {"kind":"p","text":"An `iter.Seq[V]` is simply a function of the form `func(yield func(V) bool)`. The range loop calls it, passing a synthesized `yield` function that runs the loop body. If `yield` returns false, the loop has broken early and the iterator should stop. This is a \"push\" iterator. `iter.Pull` converts it into a \"pull\" iterator when you need to step through values manually."},
    ],
    examples: [
      {"title":"Type parameters on functions and types","code":"func Map[T, U any](s []T, f func(T) U) []U {\n    r := make([]U, 0, len(s))\n    for _, v := range s {\n        r = append(r, f(v))\n    }\n    return r\n}\n\ntype Stack[T any] struct {\n    items []T\n}","explanation":"T and U are constrained by interfaces; inference usually lets callers omit the type arguments entirely."},
    ],
  },
  {
    heading: "13. Concurrency: Goroutines, Channels, and Select",
    blocks: [
      {"kind":"p","text":"Concurrency is Go's signature feature, and its design reflects a precise distinction Pike emphasizes. **Concurrency** is the *composition* of independently executing processes, a way of structuring a program. **Parallelism** is the *simultaneous execution* of computations, a property of how the program runs. Go gives you tools for concurrency, and parallelism follows when hardware permits."},
      {"kind":"p","text":"**Goroutines**"},
      {"kind":"p","text":"A **goroutine** is a function executing concurrently with other goroutines in the same address space. You start one by prefixing a call with `go`:"},
      {"kind":"p","text":"Goroutines are extremely cheap. They start with a small stack (currently 2 KB) that grows and shrinks on demand, and it's normal for a program to run hundreds of thousands of them. Earlier Go versions used \"segmented stacks.\" Modern Go uses **contiguous stacks that grow by copying**: when a goroutine's stack overflows, the runtime allocates a stack twice the size and copies everything over, adjusting pointers into the stack. This is possible because Go knows precisely where every pointer lives, and it is also why Go does not allow pointer arithmetic or hand out permanent addresses of stack memory."},
      {"kind":"p","text":"**The scheduler**"},
      {"kind":"p","text":"The runtime multiplexes goroutines onto OS threads with an **M:N scheduler**, usually described by three letters:"},
      {"kind":"list","items":["**G** is a goroutine.","**M** (\"machine\") is an OS thread.","**P** (\"processor\") is a scheduling context that holds a local run queue of runnable goroutines."]},
      {"kind":"p","text":"The number of Ps equals `GOMAXPROCS`, which defaults to the number of available CPUs. Since Go 1.25, this default respects Linux container CPU limits. An M must hold a P to run Go code."},
      {"kind":"p","text":"When a P's local queue empties, it checks the global run queue and the network poller, and it **steals** half the work from another P's queue. This technique, **work stealing**, keeps all cores busy without central coordination."},
      {"kind":"p","text":"When a goroutine makes a blocking system call, its M detaches from its P, and the P is handed to another M so other goroutines keep running. Network I/O, by contrast, doesn't block threads at all. The **netpoller** integrates with epoll, kqueue, or IOCP, so a goroutine \"blocked\" on a socket is simply parked until the OS reports readiness. This is why straightforward, synchronous-looking Go network code scales like hand-written event-loop code. You get the performance of asynchronous I/O without \"function coloring\" or async/await."},
      {"kind":"p","text":"Preemption was originally cooperative, happening at function calls. Since Go 1.14, the runtime also uses **asynchronous preemption** via OS signals, so a tight loop without function calls can no longer starve the scheduler or the garbage collector."},
      {"kind":"p","text":"**Channels**"},
      {"kind":"p","text":"**Channels** are typed conduits for communication and synchronization between goroutines. They embody the Go proverb **\"Do not communicate by sharing memory; instead, share memory by communicating.\"**"},
      {"kind":"list","items":["**Creating channels:** `make(chan T)` creates an **unbuffered** channel. `make(chan T, n)` creates a **buffered** channel with capacity `n`.","**Sending and receiving:** `ch <- v` sends, and `v := <-ch` receives.","**Unbuffered channels** are a synchronous rendezvous. A send blocks until a receiver takes the value, so the two goroutines synchronize at that moment.","**Buffered channels** decouple sender and receiver up to the buffer's capacity. Sends block only when the buffer is full, and receives block only when it's empty.","**Directional types:** `chan<- T` is send-only and `<-chan T` is receive-only. They document intent and are enforced by the compiler."]},
      {"kind":"p","text":"**Closing** a channel with `close(ch)` signals that no more values will be sent. Receivers then drain any remaining buffered values, after which they receive zero values with `ok == false` in the comma-ok form. `for v := range ch` loops until the channel is closed. Only senders should close channels, and closing is only necessary when receivers need to know that the stream has ended."},
      {"kind":"p","text":"Several edge cases are worth memorizing:"},
      {"kind":"list","items":["Sending on a closed channel panics.","Closing an already-closed channel panics.","Operations on a **nil channel block forever**. This sounds useless, but it is a deliberate tool inside `select`: setting a channel variable to nil disables that case."]},
      {"kind":"p","text":"Internally, a channel is a runtime struct (`hchan`) containing a mutex, a circular buffer, and queues of waiting senders and receivers. A send to a waiting receiver copies the value directly onto the receiver's stack."},
      {"kind":"p","text":"**Select**"},
      {"kind":"p","text":"**`select`** waits on multiple channel operations at once:"},
      {"kind":"p","text":"If several cases are ready, one is chosen **uniformly at random**, which prevents starvation. A `default` case makes the select non-blocking. `select` is the basis of timeouts, cancellation, multiplexing, and non-blocking sends and receives."},
    ],
    examples: [
      {"title":"Starting a goroutine","code":"go handle(conn)","explanation":"The go statement runs handle concurrently in the same address space; returning from main does not wait for it."},
      {"title":"Multiplexing channel operations","code":"select {\ncase msg := <-inbox:\n    handle(msg)\ncase out <- result:\n    // sent\ncase <-time.After(time.Second):\n    // timeout\ncase <-ctx.Done():\n    return ctx.Err()\n}","explanation":"select waits on several cases at once, picks a ready one uniformly at random, and becomes non-blocking with a default case."},
    ],
  },
  {
    heading: "14. Shared-Memory Synchronization and the Memory Model",
    blocks: [
      {"kind":"p","text":"Channels are not always the right tool. Go is pragmatic, and the `sync` package offers classic primitives:"},
      {"kind":"list","items":["**`Mutex`** and **`RWMutex`** provide mutual exclusion. RWMutex allows many readers or one writer.","**`WaitGroup`** waits for a collection of goroutines to finish. Go 1.25 added the convenience method `wg.Go(f)`.","**`Once`** guarantees that a piece of code runs exactly once. It has relatives `OnceFunc` and `OnceValue`.","**`Cond`** is a condition variable. It is rarely needed.","**`Pool`** caches reusable temporary objects to relieve GC pressure. Pooled objects can be dropped at any garbage collection.","**`sync.Map`** is a concurrent map specialized for read-mostly or disjoint-key workloads."]},
      {"kind":"p","text":"The `sync/atomic` package provides lock-free atomic operations and typed wrappers like `atomic.Int64` and `atomic.Pointer[T]`."},
      {"kind":"p","text":"A practical heuristic: use channels to transfer *ownership* of data or to *coordinate* goroutines, and use mutexes to protect *state*. A mutex guarding a map is often simpler and faster than a goroutine that owns the map and serves requests over channels."},
      {"kind":"p","text":"**The memory model**"},
      {"kind":"p","text":"The **Go memory model** defines when a write in one goroutine is guaranteed to be visible to a read in another. It does so in terms of the **happens-before** relation, which is established by synchronization events:"},
      {"kind":"list","items":["A channel send happens before the corresponding receive completes.","An unlock happens before the next lock.","Starting a goroutine happens after the `go` statement.","Atomic operations synchronize with one another."]},
      {"kind":"p","text":"A **data race** occurs when two goroutines access the same memory concurrently, at least one access is a write, and no happens-before ordering exists between them. The model was formally revised in 2022. Go guarantees **DRF-SC** (data-race-free programs behave sequentially consistently), and Go's atomics are sequentially consistent, which is simpler than C++'s menu of memory orderings. Racy programs aren't given C's unbounded \"undefined behavior.\" Instead, a racing read observes some value actually written. The major caveat is multi-word values: racing on an interface, slice, or string can observe a torn value, such as a type word from one write and a data word from another, and that can corrupt memory. The practical upshot is simple: races are bugs. Run tests with the **race detector** (`go test -race`). It instruments memory accesses using ThreadSanitizer technology and reports races it actually observes at runtime."},
      {"kind":"p","text":"**Context**"},
      {"kind":"p","text":"The **`context`** package carries cancellation signals, deadlines, and request-scoped values across API boundaries and goroutines. A `context.Context` is passed explicitly, by convention as the first parameter named `ctx`. Derived contexts form a tree: canceling a parent cancels all its descendants. Long-running operations should watch `ctx.Done()`. Context values should carry request-scoped metadata such as trace IDs, not optional function parameters."},
      {"kind":"p","text":"**Concurrency patterns and pitfalls**"},
      {"kind":"p","text":"The canonical patterns have names worth knowing:"},
      {"kind":"list","items":["**Pipelines:** stages connected by channels, each stage a goroutine.","**Fan-out / fan-in:** distribute work across many goroutines, then merge their results.","**Worker pools:** a fixed number of goroutines consuming a jobs channel.","**Semaphores:** often built from a buffered channel.","**errgroup** (`golang.org/x/sync/errgroup`): run goroutines, collect the first error, and cancel the rest."]},
      {"kind":"p","text":"The dominant pitfall is the **goroutine leak**: a goroutine blocked forever on a channel nobody will ever service. It is invisible to the garbage collector, which cannot collect running goroutines. Every goroutine you start should have a clear answer to the question \"how does this stop?\" `testing/synctest` (stable in 1.25) helps test concurrent code deterministically by running goroutines in an isolated \"bubble\" with a fake clock."},
    ],
  },
  {
    heading: "15. The Runtime and Garbage Collector",
    blocks: [
      {"kind":"p","text":"Go binaries include the **runtime**, a library statically linked into every program. It provides the scheduler, memory allocator, garbage collector, stack management, map and channel implementations, and reflection support. There is no virtual machine: Go compiles ahead of time to native machine code."},
      {"kind":"p","text":"The **allocator** descends from TCMalloc. It uses per-P caches (`mcache`) and size classes, so most small allocations need no locks."},
      {"kind":"p","text":"The **garbage collector** is a **concurrent, tri-color, mark-and-sweep** collector that is **non-generational** and **non-moving**:"},
      {"kind":"list","items":["**Tri-color** refers to the classic abstraction. Objects are white (not yet seen), grey (seen, but their references haven't been scanned), or black (fully scanned). Marking proceeds until no grey objects remain, and the remaining white objects are garbage.","**Concurrent** means marking happens while your goroutines keep running. To stay correct while the program mutates pointers mid-mark, the compiler inserts **write barriers**. Go uses a hybrid Yuasa/Dijkstra-style barrier (since 1.8) that eliminated stack rescanning and reduced stop-the-world pauses typically to well under a millisecond.","**Non-moving** means objects are never relocated. This simplifies interoperation with C.","**Non-generational** reflects the fact that escape analysis already keeps many short-lived values off the heap, which weakens the generational hypothesis's payoff for Go."]},
      {"kind":"p","text":"Go optimizes for **latency** (short pauses) over raw **throughput**. The collector also recruits allocating goroutines to help with marking work, a mechanism called **mark assist**, so heavy allocators pay for their own garbage."},
      {"kind":"p","text":"The GC has two main tuning knobs:"},
      {"kind":"list","items":["**`GOGC`** (default 100) sets heap growth: the next collection triggers when the live heap has grown by that percentage.","**`GOMEMLIMIT`** (Go 1.19) sets a soft total memory limit, which makes the collector work harder as memory approaches the limit. This is ideal for containers."]},
      {"kind":"p","text":"A newer collector design called \"Green Tea,\" which scans memory in page-sized batches for better locality, shipped as an experiment in Go 1.25."},
    ],
  },
  {
    heading: "16. Tooling: The `go` Command and Friends",
    blocks: [
      {"kind":"p","text":"Go's tooling is unusually integrated and opinionated, and much of the ecosystem's productivity comes from it:"},
      {"kind":"list","items":["**`go build`** compiles, and **`go run`** compiles and runs in one step.","**`go test`** runs tests.","**`go vet`** runs static checks for suspicious code, such as mismatched `Printf` arguments or accidentally copied mutexes.","**`go fmt`** / `gofmt` formats code.","**`go mod tidy`** reconciles dependencies with your imports.","**`go generate`** runs code generators declared in `//go:generate` comments.","**`gopls`** is the official language server that powers editor features.","**`govulncheck`** reports known vulnerabilities that your code actually calls into.","**`staticcheck`** is a widely used third-party linter."]},
      {"kind":"p","text":"**Testing**"},
      {"kind":"p","text":"Testing is built in. Files ending in `_test.go` contain functions of the form `func TestXxx(t *testing.T)`. The idiomatic style is **table-driven tests**: a slice of anonymous structs describing inputs and expected outputs, iterated with `t.Run` to create named **subtests**. The same machinery supports several other kinds of tests:"},
      {"kind":"list","items":["**Benchmarks** (`func BenchmarkXxx(b *testing.B)`). Go 1.24 introduced the `b.Loop()` style.","**Examples** (`func ExampleXxx()`), which are compiled, verified against their `// Output:` comments, and rendered in documentation.","**Native fuzzing** (`func FuzzXxx(f *testing.F)`, since 1.18), which mutates inputs automatically to find crashes and edge cases."]},
      {"kind":"p","text":"Coverage is one flag away: `go test -cover`."},
      {"kind":"p","text":"**Profiling and optimization**"},
      {"kind":"list","items":["**pprof** (`runtime/pprof`, `net/http/pprof`) provides CPU, heap, goroutine, block, and mutex profiles.","**`go tool trace`** visualizes scheduler events, GC phases, and goroutine lifecycles at microsecond resolution.","**Profile-guided optimization (PGO)** (generally available since 1.21) feeds a production CPU profile back into the compiler, which uses it for smarter inlining and devirtualization. It typically yields a few percent improvement for free."]},
      {"kind":"p","text":"The compiler performs **inlining**, **escape analysis**, **bounds-check elimination**, and **devirtualization**. Flags like `-gcflags=-m` reveal its decisions."},
      {"kind":"p","text":"**Building and distribution**"},
      {"kind":"list","items":["**Cross-compilation** is trivial. Setting environment variables like `GOOS=linux GOARCH=arm64 go build` produces a binary for another platform from any machine.","**Static binaries.** With `CGO_ENABLED=0`, binaries are fully static, single files with no runtime dependencies. This is a major reason Go dominates cloud and container tooling, including Docker, Kubernetes, Terraform, and Prometheus.","**Build constraints** (`//go:build linux && amd64`) and filename suffixes (`_windows.go`) select platform-specific files.","**`//go:embed`** (1.16) compiles files and directories directly into the binary."]},
    ],
  },
  {
    heading: "17. The Sharp Tools: Reflection, unsafe, and cgo",
    blocks: [
      {"kind":"p","text":"**Reflection** (`reflect`) lets a program inspect and manipulate types and values at runtime, working from an interface value's type descriptor. It powers `encoding/json`, `fmt`, and ORMs. It is powerful, slow, and loses compile-time safety. The proverb is \"Clear is better than clever. Reflection is never clear.\""},
      {"kind":"p","text":"**`unsafe`** allows converting between arbitrary pointer types via `unsafe.Pointer`, doing pointer arithmetic, and inspecting memory layout with `unsafe.Sizeof`, `Alignof`, and `Offsetof`. Its use is governed by specific documented rules that keep code compatible with the garbage collector. Code that uses `unsafe` gives up both portability guarantees and the compatibility promise."},
      {"kind":"p","text":"**cgo** lets Go call C and C calls Go. It carries real costs. Each call crosses a boundary between Go's growable stacks and C's fixed stacks, with scheduler bookkeeping on every crossing. It complicates cross-compilation and static linking, and it imposes strict rules about passing Go pointers to C. The proverb is blunt: \"Cgo is not Go.\""},
      {"kind":"p","text":"Compiler **directives** are special comments that begin with `//go:`. Examples include `//go:noinline`, `//go:nosplit`, and `//go:linkname`, which accesses unexported symbols in other packages. They exist mostly for runtime and standard library internals, and the Go team has increasingly restricted `linkname` misuse."},
    ],
  },
  {
    heading: "18. Idioms, Style, and Culture",
    blocks: [
      {"kind":"p","text":"Idiomatic Go (\"Go-like\" code) follows a set of shared conventions:"},
      {"kind":"list","items":["**Naming.** Use MixedCaps rather than underscores. Keep names short in small scopes (`i`, `r`, `buf`) and descriptive in large ones.","**Receivers** get one- or two-letter names, never `this` or `self`.","**Packages** get short, lowercase, singular names, with no \"util\" grab-bags.","**Avoid stutter.** Write `http.Server`, not `http.HTTPServer`.","**Getters** omit \"Get\": a field `owner` has a method `Owner()`.","**One-method interfaces** are named with an \"-er\" suffix: `Reader`, `Formatter`, `Stringer`.","**Doc comments** start with the name of the thing they describe."]},
      {"kind":"p","text":"Common patterns include:"},
      {"kind":"list","items":["**Constructor functions** named `NewThing`, used when the zero value can't suffice.","**Functional options** (`NewServer(addr, WithTimeout(5*time.Second))`) for extensible configuration.","**Early returns**, which keep the \"happy path\" aligned along the left margin.","**Small packages with clear, acyclic dependencies.** The compiler forbids import cycles outright, which enforces layered architecture."]},
      {"kind":"p","text":"The **Go Proverbs**, from Pike's 2015 talk, compress the culture into slogans:"},
      {"kind":"list","items":["\"Don't communicate by sharing memory, share memory by communicating.\"","\"Concurrency is not parallelism.\"","\"Channels orchestrate; mutexes serialize.\"","\"The bigger the interface, the weaker the abstraction.\"","\"Make the zero value useful.\"","\"interface{} says nothing.\"","\"A little copying is better than a little dependency.\"","\"Clear is better than clever.\"","\"Errors are values.\"","\"Don't just check errors, handle them gracefully.\"","\"Don't panic.\""]},
    ],
  },
  {
    heading: "19. A Field Guide to Classic Gotchas",
    blocks: [
      {"kind":"p","text":"Collected in one place, these are the traps that catch even experienced engineers:"},
      {"kind":"list","ordered":true,"items":["**Typed nil in an interface.** A nil pointer stored in an interface makes the interface non-nil.","**Slice aliasing.** `append` may or may not share memory with the original slice, depending on spare capacity.","**Retained memory.** A small sub-slice of a huge array keeps the entire array alive. Copy the data out if you only need a little of it.","**Concurrent map writes.** These cause fatal, unrecoverable crashes.","**Range copies.** `for _, v := range` gives you copies, so mutating `v` changes nothing in the collection.","**`:=` shadowing.** Using `:=` in an inner scope can silently shadow an outer `err`.","**Defer in loops.** Deferred calls accumulate until the *function* returns, not until the iteration ends.","**Early-evaluated defer arguments.** `defer fmt.Println(x)` captures `x`'s value now, not later.","**Copying locks.** Copying a struct that contains a `sync.Mutex` copies the lock state too (`go vet` catches this).","**Main doesn't wait.** Returning from `main` kills all goroutines without waiting for them.","**Nil channels block forever.** Useful in `select`, but a deadlock anywhere else.","**Pre-1.22 loop variables.** In older modules, closures capture a loop variable shared across iterations.","**Rogue goroutines.** A goroutine blocked forever on an abandoned channel is a memory leak that the GC can never reclaim."]},
    ],
  },
  {
    heading: "20. The Unifying Mental Model",
    blocks: [
      {"kind":"p","text":"If you compress Go into a single picture, it looks like this. **Everything is a value, and everything is copied.** Some values are small headers pointing to shared data: slices, maps, channels, strings, and interfaces. **Behavior is decoupled from data**: structs hold state, methods attach behavior, and interfaces describe behavior implicitly, so components connect without knowing each other. **Composition replaces inheritance**: types are built by embedding parts, and polymorphism comes only from interfaces. **Failure is ordinary**: errors are values returned and handled explicitly, and panics are reserved for the truly broken. **Concurrency is structural**: cheap goroutines scheduled across cores by a work-stealing runtime, coordinated through channels, context, and occasionally locks, all governed by a precise happens-before memory model. **The runtime is a silent partner**: it grows stacks, schedules goroutines, integrates with the OS's I/O readiness mechanisms, and collects garbage concurrently with short pauses. **The toolchain enforces the culture**: one format, built-in testing, race detection, profiling, trivial cross-compilation, and a compatibility promise that lets code written a decade ago build today."},
      {"kind":"p","text":"Go's deepest idea is that most of software engineering's difficulty is social and temporal: many people maintaining code over many years. A language can help most by being small, explicit, uniform, and fast to build. The features Go lacks are as deliberate as the ones it has. Mastery of Go means understanding its mechanisms precisely, as described above, and also internalizing that restraint: writing the plain, obvious code the language was designed to make natural."},
    ],
  },
];;
