import type { LessonSection } from "../curriculum";

export const sections: readonly LessonSection[] = [
  {
    heading: "The word itself is the first concept",
    blocks: [
      {"kind":"p","text":"\"Hermitage\" comes from the French *ermitage*, ultimately from the Greek *erēmos*, \"solitary place.\" A hermitage is where a hermit retreats from the world. That the largest and one of the most crowded art museums on earth carries this name is the founding paradox of the institution, and it tells you a great deal about how it came to be."},
      {"kind":"p","text":"In the 1760s Catherine II (the Great) built a small pavilion beside the Winter Palace in St. Petersburg where she could dine with a chosen circle of friends away from court ceremony. Mechanical tables rose through the floor already laid, so servants were unnecessary; a posted set of rules required guests to leave their rank at the door, speak freely, and not drink too much. This was the \"Small Hermitage.\" The paintings she was buying hung there and in galleries built along a hanging garden. The art, in other words, began as the décor of an Enlightenment empress's private retreat. Everything that followed is the story of that retreat being pried open to the public, and the museum still bears the architectural and psychological shape of that origin: a palace first, a museum second, and never quite able to decide which it is."},
    ],
  },
  {
    heading: "The origin story and its political logic",
    blocks: [
      {"kind":"p","text":"The conventional founding date is 1764, when Catherine acquired 225 paintings from the Berlin merchant Johann Ernst Gotzkowsky. He had assembled them for Frederick the Great of Prussia, who after the Seven Years' War could not pay. Catherine, Frederick's rival and former protégée, bought the lot. The gesture was not primarily aesthetic. It signalled that Russia had the cash and the cultivation that Prussia lacked, and it announced Catherine, a German-born usurper who had come to the throne two years earlier over her murdered husband, as a monarch of the European Enlightenment."},
      {"kind":"p","text":"She then collected with a scale and speed that is hard to overstate. Through her agents, notably Denis Diderot, she bought entire aristocratic cabinets as they came onto the market: the Brühl collection from Dresden in 1769, the Crozat collection from Paris in 1772 (which brought Rembrandt's *Danaë*, Giorgione's *Judith*, and a run of Rubens and Van Dyck), and in 1779 the Walpole collection from Houghton Hall in England, a transaction that scandalised the British and was debated as a national loss. Catherine wrote candidly to her correspondent Friedrich Melchior Grimm that she was no connoisseur, she was a glutton. The important conceptual point is that she was buying collections already shaped by seventeenth- and eighteenth-century European taste, so the Hermitage inherited the canon of the Old Masters almost intact and almost at once, rather than assembling it piece by piece."},
      {"kind":"p","text":"This is why the Hermitage belongs to a specific type: the universal or encyclopaedic museum, like the Louvre, the British Museum, and the Metropolitan, which claims to narrate all of human artistic production rather than a nation's. But unlike the Louvre, which was turned over to the public by a revolution in 1793, the Hermitage remained an imperial possession for another century and a half. Its universalism was a dynastic project. The collection did not belong to Russia; it belonged to the Romanovs, and the Romanovs used it, as they used ballet and architecture, to assert their place among the great powers."},
    ],
  },
  {
    heading: "The building, or rather the buildings",
    blocks: [
      {"kind":"p","text":"The Hermitage is not one structure but an ensemble strung along the Palace Embankment of the Neva. From west to east: the Winter Palace (Bartolomeo Rastrelli's baroque extravagance of 1754–62, the main imperial residence); the Small Hermitage (Catherine's pavilion and galleries, by Vallin de la Mothe and Felten); the Old or Large Hermitage (Felten, 1770s–80s, built when the collection outgrew the Small); the Hermitage Theatre (Quarenghi, 1780s, on the site of Peter the Great's original Winter Palace, whose remnants are now visible beneath it); and, set back behind these, the New Hermitage, designed by the Munich architect Leo von Klenze and opened in 1852 under Nicholas I. Across Palace Square, the east wing of Carlo Rossi's General Staff Building has housed the nineteenth- and twentieth-century collections since 2014."},
      {"kind":"p","text":"Two episodes in the building history matter conceptually. The first is the fire of December 1837, which gutted the interiors of the Winter Palace. Nicholas I had them rebuilt in about fifteen months, and most of what a visitor now takes to be \"Rastrelli's\" palace is in fact a nineteenth-century reconstruction by Vasily Stasov and Alexander Briullov, sometimes faithful and sometimes freely reimagined. The Malachite Room, the Jordan Staircase in its present form, the vast parade halls: these are a Nicholaevan vision of an eighteenth-century palace. The Hermitage is, among other things, a monument to the idea that an authentic interior can be remade."},
      {"kind":"p","text":"The second is Klenze's New Hermitage, often cited as the first building in Russia designed from the ground up as a public museum. Klenze, who had already built the Glyptothek and Alte Pinakothek in Munich, brought the German museological idea of the 1830s and 40s: top-lit galleries for paintings, ground-floor halls for antiquities with decorative programmes keyed to their contents, and an organisation by national school and chronology that converts a princely accumulation into an educational narrative. The ten granite atlantes by Alexander Terebenev that hold up its portico have become one of the city's emblems. When the New Hermitage opened in 1852 the public was admitted, but under tight conditions: tickets issued by the court office, formal dress, no women unaccompanied. It was public in the way that an aristocrat's drawing room is public."},
    ],
  },
  {
    heading: "1917: the palace becomes a symbol",
    blocks: [
      {"kind":"p","text":"The Winter Palace is where, after the February Revolution, the Provisional Government sat, and where on the night of 25–26 October (7–8 November) 1917 the Bolsheviks arrested it. The \"storming\" was in reality a disorganised infiltration with relatively few casualties. Sergei Eisenstein's 1927 film *October* staged it as a mass assault with thousands of extras, and the film became the memory; it is often said the re-enactment did more damage to the building than the event. For anyone thinking about the Hermitage, this is an instructive lesson about how museums and their myths are co-produced."},
      {"kind":"p","text":"Nationalisation followed. The imperial collections, and then the confiscated collections of the aristocracy and the merchant class, poured into the Hermitage. Two merchant collections above all transformed it: those of Sergei Shchukin and Ivan Morozov, Moscow textile magnates who between roughly 1898 and 1914 bought Monet, Cézanne, Gauguin, Van Gogh, Picasso, and Matisse with a daring that Paris itself did not match. Shchukin commissioned Matisse's *Dance* and *Music* for his staircase. After 1917 these works were housed in Moscow's Museum of New Western Art until Stalin closed it in 1948 as a nest of \"formalism.\" The collections were divided between the Hermitage and the Pushkin Museum in Moscow, which is why the finest ensemble of early Matisse and Picasso in the world is split between two cities and why, for decades, much of it was in storage, too ideologically dangerous to hang."},
    ],
  },
  {
    heading: "The Soviet sales: the museum as treasury",
    blocks: [
      {"kind":"p","text":"Between 1928 and 1934 the Soviet state, desperate for hard currency to finance industrialisation, sold off parts of the Hermitage. The most consequential buyer was Andrew Mellon, the American Treasury Secretary, who quietly acquired about twenty-one masterpieces, including Raphael's *Alba Madonna*, Van Eyck's *Annunciation*, Botticelli's *Adoration of the Magi*, and Titian's *Venus with a Mirror*. These became the core of the National Gallery of Art in Washington, which Mellon founded. Calouste Gulbenkian in Lisbon took others. The Hermitage's curators fought the sales, sometimes at real personal risk, and the episode remains a wound in the institution's self-understanding. It also complicates any simple narrative of looting and restitution: the Hermitage is both a repository of objects taken from others and a victim of state-sanctioned dispersal."},
    ],
  },
  {
    heading: "War, siege, and trophy art",
    blocks: [
      {"kind":"p","text":"In the summer of 1941 the staff packed more than a million objects onto trains to Sverdlovsk (Yekaterinburg) in the Urals. During the nine-hundred-day siege of Leningrad the remaining staff lived in the cellars, sheltering some two thousand people, while curators gave tours of the empty frames to soldiers, describing the absent pictures from memory. This is the Hermitage's heroic legend, and unlike the storming of the palace it is largely true."},
      {"kind":"p","text":"After 1945 the museum received a different kind of cargo: art removed from Germany by Soviet trophy brigades, held in secret storage for half a century. In 1995 the exhibition *Hidden Treasures Revealed* displayed seventy-four Impressionist and Post-Impressionist works from German private collections (Degas's *Place de la Concorde* among them) that had been presumed destroyed. Russia's 1998 law on displaced cultural valuables declared most such objects federal property as compensation for Soviet losses. The German position is that they are looted. The Hermitage sits at the centre of an unresolved international dispute about who owns the spoils of the twentieth century, and it has generally taken the hard line that they are staying."},
    ],
  },
  {
    heading: "The collection as it actually is",
    blocks: [
      {"kind":"p","text":"Numbers first, with appropriate scepticism: roughly three million items, of which perhaps a few percent are on display across some three hundred and sixty rooms; something like a thousand rooms in the complex overall; and pre-pandemic attendance of three to four million. Beyond the main ensemble, the museum includes the Menshikov Palace on Vasilyevsky Island, the Imperial Porcelain Museum, and the Staraya Derevnya restoration and storage centre, where open storage lets visitors see the vast reserve."},
      {"kind":"p","text":"What should a beginner know is there? The Western European paintings: two Leonardo Madonnas (the *Benois* and the *Litta*, the latter's attribution long debated), the largest Rembrandt holdings outside the Netherlands including *The Return of the Prodigal Son* and *Danaë*, a Rubens room, Titian's late *St Sebastian*, Giorgione, a run of Spanish painting with Velázquez and Zurbarán and El Greco, and the Shchukin-Morozov French moderns now across the square. The Peacock Clock by James Cox, a life-size gilt automaton bought by Potemkin in 1781, still performs in the Pavilion Hall. Catherine's copy of Raphael's Vatican Loggias, commissioned when she could not have the original, is a monument to the eighteenth-century conviction that a perfect copy was itself a form of possession."},
      {"kind":"p","text":"What a specialist will tell you is that the painting galleries are not even the most extraordinary part. The Hermitage's Department of Archaeology holds the Siberian Collection of Peter the Great (Scythian gold acquired from grave-robbers in the early 1700s), the frozen tombs of Pazyryk in the Altai with the oldest surviving knotted-pile carpet and tattooed human remains from the fifth century BCE, and material from excavations across Central Asia, the Caucasus, and the Black Sea steppe that make it the key institution for understanding the nomadic world between Greece and China. The Hermitage ran and runs its own expeditions; it is a research institute with a museum attached as much as the reverse. Its Oriental department, its numismatics (over a million coins), its arms and armour, its Russian cultural history, and its restoration laboratories are each the size of a respectable national museum."},
    ],
  },
  {
    heading: "People and institutions: the Piotrovsky dynasty",
    blocks: [
      {"kind":"p","text":"The Hermitage has been directed by a father and son for most of the last sixty years. Boris Piotrovsky, an archaeologist of Urartu, ran it from 1964 to 1990 and steered it through late Soviet stagnation. His son Mikhail, an Arabist, has been director since 1992, making him one of the longest-serving museum heads anywhere. Under Mikhail the museum globalised: branch outposts in Amsterdam, London's Somerset House, Las Vegas (with the Guggenheim), Kazan, Vyborg, Omsk, and Venice. He also became a prominent public figure of the Putin era, and after the invasion of Ukraine in 2022 he defended Russian cultural projection abroad in terms that many Western colleagues found indefensible. Hermitage Amsterdam severed ties and rebranded; international loans froze. The museum that Catherine built to show Russia belonged to Europe is now, for the moment, largely cut off from it, which is itself a chapter in the same long story about art as an instrument of state."},
    ],
  },
  {
    heading: "Three conceptual lenses worth carrying",
    blocks: [
      {"kind":"p","text":"First, the palace-museum problem. In most museums the building serves the objects. In the Hermitage the building is one of the objects, and the two compete. You walk up the Jordan Staircase (named for the Epiphany blessing of the Neva that the tsars attended) not to reach a painting but because the staircase is the point. The best way to visit is to accept this and to treat the rooms, the ceilings, the parquet, and the views of the river as part of the collection."},
      {"kind":"p","text":"Second, provenance as a history of power. Almost every object has a story of transfer: bought from a bankrupt prince, confiscated from a merchant, dug from a Siberian barrow, carried from Berlin in 1945, or sold to Washington in 1931. The Hermitage is arguably the best place in the world to think about how collections move when states rise and fall, because it has been on every side of that process."},
      {"kind":"p","text":"Third, the museum as self-image. Catherine used it to prove Russia was European. Nicholas I used it to prove the autocracy was enlightened. The Soviets used it to prove the people had inherited the palaces, and then sold its treasures to build tractors, and then hid its Matisses. Post-Soviet Russia used it to re-enter the world and then, more recently, to defy it. Alexander Sokurov's film *Russian Ark* (2002), shot in a single ninety-six-minute take moving through thirty-three rooms and three centuries, understood this better than any catalogue: the Hermitage is Russia's argument with itself about what it is."},
    ],
  },
  {
    heading: "Small things that people love to know",
    blocks: [
      {"kind":"p","text":"A population of cats has lived in the cellars since Empress Elizabeth ordered them from Kazan in 1745 to control mice; they number several dozen today, have their own staff and press officer, and are a genuine part of the institution's identity. Rembrandt's *Danaë* was attacked with sulphuric acid and a knife in 1985 and took twelve years to restore; the picture you see is partly reconstruction, and its condition is a case study in conservation ethics. The Winter Palace is often said to contain over a thousand rooms, more than a hundred staircases, and nearly two thousand windows, figures that vary by source and that nobody appears to have counted the same way twice, which seems appropriate."},
      {"kind":"p","text":"If you remember only one thing: the Hermitage began as a private place for a woman who wanted to escape her own court, and it became the public face of an empire. Every strange feature of it, from its grandeur to its secrecy, from its universal ambitions to its nationalist defensiveness, follows from that."},
    ],
  },
];;
