import type { LessonSection } from "../curriculum";

export const sections: readonly LessonSection[] = [
  {
    heading: "An introductory course on food tolerance, weight gain, and symptom management",
    blocks: [
      {"kind":"callout","variant":"key","title":"Scope:","text":"This document provides general education, not a diagnosis or an individualized treatment plan. Significant weight loss, persistent difficulty eating, or new and worsening symptoms should be assessed by a healthcare professional."},
      {"kind":"p","text":"**Learning objectives**"},
      {"kind":"p","text":"By the end of this course, you should be able to:"},
      {"kind":"list","items":["Distinguish visceral hypersensitivity from a physically narrowed or blocked bowel.","Understand why eating—and sometimes abdominal pressure—can trigger symptoms.","Approach weight gain without relying on large, symptom-provoking meals.","Separate short-term symptom relief from long-term management."]},
    ],
  },
  {
    heading: "Lesson 1 — Understanding IBS and visceral hypersensitivity",
    blocks: [
      {"kind":"p","text":"**What is IBS?**"},
      {"kind":"p","text":"**Irritable bowel syndrome (IBS)** is a disorder of gut–brain interaction. Its main features are recurrent abdominal pain associated with changes in bowel movements, such as constipation, diarrhea, or both. Bloating and a sense of incomplete evacuation are also common."},
      {"kind":"p","text":"“Gut–brain interaction” refers to the two-way communication between the digestive tract and the nervous system. IBS can involve changes in intestinal movement, sensory processing, and the way the body responds to eating or stress."},
      {"kind":"p","text":"IBS itself is not expected to damage the intestine or cause significant nutrient malabsorption. Other conditions can coexist with IBS, however, and should not be overlooked."},
      {"kind":"p","text":"**What is visceral hypersensitivity?**"},
      {"kind":"p","text":"**Visceral hypersensitivity** means increased sensitivity to sensations arising from internal organs."},
      {"kind":"p","text":"For some people with IBS, ordinary intestinal events—stretching after a meal, movement of gas, or bowel contractions—produce unusually strong discomfort or pain. Sensory signals may be amplified in the gut’s nerves, the spinal cord, the brain, or a combination of these."},
      {"kind":"p","text":"This sensitivity is common in IBS, but it is not present in every person with the condition."},
      {"kind":"callout","variant":"key","title":"Insight:","text":"Pain intensity does not always correspond to the amount of gas, stretching, or tissue damage. A relatively ordinary digestive event can produce substantial pain in a sensitized system. That pain is real."},
      {"kind":"p","text":"**Does a “contracted” gut mean the bowel is closed?**"},
      {"kind":"p","text":"Not necessarily. The intestine normally contracts rhythmically to move its contents."},
      {"kind":"p","text":"A feeling of tightness, constriction, or being “locked up” may reflect:"},
      {"kind":"list","items":["Painful or altered intestinal contractions.","Heightened sensitivity to otherwise ordinary movement.","Constipation and associated distension.","Abdominal-wall muscle tension or protective bracing.","Sometimes, a coexisting pelvic-floor evacuation problem."]},
      {"kind":"p","text":"**The sensation of constriction is not proof of a fixed narrowing or obstruction.** A persistent physical blockage is a different medical problem—not a usual feature of IBS."},
      {"kind":"p","text":"**Safety checkpoint**"},
      {"kind":"p","text":"Seek urgent assessment for severe or worsening abdominal pain, repeated vomiting, a markedly swollen abdomen with inability to pass stool or gas, heavy bleeding, or black, tarry stools."},
      {"kind":"p","text":"Arrange medical evaluation for unexplained weight loss, persistent difficulty eating, anemia, fever, blood in the stool, or diarrhea that repeatedly wakes you from sleep. These findings should not automatically be attributed to IBS."},
    ],
  },
  {
    heading: "Lesson 2 — Why gaining weight can be difficult",
    blocks: [
      {"kind":"p","text":"**The main obstacle is often intake, not absorption**"},
      {"kind":"p","text":"In uncomplicated IBS, difficulty gaining weight is more often related to **insufficient or poorly tolerated food intake** than to an inability to absorb calories."},
      {"kind":"p","text":"A common cycle is:"},
      {"kind":"p","text":"**Eating → discomfort or urgency → smaller portions and food avoidance → inadequate energy intake → difficulty gaining weight.**"},
      {"kind":"p","text":"Several factors can reinforce this cycle:"},
      {"kind":"list","items":["Feeling full or uncomfortable before a meal is finished.","Avoiding foods associated with previous symptoms.","Skipping meals to avoid pain during work, travel, or social activities.","Removing multiple food groups without suitable replacements.","Trying to compensate with one very large meal or shake, which provokes more symptoms."]},
      {"kind":"p","text":"Prominent early fullness or upper-abdominal discomfort can also overlap with conditions such as functional dyspepsia. Persistent early satiety, vomiting, or weight loss deserves assessment rather than being assumed to be IBS alone."},
      {"kind":"p","text":"**Why “just eat more” may not work**"},
      {"kind":"p","text":"A large increase in food intake can simultaneously increase:"},
      {"kind":"list","ordered":true,"items":["**Volume:** More material stretches the digestive tract.","**Nutrient load:** Eating stimulates digestive hormones and bowel activity.","**Trigger exposure:** Larger servings may contain more fat, lactose, fermentable carbohydrates, or other poorly tolerated ingredients."]},
      {"kind":"p","text":"Weight gain therefore often requires changing **how calories are distributed and delivered**, not merely increasing portion size."},
      {"kind":"callout","variant":"key","title":"Insight:","text":"A gut that feels tight does not necessarily prevent nutrient absorption. The practical challenge is often finding a tolerable way to eat enough consistently—not mechanically “opening” the intestine."},
    ],
  },
  {
    heading: "Lesson 3 — Understanding symptom triggers",
    blocks: [
      {"kind":"p","text":"**A. Calorie-dense and fatty foods**"},
      {"kind":"p","text":"Calorie density is not a universal IBS trigger. Symptoms often depend on the food’s composition, serving size, and timing—not just its calorie count."},
      {"kind":"list","items":["A large, calorie-rich meal — Greater stretching and stronger meal-related bowel responses; Practical implication: Splitting the intake may be easier than eating it all at once","A large amount of fat in one sitting — Fat can slow stomach emptying, prolong fullness, and alter intestinal motor and sensory responses; Practical implication: Test smaller amounts of fat across meals rather than eliminating it entirely","Rich shakes or supplements — Lactose, certain fibers, or sugar alcohols may be poorly tolerated; Practical implication: Check ingredients as well as calories","Large servings of fermentable carbohydrates — Poorly absorbed carbohydrates can increase intestinal water and gas; Practical implication: Identify specific foods and portions rather than avoiding all carbohydrates"]},
      {"kind":"p","text":"**The gastrocolic response**"},
      {"kind":"p","text":"Eating normally signals the colon to become more active. In some people with IBS, this **gastrocolic response** is especially noticeable, producing cramps or urgency after meals."},
      {"kind":"p","text":"An urgent bowel movement immediately after eating does **not** mean the meal has already passed through the entire digestive tract. The meal can stimulate movement of material already in the colon."},
      {"kind":"p","text":"**Fat is not the enemy**"},
      {"kind":"p","text":"Fat is nutritionally important and provides substantial energy in a small volume. This can be useful when gaining weight."},
      {"kind":"p","text":"The difficulty may be the **amount of fat per eating occasion**, rather than fat being intolerable in every form or quantity. A modest addition of oil or nut butter may be manageable even when a large fried meal is not."},
      {"kind":"p","text":"Also, **fat and FODMAPs are different issues**. A low-FODMAP meal can still be very fatty and trigger symptoms."},
      {"kind":"callout","variant":"key","title":"Insight:","text":"“More calories with less volume” can help, but concentrating those calories into a large fat load may backfire. The useful balance is individual."},
      {"kind":"p","text":"**B. Mechanical stimulation inside the gut**"},
      {"kind":"p","text":"Mechanical stimulation includes stretching and pressure caused by:"},
      {"kind":"list","items":["Food and fluid entering the digestive tract.","Gas moving or accumulating.","Stool retention.","Normal muscular contractions."]},
      {"kind":"p","text":"With visceral hypersensitivity, these ordinary events may be experienced as painful. Constipation can increase the mechanical load, making otherwise tolerable meals more uncomfortable."},
      {"kind":"p","text":"Bloating also does not always mean there is an unusually large amount of gas. Sensitivity and the body’s muscular responses can contribute."},
      {"kind":"p","text":"**C. Pressure or movement around the abdomen**"},
      {"kind":"p","text":"Some people notice symptoms with:"},
      {"kind":"list","items":["Tight waistbands or belts.","Leaning the abdomen against a hard surface.","Deep abdominal massage.","Strong abdominal bracing or certain exercises."]},
      {"kind":"p","text":"However, pain from external pressure is **not automatically visceral hypersensitivity**. The abdominal wall, muscles, skin, and nerves can also be sources of pain. New, sharply localized, or persistent tenderness warrants assessment."},
      {"kind":"p","text":"Gentle everyday movement is generally not harmful and should not automatically be avoided. Forceful massage or repeatedly pressing on a painful area is not an established way to “release” an IBS gut."},
    ],
  },
  {
    heading: "Lesson 4 — Short-term management",
    blocks: [
      {"kind":"p","text":"**Immediate measures and the next several days**"},
      {"kind":"p","text":"The near-term aim is to lower symptom-provoking loads **while maintaining hydration and nutrition**."},
      {"kind":"p","text":"**1. Reduce the burden of individual meals**"},
      {"kind":"p","text":"For some people, three smaller meals plus one or two snacks are easier to tolerate than a few large meals."},
      {"kind":"p","text":"Useful adjustments include:"},
      {"kind":"list","items":["Splitting a large meal into two smaller eating occasions.","Eating at a comfortable pace rather than rushing.","Avoiding a very large, fatty meal when symptoms are already active.","Dividing a nutritional drink into smaller servings if a full serving causes symptoms."]},
      {"kind":"p","text":"These are experiments, not universal rules. More frequent eating can trigger repeated urgency in some people, so the pattern should be adjusted to the response."},
      {"kind":"p","text":"**Avoid using prolonged fasting as the main symptom-management strategy when weight gain is the goal.**"},
      {"kind":"p","text":"**2. Preserve calories with tolerated substitutions**"},
      {"kind":"p","text":"Reducing a trigger should ideally mean **replacing its nutritional contribution**, not simply removing food."},
      {"kind":"p","text":"Possible options, depending on individual tolerance, include:"},
      {"kind":"list","items":["Rice, potatoes, oats, bread, or other tolerated carbohydrate sources.","Eggs, fish, poultry, tofu, dairy, or other suitable protein sources.","Lactose-free alternatives when lactose is genuinely a problem.","Small additions of fat distributed across meals.","A dietitian-selected oral nutrition supplement when ordinary food is insufficient."]},
      {"kind":"p","text":"These are examples, not a universal “safe food” list. Supplements can also provoke symptoms because of their ingredients or serving size."},
      {"kind":"p","text":"**3. Reduce unnecessary pressure and bracing**"},
      {"kind":"p","text":"During a flare:"},
      {"kind":"list","items":["Loosen restrictive clothing.","Use a comfortably warm, covered heat pack, avoiding burns.","Try slow, comfortable breathing without forcing the abdomen outward.","Take a gentle walk if it feels helpful.","Avoid forceful abdominal massage or exercises that clearly worsen pain."]},
      {"kind":"p","text":"These measures may reduce discomfort or muscle guarding. They do not treat a mechanical obstruction."},
      {"kind":"p","text":"**4. Match symptom relief to the bowel pattern**"},
      {"kind":"p","text":"A clinician or pharmacist can help select appropriate options."},
      {"kind":"list","items":["**Cramping:** Some antispasmodics may help, although evidence and side effects vary. Some can worsen constipation.","**Pain or bloating:** Enteric-coated peppermint oil helps some people but may aggravate reflux.","**Constipation:** Appropriate treatment can reduce stool retention and pressure. Suddenly adding large amounts of fiber may worsen bloating.","**Diarrhea:** Hydration and, when appropriate, targeted treatment can reduce urgency. Controlling diarrhea does not necessarily resolve pain."]},
      {"kind":"callout","variant":"key","title":"Insight:","text":"Short-term relief is useful when it makes eating and daily activity more manageable. It should not become a cycle of increasingly restrictive eating and repeated rescue treatment without review."},
    ],
  },
  {
    heading: "Lesson 5 — Long-term management",
    blocks: [
      {"kind":"p","text":"**Sustained and structural measures**"},
      {"kind":"p","text":"Long-term management focuses on adequate nutrition, appropriate bowel function, and reduced symptom reactivity—not on trying to physically widen the bowel."},
      {"kind":"p","text":"**1. Confirm the diagnosis and look for overlapping problems**"},
      {"kind":"p","text":"IBS can often be diagnosed from a characteristic symptom pattern with selected testing. Extensive testing is not necessary for everyone."},
      {"kind":"p","text":"When weight gain is difficult, assessment may need to consider:"},
      {"kind":"list","items":["Whether intake is sufficient.","Celiac disease or other causes of malabsorption.","Inflammatory bowel disease when symptoms suggest it.","Persistent upper-digestive symptoms.","Constipation or an evacuation disorder.","Medication effects."]},
      {"kind":"p","text":"Do not assume that every new symptom belongs to an existing IBS diagnosis."},
      {"kind":"p","text":"**2. Build a nutrition plan that is sufficient and minimally restrictive**"},
      {"kind":"p","text":"A registered dietitian familiar with IBS can help establish:"},
      {"kind":"list","items":["Individual energy and protein needs.","Tolerable meal sizes and timing.","Nutritionally equivalent food substitutions.","A gradual method of increasing intake.","A plan for restoring foods that have been unnecessarily excluded."]},
      {"kind":"p","text":"If appropriate, a **low-FODMAP trial** may help identify dietary triggers. It is usually a short restriction phase—commonly about 2–6 weeks—followed by structured reintroduction and personalization."},
      {"kind":"p","text":"It is not intended to become a permanently restrictive diet. When someone is underweight, losing weight, or already eating very little, a full elimination phase may be inappropriate without specialist guidance."},
      {"kind":"callout","variant":"key","title":"Insight:","text":"The long-term objective is the broadest diet that supports adequate nutrition and acceptable symptoms—not the smallest possible list of “safe” foods."},
      {"kind":"p","text":"**3. Treat constipation, diarrhea, and evacuation problems appropriately**"},
      {"kind":"p","text":"Management differs between constipation-predominant, diarrhea-predominant, and mixed IBS."},
      {"kind":"p","text":"Examples include:"},
      {"kind":"list","items":["Gradually introduced soluble fiber, such as psyllium, when appropriate.","Clinician-selected treatment for persistent constipation or diarrhea.","Pelvic-floor assessment when there is excessive straining, a blockage sensation, or persistent incomplete evacuation."]},
      {"kind":"p","text":"If a defecatory disorder is confirmed, pelvic-floor biofeedback can be useful. Simply eating more fiber or doing generic strengthening exercises may not address the problem."},
      {"kind":"p","text":"**4. Address gut–brain sensitivity**"},
      {"kind":"p","text":"Treatments that target pain processing can help even when a person does not have an anxiety disorder."},
      {"kind":"p","text":"Options include:"},
      {"kind":"list","items":["**Gut-directed cognitive behavioral therapy.**","**Gut-directed hypnotherapy.**","**Clinician-prescribed neuromodulators** for selected patients.","Consistent sleep and manageable physical activity.","Strategies for reducing persistent abdominal bracing and symptom-related fear."]},
      {"kind":"p","text":"Medication choice matters: some medicines used for pain modulation can worsen constipation, for example."},
      {"kind":"p","text":"These approaches do not imply that symptoms are imagined. They address the nervous-system component of a genuine digestive disorder."},
      {"kind":"p","text":"**5. Increase intake gradually and review the trend**"},
      {"kind":"p","text":"A practical progression is:"},
      {"kind":"list","ordered":true,"items":["Establish several reliably tolerated meals.","Add one small snack or increase one meal component.","Observe the response without changing many other variables.","Retain successful additions and adjust unsuccessful ones.","Review weight and nutritional adequacy over time."]},
      {"kind":"p","text":"A weekly weight trend is usually more informative than repeated daily measurements, which are strongly affected by fluid and stool."},
      {"kind":"p","text":"Marked underweight, rapid weight loss, or prolonged very low intake warrants medical and dietetic supervision rather than an unsupervised “bulking” plan."},
    ],
  },
  {
    heading: "Application exercise — Build a tolerable weight-gain strategy",
    blocks: [
      {"kind":"p","text":"Use this framework to organize observations or prepare for a clinical appointment:"},
      {"kind":"list","items":["What is the main barrier? — Early fullness, urgency after meals, constipation, or pain from large portions","Which feature seems relevant? — Meal size, fat amount, a particular ingredient, or abdominal pressure","What can change without reducing total nutrition? — Split the meal, replace an ingredient, or distribute fat more evenly","What single addition might be tolerable? — One extra snack or a small increase in a familiar food","What should improve? — More consistent intake, better meal completion, manageable symptoms, and an appropriate weight trend"]},
      {"kind":"p","text":"Keep any food-and-symptom record brief and purposeful. The aim is to identify useful patterns—not to monitor every sensation indefinitely."},
      {"kind":"p","text":"**Central takeaway**"},
      {"kind":"p","text":"**IBS-related tightness and visceral hypersensitivity can make eating difficult, but they do not usually mean that the intestine is physically closed or unable to absorb nutrients.** Progress generally comes from combining adequate, tolerable nutrition with bowel-pattern treatment and gut–brain care—while investigating weight loss or other warning signs rather than attributing everything to IBS."},
    ],
  },
  {
    heading: "Further learning",
    blocks: [
      {"kind":"list","items":["[NIDDK: Irritable Bowel Syndrome](https://www.niddk.nih.gov/health-information/digestive-diseases/irritable-bowel-syndrome)","[NICE: Irritable bowel syndrome in adults](https://www.nice.org.uk/guidance/cg61)","[Monash University: FODMAP information and dietary guidance](https://www.monashfodmap.com/)"]},
    ],
  },
];;
