import type { LessonSection } from "../curriculum";

export const sections: readonly LessonSection[] = [
  {
    heading: "The central idea",
    blocks: [
      {"kind":"p","text":"Kubernetes, often shortened to K8s, is a distributed control system for running applications packaged as containers. You tell it what should exist—perhaps three copies of a web API—and it continually compares that declaration with what exists. If one copy dies, Kubernetes tries to replace it. If you request a different image, it tries to roll out new copies."},
      {"kind":"p","text":"The important word is “tries.” Kubernetes cannot create a machine that does not exist, repair an application bug, or make a database consistent merely by restarting it. An accepted declaration is stored intent, not a guarantee that the intent has been fulfilled."},
      {"kind":"p","text":"A cluster consists of a control plane, which makes and records decisions, and Nodes, which are machines that run workloads. A Node may be a physical server or a virtual machine. Containers package an application and its dependencies as processes with isolation and resource controls; they are not miniature virtual machines. Kubernetes orchestrates those processes across Nodes."},
    ],
  },
  {
    heading: "Objects, desired state, and reconciliation",
    blocks: [
      {"kind":"p","text":"You interact primarily with the Kubernetes API. An API object has a kind, such as Pod or Deployment, and metadata such as a name. Many objects also have a spec, describing desired state, and a status, reporting observations. A Deployment’s spec might request three replicas; its status might report that only two are currently available."},
      {"kind":"p","text":"You commonly describe objects in YAML manifests and submit them with kubectl apply. The command does not directly launch three containers. It writes objects to the API. Controllers then observe those objects and take actions intended to bring actual state toward desired state. This repeated observe–compare–act process is called reconciliation."},
      {"kind":"p","text":"Reconciliation is asynchronous. Different controllers can observe changes at different times; a scheduler can find no suitable Node; an image download can fail. Thus, “the object exists,” “a Pod was scheduled,” “its process is running,” and “the application is ready to serve” are four different claims."},
      {"kind":"p","text":"Objects also have identity and ownership. A name is human-friendly, but a UID distinguishes one incarnation from another object later created with the same name. Namespaces scope many objects: a Service named api can exist separately in two namespaces. A Namespace is an administrative scope, not a Linux network namespace or, by itself, a strong security boundary. Labels are short key–value attributes used for selection—for example, identifying which Pods belong behind a Service. Annotations carry metadata that is generally not used for selection."},
      {"kind":"p","text":"A controller can set owner references so dependent objects are garbage-collected when their owner is deleted. A finalizer does the opposite for a time: it holds deletion open while a controller performs cleanup. A stuck finalizer can therefore leave an object perpetually “terminating.”"},
      {"kind":"p","text":"Two less visible fields matter when reasoning about races. Generation identifies revisions of an object’s desired state; observedGeneration, when a controller reports it, helps indicate whether its status reflects the latest revision. ResourceVersion is an opaque concurrency token used to detect conflicting updates, not a timestamp or a general-purpose sequence number."},
    ],
  },
  {
    heading: "What runs the cluster",
    blocks: [
      {"kind":"p","text":"The API server is the front door. It authenticates requests, checks authorization, applies admission rules, and reads or writes cluster state. etcd is the strongly consistent datastore behind that state. It stores Kubernetes API data, not your application’s database records. A highly available etcd installation needs a majority of its members to make progress."},
      {"kind":"p","text":"The controller manager runs many built-in control loops. The scheduler chooses a Node for an unscheduled Pod, considering resource requests and placement rules. On each Node, the kubelet works to make assigned Pods run. It talks to a container runtime, commonly containerd, through the Container Runtime Interface, or CRI. OCI standards describe underlying container image and runtime conventions; Kubernetes does not require the Docker engine."},
      {"kind":"p","text":"Other interfaces separate Kubernetes from infrastructure implementations. A CNI plugin supplies Pod networking. CSI drivers integrate storage. Device plugins and related mechanisms expose specialized hardware such as GPUs. A cloud controller manager, where applicable, integrates cloud-specific Nodes, routes, and load balancers. CoreDNS commonly supplies cluster DNS. These components are related but not interchangeable: scheduling a Pod, connecting it to the network, and mounting its volume are distinct operations."},
      {"kind":"p","text":"Some network implementations use kube-proxy to program Service traffic forwarding on Nodes; others replace that function, often using eBPF. Despite its name, kube-proxy commonly programs packet-handling rules rather than relaying every request through a user-space proxy."},
      {"kind":"p","text":"A useful failure distinction follows from this architecture: if the control plane becomes temporarily unavailable, already-running containers may keep running and some existing traffic may keep flowing. Creating replacements, changing desired state, or reacting to failures may not work until control-plane service returns. “Control plane down” and “every application process stopped” are not equivalent."},
    ],
  },
  {
    heading: "Pods: the unit Kubernetes places",
    blocks: [
      {"kind":"p","text":"A Pod is the smallest unit the Kubernetes scheduler places on a Node. It contains one or more containers that share a network namespace and therefore a Pod IP and localhost. Containers in one Pod can communicate over localhost, but they can also conflict if they try to bind the same port. They may share volumes that the Pod declares."},
      {"kind":"p","text":"Most Pods contain one main application container. Multiple containers are appropriate when they genuinely share a lifecycle and locality—for example, an application and a closely coupled helper. Init containers run before the main application containers. Sidecars provide ongoing support, while ephemeral containers can be added for debugging in supported circumstances."},
      {"kind":"p","text":"A Pod is not a permanent machine. A container can restart within an existing Pod, depending on its restart policy. If the Pod itself is replaced, the replacement has a new UID and ordinarily a new IP, even if a higher-level controller gives it a familiar-looking name. Applications should not treat an ordinary Pod IP or its writable container filesystem as durable identity or storage."},
      {"kind":"p","text":"Health checks have different meanings. A liveness probe asks whether a container should be restarted. A readiness probe asks whether it should ordinarily receive Service traffic. A startup probe gives a slow-starting application time before other probes take effect. A process can be running but not ready. Poorly designed liveness probes—for example, killing every application instance because a shared dependency is momentarily slow—can turn a transient incident into a cluster-wide outage."},
    ],
  },
  {
    heading: "Workload controllers",
    blocks: [
      {"kind":"p","text":"You normally create a controller rather than a bare Pod. A Deployment manages interchangeable Pods, usually for stateless applications. It creates ReplicaSets, which maintain the requested number of Pod replicas. When you change the Pod template, the Deployment generally creates a new ReplicaSet and replaces Pods according to its rollout settings. Kubernetes can roll back the Pod template to a previous revision; that does not roll back database migrations or other external changes."},
      {"kind":"p","text":"A StatefulSet is for workloads needing stable per-replica identity and often persistent storage. Its Pods receive predictable names such as database-0, and each can retain an associated persistent claim across Pod replacement. A headless Service can provide per-Pod DNS names. These facilities help operate a database; they do not implement replication, leader election, transactions, backups, or recovery for the database itself."},
      {"kind":"p","text":"A DaemonSet seeks to run a Pod on every eligible Node, or on a selected subset. Node-level log collectors and networking agents are common examples. A Job runs work toward completion, with controls for retries and parallelism. A CronJob creates Jobs on a schedule. Neither Jobs nor CronJobs provide a magical “exactly once” guarantee for external effects: failures, retries, and scheduling races mean tasks that charge cards or mutate external systems should be designed for idempotency."},
    ],
  },
  {
    heading: "Networking and service discovery",
    blocks: [
      {"kind":"p","text":"In the usual Kubernetes network model, each Pod has its own IP, and Pods can communicate over the cluster network. A networking plugin makes that model real through routing, overlays, policy, or other mechanisms. The Pod IP is an endpoint, not a stable application address."},
      {"kind":"p","text":"A Service supplies a stable way to reach a changing set of Pods. Typically, its label selector chooses candidate Pods, and readiness determines which are ordinarily published as usable endpoints. EndpointSlice objects represent those endpoints efficiently. A Service can have a stable virtual IP even while its Pods are repeatedly replaced."},
      {"kind":"p","text":"A ClusterIP Service is reachable inside the cluster. NodePort exposes a port on Nodes. LoadBalancer asks an infrastructure integration or other implementation to expose the Service externally. ExternalName is primarily a DNS alias, not a proxy. A headless Service has no virtual ClusterIP and exposes endpoint identities through DNS, which is particularly useful with StatefulSets."},
      {"kind":"p","text":"Cluster DNS commonly lets an application resolve a name such as api.shop.svc.cluster.local: the api Service in the shop namespace. The exact cluster DNS suffix is configurable. DNS answers and established connections do not necessarily change at the instant an endpoint changes; applications still need sensible connection timeouts and retry behavior."},
      {"kind":"p","text":"Services mainly solve stable discovery and transport-level distribution. Ingress describes HTTP or HTTPS routing by properties such as host and path, but it does nothing without an Ingress controller. Gateway API offers a more expressive family of routing resources, also requiring an implementation. A service mesh, if installed, can add features such as workload-to-workload mTLS and traffic policy; it is optional infrastructure, not an inherent property of a Service."},
      {"kind":"p","text":"NetworkPolicy is about permitted Pod traffic, usually at the IP-and-port level. It works only when the network implementation enforces it. In the absence of applicable policies, Kubernetes NetworkPolicy does not impose a default isolation boundary. Policies are additive allow rules rather than ordered firewall rules with explicit deny precedence. Once you restrict egress, remember that workloads may also need permission to reach DNS and necessary dependencies. NetworkPolicy alone does not authenticate an HTTP caller or encrypt traffic."},
    ],
  },
  {
    heading: "Storage, configuration, and secrets",
    blocks: [
      {"kind":"p","text":"A container’s writable layer is normally disposable. An emptyDir volume lasts for the lifetime of a Pod and survives an individual container restart, but disappears when that Pod is removed. A PersistentVolume, or PV, represents available persistent storage; a PersistentVolumeClaim, or PVC, requests it. A StorageClass describes how storage can be provisioned, commonly through a CSI driver. “Persistent” describes the storage’s intended lifecycle relative to Pods, not immunity to operator error, provider failure, or data corruption."},
      {"kind":"p","text":"Storage placement interacts with scheduling. A volume that exists in one availability zone may prevent its Pod from running in another. A StorageClass with WaitForFirstConsumer binding can postpone provisioning until the scheduler has enough context to avoid that mismatch. Access modes also matter: ReadWriteOnce generally means writable from one Node, not necessarily one Pod; ReadWriteOncePod, when supported, restricts use to one Pod; ReadWriteMany permits access across Nodes when the storage system provides it. Shared access does not make concurrent writes application-safe."},
      {"kind":"p","text":"Reclaim policies affect what happens to underlying storage after a claim is released. Volume snapshots depend on driver support and are not automatically application-consistent backups. Databases still need appropriate quiescing, backup, restore testing, and often copies outside the cluster."},
      {"kind":"p","text":"A ConfigMap holds non-secret configuration. A Secret holds sensitive values as an API object, but base64 representation is encoding, not encryption. Protect Secrets with narrowly scoped permissions, encryption at rest where configured, and careful handling of what Pods can mount. A value provided through an environment variable will not change inside a running process merely because its ConfigMap or Secret changes; mounted values can be refreshed eventually in common configurations, with exceptions such as subPath mounts. Configuration rollout strategy is therefore part of application design."},
    ],
  },
  {
    heading: "Scheduling and resource economics",
    blocks: [
      {"kind":"p","text":"A resource request tells Kubernetes how much CPU, memory, or another schedulable resource a Pod asks for. The scheduler places Pods based primarily on requests and Node allocatable capacity, not a forecast of what the process will use tomorrow. Requests are not, by themselves, hard ceilings. Limits are ceilings enforced at runtime where applicable: a CPU-constrained container can be throttled; a container exceeding a memory limit can be killed. Node memory pressure can also cause eviction. Ephemeral storage—logs, writable layers, and disk-backed temporary volumes—can become a scheduling or eviction concern."},
      {"kind":"p","text":"This creates an economic tradeoff. Requests that are too small permit overcommit but can produce contention and eviction. Requests that are far too large strand capacity and leave Pods Pending despite apparently idle machines. Kubernetes classifies Pods into Guaranteed, Burstable, and BestEffort quality-of-service classes according to their resource settings; these affect behavior under resource pressure but are not absolute promises of availability. LimitRange and ResourceQuota can establish defaults and boundaries for a namespace."},
      {"kind":"p","text":"The scheduler first filters out Nodes that cannot satisfy hard constraints and then scores eligible Nodes. A node selector or required node affinity constrains placement by labels. Preferred affinity expresses a softer preference. Pod affinity or anti-affinity considers where other Pods are running. Topology spread constraints aim to distribute replicas across failure domains such as Nodes or zones."},
      {"kind":"p","text":"Taints repel Pods; tolerations allow Pods to disregard specified taints. A toleration permits placement but does not demand it. A NoExecute taint can also cause eviction, subject to tolerations. Priority classes can let important Pods preempt less important ones, but priority cannot manufacture capacity or fix impossible constraints. The normal scheduler places unscheduled Pods; it does not continuously migrate healthy running Pods to improve balance."},
      {"kind":"p","text":"Availability is often limited by constraints rather than raw totals. A cluster might have enough aggregate CPU for three replicas but only one eligible zone because of volume location, affinity, or a taint. The precise question is not “How much CPU does the cluster have?” but “Can each required Pod be placed while satisfying every relevant constraint and failure-domain objective?”"},
      {"kind":"p","text":"Scaling is several interacting control loops. A Horizontal Pod Autoscaler, or HPA, changes replica counts using metrics; CPU utilization targets are expressed relative to CPU requests. A Vertical Pod Autoscaler, if installed, recommends or changes resource requests and may require Pod replacement. A cluster autoscaler or other Node provisioner changes machine capacity. More Pods can therefore become Pending before more Nodes exist, and new Nodes do not immediately yield ready application endpoints. Multiple controllers writing the same replica count—for example, an HPA and a manifest repeatedly reapplied with a fixed count—can fight each other."},
    ],
  },
  {
    heading: "Rollouts and failure tolerance",
    blocks: [
      {"kind":"p","text":"A rolling Deployment update replaces old Pods gradually, constrained by settings such as maxSurge and maxUnavailable. “Zero downtime” is not a property of the update strategy alone. It also requires enough spare capacity, reliable readiness checks, an application that can terminate gracefully, and compatible changes to dependencies and data."},
      {"kind":"p","text":"When a Pod terminates, its endpoints are updated asynchronously, containers are given a termination grace period, and processes generally receive a termination signal before being forcibly stopped. A preStop hook can participate in shutdown, but consumes part of that grace period. Existing connections and in-flight requests require application-level handling; there is no cluster-wide atomic instant at which all traffic moves to new Pods."},
      {"kind":"p","text":"A PodDisruptionBudget, or PDB, constrains certain voluntary disruptions using the Eviction API, notably during Node draining. It does not prevent a machine from failing, guarantee replacement capacity, or universally govern a Deployment’s own rolling update. A strict PDB combined with strict placement rules and no spare Nodes can make maintenance impossible until capacity is added."},
      {"kind":"p","text":"Replicas distributed across Nodes and zones can survive some failures, but replicas of a broken release can all fail together. Kubernetes improves the mechanics of recovery; genuine resilience also requires independent failure domains, capacity headroom, safe data handling, and application behavior under partial failure."},
    ],
  },
  {
    heading: "Security and tenancy",
    blocks: [
      {"kind":"p","text":"An API request passes through authentication, authorization, and admission. Users commonly authenticate through external identity systems or certificates; ServiceAccounts are API objects that give workloads an identity. RBAC expresses allowed actions with Roles and ClusterRoles, bound to subjects through RoleBindings and ClusterRoleBindings. A RoleBinding can grant a ClusterRole’s permissions within one namespace; a ClusterRoleBinding grants them at cluster scope."},
      {"kind":"p","text":"ServiceAccount credentials are commonly projected into Pods. Workloads that do not need the API can disable automatic mounting, and workloads that access cloud services should prefer appropriately scoped workload identity over long-lived static credentials. A significant permission trap is that a principal allowed to create arbitrary Pods in a namespace may be able to mount and extract Secrets there even without direct permission to read Secret objects."},
      {"kind":"p","text":"Pod Security Admission can enforce levels such as baseline or restricted. Other defenses include non-root execution, dropped Linux capabilities, seccomp, carefully controlled host access, image scanning and signing, admission policy, and network isolation. Privileged Pods, hostPath mounts, and broad API permissions are especially powerful. Namespaces organize policy and access, but mutually hostile tenants sharing Nodes need a more rigorous isolation design; ordinary containers share a kernel."},
      {"kind":"p","text":"Kubernetes uses TLS for its API, but it does not automatically encrypt every application connection or encrypt every Secret at rest in every installation. The security of a workload also depends on its image supply chain, registry access, runtime configuration, Nodes, networking, storage, and the humans or automation permitted to change those things."},
    ],
  },
  {
    heading: "Extending and operating the system",
    blocks: [
      {"kind":"p","text":"A CustomResourceDefinition, or CRD, adds a new API kind. An operator is typically a controller that watches such resources and reconciles some domain-specific system—for example, provisioning and maintaining a database cluster. Good controllers are idempotent because events can be repeated and an action may succeed before its result is observed. They report useful status and handle deletion cleanly with finalizers where needed. CRDs extend the vocabulary of Kubernetes; they do not change the asynchronous nature of reconciliation."},
      {"kind":"p","text":"Admission webhooks can validate or mutate API requests. They are powerful policy points, but their latency and availability become part of the API write path. Server-side apply tracks ownership of individual object fields and can report conflicts when independent managers try to control the same field. This matters when Helm, GitOps automation, operators, autoscalers, and humans all touch the same object."},
      {"kind":"p","text":"Helm packages and renders Kubernetes resources; Kustomize assembles and customizes manifests; GitOps controllers such as Argo CD or Flux try to reconcile cluster configuration with a version-controlled source. These are ecosystem tools, not substitutes for the built-in workload controllers. They add another layer of desired-state management, and conflicting sources of truth still cause trouble."},
      {"kind":"p","text":"Operationally, inspect both intent and observation. kubectl get provides a quick view; kubectl describe exposes conditions and recent Events; kubectl logs shows container output; kubectl rollout status follows a rollout. Events are useful but short-lived, not a durable audit trail. Metrics Server can support resource metrics for commands such as kubectl top and some autoscaling uses; substantial monitoring, centralized logs, tracing, alerting, and audits require additional systems."},
      {"kind":"p","text":"Status labels should be read precisely. Pending can mean scheduling or setup has not completed. ImagePullBackOff points toward image retrieval trouble; CrashLoopBackOff describes repeated restart attempts; OOMKilled indicates a memory-related kill. These displayed reasons are not all Pod phases. A Pod whose phase is Running can still be unready and receive no ordinary Service traffic."},
    ],
  },
  {
    heading: "An end-to-end example",
    blocks: [
      {"kind":"p","text":"Suppose you declare a three-replica Deployment for an API and a Service selecting its Pods. The Deployment controller creates a ReplicaSet; the ReplicaSet controller creates Pods. The scheduler assigns each Pod to a suitable Node. Each Node’s kubelet asks its runtime to start the containers, its networking implementation to connect the Pod, and the relevant storage components to mount requested volumes. Once readiness succeeds, endpoint data is updated, and the Service can send suitable new traffic to the Pod."},
      {"kind":"p","text":"If one Node fails, the control plane eventually notices missing or unhealthy Pods and tries to restore the requested replica count elsewhere. That attempt succeeds only if another Node has capacity, the scheduling rules permit placement, storage can attach there, images can be fetched, and the application can become ready. This is Kubernetes in miniature: powerful automation, bounded by physical resources, distributed-system delays, and application correctness."},
      {"kind":"p","text":"The deepest mental model is therefore not “Kubernetes runs containers.” It is “Kubernetes exposes an API for intent and coordinates many imperfect, asynchronous control loops toward that intent.” Knowing which layer owns a particular promise—application, workload controller, scheduler, network, storage system, or operator—is the difference between recognizing Kubernetes vocabulary and understanding what a cluster will actually do."},
    ],
  },
];;
