import type { LessonSection } from "../curriculum";

export const sections: readonly LessonSection[] = [
  {
    heading: "What it is, and what it is not",
    blocks: [
      {"kind":"p","text":"LangChain is an open-source library, available in Python and TypeScript, whose job is to sit between your application code and a large language model, which here means a hosted or local neural network that takes text (and increasingly images, audio, and structured tool results) and produces text or structured output. The library exists because the raw experience of calling such a model is deceptively simple and then becomes a mess in every direction at once: each provider exposes a different HTTP shape, prompts are strings that you somehow have to template safely, the model returns prose when you wanted JSON, the model is stateless when your product needs a conversation, the model knows nothing about your documents, and almost nothing interesting fits in a single call. LangChain's claim is that each of those problems can be given an interface, and that the interfaces can be made to compose."},
      {"kind":"p","text":"The single most useful thing to understand before learning any vocabulary is that LangChain has two very different kinds of surface. The first is a small set of load-bearing abstractions, meaning concepts that encode a real decision about how LLM applications are shaped and that you will keep using even if you abandon the library: the message, the model interface, the tool-call schema, the document, the runnable protocol, and the state graph. The second is a large and historically unstable layer of convenience constructors, pre-built chains, memory classes, and agent executors that wrap those primitives into one-liners. The convenience layer is where newcomers start and where senior engineers get burned, because it has churned repeatedly and much of it has been deprecated. Throughout this piece I will say which is which, and where my knowledge of the current state may be stale, since the framework reorganized itself substantially in a 1.0 release in late 2025 and I may be describing some details from the pre-1.0 world."},
    ],
  },
  {
    heading: "The model interface",
    blocks: [
      {"kind":"p","text":"The foundation is an abstraction over the model itself. LangChain originally distinguished an LLM, meaning a text-in text-out completion endpoint, from a chat model, meaning a model whose input is a sequence of role-tagged messages and whose output is a single message. The distinction mattered in 2023 and barely matters now, because nearly every serious provider only ships chat-shaped APIs; treat the chat model as the real interface and the bare LLM class as legacy."},
      {"kind":"p","text":"A message is a small record with a role and content. The roles you will meet are the system message, which carries instructions the model should treat as authoritative framing; the human message, which carries the user's turn; the AI message, which carries the model's turn and may also carry tool calls, discussed below; and the tool message, which carries the result of executing a tool back to the model. The message type is one of the genuinely load-bearing concepts, because it is LangChain's lingua franca across providers: you build a list of messages once, and the provider integration translates them into whatever OpenAI, Anthropic, Google, Mistral, Ollama, or Bedrock actually wants on the wire. The problem it solves is portability. Where it leaks is in the places providers disagree: whether a system message can appear mid-conversation, whether consecutive messages of the same role are allowed, how images are embedded in content, how many tool calls a single AI message may carry, and what a token budget means for a given model. The abstraction hides the translation but cannot hide the fact that some conversations are valid for one provider and rejected by another, and the error you see will be the provider's, not LangChain's."},
      {"kind":"p","text":"Content itself has grown complicated. Early on, content was a string; now it is either a string or a list of content blocks, meaning typed parts such as text, image, or provider-specific reasoning blocks. The 1.0 line standardized a content-block format across providers, and I would flag the precise shape of that as uncertain in my memory; what is certain is that if you write code assuming message content is always a string, it will break the first time a model returns a structured block."},
    ],
  },
  {
    heading: "Prompts and templates",
    blocks: [
      {"kind":"p","text":"A prompt template is a prompt with holes in it. The problem it solves is that string formatting with user-supplied data is both tedious and a security hazard, and that chat prompts are lists of messages rather than single strings, so you want to template the whole list, including placeholders for an entire conversation history. The chat prompt template lets you declare a system message with variables, a placeholder slot where prior messages are spliced in, and a human message with variables, and then fill the whole thing from a dictionary. This is useful but not deep. The leak is twofold. First, templates are rendered as plain substitution, so untrusted input can still inject instructions, and the template does nothing to protect you; prompt injection, meaning the exploitation of a model's inability to distinguish data from instructions, is a property of the model and no templating layer fixes it. Second, templates encourage you to think of prompts as static artifacts when the hard engineering problem is usually dynamic: which examples to include, how to truncate history, how to render retrieved documents. Templates are worth knowing as vocabulary, but I would call them incidental API surface rather than architecture."},
    ],
  },
  {
    heading: "Output parsers and structured output",
    blocks: [
      {"kind":"p","text":"An output parser takes the model's text and turns it into a Python object: a string, a JSON dictionary, a list, or a Pydantic model, which is a Python class describing a typed schema with validation. The problem is obvious, since a model's reply is a sentence and your code wants a value. The original parsers worked by injecting format instructions into the prompt and then regex-or-JSON-parsing the reply, which was fragile. The modern answer, exposed as a method on chat models that binds a schema and returns validated objects, uses the provider's native structured-output or tool-calling mechanism, where the model is constrained or at least strongly steered to emit JSON conforming to a schema. This is one of the places where LangChain adds real value: you hand it a Pydantic class or a JSON schema and it picks the best provider mechanism available. Where it leaks is in the question of what \"best\" means. Some providers offer hard constrained decoding, some offer soft tool-calling, some offer neither, and the method's behavior differs in failure modes, in whether optional fields are honored, in whether nested schemas are supported, and in whether you get back a partially valid object on error. The single method name hides three different reliability tiers. Senior engineers should always ask which mode is actually being used underneath."},
    ],
  },
  {
    heading: "The runnable protocol and LCEL",
    blocks: [
      {"kind":"p","text":"Here is the first genuinely architectural idea. A runnable is any object that implements a standard protocol: a synchronous invoke that takes one input and returns one output, a batch that takes many, a stream that yields incremental output, and asynchronous versions of all three. Models, prompt templates, parsers, retrievers, and arbitrary functions all implement this protocol, which means they can be composed, and the composed thing is itself a runnable with the same methods. LangChain Expression Language, universally called LCEL, is the composition syntax: in Python, the pipe operator chains runnables so that the output of one becomes the input of the next, dictionaries of runnables run in parallel and produce a dictionary, and plain functions are wrapped automatically."},
      {"kind":"p","text":"The problem LCEL solves is not aesthetic. If you hand-write a pipeline as a function that calls a template, then a model, then a parser, you get a sync, non-streaming, non-batched pipeline, and adding streaming or async later means rewriting it. Because every LCEL component implements the whole protocol, a composed chain gets streaming, batching, async, retries, fallbacks, and tracing for free. Streaming in particular is nontrivial: a parser that can consume partial JSON lets you stream a structured object as it is generated, and LCEL wires that through automatically. That is the load-bearing part, and the runnable protocol itself is a sound idea you could reimplement without LangChain."},
      {"kind":"p","text":"Where it leaks is well known. Operator overloading makes stack traces opaque; when a chain fails three levels deep you get a trace through generic sequence machinery rather than through your code. The coercion rules that turn a dictionary into a parallel runnable or a lambda into a runnable are convenient until you cannot tell why your input was reshaped. Wrapping an ordinary function breaks streaming, because the function needs the whole input before it can run, and a single such step silently makes the rest of the chain non-streaming. And LCEL is a directed acyclic graph: it can branch and merge but cannot loop, which is exactly what an agent needs, and that limitation is the reason LangGraph exists."},
      {"kind":"p","text":"One more concept travels with runnables: the runnable config, meaning a dictionary passed alongside the input carrying callbacks, tags, metadata, a run name, and configurable fields such as which model to use. Config is how tracing propagates through a chain. It leaks at concurrency boundaries: in Python it rides on context variables, which are not reliably inherited across threads and some async boundaries, so a tracing span can mysteriously detach if you spawn work manually. If a trace looks truncated, this is the first place to look."},
    ],
  },
  {
    heading: "Legacy chains and the deprecation story",
    blocks: [
      {"kind":"p","text":"Before LCEL, LangChain shipped named chain classes: a chain that wrapped a prompt and a model, a chain that answered questions over documents, a chain that summarized by mapping over chunks and reducing, a chain that routed between sub-chains. These were the library's original pitch and most tutorials from 2023 use them. They were progressively deprecated in favor of LCEL equivalents and, as I understand the 1.0 reorganization, moved into a separately installed legacy package so that the main package could be slimmed down. I would treat the exact package name and import paths as uncertain, but the direction is not: if you find yourself reaching for a named chain class, assume it is legacy and look for the two-line LCEL or LangGraph replacement. The lesson for distinguishing surface from substance is that these chains were never abstractions; they were recipes, and recipes should live in your codebase where you can read them."},
    ],
  },
  {
    heading: "Tools and tool calling",
    blocks: [
      {"kind":"p","text":"A tool is a function the model may ask to have executed on its behalf, described to the model by a name, a natural-language description, and a JSON schema of its arguments. Tool calling is the provider feature whereby the model, instead of replying in prose, emits a structured request naming a tool and supplying arguments, and your code is responsible for actually running it and sending the result back as a tool message. This is the mechanism underlying agents, structured output, and most of what makes current models useful beyond chat, and the tool-call schema is a load-bearing concept that long outlives any particular library."},
      {"kind":"p","text":"LangChain's contribution is a decorator that turns an ordinary function into a tool, inferring the schema from type hints and the docstring, and a method on chat models that binds a set of tools so the model knows about them. The AI message that comes back has a list of tool calls, each with a name, parsed arguments, and an id that must be echoed in the corresponding tool message so the model can correlate results. The problem solved is, again, portability plus boilerplate removal: writing JSON schemas by hand for every function is miserable and provider formats differ."},
      {"kind":"p","text":"The leaks are instructive. Schema inference is only as good as your type hints, and complex types degrade into loose schemas the model will fill badly. Providers differ on whether the model may emit several tool calls at once, on whether tool-call arguments arrive as a parsed object or a JSON string that may be malformed, on how strictly the schema is enforced, and on whether a tool message can be followed by anything other than an AI message. The description string is doing enormous and invisible work, since the model chooses tools by reading it, and no amount of type safety helps if the description is vague. And the decorator hides the fact that tool execution is your responsibility: nothing runs automatically unless you put it in a loop, which brings us to agents."},
    ],
  },
  {
    heading: "Agents",
    blocks: [
      {"kind":"p","text":"An agent, in LangChain's vocabulary, is a loop in which a model is given tools, decides whether to call one, the call is executed, the result is appended to the messages, and the model is invoked again until it replies without a tool call. This pattern descends from the ReAct paper, which interleaved reasoning text with actions; modern agents mostly rely on native tool calling rather than parsing reasoning out of prose, but the name stuck. The problem agents solve is that you cannot script in advance which tools a task needs or in what order; you let the model plan at runtime."},
      {"kind":"p","text":"The implementation history is the single churniest part of the library, and here I will be careful. The original agent executor was a class wrapping the loop with configurable parsing and stopping conditions, and it is deprecated. It was replaced by a prebuilt function in LangGraph that constructs the loop as a graph, which became the recommended path through 2024 and most of 2025. The 1.0 release then introduced a new top-level agent constructor in the main package, built on LangGraph underneath, with a middleware mechanism for inserting behavior before and after the model call and around tool execution, intended to cover things like summarizing history, approving dangerous tool calls, and enforcing budgets. I am reasonably confident about that shape and less confident about the exact middleware API, so verify against current docs rather than trusting any specific hook name from memory."},
      {"kind":"p","text":"Where agents leak is where every autonomous loop leaks. Termination is not guaranteed, so you need an iteration cap, and the cap is a crude tool. Cost scales with turns and with the growing message history that is re-sent every turn. The model may call a tool with hallucinated arguments, call the wrong tool, or ignore a tool it should use, and the framework can detect none of this; it can only run the loop. Error handling for failed tools is a design decision, since you must choose whether to surface the exception to the model as a tool message, retry, or abort, and the convenience constructors each pick a default you may not want. Most importantly, the one-line agent constructor hides a graph, and the moment you need to customize the loop you will be reading that graph anyway, so it is worth understanding the graph first."},
    ],
  },
  {
    heading: "Memory",
    blocks: [
      {"kind":"p","text":"Memory in LangChain means persistence of conversation state across invocations, since the model itself remembers nothing. The original memory classes stored a transcript buffer, a window of recent turns, a running summary, or an entity table, and were attached to chains that would read from and write to them automatically. These classes are deprecated and I would call them incidental surface. They were replaced first by a runnable wrapper that threads message history keyed by a session id into any LCEL chain, and then, in the LangGraph era, by checkpointing, which is described below and is the actual recommended mechanism."},
      {"kind":"p","text":"The problem memory solves is real, but the abstraction leaks in two ways that the class names obscured. First, memory is just more tokens in the prompt, so a growing transcript eventually exceeds the context window, meaning the maximum number of tokens the model can attend to, and any summarization strategy loses information in ways you must evaluate rather than assume. Second, conversational memory is not learning; nothing about the model changes, and users consistently expect more than a transcript provides. Long-term memory across sessions, such as remembering a user's preferences, is a retrieval problem rather than a buffer problem, and the library has shipped a separate store abstraction for it whose maturity I would not vouch for from memory."},
    ],
  },
  {
    heading: "Retrieval and the document pipeline",
    blocks: [
      {"kind":"p","text":"Retrieval-augmented generation, usually shortened to RAG, is the pattern of fetching relevant text from your own corpus and inserting it into the prompt so the model can answer from it. LangChain's retrieval vocabulary is extensive and most of it is genuinely useful."},
      {"kind":"p","text":"A document is a record with a text body and a metadata dictionary; it is the load-bearing type for the whole pipeline. A document loader reads some source, such as PDFs, web pages, databases, or Notion, and produces documents; there are hundreds, and they are thin wrappers whose quality varies enormously. A text splitter breaks long documents into chunks, meaning pieces small enough to embed and to fit several into a prompt, usually with overlap so that a sentence straddling a boundary appears in both neighbors. An embedding model maps text to a vector, meaning a fixed-length list of numbers such that semantically similar texts are near each other. A vector store indexes vectors and answers nearest-neighbor queries, and LangChain wraps dozens of them behind one interface. A retriever is the runnable that takes a query string and returns documents, which may be backed by a vector store, a keyword index, a web search, or a composition of several with re-ranking."},
      {"kind":"p","text":"The problem solved is that every one of those components has many vendors and you want to swap them. The leaks are the substance of RAG engineering. Chunk size and strategy dominate retrieval quality and no default is right; splitting by characters ignores document structure, splitting by headings fails on unstructured text, and the splitter interface cannot tell you which to use. Embedding models are not interchangeable, since vectors from one model are meaningless to another, so changing models means re-indexing everything, and the common interface makes that swap look free when it is not. Metadata filtering, meaning restricting a search to documents matching some attribute, is where vector store wrappers diverge most, because each backend has its own filter syntax and the abstraction either exposes the raw syntax or supports a lowest common denominator. And the retriever interface makes retrieval look like a function call when it is really a ranking problem with precision and recall you must measure; the library gives you no evaluation for free, and a retriever that returns plausible-looking chunks that happen to be wrong is the most common failure in production RAG."},
    ],
  },
  {
    heading: "Callbacks and tracing",
    blocks: [
      {"kind":"p","text":"A callback handler is an object with methods that fire on events such as a chain starting, a model producing a token, a tool returning, or an error being raised. Callbacks are how LangChain implements logging, token counting, streaming to a UI, and tracing. Tracing records every nested run in a tree with inputs, outputs, timings, and token usage, and LangSmith is the company's hosted product for viewing those traces, evaluating outputs against datasets, and managing prompts. Tracing is enabled by environment variables and requires no code changes, which is why it works even on chains you did not write."},
      {"kind":"p","text":"The problem solved is observability in a system where the interesting failures are semantic rather than exceptional: the chain succeeded and the answer was wrong, and you need to see every intermediate prompt to understand why. This is close to indispensable in practice. The leaks are the config propagation issue mentioned earlier, the fact that custom callbacks run in the request path and can slow or break it if they raise, and the vendor coupling: the open-source tracing emits a format designed for LangSmith, and while OpenTelemetry bridges exist, I would check their current state rather than assume parity. A newer streaming API that yields a typed stream of events from anywhere inside a chain is built on the same callback machinery and is the right way to stream intermediate steps to a frontend."},
    ],
  },
  {
    heading: "LangGraph",
    blocks: [
      {"kind":"p","text":"LangGraph is a separate library from the same team, and in the current era it is where the architecture lives; the agent constructors in the main package are built on it. It exists because LCEL is acyclic and agents are loops, and because real applications need to pause for human input and resume later, which a function call cannot do."},
      {"kind":"p","text":"A graph in LangGraph is built from a state schema, nodes, and edges. The state is a typed dictionary describing everything the workflow knows, such as the message list, retrieved documents, and counters. Each key may have a reducer, meaning a function that specifies how a node's returned value for that key is merged into the existing value; the default replaces, and the standard reducer for messages appends while deduplicating by message id. A node is a function that receives the state and returns a partial update. An edge connects nodes, and a conditional edge is a function that inspects the state and chooses which node runs next, which is how you express the agent's decision between calling a tool and finishing. Execution proceeds in super-steps, a term borrowed from the Pregel model of graph computation, where all nodes activated in a step run, their updates are merged via reducers, and the next step begins; this is why two nodes running in parallel can both append to messages without clobbering each other."},
      {"kind":"p","text":"A checkpointer persists the state after every super-step, keyed by a thread id, meaning an identifier for one conversation or workflow instance. That single mechanism provides conversational memory, since invoking the same thread resumes with its history; durability, since a crash mid-workflow can resume from the last checkpoint; and human-in-the-loop, since a node can raise an interrupt that suspends execution, returns control to your application, and resumes when you supply a value, possibly days later. Time travel, meaning rewinding to an earlier checkpoint and forking, falls out for free. A send primitive lets a node fan out to many copies of another node with different inputs, which is how you express map-reduce over a dynamic list, and subgraphs let a node be a graph itself. A command type lets a node return both a state update and a routing decision, which has reduced the need for separate conditional edges; I believe this is now the preferred idiom but would flag it as an area of active change."},
      {"kind":"p","text":"The problem LangGraph solves is control flow and durability for stateful, cyclic, long-running LLM workflows, and the state graph with reducers and checkpointing is the most load-bearing idea in the entire ecosystem. The leaks are worth internalizing. Reducers surprise people: forgetting that a key appends rather than replaces produces silently growing state, and the message reducer's id-based deduplication means that returning an existing message object with modifications updates it in place, which is useful and startling. Everything in state must be serializable for the checkpointer, so putting a live client object in state fails at checkpoint time rather than at assignment. Checkpoints encode the state schema of the code that wrote them, so changing node names or state keys while threads are in flight is a migration problem the library does not solve for you. The super-step model means a node cannot observe a sibling's output within the same step, which is correct but non-obvious. And the graph builder's static typing is advisory; most wiring mistakes are discovered at runtime."},
    ],
  },
  {
    heading: "Packages and ecosystem",
    blocks: [
      {"kind":"p","text":"The code is split into a core package holding the runnable protocol, messages, and base interfaces; a main package holding higher-level constructors; a community package holding the long tail of third-party integrations; and per-provider partner packages, such as one each for OpenAI and Anthropic, that are maintained with the vendors and versioned independently. The intent is that the core moves slowly and integrations can break without breaking you. In practice, version skew between these packages is a recurring source of confusing import errors, and pinning compatible versions together is necessary. LangServe, a layer for exposing a runnable as a REST endpoint, was effectively superseded by a hosted deployment platform for LangGraph applications, and I would not start a new project on it. The TypeScript library tracks the Python one with a lag and some API differences; nothing above should be assumed identical across the two without checking."},
    ],
  },
  {
    heading: "What to keep",
    blocks: [
      {"kind":"p","text":"If you strip LangChain to what would survive a rewrite, you are left with a handful of commitments: that a conversation is a list of role-tagged messages with structured content; that a model exposes invoke, batch, and stream in sync and async forms and that composable things should too; that a tool is a schema plus a description plus an id-correlated result; that a document is text plus metadata; and that an agent is a state graph with reducers, persisted at every step. Everything else, including the named chains, the memory classes, the agent executor, the prompt templates, and the specific one-line constructors, is a recipe layered on top, and recipes are what has churned and will churn again. A newcomer should learn the vocabulary of the recipes because tutorials speak it, but should build on the commitments. A senior engineer should notice that each commitment is also exactly where the library's abstraction leaks, since portability layers cannot erase provider differences, composition layers cannot erase the acyclicity of pipes, and persistence layers cannot erase schema migrations; the library's real value is that it makes those leaks visible in one place rather than scattered across every call site you would otherwise have written yourself."},
    ],
  },
];;
