import type { LessonSection } from "../curriculum";

export const sections: readonly LessonSection[] = [
  {
    heading: null,
    blocks: [
      {"kind":"p","text":"Louis Armstrong: a concepts-and-vocabulary guide, from basics to advanced"},
    ],
  },
  {
    heading: "Start with the sound",
    blocks: [
      {"kind":"p","text":"Imagine a shellac disc from June 28, 1928, turning at seventy-eight revolutions a minute. Before any band enters, a lone trumpet plays about twelve seconds of unaccompanied music: a bugle-like rising figure, a tumbling run that seems to lose its footing on purpose and then catches itself, a climb to the top of the horn, and a slow settle onto a long note. Then a small band eases in with a slow blues. This is the opening of \"West End Blues,\" recorded in Chicago by Louis Armstrong and his Hot Five for the Okeh label, and almost everyone who writes about jazz treats that opening as a hinge in the history of American music. The unaccompanied passage is a cadenza, a term borrowed from classical concertos for a stretch where the orchestra stops and the soloist shows the full range of the instrument and the imagination. Nothing on a dance record was supposed to sound like that in 1928. To understand why it mattered, you need the vocabulary of the music Armstrong grew up inside and then transformed."},
      {"kind":"p","text":"Armstrong was born in New Orleans on August 4, 1901. He himself always gave July 4, 1900, and that date appears in older books; a baptismal record located by the researcher Tad Jones in the 1980s settled the matter. He grew up in a poor Black neighborhood, was sent to the Colored Waif's Home for Boys after firing a pistol into the air on New Year's Eve 1912, and there received his first formal instruction on the cornet from a teacher named Peter Davis. The cornet is a close cousin of the trumpet: same valves, same fingerings, same basic range, but with tubing that is more conical, widening gradually along its length, which produces a rounder, mellower, slightly veiled tone. The trumpet's tubing is more cylindrical, staying the same bore for longer before flaring, which gives a brighter, more penetrating sound that carries over a big band or across a dance hall. New Orleans players of Armstrong's youth were almost all cornetists. Armstrong switched to trumpet gradually around 1926 and 1927, while playing in Erskine Tate's pit orchestra at Chicago's Vendome Theatre, where the brilliance of the trumpet suited the setting. By \"West End Blues\" he was a trumpeter, and his adoption of the instrument helped make it the lead brass voice of jazz for the rest of the century."},
    ],
  },
  {
    heading: "New Orleans music and its grammar",
    blocks: [
      {"kind":"p","text":"The style Armstrong learned is called New Orleans jazz, and sometimes dixieland or hot jazz. The three names are not quite synonyms. New Orleans jazz describes the music as Black and Creole musicians played it in that city in roughly the 1900s through the early 1920s. Dixieland derives from the Original Dixieland Jass Band, a white New Orleans group that in 1917 made what is generally counted as the first jazz record; the word later attached itself to the 1940s revival of the old style and to a somewhat formulaic version of it, and many Black musicians, Armstrong included, disliked the label. Hot jazz was period slang for jazz that was improvised and rhythmically driving, as opposed to the sweeter, more arranged dance music of the day. Hot meant alive."},
      {"kind":"p","text":"A New Orleans band divided into two groups. The front line was the melody instruments, typically three: cornet, clarinet, and trombone. The rhythm section was everyone who kept time and supplied the chords: piano, banjo or guitar, tuba or string bass, and drums. The front line's defining practice was collective improvisation, also called ensemble polyphony. Polyphony is the technical word for several independent melodic lines sounding at once. In a New Orleans ensemble the cornet plays the lead, meaning the recognizable tune, often decorated but kept intact. The clarinet weaves a faster, higher, embroidering line above it, called an obbligato. The trombone plays a slower countermelody underneath, sliding between the important notes of the harmony; this is called tailgate trombone, after the custom of seating the trombonist at the back of an advertising wagon so the slide would not hit anyone. Nobody is reading music, and nobody is exactly soloing. Everyone improvises at once, within roles. The thrill is the controlled traffic of three lines that never collide."},
      {"kind":"p","text":"The raw materials of that music were ragtime and the blues. Ragtime was a composed, published piano music that flourished from the 1890s to the 1910s; Scott Joplin's \"Maple Leaf Rag\" of 1899 is the famous example. Its signature is syncopation: placing accents where the ear does not expect them, between the beats or on the weak beats, against a steady, marching left hand. Rags were built like marches, in several sixteen-bar sections called strains, played in sequences such as AABBACCDD. Many early jazz pieces, including some Hot Five titles, keep that multi-strain architecture, which is why their forms can seem oddly long to someone expecting a simple song."},
      {"kind":"p","text":"The blues contributed something ragtime did not have: a specific harmonic cycle and a specific way of bending pitch. The twelve-bar blues is a chord sequence twelve measures long. In its plain form it spends four bars on the home chord, which musicians label with the Roman numeral I, two bars on the chord built on the fourth step of the scale, the IV, two bars back home, then a bar on the V chord, a bar on the IV, and two bars home again. Over that cycle singers and horn players use blue notes, pitches that sit between the notes of the European scale, most often a lowered or bent third, a lowered seventh, and a flattened fifth. A blue note is less a fixed pitch than a gesture: a tone that slides or sags toward its neighbor. The slow blues on \"West End Blues\" is a twelve-bar blues, and nearly every lament in Armstrong's early catalogue, from \"Gully Low Blues\" to \"Savoy Blues,\" is built on the same twelve bars."},
      {"kind":"p","text":"The last foundational term is swing, and it is the hardest to define. Written music divides a beat into two equal eighth notes. Jazz musicians do not play them equally. The first eighth is held longer, the second shortened and lightly accented, in a ratio that drifts with tempo somewhere between two-to-one and nearly even. These are swung eighth notes, and together with a relaxed forward lean against the beat they produce swing feel, the sensation that the music is propelled rather than merely counted. Nobody swung harder or more freely than Armstrong, and part of his historical importance is that he showed what swing could do once a single player, instead of an ensemble, carried it."},
      {"kind":"p","text":"Tied to swing is a change in meter. Early New Orleans and ragtime-derived music tends to feel in 2/4, two heavy beats per bar, the oompah of tuba on beats one and three and banjo chopping on two and four. This is called two-beat. Across the 1920s and into the 1930s the rhythm section flattened that into 4/4, four even pulses per bar, the four-beat walking bass and strummed guitar of the swing era. The difference matters because four-beat gives a soloist a smooth, continuous carpet rather than a lurching bounce, and lets long phrases flow across bar lines. Armstrong's own phrasing, which already thought in four even beats while his rhythm sections still bounced in two, was one of the forces that pulled the music across that divide."},
    ],
  },
  {
    heading: "Chicago, King Oliver, and the laboratory years",
    blocks: [
      {"kind":"p","text":"Armstrong's teenage mentor was Joe \"King\" Oliver, the most admired cornetist in New Orleans. When Oliver left for Chicago in 1918, Armstrong took his chair in Kid Ory's band and then spent the summers of 1919 through 1921 on Mississippi riverboats in the orchestra of pianist Fate Marable, where he learned to read music fluently. In the summer of 1922 Oliver summoned him to Chicago to play second cornet in King Oliver's Creole Jazz Band at the Lincoln Gardens dance hall. Second cornet is a harmony and support role, and Armstrong's discipline in it was legendary; witnesses recalled the two cornets inventing matching two-bar breaks on the spot, seemingly by telepathy, as you can hear on the band's 1923 recording of \"Snake Rag.\" A break is a brief gap, usually two bars, where the whole band stops and one player fills the silence alone before everyone re-enters. It is the ancestor of the solo."},
      {"kind":"p","text":"The Creole Jazz Band's 1923 recordings for Gennett, Okeh, Columbia, and Paramount are the finest documents of New Orleans ensemble polyphony on disc. \"Chimes Blues\" contains Armstrong's first recorded solo, a modest, correct statement. \"Dipper Mouth Blues\" belongs to Oliver, whose three choruses with a wa-wa mute were memorized note for note by trumpeters across the country; the title is one of Armstrong's nicknames, to which we will return. Lil Hardin, the band's pianist, married Armstrong in February 1924 and pressed him to leave Oliver's shadow. He spent late 1924 and 1925 in New York with Fletcher Henderson's dance orchestra, where his solos reportedly rearranged the section players' sense of rhythm, and he recorded with blues singers including Bessie Smith, whose \"St. Louis Blues\" of January 1925 features his cornet answering her lines."},
      {"kind":"p","text":"In November 1925 he returned to Chicago, and Okeh began recording him as a leader. The Hot Five was a studio group: Armstrong on cornet, Kid Ory on trombone, Johnny Dodds on clarinet, Lil Hardin Armstrong on piano, and Johnny St. Cyr on banjo. No drums, no bass, partly because the early sessions used the acoustic recording horn, which handled loud low-frequency instruments badly. In May 1927 the group expanded for a week of sessions into the Hot Seven, adding Pete Briggs on tuba, Baby Dodds on drums, and John Thomas replacing the absent Ory. The 1928 band, still issued as the Hot Five, was a different unit built around the pianist Earl Hines and the drummer Zutty Singleton. The roughly sixty-five sides from 1925 to 1928 are, by common consent, the most influential body of recordings in jazz."},
      {"kind":"p","text":"\"Potato Head Blues,\" recorded by the Hot Seven on May 10, 1927, is the showpiece, and the first thing a careful listener should know is that despite its title it is not a twelve-bar blues; its main section is a thirty-two-bar song form. Its celebrated final chorus is in stop-time, a device in which the rhythm section plays only on isolated beats, here roughly one chord every two bars, and rests in between, leaving the soloist suspended over near-silence. Stop-time came from tap dancing, where the band stops so the audience can hear the feet. Armstrong's stop-time chorus turns exposure into drama: he leaps into the gaps, holds notes across them, lands phrases a hair behind the chords so that the band seems to be following him, and builds a line that is both unpredictable and inevitable. Writers from Gunther Schuller onward have used it as the textbook example of rhythmic freedom against a fixed grid."},
      {"kind":"p","text":"\"Struttin' with Some Barbecue,\" recorded December 9, 1927, with Ory back on trombone, is credited to Lil Hardin Armstrong, though Louis later claimed it, and the title's barbecue was reportedly New Orleans slang for an attractive woman. It shows the other side of his gift: a bright, strutting, perfectly poised lead over a thirty-two-bar form, with a solo entered through a sprung two-bar break and a final ensemble in which the old collective style is still intact but obviously orbiting one star. Listen to it beside \"Hotter Than That,\" recorded the same week with the guitarist Lonnie Johnson, and you hear the full range of what the band could do."},
      {"kind":"p","text":"Then \"West End Blues,\" composed by King Oliver, who had recorded it himself two weeks earlier. After the cadenza, the record is a sequence of twelve-bar choruses. A chorus, in jazz usage, is one complete pass through the song's form, whether twelve bars of blues or thirty-two bars of a popular tune; a performance is a stack of choruses, and a soloist takes one or several. Armstrong states the melody, trombone takes a chorus, then the clarinet plays low phrases and Armstrong answers each one by wordless singing, then Hines plays a chorus of rippling piano, and in the final chorus Armstrong enters on a high B-flat and holds it for almost four bars before releasing it into a descending flurry. The cadenza at the start is not a break, because nothing has started yet, and it is not stop-time, because no band is punctuating it. It is a declaration that the soloist, not the ensemble, is the subject of the record."},
    ],
  },
  {
    heading: "The voice",
    blocks: [
      {"kind":"p","text":"The wordless singing on \"West End Blues\" is scat: improvised vocal music on nonsense syllables, treating the voice as a horn. The origin story most people know comes from the Hot Five's February 26, 1926, recording of \"Heebie Jeebies,\" a novelty tune by Boyd Atkins. Armstrong sings a chorus of lyrics and then breaks into syllables. The legend says he dropped the lyric sheet and improvised rather than ruin the take. Armstrong told versions of the story himself, and the Okeh producer Richard M. Jones repeated it, but it should be treated with suspicion. Scat singing existed on record before 1926, including Cliff Edwards's eefing and Don Redman's vocal on a 1924 Fletcher Henderson side, and in New Orleans it was a familiar entertainer's trick; Jelly Roll Morton insisted a singer named Joe Sims had done it long before. What is beyond dispute is the effect: the record sold heavily, scat became a vocabulary, and the chorus is rhythmically so sly that the dropped-sheet story, true or not, undersells how deliberate it sounds."},
      {"kind":"p","text":"The deeper point concerns the relationship between Armstrong the singer and Armstrong the trumpeter. His vocal phrasing came from the horn: he approached a melody as a set of structural tones he could delay, anticipate, reharmonize, or discard, singing a simplified or altered line that floated behind the beat. His instrumental phrasing in turn came from singing: the phrases breathe, they have consonants and vowels, they land on words you can almost hear. Listen to his 1929 \"I Can't Give You Anything But Love\" or either take of his 1931 \"Stardust,\" where he sings the Hoagy Carmichael melody almost without its written contours, repeating fragments of text as rhythmic objects, and then plays a trumpet chorus that does the same thing. Bing Crosby and Billie Holiday both acknowledged him as the model for conversational, rhythmically free popular singing. The gravel in his voice, which worsened over the decades, was a texture rather than a limitation; he used it the way he used a brass growl."},
    ],
  },
  {
    heading: "Brass vocabulary",
    blocks: [
      {"kind":"p","text":"Armstrong's horn sound was predominantly open, meaning no mute, which already distinguished him from Oliver, whose fame rested on muted effects. A mute is any object placed in or over the bell of a brass instrument to change its color. The plunger is literally the rubber cup of a toilet plunger, held in the left hand and opened and closed over the bell to produce the wa-wa that Oliver made famous and that Duke Ellington's brass players later elaborated. The cup mute is a cone with an attached cup that softens and darkens the tone. The Harmon mute is a hollow metal mute with a cork seal and an adjustable stem; without the stem it gives the thin, buzzing, intimate sound later associated with Miles Davis. The growl is produced by humming or flutter-tonguing while playing, adding a rasp to the tone, and Armstrong used it sparingly for emphasis. Vibrato is the slight, regular wavering of pitch that warms a sustained note. Armstrong's version is called terminal vibrato: he starts a long note dead straight and lets the vibrato bloom and widen as the note ends, so that the tail of each phrase seems to shimmer. Schuller singled it out as the most imitated single mannerism in jazz. The upper register, the high notes above the staff, was Armstrong's weapon of theater; in the 1930s his big-band records such as \"Swing That Music\" in 1936 end with dozens of high Cs capped by a higher note still, and the toll on his lip, which split badly in 1935, forced him to pace himself later."},
      {"kind":"p","text":"Two further role distinctions matter. Lead playing means carrying the melody with authority so that an ensemble can hang its lines on it, a job of tone, placement, and command rather than invention; soloing means improvising a new line over the chords while the others accompany. Armstrong was supreme at both, and his lead on the final choruses of the Hot Five records is as individual as his solos. Call-and-response is the alternation of a phrase and an answer, inherited from Black church and work song; the clarinet-and-scat exchange on \"West End Blues\" is call-and-response, and so is the answering of a soloist by a horn section in a big band. A riff is a short, repeated phrase, usually two or four bars, used as a background or a melody; the big bands Armstrong fronted from 1929 onward, including Luis Russell's orchestra, which became his regular band in the later 1930s, set riffs behind him as cushions and springboards, and his own improvised lines often spin a riff-like fragment through a chorus, raising or shifting it to track the chords."},
      {"kind":"p","text":"Finally, the forms. Beyond the twelve-bar blues, the commonest Armstrong vehicle is the thirty-two-bar popular song, often in AABA shape: an eight-bar phrase, repeated, then a contrasting eight-bar section called the bridge or release, then the first phrase once more. The last two bars of any chorus are the turnaround, a short chord progression that steers the harmony back to the beginning so the next chorus can start without a bump; soloists use it as a runway, and many of Armstrong's most striking entrances are launched out of a turnaround or a break placed over one."},
    ],
  },
  {
    heading: "The solo as the subject",
    blocks: [
      {"kind":"p","text":"Here is the historical claim that sits under everything else. Before Armstrong, jazz was an ensemble art, and its records are glorious crowds. After the Hot Five and Hot Seven, jazz was understood as a soloist's art, and every subsequent development, from the swing-era star sideman to bebop's small-group marathons, to the free improviser alone on stage, rests on the assumption that one improvising musician can be the whole point of a performance. Armstrong did not simply play longer breaks. He demonstrated, record after record, that an improvised chorus could have the shape of a composition: an opening idea, development, a point of maximum tension, and a resolution. Writers speak of his solos as composed narratives, and the word composed is not casual. He often worked out and refined his solos over successive performances, and his best recorded choruses reward the kind of analysis normally given to notated music. The stop-time chorus of \"Potato Head Blues\" builds in waves toward a climactic high phrase; the last chorus of \"West End Blues\" opens with a long held note, the emotional summit, and then spends the rest of its twelve bars descending from it, as if the whole record had been a climb to that B-flat and a graceful fall away."},
      {"kind":"p","text":"The advanced ear should listen to the length and the breath of his phrases. New Orleans players phrased in two- and four-bar units aligned with the song. Armstrong phrased in sentences that begin late, run across the bar line and across the four-bar seam, and end early, leaving pockets of silence that are as composed as the notes. He thinks over the chord changes rather than inside them, choosing notes from the upper extensions of a chord, the ninths and sixths, and approaching target tones by chromatic half steps, the kind of slippery, decorated approach that would later be a bebop commonplace. He plays double-time passages, phrases at twice the prevailing rhythmic density, as early as 1927, and then relaxes back into long tones, so that a single chorus contains several speeds. Everything is vocalized: the attack, the swell, the terminal vibrato, the slight scoop into a note, all borrowed from the singing voice and from the blues. The result is music that is melodically simple enough to hum and rhythmically so sophisticated that no one has fully imitated it."},
    ],
  },
  {
    heading: "Inheritance and the classroom",
    blocks: [
      {"kind":"p","text":"What did later players take from him? The swing-era trumpeters, from Roy Eldridge to Harry James, took the upper register, the drama, and the terminal vibrato. The bebop generation of the 1940s, who publicly rebelled against his showmanship and whom he in turn mocked, nonetheless inherited his central assumptions: that the soloist is the subject, that a line should move through chord extensions and chromatic approach notes, that rhythm can float free of the written beat, and that a solo should be a shaped statement rather than a decoration. Dizzy Gillespie and Miles Davis both said in later years, in various formulations, that everything playable on a jazz trumpet traces back to him; the paraphrase is safer than any single quotation, but the sentiment is well documented in both men's interviews and memoirs. Even the saxophone lineage runs through him: Coleman Hawkins and Lester Young absorbed his phrasing in the Henderson years and the Kansas City jukeboxes."},
      {"kind":"p","text":"That transmission happened through records, which is the last large idea in this guide. Jazz is an aural tradition, but from 1923 onward it was learned mostly from discs. Bix Beiderbecke and the young white Chicagoans wore out Oliver's and Armstrong's sides; Black and white trumpeters across the country learned the \"Dipper Mouth Blues\" and \"West End Blues\" solos by ear, slowing the turntable to catch every note. In 1927 the Melrose music publishers issued two booklets, \"50 Hot Choruses for Cornet\" and \"125 Jazz Breaks for Cornet,\" transcribed from private cylinders Armstrong made for the purpose, the recordings themselves now lost. It is the first time an improviser's solos were sold as texts to be studied, and it marks the moment when the phonograph became the conservatory of jazz. Every later practice of transcribing solos, from Charlie Parker's followers to today's university programs, descends from the way young musicians learned Armstrong."},
    ],
  },
  {
    heading: "The man and his names",
    blocks: [
      {"kind":"p","text":"The names people called him encode his biography. In New Orleans he was Dipper or Dippermouth, from the wide mouth likened to a water dipper, and also Gatemouth and Satchelmouth, all on the same joke. In Oliver's band he was Little Louis. Satchmo, the name that became a brand, is usually traced to July 1932, when Percy Brooks, editor of the British magazine Melody Maker, is said to have greeted him in London with \"Hello, Satchmo,\" garbling Satchelmouth. Armstrong repeated this story, but it is not independently verifiable, and some researchers think the contraction was already circulating; it should be told as legend. Pops was what he called everyone whose name he had forgotten, and the musicians returned it to him, so that by the 1950s Pops meant Armstrong."},
      {"kind":"p","text":"The career arc, in brief, runs from the Waif's Home and the riverboats to Chicago with Oliver, New York with Henderson, the Hot Five years, and then stardom as a singer and big-band front man after his 1929 Broadway success with \"Ain't Misbehavin'.\" He toured Europe in 1932 and from 1933 to 1935, placed his business in the hands of the manager Joe Glaser in 1935, and appeared in films. In 1947, with big bands collapsing financially, he formed the All Stars, a six- or seven-piece group modeled loosely on the old New Orleans instrumentation, with sidemen including Jack Teagarden, Earl Hines, and Barney Bigard, and he led versions of it for the rest of his life, touring the world so relentlessly that the State Department used him as an ambassador, a role he jeopardized in 1957 by denouncing President Eisenhower's handling of school desegregation in Little Rock. On December 3, 1963, he recorded \"Hello, Dolly!,\" which in May 1964 reached number one on the Billboard chart, displacing the Beatles and making him, at sixty-two, the oldest artist to have done so. \"What a Wonderful World\" followed in 1967. He died in Queens, New York, on July 6, 1971."},
      {"kind":"p","text":"None of that late fame is the reason he matters, but it is not irrelevant either. The entertainer with the handkerchief and the grin and the trumpeter of \"West End Blues\" were the same person, and part of the advanced understanding of Armstrong is refusing to separate them. The vocabulary in this guide, from blue notes and breaks to chorus structure and terminal vibrato, describes a musician who took the collective grammar of one city and turned it into a language a single voice could speak, and who then spoke it, on record, so clearly that the whole art form learned to talk."},
    ],
  },
];;
