import type { LessonSection } from "../curriculum";

export const sections: readonly LessonSection[] = [
  {
    heading: "0. The first thing to unlearn",
    blocks: [
      {"kind":"p","text":"Most introductions to Hayao Miyazaki arrive pre-softened: gentle nature spirits, plucky girls, food you want to eat, a vague ecological sweetness. That version is not wrong so much as it is the marketing residue of a body of work that is, on inspection, pessimistic, formally severe, politically uncomfortable, and built on contradictions its maker refuses to resolve. The man who drew Totoro also spent twelve years drawing a manga that ends with its heroine choosing a poisoned world over a purified one, and made his last-but-one feature about a man who builds beautiful machines that kill people, knowing they will."},
      {"kind":"p","text":"So the frame for this lesson: **Miyazaki is a formalist whose subject is irresolvable contradiction.** Everything else — the animism, the flight, the bread and ham — follows from that."},
    ],
  },
  {
    heading: "1. Biography as engine, not trivia",
    blocks: [
      {"kind":"p","text":"Born 1941 in Tokyo. His family's firm, Miyazaki Airplane, manufactured rudders for the Mitsubishi A6M Zero. The Miyazakis were comparatively comfortable *because* of the war, and fled the firebombing of Utsunomiya by truck — a truck on which, by his own telling, his family refused space to a neighbour woman carrying a child. He has narrated that memory his whole life as the founding shame. **Complicity with beauty-producing violence is not a theme he chose; it is an inheritance.**"},
      {"kind":"p","text":"His mother, Yoshiko, spent roughly nine years ill with spinal tuberculosis, much of it bedridden at home. Hence the absent-or-fragile mother who recurs from *Totoro* to *Ponyo*: not a lazy trope but an autobiographical wound processed repeatedly and, notably, always with the child instructed to carry on."},
      {"kind":"p","text":"He read political economy at Gakushuin, joined Toei Dōga in 1963, and became chief secretary of its labour union — a Marxist, a serious one, who later described his gradual disillusionment as a long grief rather than a conversion. Two films redirected him: Lev Atamanov's Soviet *The Snow Queen* (1957), which he says persuaded him animation could carry genuine feeling, and Paul Grimault's French *La Bergère et le Ramoneur* / *Le Roi et l'Oiseau*, whose vertical architecture and anti-authoritarian politics are visible in *Cagliostro*, *Laputa* and the tower of *The Boy and the Heron*. Note what is *not* in that list: Disney. Miyazaki's lineage is European and Soviet, routed through Toei's brief, doomed ambition to make Japanese feature animation an art form."},
      {"kind":"p","text":"The other decisive fact is **Isao Takahata** — colleague, mentor, rival, and permanent irritant, from *Horus: Prince of the Sun* (1968) to Takahata's death in 2018. Takahata couldn't draw, worked from research and documentary logic, and was ruthless about sentiment. Miyazaki draws compulsively and thinks in movement. Studio Ghibli is best understood as the field of force between an empiricist and a romantic. When Miyazaki says he is not making \"anime\" but ***manga eiga*** (漫画映画, \"cartoon film\" — the older, cinematic, child-addressed tradition), he is placing himself in Takahata's argument and against the television-derived, otaku-facing industry that grew up around him."},
    ],
  },
  {
    heading: "2. The conceptual vocabulary",
    blocks: [
      {"kind":"p","text":"**Ma (間).** Literally interval, gap, negative space. Miyazaki explained it to Roger Ebert by clapping once and letting the silence run: the film's emptiness is not dead time but the thing that makes the rest legible. Practically, this means held shots where nothing \"happens\" — Satsuki and Mei waiting at the bus stop, Chihiro on the train, Ashitaka simply riding. A caution for the PhD register: Miyazaki's *ma* is an idiosyncratic, artist's appropriation of a term with a long life in Noh, architecture and music. Treat it as **a rhythmic doctrine of emotional pacing**, not as a certified traditional aesthetic imported wholesale."},
      {"kind":"p","text":"**Animism, but de-institutionalised.** The kami of the films are not Shinto orthodoxy; they are a syncretic, deliberately unsystematised sense that the world is *inhabited*. The camphor tree in *Totoro* with its shimenawa, the shishigami of *Mononoke*, the eight-million minor gods queuing at the bathhouse. Two scholarly sources matter here: **Nakao Sasuke's** theory of *shōyōjurin* (laurel/evergreen broadleaf forest) culture, which posits a pre-rice, forest-dwelling Japanese substratum, and the medieval historian **Amino Yoshihiko**, whose work on *muen, kugai, raku* — zones \"unattached\" to feudal authority, populated by ironworkers, outcasts, lepers, sex workers and wandering artisans — is the direct armature of Irontown in *Princess Mononoke*. This is why Lady Eboshi runs a factory *and* a leper hospice *and* a refuge for trafficked women while she guns down a god. Miyazaki is dramatising a real historiographic argument: that the destruction of the forest and the emancipation of the marginalised were **the same event**."},
      {"kind":"p","text":"**Satoyama (里山).** The managed borderland between village and wilderness — coppiced woods, paddies, shrines, shared water. Not wilderness, not city: a human-nature composite. *Totoro*'s landscape is satoyama, and Miyazaki has spent real money conserving the Sayama Hills that inspired it. His ecology is not preservationist purity; it is about **a workable, mutually-obligated cohabitation that Japan's post-war growth destroyed.**"},
      {"kind":"p","text":"**Kamikakushi (神隠し).** \"Spirited away\" — the folk category for a child vanished by gods. *Sen to Chihiro no Kamikakushi* is literally titled with it. Thresholds are everywhere in Miyazaki: tunnels, gates, stairs, the surface of water. Crossing is never a special effect; it is always a *walk*."},
      {"kind":"p","text":"**Mono no aware.** The pathos of transience. Useful, but don't over-apply it — Miyazaki's endings are usually not elegiac so much as *unresolved*: the world stays broken, the character has changed their stance toward it."},
    ],
  },
  {
    heading: "3. How the films are actually made (the part professionals need)",
    blocks: [
      {"kind":"p","text":"**There is no finished screenplay.** Miyazaki begins with **image boards** — loose watercolours of a place, a machine, a face — and lets story emerge from image. He then draws the ***e-konte*** (絵コンテ, storyboard) *while the film is in production*, so that animators are working on act one before act three exists. On *Mononoke* and *Spirited Away* the boards were still arriving as the release date closed. He has said plainly that he doesn't know the ending when he starts."},
      {"kind":"p","text":"Understand the trade honestly: this method buys **an organic, unpredictable causality** that scripted animation rarely achieves — scenes that go where a script wouldn't allow — and it costs **crunch, budget risk, and total dependence on an institution willing to absorb both.** That institution was Toshio Suzuki, Tokuma Shoten's money, and salaried staff. If you steal the method without the shock absorber, you will hurt people."},
      {"kind":"p","text":"**The layout is the unit of authorship.** This is the genuinely transferable innovation, and it comes from Takahata and Miyazaki's work on *Heidi, Girl of the Alps* (1974). A **layout** (レイアウト) is a single drawing that fixes staging, perspective, character placement, background composition, camera move and timing simultaneously — the shot's constitution. Miyazaki personally draws or redraws essentially all of them, tens of thousands per film. This is how one hand governs a hundred-person production without micromanaging every in-between. If you want to know where \"Miyazaki style\" lives, it is not in character design; it is in the layout."},
      {"kind":"p","text":"Alongside this sits **location hunting** — the *Heidi* team went to Switzerland; the *Laputa* team went to Welsh mining towns during the 1984 miners' strike, which Miyazaki cites as the emotional source of that film's solidarity. Fantasy is made credible by observed specificity."},
    ],
  },
  {
    heading: "4. The image-technics",
    blocks: [
      {"kind":"p","text":"**Full versus limited animation.** Japanese TV animation standardised on \"threes\" — eight drawings per second. Ghibli works largely on twos, dropping to ones for fast action, with drawing counts per feature in the tens of thousands above industry norms. But Miyazaki's spend is *selective*: he lavishes frames on weight, recovery, breath and incidental gesture — a character shifting balance, scratching a foot, gripping a handle — rather than on spectacle. **The credibility of the fantastic is purchased with the accuracy of the mundane.**"},
      {"kind":"p","text":"**Animetism.** Thomas Lamarre's concept (from *The Anime Machine*) is the single most useful theoretical tool here. Cartesian \"cinematism\" moves *into* depth — the ballistic, gun-barrel, first-person penetration of space typical of Hollywood action. **Animetism** moves *across* layered planes, sliding laterally, the legacy of the multiplane camera where the image is a stack of sheets in relative motion. Miyazaki's flight is almost purely animetic: Nausicaä on the mehve, Kiki on the broom, Sheeta falling — gliding across strata of cloud and landscape rather than drilling through them. This is why his action feels open and buoyant rather than aggressive, and it is a technical fact about the apparatus before it is an aesthetic preference."},
      {"kind":"p","text":"**Sakuga and the named hands.** For the geek register: Ghibli authorship is distributed. **Yoshinori Kanada**, whose kinetic, rubber-physics effects style shaped a generation, animated for *Nausicaä* and beyond; a young **Hideaki Anno** animated the God Warrior's disintegrating assault. **Kazuo Oga**'s background paintings — the saturated greens of *Totoro* — created what people actually mean when they say a scene \"looks Ghibli.\" **Michiyo Yasuda** ran colour design for decades; **Yoshifumi Kondō**, the designated heir, directed *Whisper of the Heart* and died at 47 in 1998, a loss Miyazaki has connected to the studio's working conditions and to his own subsequent behaviour."},
      {"kind":"p","text":"**Music and sound.** **Joe Hisaishi** has scored every Miyazaki feature since *Nausicaä*, typically beginning with an **image album** composed from Miyazaki's boards before the film exists — music as pre-production, not post. His idiom is minimalist cells inside late-Romantic orchestration, and crucially he is allowed to *stop*: the scores respect *ma*. Sound design is equally deliberate. *The Wind Rises* renders aircraft engines, wind and the Great Kantō Earthquake with human voices — an audacious estrangement device that makes a war machine sound like a man's breath."},
      {"kind":"p","text":"**Digital.** Ghibli adopted it late and grudgingly; roughly a tenth of *Mononoke* involved digital ink-and-paint and CG compositing. The studio's experiment with full CG (*Earwig and the Witch*, directed by Gorō Miyazaki) is widely judged a failure, and *The Boy and the Heron* returned to paper across a seven-year production. The stubbornness is ideological: for Miyazaki, the drawn line carries the labour and the hand, and that is not decoration."},
    ],
  },
  {
    heading: "5. Recurring structures",
    blocks: [
      {"kind":"p","text":"**Flight as cursed grace.** Aviation is Miyazaki's erotics and his guilt. He loves engines, rivets, cowlings, ornithopters — and he knows exactly what they were for. His own formulation: he loves weapons and hates war. *Porco Rosso* and *The Wind Rises* are the two films where this is the subject rather than the pleasure."},
      {"kind":"p","text":"**Wind.** Grass, hair, laundry, clouds. Wind is Miyazaki's cheapest and most reliable way of asserting that the drawn world is a *physical* one; it is also, frequently, the signal that a scene has turned."},
      {"kind":"p","text":"**Work and food.** Nobody in these films is idle. Kiki delivers, Sophie cleans, Chihiro scrubs. Labour is animated with procedural respect, and eating is staged as the primary sign of aliveness and hospitality — the ham-and-egg breakfast in *Howl's*, the bread in *Laputa*, Chihiro forcing down an onigiri while she weeps. **Bodies that eat and work are bodies you believe in.**"},
      {"kind":"p","text":"**The refused villain.** From *Mononoke* onward the antagonist structure collapses deliberately. Eboshi is admirable; Yubaba is a businesswoman; the conflicts are between *incompatible goods*. Miyazaki has said he wanted a film whose conflict could not be resolved, only survived. For writers, this is the hardest and most valuable lesson in his work."},
      {"kind":"p","text":"**The girl who is not a love interest.** The protagonist is usually a girl between ten and fifteen, and the plot is usually her *jiritsu* — independence, self-establishment — rather than romance or rescue. Miyazaki's stated rationale: contemporary girls don't face survival, they face self-realisation, which is harder to dramatise and more worth dramatising."},
      {"kind":"p","text":"**Catastrophe as ordinary weather.** Floods, collapses, apocalypses. Note the unnerving tonal detail: in *Ponyo*, the tsunami is *joyful*. Post-2011, this is very hard to watch, and Miyazaki knew it."},
    ],
  },
  {
    heading: "6. The canon, periodised",
    blocks: [
      {"kind":"p","text":"**Apprenticeship and the adventure romances.** *Horus* (1968, as animator) established the ambivalent heroine. *Future Boy Conan* (1978) is the TV laboratory where the whole toolkit is assembled. *Lupin III: The Castle of Cagliostro* (1979) is the technical masterclass and still the best entry point for action fans. *Nausicaä of the Valley of the Wind* (1984) funded the studio's founding in 1985 — but the film is only the first quarter of **the manga** (1982–1994), which is the indispensable text: longer, darker, and ending with Nausicaä destroying a stored, purified humanity in favour of the contaminated, dying one that actually exists. Read it or you will misunderstand everything after. *Castle in the Sky* (1986) is the last unambiguously utopian work."},
      {"kind":"p","text":"**The interior turn.** *My Neighbour Totoro* (1988), released on a double bill with Takahata's *Grave of the Fireflies* — an almost insane exhibition decision that tells you something about the studio's seriousness. *Kiki's Delivery Service* (1989), the first real hit, and a precise allegory of creative block and burnout. *Porco Rosso* (1992), Miyazaki's self-portrait as a middle-aged pig who would rather be a pig than a fascist: the first film where his disgust with himself becomes material."},
      {"kind":"p","text":"**The mature irresolvable.** *Princess Mononoke* (1997) — Amino and Nakao made cinematic, the highest-grossing Japanese film until *Titanic*, and a retirement announcement he broke. *Spirited Away* (2001) — the bathhouse as Japan's service and *mizu-shōbai* economy, name-theft as labour contract, and the only hand-drawn film to win the Academy Award for Animated Feature."},
      {"kind":"p","text":"**Late style.** *Howl's Moving Castle* (2004), made in anger at the Iraq war, where the plot's incoherence is arguably the point: war and ageing are both things that happen to you. *Ponyo* (2008), drawn almost entirely by hand including the sea, Wagner under a pre-Cambrian tide, deliberately regressive draughtsmanship. *The Wind Rises* (2013), the ethical knot pulled tight — Horikoshi Jirō, the Zero, Hori Tatsuo, Thomas Mann, and Valéry's *\"le vent se lève, il faut tenter de vivre.\"* *The Boy and the Heron* (2023), titled in Japanese after Yoshino Genzaburō's 1937 *How Do You Live?*, an autofictional succession drama in which an old man begs a boy to inherit a tower of stacked blocks and the boy declines."},
    ],
  },
  {
    heading: "7. The critiques (you are not required to love him)",
    blocks: [
      {"kind":"p","text":"**Nostalgia and the nation.** *Totoro*'s 1950s countryside is a constructed *furusato*, a homeland that never quite existed, and it has been absorbed into a conservative Japanese self-image Miyazaki himself detests. The tension between his explicit anti-nationalism and his imagery's nostalgic utility is real and unresolved."},
      {"kind":"p","text":"***The Wind Rises* controversy.** He was attacked from the Japanese right for calling the war a mistake and for publicly demanding Japan apologise for its colonial conduct, and criticised from Korea, China and elsewhere for aestheticising a fighter that strafed Asia. Both critiques land. The film's defence is that it stages the complicity rather than excusing it — but a defence is not an acquittal, and teaching the film well means holding that open."},
      {"kind":"p","text":"**Gender.** Enormous agency granted to girls; also an enormous burden placed on girls to redeem adult worlds they didn't break. And the recurring adolescent-girl protagonist sits, however chastely, inside an industry economy Miyazaki loudly condemns."},
      {"kind":"p","text":"**Labour.** The auteur model rests on hundreds of hands, punishing schedules, and an industry whose broader pay conditions are indefensible. Miyazaki is candid in the documentaries (*The Kingdom of Dreams and Madness*, *10 Years with Hayao Miyazaki*, *Never-Ending Man*) about having been an absent father and a difficult man. Ghibli itself restructured its production arm in 2014 and was acquired by Nippon TV in 2023. **The films are not evidence that the system that produced them is humane.**"},
    ],
  },
  {
    heading: "8. If you want to practise, not just watch",
    blocks: [
      {"kind":"p","text":"Do these in order. Watch *Totoro* once normally, then again with a stopwatch, timing every shot in which no narrative event occurs; you will learn *ma* faster than from any essay. Take a three-minute sequence from *Kiki* and draw its layouts as thumbnails — staging, horizon line, camera — and you will feel where the authorship actually sits. Write a two-hander scene in which both characters are right and neither can concede, and refuse yourself a villain. Then animate someone picking up a heavy object badly. That last exercise is the whole aesthetic in miniature."},
      {"kind":"p","text":"**Read next:** Miyazaki's own *Starting Point 1979–1996* and *Turning Point 1997–2008* (essential, unguarded, contradictory); the *Nausicaä* manga in full; Susan Napier, *Miyazakiworld*; Thomas Lamarre, *The Anime Machine* for animetism; Rayna Denison's edited volume on *Princess Mononoke*; Jonathan Clements, *Anime: A History*, for the industrial context that keeps you from mistaking one studio for a nation."},
      {"kind":"p","text":"**The thesis to carry away:** Miyazaki's films are beautiful not in spite of the fact that he does not believe things will be all right, but because of it. He makes work for children on the explicit premise that he owes them a reason to be glad they were born — and he has never once pretended the world deserves that gladness. That gap, held open for sixty years, is the art."},
    ],
  },
];;
