import type { LessonSection } from "../curriculum";

export const sections: readonly LessonSection[] = [
  {
    heading: "I. What Old English Is (and Isn't)",
    blocks: [
      {"kind":"p","text":"Old English—also called Anglo-Saxon—is the earliest recorded stage of the English language, spoken and written in England roughly from 450 to 1150 CE. The first thing every beginner must internalize is that Old English is not \"old-fashioned English.\" Shakespeare is not Old English; Chaucer is not Old English. Those are Early Modern and Middle English respectively. Old English is a fully inflected Germanic language, closer in grammatical texture to modern German or Icelandic than to the English you speak. A sentence like *Se cyning geaf þām eorle gold* (\"The king gave the earl gold\") is decipherable with effort, but *Hwæt sceal ic singan?* (\"What shall I sing?\") requires actual study. You are learning a foreign language that happens to be the ancestor of your own."},
      {"kind":"p","text":"The language arrived with the migration of Angles, Saxons, Jutes, and Frisians from the North Sea coastal regions of what is now Germany, Denmark, and the Netherlands, beginning traditionally in 449 CE (the date Bede gives, though archaeology suggests a messier, longer process). It belongs to the West Germanic branch of the Germanic family, itself a branch of Indo-European. Its closest relatives are Old Frisian (its nearest sibling, together forming the \"Anglo-Frisian\" or Ingvaeonic group), Old Saxon, and Old High German."},
    ],
  },
  {
    heading: "II. The Alphabet and Sounds: Your First Obstacles",
    blocks: [
      {"kind":"p","text":"Old English was written in a modified Latin alphabet supplemented by characters the Roman alphabet lacked. You must learn four special letters immediately:"},
      {"kind":"p","text":"**Þ, þ (thorn)** — borrowed from the runic alphabet, representing the *th* sounds in both \"thin\" and \"this.\""},
      {"kind":"p","text":"**Ð, ð (eth)** — a crossed *d*, interchangeable with thorn; scribes used both indiscriminately for the same sounds."},
      {"kind":"p","text":"**Æ, æ (ash / æsc)** — a distinct vowel, the sound in Modern English \"cat.\" Crucially, *æ* and *a* were different phonemes: *mann* (man) versus *mæg* (kinsman/may)."},
      {"kind":"p","text":"**Ƿ, ƿ (wynn)** — a runic letter for /w/, which modern editions almost always replace with *w* to spare your sanity, since it looks treacherously like *p*."},
      {"kind":"p","text":"You will also encounter **ȝ (yogh)** in some editions, though most print *g*. This letter conceals a critical complexity: Old English *g* had multiple pronunciations—a hard /g/ before back vowels (*gōd*, \"good\"), a /j/ sound before front vowels (*geong* = \"young,\" pronounced roughly \"yong\" with initial y), and a voiced velar fricative between back vowels. Similarly, *c* was /k/ in some environments (*cyning*, \"king\") but /tʃ/ (\"ch\") in others (*ċild*, \"child\"). Modern student editions often mark the palatal pronunciations with dots (*ċ*, *ġ*)—a scholarly convenience absent from the manuscripts. The digraph *sc* was almost always /ʃ/ (\"sh\"): *scip* = \"ship,\" *fisc* = \"fish.\""},
      {"kind":"p","text":"Vowel **length** was phonemic—it distinguished words. *God* (God) versus *gōd* (good); *ac* (but) versus *āc* (oak). Manuscripts did not mark length; editors add macrons. Every vowel and consonant was pronounced: *cniht* (\"boy,\" ancestor of \"knight\") sounded its *c*, and *hring* (\"ring\") sounded its *h*. Double consonants were genuinely long (geminate), as in modern Italian."},
    ],
  },
  {
    heading: "III. Historical Phonology: How the Sounds Got That Way",
    blocks: [
      {"kind":"p","text":"For advanced understanding, several sound changes are foundational vocabulary in the field:"},
      {"kind":"p","text":"**Grimm's Law** (the First Germanic Consonant Shift) transformed Proto-Indo-European stops into the Germanic system: PIE *p, t, k* became *f, þ, h* (hence Latin *pater* : OE *fæder*; Latin *trēs* : OE *þrēo*; Latin *cornū* : OE *horn*). **Verner's Law** explains apparent exceptions: when the PIE accent didn't immediately precede, the resulting fricatives voiced—which is why Old English has alternations like *wesan* / *wǣron* (s/r alternation, called **rhotacism** in its later stage) and *cwæþ* / *cwǣdon*."},
      {"kind":"p","text":"**I-mutation (i-umlaut)** is the single most important prehistoric Old English sound change for understanding the lexicon. An *i* or *j* in a following syllable fronted or raised the preceding vowel, then often disappeared, leaving its fingerprint. This explains *mann* → *menn* (men), *fōt* → *fēt* (feet), *mūs* → *mȳs* (mice), *full* → *fyllan* (to fill), *dōm* → *dēman* (to deem/judge), *gold* → *gyldan* (to gild). Modern English irregular plurals and pairs like *food/feed*, *blood/bleed*, *strong/strength* are fossils of i-mutation."},
      {"kind":"p","text":"**Breaking (fracture)** diphthongized front vowels before certain consonant clusters (*h*, *r* + consonant, *l* + consonant): hence *heard* (hard), *eald* (old), *seah* (saw). **Palatalization and assibilation** produced the *c*/*ch* and *g*/*y* splits described above. **West Germanic gemination** doubled consonants before *j* (explaining *settan* \"to set\" from **satjan*). Understanding these processes converts Old English from a list of arbitrary forms into a predictable system—this is where philology becomes genuinely elegant."},
    ],
  },
  {
    heading: "IV. Grammar: The Inflectional Machine",
    blocks: [
      {"kind":"p","text":"**Nouns, Case, and Gender**"},
      {"kind":"p","text":"Old English nouns carry **grammatical gender** (masculine, feminine, neuter—assigned arbitrarily: *wīf*, \"woman,\" is neuter; *wīfmann*, also \"woman,\" is masculine) and inflect for four **cases** across singular and plural:"},
      {"kind":"p","text":"The **nominative** marks subjects; the **accusative** marks direct objects; the **genitive** marks possession and partitive relationships (\"of the men\"); the **dative** marks indirect objects and objects of most prepositions, and absorbs the old **instrumental** case (\"by means of\"), which survives vestigially in a few pronoun and adjective forms (*þȳ*, *þon*—fossilized in Modern English \"the more the merrier\")."},
      {"kind":"p","text":"Nouns fall into declension classes inherited from Germanic stem-types. The workhorses: the **strong masculine a-stems** (*stān*, *stānes*, *stāne*; plural *stānas*—the ancestor of our universal -s plural), **strong neuter a-stems** (*scip*, plural *scipu*; but long-stemmed *word* has plural *word*, unchanged—hence \"deer\" and \"sheep\" today), **strong feminine ō-stems** (*giefu*, \"gift\"), and the **weak n-stems** of all genders (*nama*, plural *naman*—the ancestor of \"oxen\"). The **athematic (root) nouns** show i-mutated plurals: *fōt/fēt*, *mann/menn*, *bōc/bēc* (\"book/books\"—we regularized that one). Minor classes (r-stems like *fæder*, nd-stems like *frēond/frīend*) fill out the system. The scholarly vocabulary here—**stem class, thematic vowel, paradigm, syncretism** (when distinct case forms collapse together)—is essential for reading grammars."},
      {"kind":"p","text":"**The Two-Fold Adjective**"},
      {"kind":"p","text":"Old English adjectives have two complete declensions, and the choice is syntactic, not lexical—one of the language's most Germanic features. The **strong (indefinite) declension** appears when the adjective stands alone with its noun: *gōd cyning*, \"a good king.\" The **weak (definite) declension** appears after demonstratives and possessives: *se gōda cyning*, \"the good king.\" German still does exactly this. Modern English lost it entirely."},
      {"kind":"p","text":"**Pronouns and Demonstratives**"},
      {"kind":"p","text":"The demonstrative *se, sēo, þæt* functioned as both \"the\" and \"that\" and inflected fully for case, gender, and number—it is the load-bearing wall of Old English syntax, since it signals grammatical relations that word order no longer must. There was no true indefinite article; *ān* (\"one\") and *sum* (\"a certain\") did related work. The personal pronouns preserve a **dual number**—forms meaning precisely \"we two\" (*wit*) and \"you two\" (*git*)—a poignant archaism that poets exploited for intimacy: *wit* in \"The Wanderer\" and \"Wulf and Eadwacer\" carries emotional weight no plural can."},
      {"kind":"p","text":"**Verbs: Strong, Weak, Preterite-Present, Anomalous**"},
      {"kind":"p","text":"The verbal system rests on a fundamental Germanic division. **Strong verbs** form their past tense by **ablaut** (systematic vowel gradation inherited from Indo-European), sorted into seven classes, each with four **principal parts** (infinitive, past singular, past plural, past participle):"},
      {"kind":"list","items":["Class I: *rīdan, rād, ridon, riden* (ride/rode/ridden)","Class II: *crēopan, crēap, crupon, cropen* (creep)","Class III: *singan, sang, sungon, sungen* (sing/sang/sung)","Class IV: *beran, bær, bǣron, boren* (bear)","Class V: *sprecan, spræc, sprǣcon, sprecen* (speak)","Class VI: *faran, fōr, fōron, faren* (fare)","Class VII: originally reduplicating verbs, now with *ē* or *ēo* pasts: *hātan, hēt* (\"to call, command\")."]},
      {"kind":"p","text":"Note the crucial detail invisible in Modern English: the past **singular** and past **plural** often had different vowels (*sang* vs. *sungon*). Modern English collapsed this, sometimes choosing the singular vowel, sometimes the plural."},
      {"kind":"p","text":"**Weak verbs** innovate the **dental suffix** past tense—the *-ed* that would conquer the language: *lufian, lufode* (love, loved); *fremman, fremede* (perform); *dēman, dēmde* (judge). They divide into Class 1 (often with i-mutation and sometimes irregular pasts: *sēċan/sōhte*, \"seek/sought\"—explaining modern *seek/sought*, *buy/bought*, *think/thought*), Class 2 (the productive *-ian* class), and the small Class 3 (*habban*, *libban*, *secgan*, *hycgan*—have, live, say, think)."},
      {"kind":"p","text":"The **preterite-present verbs** are a strange and important class: old strong pasts reinterpreted as presents, which then built new weak pasts. These became the Modern English **modals**: *cunnan* (can), *sculan* (shall), *magan* (may), *mōtan* (must), *witan* (to know—surviving in \"to wit\" and \"unwitting\"), *āgan* (to own—whence \"ought\"). Their oddity (no *-s* in \"she can\") is a 1,500-year-old fossil."},
      {"kind":"p","text":"Finally, four **anomalous verbs**: *bēon/wesan* (to be—actually a suppletive merger of multiple roots, with a fascinating semantic distinction where *bēon* forms often expressed habitual or future states), *dōn* (do), *gān* (go), *willan* (will)."},
      {"kind":"p","text":"The verb also had **two tenses only**—present and preterite. Future was expressed by the present tense plus context or modals; perfect and pluperfect constructions with *habban* and *bēon* were emerging but not yet grammaticalized. There was a fully functioning **subjunctive mood** used for hypothesis, indirect speech, wishes, and concession—one of the trickiest features for translators, since Modern English has almost lost it."},
    ],
  },
  {
    heading: "V. Syntax: Freer, but Not Free",
    blocks: [
      {"kind":"p","text":"Because inflections carried grammatical information, word order was flexible—but patterned. The standard scholarly description: main clauses tend toward **verb-second (V2)** order, like modern German (*Þā cōm se cyning*, \"Then came the king\"); subordinate clauses tend toward **verb-final (SOV)** order. Pronoun objects behave differently from noun objects. Negation used *ne* before the verb, freely doubled and tripled (**negative concord**: *ne ... nāht ... nǣfre*—multiple negatives intensified rather than canceled, and *ne + wolde* contracted to *nolde*, \"wouldn't\"). The word *nāht/nāwiht* (\"no-thing\") would eventually become \"not.\""},
      {"kind":"p","text":"Two prose-style terms every student needs: **parataxis** (clauses strung together with \"and... and... then...\", characteristic of the *Anglo-Saxon Chronicle*) versus **hypotaxis** (complex subordination, cultivated in translation from Latin). **Correlation** is pervasive and treacherous: *þā ... þā* means \"when ... then,\" and only word order tells you which clause is which. The ambiguity of *þā*, *þonne*, *þǣr* (adverb or conjunction?) is a genuine crux in editing and translating."},
    ],
  },
  {
    heading: "VI. Vocabulary and Word-Formation: The Native Genius",
    blocks: [
      {"kind":"p","text":"Old English vocabulary was overwhelmingly Germanic, and its most distinctive trait was exuberant **compounding** and **affixation** rather than borrowing. Where later English imported Latin and French terms wholesale, Old English built from native stock: *lārhūs* (\"lore-house,\" school), *tungolcræft* (\"star-craft,\" astronomy), *līchama* (\"body-covering,\" body), *þrīnes* (\"three-ness,\" Trinity), *gōdspell* (\"good news,\" gospel—a calque on Latin *evangelium*). This technique of translating a foreign word's parts is called a **calque** or loan-translation, and Alfredian and Ælfrician prose is full of them."},
      {"kind":"p","text":"Prefixes did heavy semantic lifting: *ge-* (often perfective or collective, and the regular past-participle marker: *gebunden*), *for-* (destructive/intensive: *fordōn*, \"destroy\"), *ā-*, *be-*, *of-*, *tō-*, *wiþ-* (\"against\"—surviving in \"withstand\"). The suffixes *-dōm*, *-hād*, *-scipe*, *-nes*, *-ung* built abstracts (whence -dom, -hood, -ship, -ness, -ing)."},
      {"kind":"p","text":"**Loanword strata** are themselves a field of study. Latin words arrived in three waves: continental borrowings before migration (*strǣt*, street; *weall*, wall; *wīn*, wine; *ċēap*, trade—whence \"cheap\"), conversion-era church vocabulary (*biscop*, *munuc*, *mynster*, *ċiriċe*), and later learned borrowings. **Old Norse** influence, following Viking settlement and the **Danelaw**, was profound but largely subterranean in the written record—words like *lagu* (law) and *þrǣl* (thrall) appear in late Old English, but the great Norse infusion (*sky, skin, egg, they, them, their*) surfaces mainly in Middle English. Because Old English and Old Norse were partially mutually intelligible, contact produced **doublets** (*shirt/skirt*, *shrub/scrub*—same word, native vs. Norse consonant treatment). **Celtic** loans are famously scarce (*brocc*, badger; place-name elements like *cumb*, *torr*)—a fact endlessly debated; the \"Celtic hypothesis\" argues instead for substrate influence on grammar (perhaps the progressive *-ing* and *do*-support), a live scholarly controversy."},
      {"kind":"p","text":"Core everyday vocabulary worth knowing from day one: *hlāford* (lord—literally \"loaf-guardian\") and *hlǣfdige* (lady, \"loaf-kneader\"); *wer* (man—surviving in \"werewolf\") and *wīf*; *cyning*, *eorl*, *ċeorl* (freeman—whence \"churl\"), *þegn* (thane); *swā* (so, as); *ac* (but); *ond/and*; *mid* (\"with,\" cognate with German *mit*—Old English *wiþ* meant \"against\"); *heofon*, *eorðe*, *middangeard* (\"middle-enclosure,\" the world—Tolkien's Middle-earth)."},
    ],
  },
  {
    heading: "VII. The Poetic Register: A Vocabulary of Its Own",
    blocks: [
      {"kind":"p","text":"Old English poetry maintained a specialized archaic diction and a metrical system every student must master conceptually."},
      {"kind":"p","text":"**Alliterative meter**: each line divides into two half-lines (**verses**, the **a-verse** and **b-verse**) separated by a **caesura** and bound by alliteration. Each half-line has two stressed syllables (**lifts**); the first stress of the b-verse (the **head-stave**) sets the alliterating sound, which must match one or both stresses of the a-verse and must *not* be matched by the final stress. All vowels alliterate with each other. **Eduard Sievers** classified the rhythmic patterns of half-lines into **Five Types (A–E)**—Type A is trochaic (/ x / x), Type B iambic, and so on—and \"Sievers types\" remain standard analytical vocabulary, alongside later systems by Pope (musical/isochronous theory) and Russom."},
      {"kind":"p","text":"**Poetic diction** includes:"},
      {"kind":"p","text":"**The kenning**: a compressed metaphorical compound or genitive phrase—*hronrād* (\"whale-road,\" the sea), *bānhūs* (\"bone-house,\" the body), *heofoncandel* (\"sky-candle,\" the sun), *beadolēoma* (\"battle-light,\" a sword). Distinguish the true kenning (metaphorical) from the **kend heiti** or simple poetic synonym."},
      {"kind":"p","text":"**Variation** (apposition): restating the same referent in successive parallel phrases—a king may be named, then called \"protector of earls,\" then \"giver of rings,\" in consecutive half-lines. Fred Robinson's *Beowulf and the Appositive Style* made this the key to the poetry's meaning-making."},
      {"kind":"p","text":"**Litotes**: ironic understatement, a defining Anglo-Saxon rhetorical mode (\"that was not the least of battles\" = it was enormous)."},
      {"kind":"p","text":"**Formulaic composition**: the **oral-formulaic theory** (Parry–Lord, applied to Old English by Magoun) holds that poets composed using inherited metrical formulas (\"X maþelode,\" \"X spoke,\" filling a half-line). Whether surviving poems are transcribed oral performances or literate compositions in a traditional style remains a foundational debate."},
      {"kind":"p","text":"Other key terms: the **scop** (the poet-singer), **wyrd** (fate, \"what comes to pass\"—not quite pagan Fate, not quite Providence; its semantics are a dissertation topic in themselves), **comitatus** (Tacitus's term for the lord-retainer bond that structures heroic ethics), **ubi sunt** (the elegiac \"where are they now?\" motif in \"The Wanderer\"), and the **beasts of battle** (the raven, eagle, and wolf who conventionally attend slaughter)."},
    ],
  },
  {
    heading: "VIII. Dialects and Periodization",
    blocks: [
      {"kind":"p","text":"Old English was never uniform. Four dialects are traditionally distinguished: **Northumbrian** and **Mercian** (together \"Anglian\"), **Kentish**, and **West Saxon**. The overwhelming majority of surviving manuscripts are in **Late West Saxon**, the standardized written language (**Schriftsprache**) associated with Æthelwold's Winchester school—the first standardized written English. This creates a famous irony: Modern English descends principally from *Anglian* (Mercian) dialects, not from the West Saxon we mostly read. Dialect markers are practical scholarly tools: West Saxon *ie*, Anglian **smoothing**, Northumbrian loss of final *-n*—these let scholars localize texts. Early Northumbrian survives in precious scraps: **Cædmon's Hymn**, Bede's Death Song, the **Ruthwell Cross** runic inscription, and the interlinear **gloss** to the Lindisfarne Gospels."},
      {"kind":"p","text":"Periodization: **prehistoric OE** (before written records, reconstructed), **Early OE** (c. 650–900, the age of Bede and the Alfredian translations), **Late OE** (c. 900–1066, Ælfric and Wulfstan), and **transitional/post-Conquest English** shading into Early Middle English by c. 1150, when the collapse of unstressed vowels to schwa (**leveling**) and consequent loss of inflection—accelerated by Norse contact and Norman disruption of the written standard—transformed the language's typology from **synthetic** to **analytic**."},
    ],
  },
  {
    heading: "IX. The Corpus: What Survives and Where",
    blocks: [
      {"kind":"p","text":"Roughly 3.5 million words of Old English survive—about 30,000 lines of poetry and a much larger body of prose. The poetry lives almost entirely in **four codices**, all copied around 1000 CE:"},
      {"kind":"list","ordered":true,"items":["The **Beowulf Manuscript** (Cotton Vitellius A.xv, the \"Nowell Codex\"): *Beowulf* and *Judith*, singed at the edges by the 1731 Ashburnham House fire.","The **Exeter Book**: the great anthology—the elegies (\"The Wanderer,\" \"The Seafarer,\" \"The Wife's Lament,\" \"Wulf and Eadwacer\"), the riddles (nearly a hundred, some sublime, some gloriously obscene), \"Widsith,\" \"Deor.\"","The **Vercelli Book** (stranded in northern Italy): \"The Dream of the Rood,\" \"Andreas,\" plus homilies.","The **Junius Manuscript**: biblical verse—\"Genesis\" (including *Genesis B*, translated from Old Saxon), \"Exodus,\" \"Daniel,\" \"Christ and Satan.\""]},
      {"kind":"p","text":"Major prose: the **Alfredian corpus** (translations of Boethius, Gregory's *Pastoral Care*, Orosius, and the Soliloquies, associated with King Alfred's 890s educational program—though how much Alfred personally wrote is now contested); the **Anglo-Saxon Chronicle** (a multi-manuscript annalistic history maintained for centuries); **Ælfric of Eynsham** (the supreme prose stylist, whose *Catholic Homilies* and *Lives of Saints* develop rhythmical, alliterating prose, and whose *Grammar* and *Colloquy* are the first language-teaching texts in English); **Wulfstan** (Archbishop of York, whose thunderous *Sermo Lupi ad Anglos* has an instantly recognizable insistent style); plus laws, charters, wills, medical texts (the *Leechbooks*, *Lacnunga*, with the fascinating **metrical charms**), and the **glosses**—interlinear word-by-word translations of Latin texts, invaluable for lexicography."},
      {"kind":"p","text":"Key manuscript-studies vocabulary: **scriptorium**, **scribal hand** (Insular minuscule, later Caroline influence), **folio/recto/verso**, **gloss**, **colophon**, **exemplar** (the copy a scribe worked from), **emendation** and **crux** (an editorial correction; an unresolved textual problem—*Beowulf* scholarship is a museum of cruxes)."},
    ],
  },
  {
    heading: "X. The Scholarly Apparatus: Tools of the Trade",
    blocks: [
      {"kind":"p","text":"Anyone moving from beginner to professional needs the field's infrastructure by name. The standard student grammars are **Mitchell and Robinson's *A Guide to Old English*** and Baker's *Introduction to Old English*; the monumental reference grammars are **Campbell's *Old English Grammar*** (phonology and morphology) and **Bruce Mitchell's two-volume *Old English Syntax***; Hogg and Fulk continue the tradition. The dictionaries: **Bosworth-Toller** (the venerable standard, free online), **Clark Hall** (the student's concise dictionary), and the ongoing **Dictionary of Old English (DOE)** at Toronto, built on the complete **DOE Corpus**—a searchable database of every surviving Old English text, the discipline's central digital tool. Poetry is cited from the **Anglo-Saxon Poetic Records (ASPR)**; *Beowulf* from **Klaeber's Beowulf** (4th edition). For meter, Sievers, Pope, Bliss, and Fulk's *History of Old English Meter*; for etymology within the Germanic family, terms like **Proto-Germanic**, **Ingvaeonic**, **cognate**, and the comparative method are daily bread."},
      {"kind":"p","text":"A terminological note with political weight: the field increasingly prefers \"**early medieval England**\" and \"Old English studies\" over \"Anglo-Saxon studies,\" following debates (c. 2019 onward) about the term's appropriation by racial nationalists and its historical accuracy. You should know both usages and the controversy."},
    ],
  },
  {
    heading: "XI. A Miniature Demonstration",
    blocks: [
      {"kind":"p","text":"Take the opening of *Beowulf*:"},
      {"kind":"callout","variant":"key","text":"*Hwæt! Wē Gār-Dena in geārdagum, / þēodcyninga þrym gefrūnon, / hū ðā æþelingas ellen fremedon.*"},
      {"kind":"p","text":"Everything above converges here. *Hwæt* is the famous interjection—traditionally \"Lo!\" or \"Listen!\", though Walkden's influential 2013 argument reads it as an exclamative particle bound to the clause (\"How we have heard...\")—a live crux. *Gār-Dena* is a compound (\"Spear-Danes\") in the genitive plural. *geārdagum* (\"yore-days\") is dative plural after *in*. *þēodcyninga* (\"people-kings\") — genitive plural, another compound. *gefrūnon* is a Class III strong verb, preterite plural, with the *ge-* prefix. The verb sits clause-finally. The lines alliterate on *g*, *þ*, and vowels/*ellen* respectively, and the syntax delays and interlaces in ways prose never would. Three lines in, you have met compounding, case, ablaut, meter, and an unresolved scholarly debate. That is Old English in miniature: a small corpus, intricately made, still generating argument thirteen centuries on."},
      {"kind":"p","text":"**The learning path, compressed**: master the alphabet and pronunciation; drill the demonstrative *se/sēo/þæt* and pronouns until automatic; learn the major noun paradigms and the strong-verb classes; read graded prose (Ælfric's *Colloquy*, the Chronicle, Apollonius of Tyre) before attempting verse; then take on the elegies, then *Beowulf* with Klaeber; and somewhere along the way, fall down the philological rabbit holes of i-mutation and Verner's Law, from which, be warned, few fully return."},
    ],
  },
];;
