import type { LessonSection } from "../curriculum";

export const sections: readonly LessonSection[] = [
  {
    heading: null,
    blocks: [
      {"kind":"p","text":"Park Chan-wook is a South Korean filmmaker best known internationally for *Oldboy*, *The Handmaiden*, and *Decision to Leave*. His reputation emphasizes elegant images, disturbing violence, intricate plots, and dark humor. Those descriptions are accurate, but they do not yet explain what makes his filmmaking distinctive."},
      {"kind":"p","text":"A more useful starting point is this: **Park repeatedly investigates the gap between making something intelligible and making it morally acceptable.** A revenge plan can be beautifully organized without delivering justice. A revelation can explain someone’s behavior without excusing it. An image can be seductive while showing a relationship structured by exploitation."},
      {"kind":"p","text":"This lesson assumes no background in film theory. It introduces advanced concepts through concrete examples and avoids major twists and endings."},
    ],
  },
  {
    heading: "1. Style is not decoration: it organizes your attention",
    blocks: [
      {"kind":"p","text":"In ordinary conversation, calling a film “stylish” often means that it looks attractive. In film analysis, style means something more consequential: the patterned choices through which a film directs perception and feeling."},
      {"kind":"p","text":"Camera position determines what you can see. Framing determines what remains outside the image. Editing determines when you receive information. Sound can direct your attention toward something invisible. An actor’s posture can contradict the dialogue. These decisions do not merely package the story; they help constitute it."},
      {"kind":"p","text":"Park makes this especially apparent because his images often look deliberately constructed. Architecture, color, bodies, and objects can be arranged with almost diagrammatic precision. Yet the emotional situations inside those arrangements are frequently unstable."},
      {"kind":"p","text":"That contrast matters. **Order in the image is not the same thing as order in the world.** A perfectly composed frame can contain a disastrous misunderstanding."},
      {"kind":"p","text":"Consider the famous corridor fight in *Oldboy* (2003). Its extended, side-on presentation lets you register space, obstacles, and bodily effort. It resembles the layout of a side-scrolling game, but the protagonist’s exhaustion complicates any fantasy of frictionless mastery. Duration makes fatigue visible."},
      {"kind":"p","text":"The analytical question is therefore not simply whether the sequence looks impressive. It is what this particular presentation makes you experience. Here, violence becomes an arduous physical process rather than just a series of triumphant impacts."},
      {"kind":"p","text":"This gives you a useful rule for studying Park: whenever a formal choice attracts attention, ask what work it performs. Does it clarify space, conceal knowledge, produce anticipation, create distance, or make you uncomfortably intimate with someone?"},
    ],
  },
  {
    heading: "2. Narration is the management of knowledge",
    blocks: [
      {"kind":"p","text":"A film’s **story** is the chain of events you understand to have happened. Its **narration** is the process through which you discover those events."},
      {"kind":"p","text":"Narration does not require a voice-over. A locked door, a reaction shot, a withheld conversation, or a scene shown twice can all govern what you know."},
      {"kind":"p","text":"Park frequently separates events from their initial interpretation. Something happens; you assign it a meaning; later information forces you to reconsider that meaning. The earlier event may remain exactly the same while its moral and emotional significance changes."},
      {"kind":"p","text":"This is more interesting than the idea of a twist as a surprise delivery system. A strong reversal does not merely add a missing fact. It reorganizes the relationships among facts you already possess."},
      {"kind":"p","text":"Two concepts help here."},
      {"kind":"p","text":"**Restricted narration** means that the film limits your access to information. **Unreliable narration** means that some account or presentation gives you reason to distrust it. They are not identical. A film can tell you nothing false while allowing you to build a mistaken explanation from incomplete evidence."},
      {"kind":"p","text":"Park exploits that gap between evidence and inference. His viewers are often active but overconfident interpreters."},
      {"kind":"p","text":"Another useful distinction is between **alignment** and **allegiance**. Alignment concerns following a character’s actions, perceptions, or knowledge. Allegiance concerns our moral and emotional evaluation of that character. A film can place us close to someone without making that person admirable."},
      {"kind":"p","text":"This is crucial to *Oldboy*. Following a person’s pursuit of answers does not settle whether we should approve of everything that pursuit involves."},
      {"kind":"p","text":"The deeper subject is epistemology: the study of knowledge—what can be known, how, and with what justification. In Park, knowledge is rarely just a resource for solving a problem. Acquiring it can become the problem."},
    ],
  },
  {
    heading: "3. Revenge confuses symmetry with justice",
    blocks: [
      {"kind":"p","text":"Park’s so-called Vengeance Trilogy consists of *Sympathy for Mr. Vengeance* (2002), *Oldboy* (2003), and *Lady Vengeance* (2005). These are separate stories, not successive episodes in one fictional universe."},
      {"kind":"p","text":"Their shared concern is not simply that revenge produces violence. More specifically, they examine the promise that an injury can be answered by an equivalent injury."},
      {"kind":"p","text":"That promise is psychologically powerful because it gives suffering a structure. Someone harmed me; I will identify them; I will make them suffer; the account will be balanced."},
      {"kind":"p","text":"But an emotional ledger is not a reliable model of justice."},
      {"kind":"p","text":"There is no neutral unit for measuring grief, humiliation, bodily injury, or lost time. The person being punished may understand the situation differently. The act of retaliation also creates new victims and new interpretations."},
      {"kind":"p","text":"In systems terms, revenge can become a feedback loop: the output of one person’s attempt at correction becomes the input for someone else’s grievance. Locally understandable actions can produce a globally catastrophic result."},
      {"kind":"p","text":"*Sympathy for Mr. Vengeance* makes the social conditions of this loop especially important. Illness, employment, money, and unequal resources shape what actions appear possible. To describe the film only as a meditation on universal human cruelty would miss its material circumstances."},
      {"kind":"p","text":"Yet explanation is not exoneration. Understanding why someone acts does not automatically make the action defensible."},
      {"kind":"p","text":"*Oldboy* shifts attention toward the relationship between revenge and control over another person’s knowledge. *Lady Vengeance* complicates the hope that punishment can produce purification or moral renewal."},
      {"kind":"p","text":"Across these films, an important distinction emerges: **causal closure is not ethical closure**. Discovering how everything fits together does not mean that anything has been repaired."},
    ],
  },
  {
    heading: "4. Architecture gives power a floor plan",
    blocks: [
      {"kind":"p","text":"The term **mise-en-scène** refers to what is staged before the camera: settings, objects, costumes, lighting, and the placement and movement of performers."},
      {"kind":"p","text":"In Park’s cinema, these elements are rarely just background."},
      {"kind":"p","text":"Rooms determine who can approach whom. Doors regulate access. Corridors delay encounters. Windows permit looking while preserving separation. Objects can function as evidence, instruments, gifts, threats, or signs of status."},
      {"kind":"p","text":"For a technically minded viewer, architecture often behaves like a permissions system. Different characters possess different rights to enter, observe, speak, conceal, and know."},
      {"kind":"p","text":"*The Handmaiden* (2016) offers a particularly rich example. Adapted from Sarah Waters’s novel *Fingersmith*, it moves the setting from Victorian England to Korea under Japanese colonial rule in the 1930s. This is not merely a change of scenery. It changes the historical machinery through which wealth, language, prestige, and domination operate."},
      {"kind":"p","text":"The mansion’s mixture of Japanese and European design makes cultural aspiration visible. Its spaces organize relationships between display and concealment, service and ownership, intimacy and surveillance."},
      {"kind":"p","text":"The important question is not just what a room “symbolizes.” Ask what the room allows someone to do."},
      {"kind":"p","text":"This moves analysis beyond a simplistic codebook in which every staircase means ambition and every window means freedom. An architectural feature acquires meaning through its use, its recurrence, and its relationship to particular characters."},
      {"kind":"p","text":"Park’s spaces are often beautiful because someone has exercised extraordinary control over them. The next question is what that control costs the people living inside."},
    ],
  },
  {
    heading: "5. Desire is a struggle over who gets to look",
    blocks: [
      {"kind":"p","text":"Park’s films repeatedly connect desire with observation. Characters watch, investigate, collect, remember, rehearse, and interpret other people."},
      {"kind":"p","text":"This produces a central tension: does looking bring you closer to another person, or turn that person into an object you can manage?"},
      {"kind":"p","text":"The **gaze**, in film theory, is not merely the physical act of seeing. It concerns the organization of looking: who is positioned as observer, who becomes spectacle, and whose desires structure the experience."},
      {"kind":"p","text":"The “male gaze,” associated with feminist film theorist Laura Mulvey, is therefore not simply any shot of a woman or any film directed by a man. It describes a structure in which women are organized as objects for a viewing position shaped by male desire, often at the expense of their own subjectivity."},
      {"kind":"p","text":"*The Handmaiden* is productive to study through this framework because looking is part of its machinery of power. Performance, erotic display, storytelling, and control are closely connected. At the same time, the film develops women’s desire and agency in ways that challenge the roles imposed on them."},
      {"kind":"p","text":"That does not automatically place the film beyond criticism. A work can criticize objectification while still producing images that viewers reasonably find objectifying."},
      {"kind":"p","text":"A serious reading should hold both possibilities open and examine particular scenes. Whose desire organizes the sequence? Whose reactions matter? Does the person being looked at possess knowledge, initiative, or the ability to refuse? Does the camera reveal subjectivity, or mainly offer a body for inspection?"},
      {"kind":"p","text":"The larger issue extends beyond sexuality. The detective, lover, collector, and avenger can share a dangerous assumption: that knowing more about someone grants a right over them."},
      {"kind":"p","text":"Park repeatedly tests that assumption."},
    ],
  },
  {
    heading: "6. Editing can express emotional proximity rather than physical proximity",
    blocks: [
      {"kind":"p","text":"Editing does more than connect one event to the next. It can connect spaces, memories, sensations, and associations."},
      {"kind":"p","text":"A **sound bridge** carries sound across a visual transition, linking otherwise separate moments. A **graphic match** connects images through a visual resemblance. A cut can also omit the practical steps between situations, trusting viewers to reconstruct what happened."},
      {"kind":"p","text":"Park uses these possibilities to make relationships felt rather than merely explained."},
      {"kind":"p","text":"*Decision to Leave* (2022) is especially useful here. Its detective investigation involves observation, devices, recordings, and interpretation, but the film gradually makes professional attention difficult to separate from romantic attachment."},
      {"kind":"p","text":"At moments, the detective is presented as imaginatively present in the space he watches from a distance. Physical separation remains part of the situation, but cinematic form gives his attention an intimacy that literal geography would deny."},
      {"kind":"p","text":"That is not a continuity error. It is a way of showing subjectivity: the experience of a particular consciousness."},
      {"kind":"p","text":"The film also demonstrates why recurring images should not be treated as a fixed symbolic dictionary. Mountains and the sea gather significance through their changing relationships to characters, memories, and actions. Their meanings develop rather than arrive fully assigned."},
      {"kind":"p","text":"One useful question for any transition is: did the film move because time advanced, because space changed, or because someone’s mind made a connection?"},
      {"kind":"p","text":"Park’s editing often becomes more legible once you stop assuming that chronology is its only organizing principle."},
    ],
  },
  {
    heading: "7. Bodies resist elegant moral theories",
    blocks: [
      {"kind":"p","text":"Park’s characters can invent elaborate plans and explanations, but they remain embodied beings. They bleed, desire, tire, hunger, feel shame, and become dependent on others."},
      {"kind":"p","text":"The body interrupts the fantasy that a person can control life through intelligence alone."},
      {"kind":"p","text":"In *Thirst* (2009), the vampire premise turns this conflict into something literal. A Catholic priest’s ethical commitments confront transformed bodily appetites. The horror makes dependence visible: what happens when continuing to live implicates you in harming others?"},
      {"kind":"p","text":"The resulting problem is not exhausted by a simple opposition between a pure soul and a corrupt body. Belief, appetite, self-deception, affection, and responsibility become entangled."},
      {"kind":"p","text":"Park’s tonal mixtures intensify that entanglement. Horror can become absurd; comedy can turn cruel; an apparently grotesque encounter can become unexpectedly tender."},
      {"kind":"p","text":"**Black comedy** creates humor out of disturbing situations. In Park, it can destabilize the viewer’s sense of the appropriate response. You laugh, then reconsider what your laughter assumed."},
      {"kind":"p","text":"**Melodrama**, meanwhile, is not simply a synonym for bad or exaggerated storytelling. It is a mode that gives emotional and moral conflict heightened expression through performance, gesture, music, and situation."},
      {"kind":"p","text":"Park can combine melodramatic intensity with controlled framing and dry humor. The result is neither purely sincere nor safely ironic."},
      {"kind":"p","text":"*I’m a Cyborg, But That’s OK* (2006) is a useful corrective to the idea that his imagination serves only cruelty. His stylization can also create room for eccentricity, tenderness, and care."},
    ],
  },
  {
    heading: "8. “Auteur” does not mean solitary genius",
    blocks: [
      {"kind":"p","text":"An **auteur** is a filmmaker whose work displays a recognizable pattern of concerns and formal choices. Park is a strong example, but the concept becomes misleading if it erases collaboration."},
      {"kind":"p","text":"His cinema has been shaped by collaborators including screenwriter Chung Seo-kyung, production designer Ryu Seong-hie, composer Jo Yeong-wook, and cinematographers such as Chung Chung-hoon and Kim Ji-yong."},
      {"kind":"p","text":"Recognizing a directorial signature should help us identify coordinated decisions, not imagine that one person independently creates every expressive detail."},
      {"kind":"p","text":"Historical context matters just as much. The division of Korea in *Joint Security Area* (2000), economic vulnerability in *Sympathy for Mr. Vengeance*, and colonial hierarchy in *The Handmaiden* are not interchangeable backdrops for timeless human darkness. They structure the characters’ opportunities and vulnerabilities."},
      {"kind":"p","text":"The strongest interpretation moves between levels: the individual’s psychology, the relationships among characters, the institutions around them, and the film’s organization of our perception."},
      {"kind":"p","text":"None of those levels explains everything by itself."},
    ],
  },
  {
    heading: "9. How to watch Park analytically without killing the experience",
    blocks: [
      {"kind":"p","text":"For a relatively direct introduction, begin with *Joint Security Area*. It establishes how political structures can make human relationships both possible and dangerous. *Oldboy* concentrates the concerns with revenge, knowledge, and bodily ordeal. *The Handmaiden* foregrounds perspective, performance, architecture, and gender. *Decision to Leave* develops related concerns through a more restrained romantic register. Several of these films contain graphic violence, explicit sex, or sexual violence, so individual content notes may be useful."},
      {"kind":"p","text":"On a first viewing, allow yourself to be moved, confused, amused, or repelled. Your initial response is part of the evidence."},
      {"kind":"p","text":"On a second viewing, choose a short scene and begin with description rather than interpretation. Where is the camera? What can each character see? What do you know that they do not? When does the music enter? Which gesture receives a close-up? What has the film withheld?"},
      {"kind":"p","text":"Then form a hypothesis about the scene’s effect and test an alternative. Perhaps a composed image expresses someone’s confidence. Perhaps it exposes how artificial that confidence is. Which account better explains the whole sequence?"},
      {"kind":"p","text":"This is the beginning of rigorous analysis: not accumulating impressive terminology, but making interpretations answerable to observable choices."},
      {"kind":"p","text":"The skeptical question should remain available too. Does a film’s formal control illuminate suffering, or make suffering attractive as spectacle? Park’s beauty should not receive automatic moral credit simply because it is accomplished."},
      {"kind":"p","text":"The central lesson is this: **in Park Chan-wook, seeing more clearly does not necessarily leave you morally cleaner.** His cinema makes us desire knowledge, intimacy, and resolution—then asks what those desires have made us willing to overlook."},
    ],
  },
];;
