import type { LessonSection } from "../curriculum";

export const sections: readonly LessonSection[] = [
  {
    heading: null,
    blocks: [
      {"kind":"p","text":"*From the object model to continuous batching, by way of the event loop.*"},
    ],
  },
  {
    heading: "How to read this",
    blocks: [
      {"kind":"p","text":"This is a map of a territory, written as prose rather than as a cheat sheet, because the hard part of Python-for-ML-serving is not syntax — it is knowing *which mental model applies where*. A beginner can read straight through and pick up vocabulary in dependency order. A professional can skim for the sections where the subtleties live: the object model, cancellation semantics, the GIL's interaction with native extensions, the sync/async boundary in FastAPI, and process topology on a GPU."},
      {"kind":"p","text":"The thesis of the whole document: **Python is a coordination language wearing a computation language's clothes.** In an AI service, almost no useful work happens in Python bytecode. Python's job is to describe *structure* — what the request means, which tensors go where, when to wait, when to batch, when to give up — while the actual arithmetic happens in C, CUDA, or Rust. Nearly every performance surprise and every architectural decision in this domain follows from that one fact."},
    ],
  },
  {
    heading: "I. The substrate: objects, names, and memory",
    blocks: [
      {"kind":"p","text":"Everything in Python is an **object**: a chunk of memory with a type, an identity, and a value. Integers, functions, classes, modules, and the running stack frame are all objects. There are no primitives hiding underneath, which is why Python is slow and why it is so pleasant."},
      {"kind":"p","text":"A **name** (what other languages call a variable) is not a box that holds a value; it is a label bound to an object in a namespace. `x = [1, 2]` does not create a \"list variable\"; it creates a list object and binds the name `x` to it. `y = x` binds a second name to the *same* object. This is **reference semantics**, and understanding it eliminates an entire family of bugs. The operator `is` compares **identity** (same object, same memory address, as reported by `id()`); `==` compares **equality** (as defined by the type's `__eq__`). They coincide for small cached integers and interned strings, which produces the classic confusing demo where `256 is 256` but `257 is 257` may be False."},
      {"kind":"p","text":"Objects are **mutable** or **immutable**. Lists, dicts, sets, and most of your own classes are mutable; ints, floats, strings, tuples, and frozensets are not. Immutability is what makes an object **hashable** (usable as a dict key or set member) by default, because a hash must not change while the object lives in a table. The single most famous Python trap follows directly: a default argument like `def f(items=[])` evaluates `[]` *once*, at function definition time, so the same list is shared across every call. The idiom is `def f(items=None)` with `items = [] if items is None else items`. In Pydantic and dataclasses, the equivalent is `Field(default_factory=list)`."},
      {"kind":"p","text":"CPython manages memory with **reference counting** — every object tracks how many names and containers point at it, and it is freed the instant that count hits zero — plus a **generational cycle collector** for reference cycles that counting cannot reclaim. This is why Python memory usage is usually predictable but occasionally lurches: `del` and scope exit free memory immediately, while cycles (a parent holding a child holding the parent) wait for `gc`. In a long-lived inference server this matters in two places. First, a cycle that holds a CUDA tensor keeps GPU memory pinned until collection, so you occasionally see `torch.cuda.empty_cache()` and explicit `del` in serving code. Second, before forking worker processes, `gc.freeze()` moves existing objects out of the GC's view so that collection passes don't touch — and thereby copy-on-write-dirty — pages shared with children."},
      {"kind":"p","text":"For the geek: `__slots__` on a class replaces the per-instance `__dict__` with a fixed array of descriptors, cutting memory per object substantially and speeding attribute access. `@dataclass(slots=True)` gives you this for free. It matters when you hold millions of small records, not when you hold ten model wrappers."},
    ],
  },
  {
    heading: "II. Scope, modules, packages, environments",
    blocks: [
      {"kind":"p","text":"Names live in **namespaces**, and lookup follows the **LEGB** rule: Local, Enclosing (the scope of a surrounding function), Global (module-level), Built-in. Assignment inside a function creates a local name unless you declare `global` or `nonlocal`. A **closure** is a function that captures names from an enclosing scope and keeps them alive after that scope returns; closures are the quiet foundation of decorators, dependency factories, and callbacks."},
      {"kind":"p","text":"A **module** is a single `.py` file, which is itself an object with a `__dict__`. A **package** is a directory of modules, traditionally marked by `__init__.py`. The `import` statement executes a module exactly once per interpreter and caches it in `sys.modules`; this makes module-level code an implicit singleton mechanism — and an implicit footgun, since loading a 7 GB model at import time means it loads during test collection, during `--help`, and once per forked worker. **Circular imports** arise when two modules import each other at module level; the fixes are to move the import inside a function, to invert the dependency, or to introduce a third module holding the shared type."},
      {"kind":"p","text":"An **environment** is the set of installed packages visible to one interpreter. **Virtual environments** (`venv`) isolate them per project. Modern packaging is declared in `pyproject.toml` (PEP 621 metadata, PEP 517/518 build backends); distributions ship as **sdists** (source) or **wheels** (pre-built, named by Python ABI and platform tag such as `manylinux_2_28_x86_64`). For ML this is not bureaucracy: PyTorch wheels are compiled against a specific CUDA runtime, so your \"dependency resolution\" is really an ABI compatibility problem spanning driver, CUDA, cuDNN, and the wheel. Tools: `pip`, `uv` (a very fast resolver/installer that has become the default choice), `poetry`, `conda`/`mamba` when you need non-Python binaries. A **lockfile** pins the exact resolved graph including hashes; without one, \"it worked yesterday\" is a coin flip. **Extras** (`package[gpu]`) and **dependency groups** let you keep training-only dependencies out of your serving image."},
    ],
  },
  {
    heading: "III. Functions as first-class values, and decorators",
    blocks: [
      {"kind":"p","text":"Functions are objects: you can pass them, return them, store them in dicts, and attach attributes to them. Parameters come in flavors — positional, keyword, variadic `*args`, variadic keyword `**kwargs` — and the markers `/` and `*` in a signature force **positional-only** and **keyword-only** parameters respectively. Keyword-only parameters are good hygiene in ML code, where `predict(model, data, True, False, 32)` is unreadable and `predict(model, data, normalize=True, stream=False, batch_size=32)` is self-documenting."},
      {"kind":"p","text":"A **decorator** is a function that takes a function (or class) and returns a replacement; `@app.get(\"/x\")` and `@lru_cache` are the same mechanism. Always wrap with `functools.wraps` so the result keeps the original's `__name__`, docstring, and — critically for FastAPI — its `__signature__` and type annotations, because frameworks introspect those. From `functools` you will reach for `partial` (pre-bind arguments), `lru_cache` / `cache` (memoize pure functions), `cached_property` (compute once per instance), and `singledispatch` (type-based function overloading, a clean way to handle \"this handler accepts images or text or tensors\")."},
      {"kind":"p","text":"A sharp edge: `lru_cache` on an `async def` function caches the **coroutine object**, not its result. Awaiting it twice raises `RuntimeError: cannot reuse already awaited coroutine`. Cache the awaited value yourself, cache a `Task`/`Future` instead, or use a library such as `async-lru`."},
    ],
  },
  {
    heading: "IV. The data model: dunder protocols and duck typing",
    blocks: [
      {"kind":"p","text":"Python's extensibility is expressed through **special methods** (\"dunders\"). Implement `__len__` and `len()` works; `__iter__` and `for` works; `__getitem__` and subscripting works; `__call__` and your instance becomes callable (the idiomatic way to wrap a model: `class Predictor: def __call__(self, batch): ...`). `__enter__`/`__exit__` make a **context manager** usable with `with`; `__aenter__`/`__aexit__` make an **async context manager** usable with `async with`. `__repr__` should be unambiguous for debugging; `__eq__` and `__hash__` must agree."},
      {"kind":"p","text":"This is **duck typing**: compatibility is determined by behavior, not declared ancestry. **Abstract base classes** (`abc.ABC`) let you declare an interface nominally; `typing.Protocol` lets you declare it **structurally**, so any object with the right methods satisfies it without inheriting anything — the right tool for \"anything with an `async def embed(self, texts) -> list[list[float]]`\"."},
      {"kind":"p","text":"Deeper machinery you should recognize even if you rarely write it: **descriptors** (objects defining `__get__`/`__set__`, the mechanism behind `property`, methods, and `cached_property`), **metaclasses** (classes whose instances are classes — how Pydantic and ORMs build fields from annotations), and `__init_subclass__` (a lighter-weight hook for registering plugins/model backends as they are defined)."},
    ],
  },
  {
    heading: "V. Containers, data structures, and the shape of memory",
    blocks: [
      {"kind":"p","text":"The **list** is a dynamic array: O(1) indexing and amortized O(1) append, O(n) insertion at the front. The **tuple** is its immutable sibling and is the natural type for fixed heterogeneous records and for shapes. The **dict** is a hash table that preserves insertion order (guaranteed since 3.7) with O(1) average lookup; it is also the substrate of objects, kwargs, and JSON. The **set** is a hash table without values, for membership and deduplication. From `collections`: `deque` (O(1) at both ends — the right queue for a sliding window), `defaultdict`, `Counter`, `OrderedDict` (now mostly for `move_to_end`). From `heapq`: a binary heap for priority queues, which is how you implement priority-aware request scheduling."},
      {"kind":"p","text":"Then the layer that matters for ML: **bytes** (immutable binary), **bytearray** (mutable), and **memoryview**, which exposes the **buffer protocol** — a standardized way for objects to share a raw memory region without copying. NumPy arrays, PyTorch CPU tensors, Arrow buffers, and `mmap` regions all speak it. \"Zero-copy\" in Python means \"we passed a buffer view, not a serialized copy,\" and it is the difference between a 50 ms and a 0.05 ms handoff for a 100 MB tensor. `struct` packs and unpacks fixed binary layouts; `pickle` protocol 5 (PEP 574) supports **out-of-band buffers** so large arrays can be transferred alongside the pickle stream rather than inside it — the mechanism underlying fast inter-process tensor transfer in Dask, Ray, and `torch.multiprocessing`."},
      {"kind":"p","text":"**Comprehensions** (`[f(x) for x in xs if p(x)]`, plus dict and set forms) are the idiomatic transformation syntax, and generator expressions `(f(x) for x in xs)` are their lazy counterpart. But in numerical code, a comprehension over an array is a performance bug: a loop in Python costs tens of nanoseconds per iteration in interpreter overhead alone, whereas the vectorized NumPy/PyTorch equivalent dispatches once into SIMD- and thread-optimized C. **Vectorization** is the discipline of expressing computation as whole-array operations."},
    ],
  },
  {
    heading: "VI. The modeling spectrum: dataclasses, NamedTuple, attrs, Pydantic",
    blocks: [
      {"kind":"p","text":"You will represent structured data four or five different ways, and choosing well is a real design skill."},
      {"kind":"p","text":"A plain **class** is maximally flexible and maximally verbose. A **`NamedTuple`** is an immutable, tuple-compatible record — lightweight, unpackable, good for return values. A **`@dataclass`** generates `__init__`, `__repr__`, `__eq__` from annotations and supports `frozen=True` and `slots=True`; it performs *no validation* and is the right default for internal domain objects where you trust your own code. **attrs** is the older, more featureful ancestor of dataclasses. **Pydantic** models validate and coerce at construction, generate JSON Schema, and serialize — they are for the **boundary** of your system, where data arrives from a network and cannot be trusted. **msgspec** is a notable fast alternative when you want validation with minimal overhead."},
      {"kind":"p","text":"The architectural principle: validate at the edge with Pydantic, then convert into plain dataclasses or domain objects for the interior. Carrying request models deep into your inference code couples your math to your HTTP schema and makes every API change a refactor."},
    ],
  },
  {
    heading: "VII. Typing: gradual, structural, and — crucially — runtime-reflected",
    blocks: [
      {"kind":"p","text":"Python's type annotations are, by language semantics, **gradual** and **erased**: the interpreter does not enforce them. They exist for static checkers (`mypy`, `pyright`/Pylance), for editors, and — in this ecosystem — for *runtime frameworks that read them*. That last use is what makes typing non-optional in FastAPI work."},
      {"kind":"p","text":"Core vocabulary: `int | None` (PEP 604 union syntax, replacing `Optional[int]`); built-in generics `list[str]`, `dict[str, float]` (PEP 585, replacing `typing.List`); `TypeVar` for generic functions and classes, with PEP 695 giving the compact `def first[T](xs: list[T]) -> T` form; `ParamSpec` and `Concatenate` for decorators that preserve signatures; `Protocol` for structural interfaces; `Literal[\"cpu\", \"cuda\"]` for closed string enumerations; `TypedDict` for dicts with known keys; `NewType` for cheap nominal distinctions (`UserId = NewType(\"UserId\", str)`); `Self` for fluent APIs; `Final` and `ClassVar`; `overload` for functions whose return type depends on argument types; `TYPE_CHECKING` with `from __future__ import annotations` to break import cycles caused by type-only imports. **Variance** (covariance, contravariance, invariance) explains why `list[Dog]` is not a `list[Animal]` — mutability forces invariance — while `Sequence[Dog]` *is* a `Sequence[Animal]`. Prefer abstract parameter types (`Sequence`, `Mapping`, `Iterable`) and concrete return types."},
      {"kind":"p","text":"The keystone for this domain is **`Annotated`** (PEP 593): `Annotated[T, metadata...]` attaches arbitrary runtime metadata to a type without changing what the type checker sees. FastAPI and Pydantic use it as their primary interface — `Annotated[int, Query(ge=1, le=100)]`, `Annotated[Session, Depends(get_session)]`, `Annotated[float, Field(gt=0)]`. This is the bridge between static typing and runtime behavior, and the modern FastAPI style uses it everywhere because, unlike default-value-based declarations, it composes, it can be aliased and reused, and it does not confuse type checkers."},
      {"kind":"p","text":"A caveat specific to ML: static typing does not express tensor **shape** or **dtype**, which is where most real bugs live. Partial mitigations exist — `jaxtyping`, `nptyping`, shape assertions, `einops` with named axes — but the professional habit is to write shape contracts in docstrings and assert them at module boundaries."},
    ],
  },
  {
    heading: "VIII. Iteration, laziness, and pipelines",
    blocks: [
      {"kind":"p","text":"An **iterable** can produce an **iterator** (`__iter__`); an iterator yields items one at a time (`__next__`) and raises `StopIteration` when exhausted. A **generator function** contains `yield`, and calling it returns a generator object: a suspendable, resumable computation whose local state lives on the heap. `yield from` delegates to a sub-generator. Generators give you **laziness** — constant memory over an arbitrarily long stream — which is how you process a 200 GB JSONL dataset on a laptop, and how you stream LLM tokens to a client without buffering the whole answer."},
      {"kind":"p","text":"`itertools` is the lazy standard library: `islice`, `chain`, `groupby`, `tee`, `batched` (3.12+, finally a first-class chunker). The **pipeline** idiom — a chain of generators, each transforming the previous one — gives readable, memory-bounded ETL."},
      {"kind":"p","text":"Generators are also the historical root of coroutines: `yield` suspends a frame and returns control to a caller, which is precisely what `await` does. Understanding that `async def` functions are \"generators that yield to an event loop instead of to a `for` loop\" demystifies asyncio permanently."},
    ],
  },
  {
    heading: "IX. Errors, exceptions, and resource discipline",
    blocks: [
      {"kind":"p","text":"Exceptions are normal control flow in Python, not exceptional. The culture is **EAFP** (\"easier to ask forgiveness than permission\") rather than **LBYL** (\"look before you leap\"), because the latter has race conditions and costs a lookup. `try/except/else/finally` covers the space: `else` runs only if no exception occurred, `finally` always runs. `raise NewError(...) from original` preserves the cause chain, which is the difference between a readable incident and an archaeology project. Define a small exception hierarchy per service (`class ModelError(Exception)`, `class ModelTimeout(ModelError)`) so callers can catch at the right granularity; never `except Exception: pass`."},
      {"kind":"p","text":"**Context managers** encode acquire/release symmetry and are the correct answer to \"how do I make sure this is cleaned up\": files, locks, DB sessions, GPU streams, `torch.inference_mode()`, temporary directories, timing blocks. Write them with `@contextlib.contextmanager` around a generator with a single `yield` wrapped in `try/finally`, or `@contextlib.asynccontextmanager` for the async form. `contextlib.ExitStack` / `AsyncExitStack` manage a dynamic number of them — which is, in fact, exactly how FastAPI unwinds `yield`-based dependencies."},
      {"kind":"p","text":"Python 3.11 added **`ExceptionGroup`** and `except*` syntax, for when several concurrent operations fail at once. This is not an exotic feature; it is the normal result of a `TaskGroup` in which two tasks raise. If you run structured concurrency, you must know how to catch groups."},
    ],
  },
  {
    heading: "X. Concurrency theory: the GIL and the three kinds of parallelism",
    blocks: [
      {"kind":"p","text":"The **Global Interpreter Lock** is a mutex in CPython ensuring that only one thread executes Python bytecode at a time. The consequences are precise and widely misstated, so state them precisely: the GIL serializes *interpreter* work, not *all* work. It is released during blocking I/O (socket reads, disk, `time.sleep`) and — decisively for this field — it is released by well-written C extensions during long computations. NumPy releases it around BLAS calls; PyTorch releases it around kernel launches and ops; `cryptography`, `lxml`, Pillow, and compression libraries release it too. Therefore **threads genuinely parallelize numerical work** in Python, as long as the arithmetic happens below the C boundary. What threads cannot parallelize is pure-Python loops, JSON parsing in the stdlib, string munging, and Pydantic v1-style validation."},
      {"kind":"p","text":"(As of CPython 3.13 there is an experimental **free-threaded** build, PEP 703, which removes the GIL at some single-thread cost; 3.14 upgrades it to officially supported but still optional. **Sub-interpreters** with per-interpreter GILs, PEP 684/734, are the other escape hatch. Both are real and both are, in 2025, early for production ML serving — ecosystem C extensions must opt in.)"},
      {"kind":"p","text":"From this follows the standard taxonomy. **I/O-bound** work (waiting on network, disk, another service, a database) should use **asyncio**: thousands of concurrent waits on one thread, costing kilobytes each instead of megabytes-per-thread. **CPU-bound pure-Python** work should use **processes** (`multiprocessing`, `ProcessPoolExecutor`) to get true parallelism, paying serialization cost at the boundary. **CPU-bound native work** (NumPy, PyTorch, ONNX Runtime, tokenizers written in Rust) can use **threads**, because the GIL is released — and frequently should, because threads share the model's memory while processes would duplicate it."},
      {"kind":"p","text":"A fourth category dominates GPU serving: work that is neither CPU- nor IO-bound but **device-bound**. A GPU inference call is a kernel launch plus a wait. The launch is cheap and holds the GIL briefly; the wait, if the framework releases the GIL (PyTorch does), looks like I/O. The real constraint is that the GPU is a single serial resource with its own queue, so the correct pattern is almost always \"many concurrent request handlers feeding one serialized, batched GPU worker\" rather than \"many parallel GPU calls.\""},
    ],
  },
  {
    heading: "XI. asyncio in depth",
    blocks: [
      {"kind":"p","text":"An **event loop** is a single-threaded scheduler running an infinite cycle: ask the OS which file descriptors are ready (`epoll` on Linux, `kqueue` on BSD/macOS, IOCP on Windows), run the callbacks waiting on them, run any callbacks scheduled with `call_soon`, advance timers, repeat. **uvloop** replaces the default loop with a libuv-backed implementation that is typically two to four times faster on raw socket throughput."},
      {"kind":"p","text":"A **coroutine function** is declared `async def`; calling it returns a **coroutine object** that does nothing until awaited (a surprisingly common bug: forgetting `await` yields an un-awaited coroutine warning and silently skipped work). `await` suspends the current coroutine and returns control to the loop *at that point and only at that point*. This is **cooperative multitasking**: there is no preemption. Between two `await`s, your code is atomic with respect to other tasks on the same loop — which is a gift (far fewer data races than with threads) and a hazard (one blocking call stalls everything)."},
      {"kind":"p","text":"An **awaitable** is a coroutine, a **Future** (a placeholder for a result that will arrive), or any object with `__await__`. A **Task** is a Future that wraps a coroutine and schedules it on the loop — the unit of *concurrency*. `await coro()` runs the coroutine sequentially; `asyncio.create_task(coro())` starts it running concurrently and gives you a handle. Forgetting to keep a reference to a task lets the garbage collector eat it mid-flight; keep tasks in a set or, better, in a `TaskGroup`."},
      {"kind":"p","text":"**The cardinal sin is blocking the loop.** `time.sleep(1)`, `requests.get(...)`, a synchronous DB driver, a 300 ms `model.predict()` that does not release the GIL, `json.dumps` on a 50 MB payload, or a tight Python loop — any of these freezes *every* concurrent request on that worker, turning your p99 latency into a sawtooth. The remedies: use async-native libraries (`httpx`, `asyncpg`, `aioboto3`, `redis.asyncio`); offload with `await asyncio.to_thread(fn, *args)` or `loop.run_in_executor(pool, fn)`; or move the work to another process entirely. Enable `PYTHONASYNCIODEBUG=1` or `loop.set_debug(True)` in development — it warns on callbacks that take too long, which finds blocking calls you did not know you had."},
      {"kind":"p","text":"**Structured concurrency** (Python 3.11's `asyncio.TaskGroup`, or `anyio.create_task_group`, or Trio's nursery) says: child tasks may not outlive the block that created them. On exit, the group waits for all children; if one raises, the others are cancelled and the errors surface as an `ExceptionGroup`. This converts the hardest class of async bugs — orphaned tasks, swallowed exceptions, leaked work — into a scoping rule."},
      {"kind":"p","text":"**Cancellation** is the subtlest topic and the one that separates competent async code from production async code. `task.cancel()` arranges for `asyncio.CancelledError` to be raised inside the task *at its next suspension point*. Since 3.8, `CancelledError` derives from `BaseException`, specifically so that a careless `except Exception` does not swallow it. If you catch it for cleanup, re-raise it. Cleanup code that itself awaits must be written carefully, because a second cancellation can interrupt the cleanup; `asyncio.shield` protects a critical sub-operation. `async with asyncio.timeout(5):` (3.11+) is the modern deadline mechanism, implemented as cancellation with a marker so that the resulting error is correctly re-raised as `TimeoutError`. In a web service, cancellation is not hypothetical: when a client disconnects, the server cancels the handler, and your half-finished GPU batch, open DB transaction, and partially written cache entry all need a defined fate."},
      {"kind":"p","text":"Coordination primitives mirror the threading ones but are *not* interchangeable with them: `asyncio.Lock`, `Semaphore` (the standard concurrency limiter), `Event`, `Condition`, and `Queue` (the standard producer/consumer channel, and the backbone of batching). Use an `asyncio.Semaphore` to cap outbound calls to a flaky third-party model API; use an `asyncio.Queue` with a bounded `maxsize` to apply **backpressure** when work arrives faster than it can be served."},
      {"kind":"p","text":"`asyncio.gather` runs awaitables concurrently and returns results in order (with `return_exceptions=True` to collect rather than propagate); `asyncio.as_completed` yields them as they finish; `asyncio.wait` gives you fine-grained control over first-completed/first-exception semantics. Prefer `TaskGroup` when you want all-or-nothing semantics and `gather` when you want a simple fan-out of independent calls."},
      {"kind":"p","text":"**Async iteration** (`async for`, driven by `__aiter__`/`__anext__`) and **async generators** (`async def` containing `yield`) are how you stream. Async generators have a finalization caveat: if the consumer abandons them, cleanup runs at garbage-collection time via the loop's async-generator hooks, which may be too late for a held resource. `contextlib.aclosing` makes the shutdown explicit."},
      {"kind":"p","text":"Finally, **`contextvars`**. A `ContextVar` is like thread-local storage, but correct under asyncio: each Task gets a *copy* of the context at creation, so a request ID, tenant ID, auth principal, or OpenTelemetry span set in middleware is visible to everything downstream in that request, and invisible to concurrent requests. This is the proper mechanism for request-scoped ambient state; module-level globals are not, and will interleave catastrophically."},
    ],
    examples: [
      {"title":"Блок 1","code":"async with asyncio.TaskGroup() as tg:\n    emb = tg.create_task(embed(text))\n    meta = tg.create_task(fetch_metadata(doc_id))\n# both finished here; any failure cancelled the other and raised an ExceptionGroup","explanation":"Пояснение не заполнено."},
    ],
  },
  {
    heading: "XII. Threads and processes alongside the loop",
    blocks: [
      {"kind":"p","text":"Even an async service needs the other two models. `concurrent.futures` offers a uniform interface: `ThreadPoolExecutor` and `ProcessPoolExecutor` both return `Future` objects, and `loop.run_in_executor` bridges them into await-land. `asyncio.to_thread` is the ergonomic shorthand for the thread case. Under Starlette/FastAPI, this threadpool is actually AnyIO's, with a default capacity limiter of **40** threads — a number worth knowing, because if you run blocking endpoints, 41 concurrent requests queue."},
      {"kind":"p","text":"For processes, the **start method** matters enormously. `fork` (Linux default historically; 3.14 moves to `forkserver` as default on Linux) copies the parent's memory lazily via copy-on-write — fast and memory-efficient, but unsafe in a process holding locks, threads, or a **CUDA context**. Forking after CUDA initialization is a classic source of mysterious hangs and `CUDA error: initialization error`. `spawn` starts a fresh interpreter and re-imports your module (so your module must be import-safe and guarded by `if __name__ == \"__main__\":`), which is slow but correct. `forkserver` is the middle path. Anything crossing a process boundary must be **picklable**: no lambdas, no local classes, no open sockets, no CUDA tensors by value (use `torch.multiprocessing` with shared memory, or the CUDA IPC handles it arranges). `multiprocessing.shared_memory` and Arrow/Plasma-style buffers let you move large arrays without serialization."},
    ],
  },
  {
    heading: "XIII. ASGI and the anatomy of FastAPI",
    blocks: [
      {"kind":"p","text":"**WSGI** was Python's synchronous web interface: one callable, one request, one thread. **ASGI** is its asynchronous successor and its contract is beautifully small: an application is `async def app(scope, receive, send)`, where `scope` is a dict describing the connection, `receive` is an awaitable that yields incoming events, and `send` is an awaitable that emits outgoing events. This single shape covers HTTP, WebSockets, and the **lifespan** protocol (startup/shutdown messages), which is why the same server can stream an LLM response and hold a WebSocket open."},
      {"kind":"p","text":"**Uvicorn** is the usual ASGI server (with `httptools` and `uvloop` for speed); **Hypercorn** adds HTTP/2 and HTTP/3; **Granian** is a newer Rust-based option. In production you typically run multiple **worker processes** — either `uvicorn --workers N` or Gunicorn with `uvicorn.workers.UvicornWorker` — each a separate OS process with its own event loop, its own memory, and *its own copy of your model*. Hold that thought; it is the central deployment decision of Section XVI."},
      {"kind":"p","text":"**Starlette** is the toolkit underneath FastAPI: routing, requests/responses, middleware, background tasks, test client, WebSockets. **FastAPI** adds, on top, a type-driven layer: it introspects your handler's signature and annotations to derive where each parameter comes from (path, query, header, cookie, body, form, file, or dependency), validates and coerces it with Pydantic, serializes the response according to `response_model`, and emits an **OpenAPI** schema from which interactive docs (`/docs` Swagger UI, `/redoc`) and client SDKs are generated. The slogan to internalize: *in FastAPI, the type annotation is the configuration.*"},
      {"kind":"p","text":"The most consequential FastAPI behavior is the **sync/async dispatch rule**. If you declare a path operation (or dependency) with `async def`, it runs **on the event loop** — and if it blocks, it blocks everything. If you declare it with plain `def`, FastAPI runs it **in the AnyIO threadpool**, which keeps the loop responsive at the cost of thread overhead and that 40-slot limiter. Therefore: `async def` for handlers that only await async things; plain `def` for handlers that call blocking libraries; and *never* `async def` wrapped around a synchronous model call. The worst configuration in the wild is an `async def` endpoint that calls a blocking `model.predict()`; it serializes your entire worker behind every inference."},
      {"kind":"p","text":"**Middleware** comes in two forms. Pure ASGI middleware wraps the `(scope, receive, send)` callable and is cheap and fully streaming-compatible. Starlette's `BaseHTTPMiddleware` (what `@app.middleware(\"http\")` gives you) is friendlier but introduces a task and memory-stream per request and has historically had awkward interactions with streaming responses, background tasks, and exception propagation. For cross-cutting concerns in a high-throughput inference service — request IDs, timing, tracing, auth — prefer pure ASGI middleware, and remember that middleware ordering is outermost-first on the way in and reversed on the way out. `CORSMiddleware`, `GZipMiddleware`, and `TrustedHostMiddleware` are the common built-ins. Note that GZip plus streaming is a trap: compression buffers, defeating token-by-token delivery."},
      {"kind":"p","text":"**Exception handling**: FastAPI turns `HTTPException` into a structured response, returns `422` with a detailed body on request validation failure, and lets you register handlers with `@app.exception_handler(MyError)`. Map your domain exceptions to HTTP semantics in one place rather than sprinkling `try/except` through handlers — `ModelOverloaded → 503` with a `Retry-After`, `ModelTimeout → 504`, `InvalidPrompt → 400`."},
      {"kind":"p","text":"**Routers** (`APIRouter`) let you split a large API into modules with shared prefixes, tags, and dependencies. **Background tasks** (`BackgroundTasks`) run after the response is sent, in the same process — acceptable for logging a usage record, unacceptable for anything that must survive a deploy. Durable work belongs in a queue (Celery, Dramatiq, ARQ, RQ, Temporal) or a stream (Kafka, Redis Streams, SQS)."},
    ],
  },
  {
    heading: "XIV. Pydantic v2 and the validation boundary",
    blocks: [
      {"kind":"p","text":"**Pydantic v2** rewrote the validation core in Rust (`pydantic-core`), yielding order-of-magnitude speedups and making the validation boundary cheap enough to use liberally. A `BaseModel` subclass declares fields as annotations; constructing or calling `Model.model_validate(data)` parses and coerces input, raising `ValidationError` with a machine-readable list of failures. `model_dump()` and `model_dump_json()` serialize out, honoring aliases, exclusions, and field serializers. `Field(...)` supplies constraints and metadata (`gt`, `max_length`, `description`, `examples`, `alias`), and in modern style lives inside `Annotated`. `field_validator` and `model_validator` add custom logic (before/after modes); `ConfigDict` configures behavior such as `extra=\"forbid\"` (reject unknown keys — do this for request bodies), `frozen=True`, `strict=True` (no type coercion), and `from_attributes=True` (build from ORM objects). `TypeAdapter` applies the whole machinery to any type, not just models — handy for validating `list[MyThing]` or a bare `dict[str, float]`. **`pydantic-settings`** loads typed configuration from environment variables and `.env` files, which is the right way to manage model paths, batch sizes, and API keys."},
      {"kind":"p","text":"The design discipline: Pydantic models are your **contract**, not your domain model, and certainly not your tensor container. Validate request shape, size limits, and enumerations at the edge; convert to plain types immediately; keep NumPy and torch out of your schemas (or wrap them with custom serializers and base64/binary endpoints rather than JSON arrays, which are enormous and slow). For responses, `response_model` both documents and filters output — a genuine security feature, since it strips fields you forgot to remove."},
      {"kind":"p","text":"On serialization performance: stdlib `json` is slow. `orjson` (and `msgspec`) are several times faster and handle `datetime`, `UUID`, and NumPy natively; FastAPI ships `ORJSONResponse` for exactly this reason. For large numeric payloads, prefer binary: raw bytes, `safetensors`, Arrow IPC, Protobuf, or MessagePack. Base64-in-JSON inflates payloads by a third and costs CPU on both ends."},
    ],
  },
  {
    heading: "XV. Dependency injection and lifespan",
    blocks: [
      {"kind":"p","text":"FastAPI's **dependency injection** is a function-composition system driven by signatures. `Annotated[Thing, Depends(get_thing)]` tells FastAPI to call `get_thing` (resolving *its* dependencies first, recursively) and pass the result. Dependencies can be `async def` or `def` (same threadpool rule applies), can declare their own request parameters (so a dependency can read a header and do auth), and are **cached per request** by default, so the same dependency appearing in five places is computed once. `dependency_overrides` replaces any dependency in tests — the cleanest testing seam in the framework. Dependencies attached at the router or app level enforce cross-cutting policy such as authentication."},
      {"kind":"p","text":"A dependency that uses `yield` is a context manager in disguise: code before the `yield` is setup, the yielded value is injected, and code after runs as teardown, after the response is generated. This is the canonical way to manage a DB session, a tracing span, or a GPU semaphore slot per request."},
      {"kind":"p","text":"**Lifespan** is where expensive, process-wide resources are created exactly once:"},
      {"kind":"p","text":"Three details earn their keep here. Loading in a thread keeps the loop alive so health checks respond during startup. **Warmup** — running a dummy inference — forces lazy CUDA context creation, cuDNN autotuning, and `torch.compile` graph capture to happen before the first real user, avoiding a 30-second first-request cliff. And the readiness probe must return \"not ready\" until warmup finishes, so Kubernetes does not route traffic into a cold pod. `app.state` (or a module-level singleton accessed through a dependency) is the idiomatic home for these objects; the dependency wrapper is what makes them overridable in tests."},
    ],
    examples: [
      {"title":"Блок 2","code":"@asynccontextmanager\nasync def lifespan(app: FastAPI):\n    app.state.model = await asyncio.to_thread(load_model, settings.model_path)\n    await warmup(app.state.model)            # compile kernels, allocate KV cache\n    app.state.batcher = Batcher(app.state.model)\n    async with asyncio.TaskGroup() as tg:\n        tg.create_task(app.state.batcher.run())\n        yield                                 # serve traffic\n        app.state.batcher.stop()              # drain on shutdown","explanation":"Пояснение не заполнено."},
    ],
  },
  {
    heading: "XVI. Serving ML: process topology, batching, and the GPU",
    blocks: [
      {"kind":"p","text":"Here is where the rest of the document pays off."},
      {"kind":"p","text":"**Process topology.** Each uvicorn worker is a process with its own Python heap, its own event loop, and — if you load the model at startup — its own full copy of the weights plus its own CUDA context (several hundred MB of overhead each). Four workers on one GPU means four copies of a 7 B model, which will not fit, and four streams of uncoordinated kernel launches contending for the same SMs, which is slower than one. The rule: **for CPU-bound Python APIs, scale with workers; for GPU inference, use one process per GPU** (or one per model replica), and get concurrency *within* that process from asyncio plus batching. Set `CUDA_VISIBLE_DEVICES` per process when sharding across devices. If you must share a GPU among processes, look at MPS or MIG rather than hoping."},
      {"kind":"p","text":"**Where the inference actually runs.** Inside the single GPU process you have choices. If the framework releases the GIL (PyTorch does), you can call it from `asyncio.to_thread` and the loop stays responsive. But concurrent unbatched calls to one GPU do not help: the device serializes them anyway, and you pay per-call launch overhead on every one. The superior pattern is a **single consumer** that pulls from a queue and runs batches."},
      {"kind":"p","text":"**Dynamic batching** (also \"adaptive\" or \"server-side\" batching) is the central throughput technique. Requests arrive independently; a background task collects them for up to a few milliseconds or until a maximum batch size is reached, runs one forward pass, and scatters results back to the waiting coroutines. Because GPU kernels are massively parallel and launch overhead is fixed, a batch of 32 often costs barely more wall time than a batch of 1 — which is to say you traded a few milliseconds of latency for an order of magnitude of throughput."},
      {"kind":"p","text":"The vocabulary around this: **batch window** / **max delay**, **max batch size**, **padding waste** (batching variable-length sequences wastes compute on pad tokens; bucket by length to reduce it), **head-of-line blocking** (one huge request delaying many small ones; mitigate with separate queues or length-based routing), and **continuous batching** (also called iteration-level scheduling), the generative-LLM refinement in which the scheduler adds and retires sequences at *every decoding step* rather than every request, so a finished sequence frees its slot immediately. vLLM's **PagedAttention** complements this by managing the **KV cache** in fixed-size blocks like virtual memory pages, eliminating fragmentation and enabling prefix sharing."},
      {"kind":"p","text":"**Buy versus build.** For nontrivial LLM serving, the batching scheduler, KV cache manager, and CUDA graph capture are a research project, not a weekend. The professional move is to let a dedicated runtime — **vLLM**, **SGLang**, **TensorRT-LLM**, **TGI**, **Triton Inference Server**, **Ray Serve** — own the GPU, and let FastAPI be the thin, well-behaved front door that does auth, validation, rate limiting, routing, prompt assembly, retrieval, logging, and streaming relay. For embeddings, classical models, and small transformers, **ONNX Runtime**, **OpenVINO**, or plain `torch.compile` with your own batcher is entirely reasonable."},
      {"kind":"p","text":"**Related vocabulary you will meet**: `torch.inference_mode()` (stronger than `no_grad`, disables autograd bookkeeping and version counters), `eval()` mode (changes dropout/batchnorm behavior — forgetting it is a silent correctness bug), **quantization** (INT8, FP8, GPTQ, AWQ, bitsandbytes — trading precision for memory and speed), **mixed precision** (fp16/bf16), **CUDA graphs** (replay a captured launch sequence to kill per-kernel overhead), **pinned memory** and non-blocking host-to-device copies, **streams** (concurrent device work), and `torch.compile` (TorchDynamo + Inductor; it's a *compile*, so budget warmup time and beware recompilation on every new input shape — mark dynamic dimensions)."},
    ],
    examples: [
      {"title":"Блок 3","code":"class Batcher:\n    def __init__(self, model, max_batch=32, max_wait=0.005):\n        self.q: asyncio.Queue[tuple[Any, asyncio.Future]] = asyncio.Queue(maxsize=1000)\n        ...\n    async def submit(self, item):\n        fut = asyncio.get_running_loop().create_future()\n        await self.q.put((item, fut))        # bounded queue == backpressure\n        return await fut\n    async def run(self):\n        while True:\n            items, futs = await self._collect()           # wait up to max_wait\n            try:\n                outs = await asyncio.to_thread(self.model, items)   # GIL released\n                for f, o in zip(futs, outs):\n                    if not f.cancelled(): f.set_result(o)\n            except Exception as e:\n                for f in futs:\n                    if not f.cancelled(): f.set_exception(e)","explanation":"Пояснение не заполнено."},
    ],
  },
  {
    heading: "XVII. Streaming and long-running inference",
    blocks: [
      {"kind":"p","text":"LLM UX requires partial results. The transport is usually **Server-Sent Events** (SSE): a `text/event-stream` response where each chunk is `data: {...}\\n\\n`. FastAPI expresses this with `StreamingResponse` over an async generator, or with `sse-starlette` for the protocol details (event IDs, retry hints, keep-alive pings)."},
      {"kind":"p","text":"The operational details that bite: any proxy (nginx, ALB, Cloudflare) may **buffer** your stream into uselessness unless you disable buffering; gzip compression does the same; idle timeouts kill long generations unless you send periodic keep-alives; and **client disconnect must cancel the upstream generation**, or a user hitting Escape costs you a full GPU-seconds-worth of tokens nobody reads. For **WebSockets**, FastAPI gives you `WebSocket` with `accept`, `receive_*`, `send_*`; they are the right choice for bidirectional or multiplexed sessions (interactive agents, audio streaming), but they complicate load balancing and horizontal scaling because they are stateful and sticky."},
      {"kind":"p","text":"For jobs too long for any HTTP timeout — fine-tuning, batch scoring, video processing — do not stream; use the **async job pattern**: `POST /jobs` returns `202 Accepted` with a job ID, work happens in a separate worker process pulling from a durable queue, and the client polls `GET /jobs/{id}` or receives a webhook. Include an **idempotency key** so retries do not duplicate expensive work."},
    ],
    examples: [
      {"title":"Блок 4","code":"@app.post(\"/chat\")\nasync def chat(req: ChatRequest, request: Request):\n    async def gen():\n        async for token in engine.stream(req.prompt):\n            if await request.is_disconnected():\n                break                      # stop paying for abandoned work\n            yield f\"data: {json.dumps({'t': token})}\\n\\n\"\n        yield \"data: [DONE]\\n\\n\"\n    return StreamingResponse(gen(), media_type=\"text/event-stream\",\n                             headers={\"Cache-Control\": \"no-cache\",\n                                      \"X-Accel-Buffering\": \"no\"})","explanation":"Пояснение не заполнено."},
    ],
  },
  {
    heading: "XVIII. Backpressure, capacity, and queueing vocabulary",
    blocks: [
      {"kind":"p","text":"Asyncio makes it trivially easy to accept more work than you can perform; the symptom is an unbounded queue, climbing memory, and latency that grows without bound while throughput stays flat. **Backpressure** is the discipline of refusing or slowing intake: bounded `asyncio.Queue`s, a `Semaphore` capping in-flight inferences, uvicorn's `--limit-concurrency`, a `503` with `Retry-After` when the queue is deep, and **load shedding** — deliberately dropping requests whose deadline has already passed rather than computing answers nobody will receive."},
      {"kind":"p","text":"**Little's Law** (L = λW) is the capacity-planning tool: average concurrency equals arrival rate times average latency. If each inference takes 200 ms and you want 100 requests/second, you need 20 concurrent inference slots. Combined with measured per-batch throughput, this tells you how many replicas you need before you deploy, rather than after the incident. Know the difference between **latency** and **throughput**, between **mean** and **tail** (**p95/p99**) latency — tails are what users experience and what retries amplify — and between **time to first token (TTFT)** and **inter-token latency (ITL)**, the two numbers that actually define generative UX."},
      {"kind":"p","text":"Related resilience vocabulary: **timeouts** on every outbound call without exception; **retries** with exponential backoff and **jitter**, and only for idempotent operations; the **circuit breaker** that stops hammering a dead dependency; the **bulkhead** that isolates resource pools so one slow dependency cannot consume all your concurrency; **graceful degradation** (fall back to a smaller model, a cached answer, or a clear error)."},
    ],
  },
  {
    heading: "XIX. Observability",
    blocks: [
      {"kind":"p","text":"You cannot operate what you cannot see, and async plus GPU makes naive debugging useless. Three pillars."},
      {"kind":"p","text":"**Logs** should be structured (JSON) and emitted through `logging` with a library like `structlog`; attach a correlation/request ID from a `ContextVar` set in middleware so one request's journey is greppable across modules and services. Log *decisions and boundaries* — batch sizes, queue depths, model version, cache hits, truncation events — not every line of control flow. Never log raw prompts or PII without a redaction policy."},
      {"kind":"p","text":"**Metrics**, via `prometheus-client` and an ASGI exporter, are the time series you alert on: request rate, error rate by class, latency histograms (not averages), queue depth, batch size distribution, GPU utilization and memory, model version in use, tokens per second, cache hit ratio. The RED method (Rate, Errors, Duration) for services and USE (Utilization, Saturation, Errors) for resources are the standard framings."},
      {"kind":"p","text":"**Traces**, via **OpenTelemetry**, stitch the span tree across async boundaries using `contextvars` — auto-instrumentation exists for FastAPI, httpx, SQLAlchemy, and Redis. A trace showing 12 ms of HTTP handling, 4 ms of validation, 180 ms queued, and 40 ms on GPU tells you instantly which lever to pull; without it you will optimize the wrong thing. For ML specifically, add **evaluation telemetry** — output length, refusal rate, guardrail triggers, user feedback, drift metrics on input distributions — because a model service can be perfectly healthy by infrastructure metrics while producing garbage."},
      {"kind":"p","text":"**Probes**: a *liveness* probe answers \"should I be restarted?\" and must not depend on the model; a *readiness* probe answers \"should I receive traffic?\" and must depend on model warmup, queue health, and downstream availability. Conflating them produces restart loops during heavy load."},
    ],
  },
  {
    heading: "XX. Performance engineering and the C boundary",
    blocks: [
      {"kind":"p","text":"Measure first. `cProfile` for deterministic profiling of CPU-bound sync code; **py-spy** for sampling a *running production process* without restarting it (including `py-spy dump` for a stack trace of a hung service — invaluable when asyncio deadlocks); **scalene** for CPU/GPU/memory with Python-vs-native attribution; **memray** for allocation tracking and leak hunting; `tracemalloc` as a stdlib fallback; and the PyTorch profiler or Nsight Systems when the bottleneck is below the CUDA boundary. For async, enable debug mode to catch slow callbacks, and instrument queue wait time separately from service time — in almost every slow ML service, the time is in the queue, not the model."},
      {"kind":"p","text":"The optimization hierarchy, in order of return on effort: fix the algorithm or the architecture (batch, cache, avoid the call entirely); move the hot loop below the C boundary (vectorize with NumPy, use a Rust tokenizer, use `orjson`); eliminate copies (buffer protocol, `memoryview`, preallocated output arrays, pinned memory); cache aggressively at the right layer (`functools.cache` for pure functions, Redis for cross-process, prefix/KV caching for LLMs, embedding caches keyed by content hash); then, and only then, rewrite in a faster language. For that last step the vocabulary is **Cython**, **Numba** (JIT for numeric loops), **PyO3/maturin** (Rust extensions — now the default choice for new native code), and `ctypes`/`cffi` for calling existing shared libraries. Note also that native thread pools interact badly with process-level parallelism: set `OMP_NUM_THREADS` / `torch.set_num_threads` deliberately, or N workers × M OpenMP threads will oversubscribe your cores and run slower than one."},
    ],
  },
  {
    heading: "XXI. Testing, reproducibility, packaging, deployment",
    blocks: [
      {"kind":"p","text":"**pytest** is the standard: plain `assert` with rich introspection, **fixtures** for composable setup/teardown (with `function`/`module`/`session` scopes), `parametrize` for table-driven tests, `monkeypatch` for surgical patching, and markers for selection. For async, `pytest-asyncio` or the `anyio` plugin lets you write `async def` tests. Test a FastAPI app either with Starlette's synchronous `TestClient` (which runs the loop in a background portal) or, preferably for async code, with `httpx.AsyncClient(transport=ASGITransport(app=app))`, which exercises the app in-process without a network socket. Use `dependency_overrides` to substitute a fake model — your test suite must not load real weights, or nobody will run it."},
      {"kind":"p","text":"ML adds test categories that classical software lacks: **golden/characterization tests** (pin the output of a fixed input so refactors cannot silently change behavior), **invariance and metamorphic tests** (paraphrase shouldn't flip the label; batching must not change per-item results — a surprisingly effective bug detector for padding and masking errors), **shape and dtype contracts**, **schema contract tests** against the OpenAPI document, and **evaluation suites** with thresholds rather than exact assertions. **Hypothesis** brings property-based testing: generate inputs, shrink failures, find the empty string and the 10,000-token prompt you forgot."},
      {"kind":"p","text":"**Reproducibility** is a first-class engineering concern: pin dependencies with a lockfile and hashes; seed `random`, `numpy`, and `torch`; know that full GPU determinism requires deterministic algorithms and often costs speed, and that floating-point reductions are order-dependent so bit-exactness across batch sizes or hardware is generally unachievable — assert within tolerances. Version your **model artifacts** alongside your code (model registry, content hashes, `safetensors` files in object storage) and expose the active version in both responses and metrics, because \"which model produced this answer?\" is the first question of every incident."},
      {"kind":"p","text":"**Deployment**: multi-stage Docker builds, with dependency installation in a cached layer *before* copying source, so code changes do not reinstall PyTorch; slim or distroless runtime bases; non-root users; an explicit `CMD` running uvicorn with the right worker count; `SIGTERM` handling so the ASGI server stops accepting, drains in-flight requests, and exits within the orchestrator's grace period (`--timeout-graceful-shutdown`, and a `preStop` sleep to let load balancers deregister). Twelve-factor configuration via environment variables parsed by `pydantic-settings`. Resource requests and limits set with knowledge that CUDA contexts, model weights, and the KV cache all live in GPU memory while tokenizers, request buffers, and Python objects live in host memory. Autoscale on queue depth or concurrency, not CPU utilization — a GPU service pegged at 100% GPU may show 8% CPU."},
    ],
  },
  {
    heading: "XXII. Security at the ML boundary",
    blocks: [
      {"kind":"p","text":"**Never unpickle untrusted data.** `pickle` executes arbitrary code during load, and a PyTorch `.pt` checkpoint from the internet is a pickle; use `safetensors` or `weights_only=True` loading, and verify provenance and hashes of every artifact. Enforce **request size limits** and token-count limits before you touch a model, or a single 10 MB prompt will exhaust your KV cache. Validate strictly (`extra=\"forbid\"`), and never interpolate user input into shell commands, SQL, file paths, or URLs — the last of which is **SSRF**, especially relevant when your service fetches user-supplied image or document URLs. Keep secrets out of code, out of logs, and out of error responses; disable verbose tracebacks in production; and remember that `response_model` filtering is a defense against leaking internal fields. Rate limit per API key, apply quotas and cost accounting per tenant, and authenticate with short-lived tokens. For LLM endpoints specifically, treat model output as untrusted input to anything downstream — **prompt injection** means the model can be made to emit whatever an attacker put in a retrieved document, so never let raw model output directly execute tools, SQL, or code without validation and sandboxing."},
    ],
  },
  {
    heading: "XXIII. Synthesis: the mental models worth keeping",
    blocks: [
      {"kind":"p","text":"**Names point at objects.** Mutability plus aliasing explains most \"impossible\" bugs in data pipelines."},
      {"kind":"p","text":"**Python coordinates; C and CUDA compute.** Optimize by moving work across that boundary or eliminating trips across it, not by micro-tuning loops."},
      {"kind":"p","text":"**The GIL serializes interpreter work, not all work.** Threads are useless for pure-Python CPU loops and genuinely useful for native numeric work. Processes buy parallelism at the cost of memory and serialization. The event loop buys cheap waiting."},
      {"kind":"p","text":"**There is one event loop per worker, and it is a shared resource.** Every `await` is a yield point; every blocking call between yield points is a stop-the-world pause for all concurrent requests. The question \"does this function block?\" is the single most important question in an async code review."},
      {"kind":"p","text":"**Concurrency is not parallelism.** Asyncio gives you ten thousand concurrent *waits*; it does not give you two simultaneous matrix multiplications."},
      {"kind":"p","text":"**The GPU is a serial, batch-loving resource behind a queue.** Design for one owner, deep queues with bounded depth, and batching that trades a few milliseconds of latency for an order of magnitude of throughput."},
      {"kind":"p","text":"**Types are the configuration.** In FastAPI and Pydantic, annotations drive validation, serialization, documentation, and injection — so invest in them the way you would invest in an interface definition."},
      {"kind":"p","text":"**Validate at the edge, trust the interior, cancel aggressively, bound every queue, time out every call, and measure the queue separately from the model.** Those six habits distinguish an inference service that survives its first viral day from one that does not."},
    ],
  },
  {
    heading: "XXIV. A compact lexicon",
    blocks: [
      {"kind":"p","text":"*Object, name/binding, identity vs equality, mutability, hashability, reference counting, cycle GC, `__slots__`. LEGB, closure, module, package, `sys.modules`, virtualenv, wheel, sdist, lockfile, extras. First-class function, decorator, `functools.wraps`, `partial`, `lru_cache`, `singledispatch`. Dunder/data model, duck typing, ABC, Protocol, descriptor, metaclass, context manager. List/dict/set/deque/heap, buffer protocol, memoryview, zero-copy, pickle protocol 5, out-of-band buffers. Dataclass, NamedTuple, Pydantic model, TypeAdapter, `model_validate`, `model_dump`, `ConfigDict`, `Field`, `field_validator`, pydantic-settings. Gradual typing, `Annotated`, `TypeVar`, `ParamSpec`, `Literal`, `TypedDict`, `Self`, variance, mypy/pyright. Iterable, iterator, generator, `yield from`, lazy pipeline, `itertools.batched`. EAFP, exception chaining, `ExceptionGroup`, `except*`, `ExitStack`. GIL, free-threading (PEP 703), sub-interpreters (PEP 734), CPU-bound vs I/O-bound vs device-bound, ThreadPoolExecutor, ProcessPoolExecutor, fork/spawn/forkserver, copy-on-write, shared memory. Event loop, uvloop, coroutine, awaitable, Future, Task, `create_task`, `gather`, `as_completed`, `TaskGroup`, structured concurrency, `CancelledError`, `shield`, `asyncio.timeout`, `to_thread`, `run_in_executor`, `asyncio.Queue`, Semaphore, backpressure, async generator, `aclosing`, `contextvars`, AnyIO, capacity limiter. ASGI, scope/receive/send, lifespan, uvicorn, worker, Starlette, FastAPI, path operation, `Depends`, dependency cache, `yield` dependency, `dependency_overrides`, `app.state`, APIRouter, middleware (ASGI vs BaseHTTP), `response_model`, `HTTPException`, OpenAPI, `StreamingResponse`, SSE, WebSocket, BackgroundTasks, ORJSONResponse. Warmup, dynamic batching, batch window, padding waste, head-of-line blocking, continuous batching, iteration-level scheduling, KV cache, PagedAttention, prefix caching, TTFT, ITL, quantization, mixed precision, CUDA graph, `torch.compile`, `inference_mode`, safetensors, ONNX Runtime, Triton, vLLM, Ray Serve. Little's Law, p99, load shedding, circuit breaker, bulkhead, idempotency key, graceful shutdown, liveness vs readiness. py-spy, memray, scalene, OpenTelemetry, structlog, Prometheus, RED/USE. pytest fixtures, `ASGITransport`, golden test, metamorphic test, Hypothesis, seeding, determinism, model registry.*"},
      {"kind":"p","text":"Learn these words and the architecture mostly writes itself: a thin, fully-async, strictly-typed HTTP layer that validates fast, refuses politely, cancels honestly, and feeds a single, well-fed, carefully-measured accelerator."},
    ],
  },
];;
