import type { LessonSection } from "../curriculum";

export const sections: readonly LessonSection[] = [
  {
    heading: null,
    blocks: [
      {"kind":"p","text":"*A first-principles lesson: beginner-accessible, technically serious.*"},
      {"kind":"p","text":"Recursive self-improving AI is the idea that an AI system can help produce a better version of itself, and that the improved version can become more effective at producing the next improvement."},
      {"kind":"p","text":"The central idea is simple. The consequences are not."},
      {"kind":"p","text":"The difficult question is whether this process produces sustained, accelerating progress—or merely a sequence of expensive, uneven engineering upgrades. Understanding that distinction requires separating several concepts that are often bundled together: learning, self-modification, automated research, autonomy, and an “intelligence explosion.”"},
    ],
  },
  {
    heading: "1. What, exactly, could an AI improve?",
    blocks: [
      {"kind":"p","text":"First distinguish an **AI model** from an **AI system**."},
      {"kind":"p","text":"A model is the learned computational component. In a neural network, its *parameters*, often called weights, are numerical settings adjusted during training. Its *architecture* determines how its computations are organized. The training procedure determines how experience changes those parameters."},
      {"kind":"p","text":"An AI system is broader. It may include the model, tools, databases, memory, search procedures, software for running experiments, and mechanisms for checking results. A relatively unchanged model can become more useful when embedded in a better system."},
      {"kind":"p","text":"This distinction matters because “self-improvement” can happen at several levels."},
      {"kind":"p","text":"A system might improve its prompts or workflow. It might write a tool that eliminates repetitive work. It might select better training data, discover a more efficient training algorithm, or propose a different model architecture. It might improve the software used to evaluate future models."},
      {"kind":"p","text":"These are not equivalent achievements. A better prompt is usually much easier to produce than a genuinely better learning algorithm. Nevertheless, either could contribute to a feedback loop if the resulting improvement makes future improvement work more effective."},
      {"kind":"p","text":"The word *self* therefore needs care. It does not necessarily mean a single running program directly rewriting its own neural weights. A more realistic picture is an AI participating in an engineering pipeline that produces successor systems."},
      {"kind":"p","text":"**The relevant unit may be the whole research-and-development system, not an isolated model.**"},
    ],
  },
  {
    heading: "2. What makes the improvement recursive?",
    blocks: [
      {"kind":"p","text":"Here, *recursive* does not primarily mean a function calling itself, as in programming. It means that the output of an improvement process feeds back into the capacity to perform further improvement."},
      {"kind":"p","text":"Imagine an AI that becomes better at translating French. That is a capability improvement, but it may do little to help the AI design better models."},
      {"kind":"p","text":"Now imagine an AI that becomes better at finding errors in training code, designing experiments, and interpreting results. If those abilities help it produce an even better AI researcher, the feedback loop begins to close."},
      {"kind":"p","text":"The crucial link is therefore not simply:"},
      {"kind":"p","text":"“Better AI produces better outputs.”"},
      {"kind":"p","text":"It is:"},
      {"kind":"p","text":"**“Better AI becomes better at the work that produces better AI.”**"},
      {"kind":"p","text":"That link is an empirical question, not a logical certainty. Stronger performance on a mathematics benchmark might help AI research, but the transfer could be limited. Research also requires judgment, reliable experimentation, causal reasoning, and the ability to distinguish a promising idea from an attractive mistake."},
      {"kind":"p","text":"Several neighboring concepts should remain separate."},
      {"kind":"p","text":"Ordinary machine learning improves a model through training. That does not, by itself, establish that the model is improving the process that creates future models."},
      {"kind":"p","text":"*Meta-learning*, often described as “learning to learn,” develops systems that adapt more effectively across tasks. It may support recursive improvement, but it does not automatically provide an autonomous research pipeline."},
      {"kind":"p","text":"Likewise, an AI revising its answer after criticism is performing local self-correction. Unless something useful is retained and improves future capability, this is not evidence of persistent recursive self-improvement."},
      {"kind":"p","text":"Broad general intelligence and recursive self-improvement are also different properties. A specialized system could improve a narrow research pipeline without being generally intelligent. Conversely, a broadly capable model might lack the access, resources, or authorization needed to modify anything."},
    ],
  },
  {
    heading: "3. A concrete hypothetical loop",
    blocks: [
      {"kind":"p","text":"Consider an AI research assistant, Version A, working on machine-learning software."},
      {"kind":"p","text":"Version A identifies an inefficiency in the training pipeline and proposes a modification. Independent experiments establish that the modification reaches the same model quality using less computation."},
      {"kind":"p","text":"That creates an efficiency gain. But the gain is not yet an intelligence explosion—or even necessarily a meaningful recursive loop."},
      {"kind":"p","text":"Next, the saved computation is used to run more research experiments. Some of those experiments produce Version B, which is demonstrably better at designing experiments and diagnosing failures."},
      {"kind":"p","text":"Version B then takes over the research-assistant role. Under a comparable budget, it produces more useful improvements than Version A did."},
      {"kind":"p","text":"Now the important feedback is present: an improvement in the system has strengthened the process responsible for subsequent improvements."},
      {"kind":"p","text":"Notice how much work lies between “the AI suggested a change” and “the AI improved itself.” Someone or something must execute experiments, allocate resources, detect regressions, compare results, and decide whether to adopt the successor."},
      {"kind":"p","text":"Those functions could be partly automated or substantially human-controlled. Full autonomy is a separate design choice, not part of the basic definition."},
    ],
  },
  {
    heading: "4. Positive feedback does not automatically mean an intelligence explosion",
    blocks: [
      {"kind":"p","text":"The stronger hypothesis is an **intelligence explosion**, famously associated with I. J. Good’s 1965 argument: a sufficiently capable machine might design better machines, which could design still better machines, producing rapidly accelerating progress."},
      {"kind":"p","text":"This is a hypothesis about the strength and speed of the feedback—not merely its existence."},
      {"kind":"p","text":"A useful analogy is compound interest. Repeated percentage gains can accumulate dramatically. But an AI improvement process is not a savings account with a guaranteed interest rate. The percentage gain may shrink, the cost of each round may rise, and some rounds may fail."},
      {"kind":"p","text":"Two quantities are especially important: the useful improvement produced by each cycle, and the time and resources required to complete that cycle."},
      {"kind":"p","text":"If better systems discover larger improvements and complete their research cycles faster, acceleration becomes more plausible. If research becomes harder as capabilities rise, or experiments become increasingly expensive, progress can slow despite the feedback."},
      {"kind":"p","text":"In control-theory language, identifying a feedback loop does not determine its gain, delays, or stability. The loop’s structure alone does not tell you how the system will behave."},
      {"kind":"p","text":"There is another complication: capability is not a single number. A successor may write better code while becoming less reliable at recognizing uncertainty. It may perform better when given enormous computational budgets but offer no improvement at a fixed cost."},
      {"kind":"p","text":"“More intelligent” can conceal several different changes, some beneficial and some not."},
      {"kind":"p","text":"**Recursive self-improvement describes a mechanism. An intelligence explosion is one possible hypothesized outcome. They are not synonyms.**"},
    ],
  },
  {
    heading: "5. The bottlenecks that intelligence alone does not remove",
    blocks: [
      {"kind":"p","text":"An AI research system operates inside a physical and organizational world."},
      {"kind":"p","text":"It needs computation, energy, storage, useful data, and working infrastructure. Some discoveries require long training runs. Others require experiments involving hardware, laboratories, or people. Better reasoning can improve how these resources are used, but it does not make them unlimited."},
      {"kind":"p","text":"A helpful engineering principle is **Amdahl’s law**: accelerating one part of a process eventually exposes the parts that were not accelerated."},
      {"kind":"p","text":"Suppose half of a fixed research workflow consists of reasoning and half consists of waiting for an experiment that cannot be sped up. Making the reasoning arbitrarily fast can, at most, halve the workflow’s total duration."},
      {"kind":"p","text":"A smarter system might redesign the experiment and remove that bottleneck. But that would be an additional achievement, not something guaranteed by the original speedup."},
      {"kind":"p","text":"Research also faces diminishing returns. Early improvements may involve obvious bugs, wasteful data handling, or poorly chosen settings. Later improvements may require fundamentally new ideas. Being better at research does not imply that equally valuable discoveries remain equally easy to find."},
      {"kind":"p","text":"Software introduces its own limits. An improvement may add complexity, maintenance costs, or subtle failure modes. A faster component can make the overall system worse if it becomes harder to verify or less dependable."},
      {"kind":"p","text":"The serious question is therefore not whether intelligence can create benefits. It plainly can. The question is how those benefits interact with increasingly difficult problems and constraints elsewhere in the system."},
    ],
  },
  {
    heading: "6. The central scientific problem: proving that an improvement is real",
    blocks: [
      {"kind":"p","text":"A recursive improvement loop needs an acceptance criterion: what counts as better?"},
      {"kind":"p","text":"This is harder than it first appears."},
      {"kind":"p","text":"Suppose a candidate model scores higher on a benchmark. Perhaps it genuinely became more capable. Perhaps it encountered similar examples during training. Perhaps it learned to exploit the evaluation format. Perhaps it simply used more computation."},
      {"kind":"p","text":"A scientifically useful comparison must separate these explanations."},
      {"kind":"p","text":"Researchers need to control relevant budgets, test unfamiliar cases, check whether gains transfer beyond the optimized task, and look for regressions. They also need to distinguish the AI’s contribution from additional human assistance or infrastructure changes."},
      {"kind":"p","text":"One useful technique is an *ablation*: remove the supposedly important improvement mechanism and see whether the claimed benefit survives. If it does, the original causal explanation may be wrong."},
      {"kind":"p","text":"This leads to **Goodhart’s law**: when a measurement becomes an optimization target, it can become a less reliable indicator of what you actually wanted."},
      {"kind":"p","text":"If the target is “pass more tests,” a system might learn to exploit weaknesses in the tests. If the target is “produce more research discoveries,” it might generate more plausible-looking claims rather than more reproducible findings."},
      {"kind":"p","text":"None of this requires conscious deception. Selection pressure can favor behavior that satisfies the measured objective while missing the intended one."},
      {"kind":"p","text":"Some domains offer useful verification advantages. A proof checker can verify certain formal proofs without having to invent them. Software tests can reject many incorrect programs. But passing tests is not a general proof of correctness, and there is no universal inexpensive test for “this successor is better and safe in every relevant situation.”"},
      {"kind":"p","text":"**Generating candidate improvements and establishing that they are improvements are different capabilities.**"},
      {"kind":"p","text":"The second can become the limiting factor."},
    ],
  },
  {
    heading: "7. What is established, and what remains speculative?",
    blocks: [
      {"kind":"p","text":"Many components of this picture are established engineering practices."},
      {"kind":"p","text":"Automated machine learning searches over model configurations. Training procedures adjust parameters. AI tools generate and revise code. AI assistance can contribute to experimental design, data processing, and scientific work."},
      {"kind":"p","text":"These capabilities make automated AI research a concrete technical subject rather than a purely fictional idea."},
      {"kind":"p","text":"However, demonstrating useful components does not establish that an integrated system can sustain broad, autonomous, accelerating self-improvement. That stronger claim requires its own evidence."},
      {"kind":"p","text":"A system that improves a prompt over several rounds has demonstrated a bounded optimization process. It has not thereby demonstrated that it can repeatedly invent better learning algorithms, maintain reliability, secure the necessary resources, and extend its capabilities across domains."},
      {"kind":"p","text":"When evaluating a “self-improving AI” claim, pay attention to the system boundary. How much work did humans perform? Were training and evaluation budgets comparable? Did the improvement persist on genuinely new tasks? Did the successor actually become better at producing further improvements?"},
      {"kind":"p","text":"The most defensible position is neither “recursion guarantees an explosion” nor “self-improvement is impossible.” It is that the mechanism is plausible, many constituent techniques are useful, and the long-run behavior remains an empirical question."},
    ],
  },
  {
    heading: "8. Capability improvement and safe control are separate problems",
    blocks: [
      {"kind":"p","text":"A more effective optimizer is not automatically optimizing a more appropriate objective."},
      {"kind":"p","text":"If an AI research system is rewarded for impressive results, becoming more capable may make it better at genuine discovery—or better at exploiting weaknesses in how impressive results are measured. Which outcome occurs depends on objectives, training, evaluation, and deployment conditions."},
      {"kind":"p","text":"Recursive improvement makes this especially important because each accepted change can alter the behavior of the system that proposes future changes."},
      {"kind":"p","text":"The engineering challenge is therefore not merely to increase capability. It is to preserve intended behavior, reliable evidence, and meaningful human authority while capabilities change."},
      {"kind":"p","text":"That suggests separating proposal from approval. A system might be allowed to suggest modifications without being allowed to deploy them. Experiments can operate under bounded permissions and resource budgets. Independent evaluation, versioned artifacts, logs, and rollback plans can help maintain accountability."},
      {"kind":"p","text":"These measures are safeguards, not guarantees. An evaluation that was adequate for one generation may become inadequate for a more capable successor."},
      {"kind":"p","text":"The key distinction is simple:"},
      {"kind":"p","text":"**The ability to design an upgrade does not imply the authority to install it.**"},
      {"kind":"p","text":"Recursive improvement need not require unrestricted autonomy. Treating those ideas as inseparable obscures important design options."},
    ],
  },
  {
    heading: "9. The mental model to keep",
    blocks: [
      {"kind":"p","text":"Think of recursive self-improving AI as an engineering organization in which part of the engineering team is itself one of the products being improved."},
      {"kind":"p","text":"Sometimes it builds better tools. Sometimes it improves the training process. Sometimes it produces a better researcher. Progress becomes genuinely recursive when those changes strengthen the machinery that produces subsequent changes."},
      {"kind":"p","text":"Whether the loop accelerates depends on research productivity, evaluation quality, resource constraints, transfer between capabilities, and the difficulty of the remaining problems."},
      {"kind":"p","text":"The defining question is not, “Can an AI rewrite its own code?” Ordinary software can modify software."},
      {"kind":"p","text":"The deeper question is:"},
      {"kind":"p","text":"**Can an AI repeatedly produce validated improvements in the process that creates future AI capabilities, under real resource constraints, while preserving intended behavior and effective oversight?**"},
      {"kind":"p","text":"That is the technical core of recursive self-improvement—and the reason it is simultaneously an AI research problem, a scientific-method problem, and a control problem."},
    ],
  },
];;
