import type { LessonSection } from "../curriculum";

export const sections: readonly LessonSection[] = [
  {
    heading: "Before We Begin: Three Assumptions Worth Questioning",
    blocks: [
      {"kind":"p","text":"**Assumption 1: \"Safdie films are chaotic and improvised.\"** They feel improvised, but the chaos is engineered. The scripts, co-written with Ronald Bronstein, are dense and heavily rehearsed. The overlapping dialogue is often choreographed, and the edits are meticulous. The looseness is a manufactured effect, not a working method. This matters because it moves the achievement from \"capturing reality\" to \"constructing a sensation of reality.\""},
      {"kind":"p","text":"**Assumption 2: \"Josh Safdie is an auteur.\"** Most of the celebrated work (*Good Time*, *Uncut Gems*) was made with his brother Benny, co-written and edited by Bronstein, scored by Daniel Lopatin (Oneohtrix Point Never), and shot by cinematographers like Sean Price Williams and Darius Khondji. The brothers' creative split around 2023–24 lets us finally test what belongs to Josh alone. *Marty Supreme* (2025) is the first major data point, and one film is a small sample."},
      {"kind":"p","text":"**Assumption 3: \"The films are about anxiety.\"** Anxiety is the effect on the viewer. It is not necessarily the subject. A credible alternative reading holds that the subject is *devotion*: characters so committed to a belief (a score, a bet, a brother, a destiny) that the commitment becomes quasi-religious. On this view, the anxiety you feel is the texture of faith under pressure."},
      {"kind":"p","text":"**The alternative lens I'll carry throughout:** read Josh Safdie less as a lone visionary than as the organizing center of a *collaborative system*, something like a small studio with a house style. I'll also read his films less as indie realism and more as *genre cinema* (heist, sports, crime) disguised in realist clothing."},
    ],
  },
  {
    heading: "The Lesson",
    blocks: [
      {"kind":"p","text":"**I. Who He Is, Briefly**"},
      {"kind":"p","text":"Josh Safdie was born in 1984 and raised between Manhattan and Queens by divorced parents. His early films came out of a DIY New York scene. *The Pleasure of Being Robbed* (2008) was a solo effort. *Daddy Longlegs* (2009), made with Benny, was a barely disguised portrait of their own erratic, loving father. From the start the work was autobiographical, small-scale, and fascinated with people who cannot stop moving."},
      {"kind":"p","text":"The trajectory from there is useful to know. There was the documentary *Lenny Cooke* (2013), about a basketball prodigy who never made the NBA. Then came *Heaven Knows What* (2014), starring Arielle Holmes and adapted from her own memoir of heroin addiction on the Upper West Side. Then the breakthrough, *Good Time* (2017), with Robert Pattinson, which premiered in competition at Cannes. Then *Uncut Gems* (2019), with Adam Sandler, the film that made \"Safdie\" an adjective. After the brothers went separate ways, Josh made *Marty Supreme* (2025), with Timothée Chalamet as a 1950s table-tennis hustler."},
      {"kind":"p","text":"**II. The Core Concept: The Compulsion Engine**"},
      {"kind":"p","text":"If you remember one idea, remember this: **a Safdie film is structured like an addiction.**"},
      {"kind":"p","text":"The protagonist wants something: money, freedom, a win. Each attempt to get it creates a new debt, which demands a bigger attempt, which creates a bigger debt. Howard Ratner in *Uncut Gems* doesn't just gamble. He *restructures his whole life as a bet* that keeps doubling. Connie Nikas in *Good Time* spends a single night compounding one mistake, a botched robbery that lands his brother in custody, into a cascade of worse ones."},
      {"kind":"p","text":"In classical screenwriting, a protagonist faces escalating obstacles from outside. In the Safdie model, the protagonist *is* the obstacle generator. Narrative momentum comes from a psychological loop, not from external plot machinery. This is why the films feel propulsive rather than suspenseful. You aren't waiting to see what happens *to* the character. You're watching him do it *to himself*, and you can't look away. The film puts you inside the same compulsion it depicts."},
      {"kind":"p","text":"For the geeks, there's a rich overlap here with behavioral economics. The characters embody loss-chasing and the sunk-cost fallacy, and the films' rhythm mirrors a variable-ratio reward schedule, the same pattern that makes slot machines addictive. Small wins keep arriving, just often enough."},
      {"kind":"p","text":"**III. Form: How the Anxiety Is Built**"},
      {"kind":"p","text":"The feeling is manufactured through specific, identifiable techniques."},
      {"kind":"p","text":"**Telephoto lenses and compressed space.** A telephoto lens is a long lens that shoots from far away. It flattens depth, so background and foreground seem crushed together. The Safdies use it constantly, often shooting faces in tight close-up from a distance on real city streets. The effect is claustrophobic *and* voyeuristic. We're jammed against the characters, yet we're also watching them like surveillance footage. There's no breathing room in the frame, because there's none in their lives."},
      {"kind":"p","text":"**Dense, overlapping sound.** Dialogue collides. Several people talk at once, phones ring, and ambient city noise refuses to politely recede. Classical sound mixing organizes a hierarchy of what matters. Safdie mixing *flattens* the hierarchy, much as the lenses flatten space. You must work to follow the scene, and that effort is itself a form of stress."},
      {"kind":"p","text":"**Lopatin's synth scores.** Daniel Lopatin's music draws on 1980s electronic scores, the kind associated with Tangerine Dream, but it often plays *against* the grime of the images. The music can be cosmic, even spiritual, while the action is sordid. That tension is the \"devotion\" reading in audible form. The score hears these characters the way they hear themselves: as heroes on a mission."},
      {"kind":"p","text":"**Street casting mixed with stars.** Non-professionals and first-timers share scenes with Sandler, Pattinson, and Chalamet. Julia Fox made her screen debut in *Uncut Gems*. Real Diamond District workers and real athletes (Kevin Garnett playing himself) populate the films. The effect is a kind of *friction realism*. The stars' polish rubs against unpolished faces, and neither register quite settles. The result is uncanny, not simply \"authentic.\""},
      {"kind":"p","text":"**IV. New York as Ecosystem**"},
      {"kind":"p","text":"Earlier New York cinema often treated the city as a backdrop or a symbol. For the Safdies it functions as an *economy*. The Diamond District, Queens housing, Upper West Side shelters, and bail bond offices form a web of exchange, where everyone owes someone and every relationship has a transactional edge. The films are lineage descendants of 1970s New Hollywood: Cassavetes' emotional volatility, Scorsese's street energy (Scorsese executive-produced *Uncut Gems*), Abel Ferrara's moral sleaze, and Jerry Schatzberg's *The Panic in Needle Park*. The key difference is that the Safdies' city is post-financialization. Hustling isn't the underworld's activity. It's everyone's."},
      {"kind":"p","text":"**V. The Ethical Problem: Authenticity and Extraction**"},
      {"kind":"p","text":"A serious lesson must include the critique. *Heaven Knows What* cast people drawn from the same world of addiction it depicted. Supporters see this as radical access: giving marginalized people screen presence and authorship (Holmes's memoir is the source). Critics see \"poverty tourism,\" with filmmakers borrowing the aura of real suffering for aesthetic intensity."},
      {"kind":"p","text":"There's no clean resolution. But notice that the tension mirrors the films' own subject. The films are about extraction: the opal pulled from an Ethiopian mine, the bet squeezed from a friend, the win wrung out of a body. The question of whether the filmmakers themselves are extracting from their subjects is not external to the work. It's the work's own theme turned back on it."},
      {"kind":"p","text":"**VI. Metaphysics: The Cosmic Zoom**"},
      {"kind":"p","text":"*Uncut Gems* opens by zooming into an opal, whose inner patterns dissolve into what looks like the cosmos. That image then transitions into a colonoscopy of Howard's body. It ends by zooming *into* a bullet wound and back out into the opal-galaxy. Stone, body, and universe are made visually continuous."},
      {"kind":"p","text":"This is the clearest evidence for the devotion reading. The films aren't merely social realism about lowlifes. They gesture toward something like mysticism, where the gambler's belief that \"this is the one\" is a degraded but genuine form of transcendence. Howard's final bet *wins*. He's right. And he dies anyway. The universe rewards faith and destroys the faithful in the same gesture. That is closer to Old Testament narrative than to crime drama, and the films' Jewish specificity (Passover seders, the Diamond District's culture, the 1950s Lower East Side world of *Marty Supreme*) supports reading them within a tradition of wrestling with a capricious God."},
      {"kind":"p","text":"**VII. The Solo Question**"},
      {"kind":"p","text":"What is Josh's, and what was the partnership's? The honest answer is still provisional. Early reception suggests *Marty Supreme* keeps the compulsion engine, the Bronstein co-writing, the Lopatin score, and the Khondji cinematography. It moves into period setting and a larger scale. Benny's *The Smashing Machine* (2025) appears to lean toward stillness and observation. One tentative hypothesis is that Josh carried more of the *velocity* and Benny more of the *patience*. Treat that as a working theory to test against the films, not a conclusion."},
    ],
  },
];;
