import type { LessonSection } from "../curriculum";

export const sections: readonly LessonSection[] = [
  {
    heading: null,
    blocks: [
      {"kind":"p","text":"“Subconscious” is a useful everyday word, but it is not the name of a single scientifically defined system. Usually, people mean mental activity that affects what they perceive, feel, remember, or do without their fully noticing how it works. You can recognize a friend’s voice in a noisy room, type without consciously locating each key, or feel uneasy before you can say what caught your attention. None of this requires a hidden second person inside your head. It requires a brain doing far more work than can be presented in conscious experience at once."},
    ],
  },
  {
    heading: "The first distinction: what are you unaware of?",
    blocks: [
      {"kind":"p","text":"There are at least three different claims people call “subconscious.” You might be unaware of an input: something influenced you although you did not notice seeing or hearing it. You might be aware of the input but unaware of the processing: you see a face and immediately recognize it, yet cannot explain the computations that made recognition possible. Or you might be aware of your choice but unsure of its causes: you know you selected one option, but cannot fully explain why it appealed to you. Evidence for one kind of unawareness does not automatically establish the others."},
      {"kind":"p","text":"Researchers generally prefer more precise terms. “Conscious” often means available to subjective experience or to flexible use in reasoning and report, although whether experience and reportability are the same thing remains debated. “Preconscious” describes information not currently in mind but readily brought to mind, such as your address. “Nonconscious” describes processing outside experience, including much sensory and bodily regulation. “Unconscious” is a broader word and also has a distinct meaning in psychoanalysis. It should not be confused with being medically unconscious."},
      {"kind":"p","text":"“Implicit” means that an influence is demonstrated indirectly through performance rather than through an explicit statement of knowledge. An implicit influence need not be completely outside awareness. “Subliminal” refers specifically to a stimulus presented below a measured threshold for awareness under particular conditions; it does not mean “powerful hidden message.” “Automatic” describes processing that tends to run with little deliberate effort. Speed, effort, intention, and awareness are separate dimensions: a practiced action can be both automatic and consciously noticed."},
    ],
  },
  {
    heading: "Where the historical idea came from",
    blocks: [
      {"kind":"p","text":"Sigmund Freud distinguished conscious, preconscious, and unconscious mental contents. His particularly influential idea was the “dynamic unconscious”: thoughts, wishes, or conflicts kept from awareness through defensive processes yet expressed indirectly in behavior or symptoms. In his later structural model, the “id,” “ego,” and “superego” represented aspects of motivation, regulation, and internalized standards. They are not three identifiable brain organs."},
      {"kind":"p","text":"“Repression” specifically means a proposed involuntary exclusion of distressing material from awareness. It is not the same as “suppression,” the deliberate decision not to think about something. Terms such as “rationalization” (constructing a plausible explanation), “projection” (attributing one’s own feelings to someone else), and “defense mechanism” remain useful descriptions in some contexts. Their proposed mechanisms and the strength of evidence for them vary, however. In particular, there is no good basis for assuming that a troubling but inaccessible memory has been stored intact and can be reliably recovered by a special technique. Suggestive techniques can create false memories; genuine delayed recall can also occur. Each case requires care rather than a universal story."},
      {"kind":"p","text":"Carl Jung’s “collective unconscious” proposed inherited, shared symbolic patterns or “archetypes.” Archetypes can be useful for interpreting stories and art, but the claim that particular symbolic narratives are genetically inherited is not an established finding of cognitive science."},
    ],
  },
  {
    heading: "Perception: awareness is the visible tip",
    blocks: [
      {"kind":"p","text":"Perception is not a camera recording that you subsequently inspect. Sensory signals are incomplete and noisy. The brain combines incoming information—often called “bottom-up” input—with prior learning, expectations, and current goals—often called “top-down” influences. This helps explain why context makes an unclear word easier to read, why an illusion can persist even when you know it is an illusion, and why you can overlook a conspicuous event while concentrating on another task."},
      {"kind":"p","text":"“Attention” is the selective allocation of processing resources; “awareness” is what enters experience. They are related but not interchangeable. “Inattentional blindness” is failure to notice something visible because attention is engaged elsewhere. “Change blindness” is failure to detect a change across views. Neither means the brain registered absolutely nothing: the experimental question is exactly what information was processed and what became accessible."},
      {"kind":"p","text":"“Priming” occurs when a prior encounter alters later processing. Seeing a word, for instance, may make a related word easier to recognize. Some perceptual and semantic priming effects are well established. Claims that barely noticed cues can reliably drive complex, long-term behavior are much less secure. “Blindsight,” in which some people with damage to visual cortex can respond to visual information without ordinary visual experience of it, provides an especially striking case of dissociation between processing and reported seeing. Even there, the details of residual awareness matter. Unconscious processing is real; claims about its sophistication must be tested task by task."},
    ],
  },
  {
    heading: "Memory: more than what you can recall",
    blocks: [
      {"kind":"p","text":"“Explicit” or “declarative” memory is knowledge you can intentionally retrieve and report. It includes “episodic” memory for events and “semantic” memory for facts and meanings. “Implicit memory” is revealed in how prior experience changes performance without requiring intentional recollection. It includes aspects of “procedural” learning, such as acquiring a skill, as well as priming and some forms of conditioning. “Statistical learning” refers to picking up regularities—for example, which sounds tend to occur together—without necessarily being able to state all the rules."},
      {"kind":"p","text":"These distinctions are supported by cases in which severe difficulty remembering new events coexists with an ability to improve at certain practiced skills. They do not imply watertight compartments: a person can know they are practicing a skill while some of the learning occurs without access to its details. The hippocampus is especially important for forming many new episodic memories; distributed cortical and subcortical systems support other forms of learning."},
      {"kind":"p","text":"Memory is also “reconstructive.” Retrieval draws on stored information, current cues, expectations, and later knowledge; it is not a replay of a recording. “Consolidation” concerns how memories become more stable over time, while “reconsolidation” concerns ways a retrieved memory may become susceptible to updating. Reconsolidation is a serious research topic, not a general-purpose method for deleting or rewriting a memory at will."},
    ],
  },
  {
    heading: "Conditioning, reward, and habit",
    blocks: [
      {"kind":"p","text":"“Classical” or “Pavlovian conditioning” is learning that one event predicts another: a particular sound comes to signal that food is coming. “Operant” or “instrumental learning” concerns how the consequences of an action affect whether that action is repeated. Both can influence behavior without a person narrating every learned association, although conscious knowledge and unconscious learning often interact."},
      {"kind":"p","text":"A useful distinction is between “goal-directed” action, selected with an anticipated outcome in mind, and “habitual” action, strongly elicited by a learned cue. In experiments, “outcome devaluation” helps distinguish them: if an outcome becomes undesirable but a response persists, that persistence suggests a habit. Ordinary behavior is usually a mixture, not a choice between two sealed systems."},
      {"kind":"p","text":"“Reinforcement learning” provides a computational vocabulary for some of this. A “reward-prediction error” is, roughly, the difference between an outcome and what was expected. Such errors can help update future behavior. Dopamine participates in these learning signals, but it is not simply “the pleasure chemical.” Likewise, “model-based” and “model-free” learning are useful computational distinctions, not perfect synonyms for conscious reasoning and unconscious habit."},
      {"kind":"p","text":"“Extinction” occurs when a learned response weakens because its expected outcome no longer follows. It often involves new learning rather than erasure of the original association. That helps explain why an old reaction can reappear in a new context or under stress. “Plasticity” is the broader capacity of neural systems to change with experience. A practiced habit can be changed, but typically through changed cues, repeated alternative actions, and time—not by issuing a single command to the subconscious."},
    ],
  },
  {
    heading: "Emotion and decision-making",
    blocks: [
      {"kind":"p","text":"Emotions combine several interacting processes: assessment of a situation (“appraisal”), changes in attention and bodily regulation, subjective feeling, and preparation for action. Some appraisals are rapid and difficult to articulate. “Interoception” is the sensing and interpretation of the body’s internal state. “Valence” describes how pleasant or unpleasant something feels; “arousal” describes its level of activation. “Allostasis” refers to regulation that anticipates bodily needs rather than merely correcting a disturbance after it happens."},
      {"kind":"p","text":"An emotion can therefore make sense before its source is clear to you. But “I feel it in my body” does not establish that the body knows a hidden truth. Feelings are valuable information to investigate, not infallible evidence. The amygdala, often called a “fear center,” participates in learning about salient and threatening events, among other functions; emotion has no single switch."},
      {"kind":"p","text":"A “heuristic” is an efficient shortcut for judgment. Heuristics make rapid decisions possible but can also produce predictable “cognitive biases.” An “implicit association” is a learned link that may influence quick responses. Tests such as the Implicit Association Test can study patterns of association, but an individual score is not a definitive measure of someone’s values or a reliable prediction of a particular act."},
      {"kind":"p","text":"The familiar “System 1/System 2” distinction captures something useful: some thinking is relatively fast and effortless; some is slower and deliberative. It is a metaphor for families of processes, not a map of two brain modules or a strict subconscious/conscious divide. Deliberation can rely on unnoticed assumptions, while a rapid response can be consciously experienced. “Metacognition” means evaluating your own thinking—such as judging how certain you are. It, too, can be mistaken. People can sometimes give plausible explanations for choices without having access to every process that produced them; this does not mean every explanation is false."},
    ],
  },
  {
    heading: "Brains and advanced models",
    blocks: [
      {"kind":"p","text":"There is no “subconscious region.” Sensory cortex, memory systems, basal ganglia, cerebellum, brainstem, and frontal and parietal networks all participate in processes that may or may not enter awareness. The brainstem helps regulate arousal; the basal ganglia contribute to action selection and learned routines; frontal networks contribute to planning and control. These are contributions, not exclusive ownership claims. The “default mode network,” associated with forms of internally directed thought such as autobiographical reflection, is not a hidden-mind headquarters."},
      {"kind":"p","text":"“Predictive processing” is an influential framework in which the brain continually generates expectations and updates them using mismatches with incoming signals, called “prediction errors.” In Bayesian language, an estimate reflects both a “prior” expectation and the “likelihood” of the sensory evidence. “Precision” roughly concerns how much confidence is assigned to different signals. This framework can illuminate perception and learning, but its broadest claims and precise neural implementations remain debated. It should not become the claim that expectations can simply override reality."},
      {"kind":"p","text":"A separate set of theories asks when processing becomes conscious. “Global neuronal workspace” theories emphasize widespread availability or “broadcast” of information to systems involved in report, reasoning, and control. “Recurrent processing” theories emphasize feedback within sensory processing. “Higher-order” theories emphasize representations of one’s own mental states. “Integrated information theory” proposes a relationship between consciousness and a system’s integrated causal structure. These theories disagree, and none has settled the problem. Explaining how a brain handles information outside awareness is related to, but not identical with, explaining why anything is experienced at all."},
      {"kind":"p","text":"A useful professional habit is to keep levels of explanation apart. One can ask what problem a system solves, what algorithm or representation it uses, what brain mechanisms implement it, and what the result feels like to the person. A claim at one level—“this choice reflects a learned expectation,” for example—does not by itself identify a particular neuron, prove a Freudian conflict, or settle a philosophical question about free will."},
    ],
  },
  {
    heading: "Dreams, therapy, and changing patterns",
    blocks: [
      {"kind":"p","text":"Sleep supports aspects of learning and memory, and dreams may draw on concerns, memories, and emotion. But there is no validated universal dictionary in which a dream object has a fixed hidden meaning. Discussing a dream can help someone reflect, without treating the interpretation as a recovered fact."},
      {"kind":"p","text":"In clinical work, “schema” often means an organized expectation about oneself or the world, such as an expectation that disagreement leads to rejection. Such patterns may be easy to state, hard to notice in the moment, or evident chiefly in behavior. “Transference” describes the possibility that expectations learned in earlier relationships shape later ones. “Dissociation,” in a clinical sense, refers to disruptions in the usual integration of experience, memory, identity, or sense of presence; it is not, by itself, evidence of a hidden memory."},
      {"kind":"p","text":"Different therapies approach persistent patterns differently. Cognitive behavioral approaches examine thoughts and actions and test alternatives. Exposure-based treatments help people learn new responses to feared situations. Psychodynamic therapies examine recurring feelings and relationship patterns. Mindfulness can improve recognition of thoughts and reactions as they occur. None requires the premise that every problem has one buried secret waiting to be uncovered. Hypnosis can alter attention and responsiveness to suggestion, but it is not a truth serum. Likewise, subliminal recordings and promises to “reprogram the subconscious” should be treated skeptically."},
    ],
  },
  {
    heading: "How scientists establish a claim",
    blocks: [
      {"kind":"p","text":"An experiment must specify what was supposedly unconscious: the stimulus, the learned rule, the cause of a decision, or something else. Researchers then compare subjective reports with objective measures such as recognition accuracy, often using ideas from “signal-detection theory” to separate sensitivity from willingness to say “I saw it.” Failure to detect awareness in a small or insensitive test is not proof that awareness was absent. Conversely, above-chance performance does not automatically show that a person possessed rich hidden understanding."},
      {"kind":"p","text":"Behavioral experiments, studies of brain injury, brain recordings, imaging, and interventions that alter neural activity answer different questions. A pattern decoded from a brain scan does not mean a scanner has read someone’s hidden thoughts; activity correlated with a behavior does not by itself show what caused it. Strong conclusions depend on controls, replication, effect sizes, and whether a result generalizes beyond the task."},
      {"kind":"p","text":"The central picture is therefore neither “everything important is consciously chosen” nor “a secret mind controls everything.” Human cognition is layered: a great deal is learned, predicted, regulated, and prepared outside immediate awareness, while conscious reflection can inspect some outcomes, set goals, and gradually reshape the conditions under which automatic processes operate."},
    ],
  },
];;
