import type { LessonSection } from "../curriculum";

export const sections: readonly LessonSection[] = [
  {
    heading: "What TypeScript actually is",
    blocks: [
      {"kind":"p","text":"TypeScript is JavaScript with a static type system layered on top, and the single most important thing to understand is that this layer is *erased*. When you compile TypeScript, every type annotation, every interface, every generic parameter disappears, and what remains is ordinary JavaScript. Types never exist at runtime. This has a profound consequence: TypeScript cannot make your program faster, cannot check data arriving from a network, and cannot stop a lie in a type annotation from being a lie. What it can do is let you make claims about the shape of your values, and then mechanically verify that those claims are mutually consistent across your entire codebase. That verification is the product. A type system is, in essence, a proof system that runs before your code does, and TypeScript's is one of the most expressive mainstream type systems in existence, precisely because it had to be flexible enough to describe the chaos of real-world JavaScript."},
      {"kind":"p","text":"The second foundational idea is that TypeScript's type system is *structural*, not *nominal*. In languages like Java or C#, two classes with identical fields are different types because they have different names. In TypeScript, a type is defined by its shape. If a function wants an object with a `name` string and an `age` number, any object that has those properties satisfies it, regardless of what you called it or whether you declared it at all. Types are sets of possible values, and compatibility is subset membership. This mental model, types as sets, will carry you all the way from your first annotation to the most arcane conditional type."},
    ],
  },
  {
    heading: "The basic vocabulary",
    blocks: [
      {"kind":"p","text":"A *type annotation* is the colon syntax that attaches a type to a variable, parameter, or return value. *Type inference* is the compiler figuring out types you did not write; if you assign the number 5 to a constant, TypeScript knows it is a number, and in fact knows it is the *literal type* 5, since a constant can never be anything else. Good TypeScript leans on inference heavily and annotates only at boundaries, because every annotation is a claim you now have to maintain."},
      {"kind":"p","text":"The *primitive types* mirror JavaScript: `string`, `number`, `boolean`, `bigint`, `symbol`, `null`, and `undefined`. Beyond those sit three special types that confuse newcomers and reward understanding. `any` is an escape hatch that turns off checking for a value; it is both assignable to everything and accepts everything, which makes it an infection vector, since anything touched by `any` tends to become `any`. `unknown` is its disciplined sibling: it also accepts any value, but you cannot *do* anything with it until you narrow it down. If `any` means \"trust me,\" `unknown` means \"prove it.\" Finally, `never` is the type with no values at all, the empty set. It is the return type of a function that always throws, the type of a variable in a code path that cannot be reached, and, as we will see, the fundamental tool for exhaustiveness checking and type-level computation."},
      {"kind":"p","text":"*Interfaces* and *type aliases* both name object shapes. The practical difference is small: interfaces can be extended and merged through *declaration merging* (declaring the same interface twice combines them, which is how libraries augment global types), while type aliases can name anything, including unions, tuples, and computed types. *Arrays* and *tuples* differ in that a tuple has a fixed length with a known type at each position, which is how TypeScript can type function argument lists. *Enums* exist but are somewhat disfavored by experienced practitioners because they generate runtime code and behave unusually; unions of string literals usually serve better."},
      {"kind":"p","text":"*Optional properties*, marked with a question mark, and *readonly* properties round out object description. Function types describe parameters and return values, and *overloads* let a single function declare several distinct signatures. *Classes* work as in modern JavaScript, with the addition of access modifiers (`public`, `private`, `protected`), which are enforced only at compile time, unlike JavaScript's `#private` fields which are enforced at runtime."},
    ],
  },
  {
    heading: "Unions, intersections, and narrowing",
    blocks: [
      {"kind":"p","text":"A *union type*, written with a vertical bar, means a value is one of several possibilities. An *intersection type*, written with an ampersand, means a value is all of several things at once. In set terms, union is set union and intersection is set intersection, which explains the otherwise puzzling fact that intersecting two object types gives you an object with *more* properties (the set of objects having both shapes is smaller, but each member is richer) while intersecting `string` and `number` gives `never` (nothing is both)."},
      {"kind":"p","text":"Unions are where TypeScript's genius for modeling real programs appears, through *narrowing*. When you check a value with `typeof`, `instanceof`, the `in` operator, an equality comparison, or a truthiness test, the compiler tracks that check through *control flow analysis* and refines the type inside the branch. Write a function that takes `string | number`, test with `typeof x === \"string\"`, and inside that branch `x` is simply `string`. This is flow-sensitive typing, and it means the type of a variable can differ from line to line."},
      {"kind":"p","text":"The most important pattern built on narrowing is the *discriminated union*, sometimes called a tagged union or, in type theory, a sum type. You define several object shapes that each carry a literal-typed property, conventionally named `kind` or `type`, and union them. A `switch` on that discriminant narrows each case to exactly one shape. If you add a `default` branch that assigns the value to a variable of type `never`, the compiler will refuse to build when you later add a new variant and forget to handle it. This is *exhaustiveness checking*, and it converts a whole category of runtime bugs into compile errors. It is also the TypeScript idiom closest to algebraic data types in ML-family languages, and it is the single most valuable technique for modeling state in applications."},
      {"kind":"p","text":"*Type guards* are user-defined narrowing functions whose return type is written as `x is SomeType`; they let you teach the compiler about checks it cannot infer on its own. *Assertion functions*, written `asserts x is SomeType`, do the same but by throwing instead of returning false. Both are how you bridge the gap between untyped data at the edges of your system and typed data within it, since remember, types are erased, so validating a JSON payload requires actual runtime code that the type system then trusts."},
    ],
  },
  {
    heading: "Generics: types parameterized by types",
    blocks: [
      {"kind":"p","text":"A *generic* is a type or function that takes other types as parameters. A function that returns whatever it is given should not be typed as taking and returning `unknown`; it should say \"for any type T, I take a T and return that same T.\" The angle-bracket parameter captures the relationship between input and output. Generics are the mechanism of *parametric polymorphism*, and they are why a well-typed `map` over an array of strings is known to produce an array of whatever your callback returns."},
      {"kind":"p","text":"*Generic constraints*, written with `extends`, restrict what types a parameter may be. \"T extends { id: string }\" means any T, provided it has a string id. The `keyof` operator produces the union of an object type's property names as literal types, and *indexed access types*, written `T[K]`, look up the type of a property. Combining them yields the canonical example: a `getProperty` function typed as taking an object of type T and a key K extending `keyof T`, returning `T[K]`. This function is fully type-safe for every object and every valid key, with zero annotations at the call site. Learning to express such relationships rather than falling back to loose types is the central skill of intermediate TypeScript."},
      {"kind":"p","text":"Generics also carry *variance* considerations, a concept most TypeScript developers encounter only through confusing errors. If `Dog` is a subtype of `Animal`, is an array of dogs a subtype of an array of animals? For reading, yes; for writing, no, because you could insert a cat. TypeScript is deliberately unsound here for arrays and methods (it treats them as *covariant* or *bivariant* for pragmatism), but it is strict for function parameters under the `strictFunctionTypes` flag, where parameter types are *contravariant*. You can now annotate variance explicitly with `in` and `out` modifiers on type parameters, mostly useful for library authors and compiler performance."},
    ],
  },
  {
    heading: "The type-level toolkit",
    blocks: [
      {"kind":"p","text":"Here the system becomes a programming language in its own right. TypeScript's type system is Turing complete, and while you should rarely exploit that fully, the constructs that make it so are indispensable in libraries and large codebases."},
      {"kind":"p","text":"*Mapped types* iterate over the keys of a type and produce a new type, as a loop produces a new array. The built-in `Partial<T>` makes every property optional; `Required<T>`, `Readonly<T>`, `Pick<T, K>`, and `Record<K, V>` are all mapped types you could write yourself in one line. Mapped types can add or strip modifiers (the `-?` syntax removes optionality) and, through *key remapping* with the `as` clause, can rename keys or filter them out."},
      {"kind":"p","text":"*Conditional types* are the if-statement: `T extends U ? X : Y`. They let a type depend on a test. Crucially, when the checked type is a bare type parameter and you pass in a union, the conditional *distributes* over each member of the union, which is how `Exclude<T, U>` removes members from a union and `NonNullable<T>` strips null and undefined. Distribution is a frequent source of surprise; wrapping both sides of the `extends` in a one-element tuple disables it when you need to test the union as a whole."},
      {"kind":"p","text":"The `infer` keyword, usable only inside a conditional type, is pattern matching. It lets you say \"if T is a function returning something, call that something R and give me R.\" This is how `ReturnType<T>`, `Parameters<T>`, and `Awaited<T>` work, and how you can peel apart promise types, array element types, or the argument types of a constructor. Together, conditional types and `infer` are the destructuring and recursion primitives of type-level programming."},
      {"kind":"p","text":"*Template literal types* apply string interpolation to types. The type `` `on${Capitalize<K>}` `` applied to a union of event names produces a union of handler names. Combined with mapped types and key remapping, this lets you derive a fully typed event emitter, or a typed router from a path pattern like `/users/:id`, where the type system extracts the parameter names from the string. Intrinsic string manipulation types (`Uppercase`, `Lowercase`, `Capitalize`, `Uncapitalize`) are provided by the compiler."},
      {"kind":"p","text":"*Recursive types* let a type refer to itself, which is how you describe JSON, nested paths, or deep variants of utilities like `DeepPartial<T>` and `DeepReadonly<T>`. Conditional types can recurse, and since TypeScript 4.5 tail-recursive conditional types are evaluated efficiently up to a generous depth limit. Still, recursion depth and instantiation count are the primary ways to make the compiler slow or hit the \"type instantiation is excessively deep\" error, so recursion at the type level deserves the same discipline as recursion at runtime."},
      {"kind":"p","text":"The `satisfies` operator, added in 4.9, resolves a long-standing tension. Annotating a value with a type *widens* it to that type, losing specific information about literals. Omitting the annotation keeps the specific inference but does not check conformance. `satisfies` checks that a value conforms to a type while preserving the narrower inferred type. It is the right tool for configuration objects, where you want both validation and precision."},
      {"kind":"p","text":"*Const assertions*, written `as const`, tell the compiler to infer the narrowest possible type: literals instead of primitives, readonly tuples instead of mutable arrays. Deriving a union type from a `const` array of strings, via `typeof arr[number]`, is a common way to keep a single source of truth between runtime values and types. The general principle, that types should be *derived* from values or from one canonical type rather than duplicated by hand, is perhaps the most important design heuristic for large TypeScript codebases."},
      {"kind":"p","text":"*Branded* or *nominal* types are a workaround for structural typing's one weakness: a `UserId` and an `OrderId` are both strings, and nothing stops you from passing one where the other is expected. By intersecting `string` with a phantom property, usually a unique symbol-keyed field that never exists at runtime, you create distinct types that the compiler will not confuse. This technique is standard in serious domain modeling."},
    ],
  },
  {
    heading: "Soundness, and where TypeScript deliberately lies",
    blocks: [
      {"kind":"p","text":"A *sound* type system guarantees that a well-typed program never has a type error at runtime. TypeScript is intentionally unsound. Its design goal was adoption by JavaScript developers, which meant accommodating existing patterns even where they could not be proven safe. The known holes include: array and method bivariance; indexed access on arrays and records returning the element type rather than element-or-undefined (fixed under `noUncheckedIndexedAccess`); type assertions with `as`, which are unchecked downcasts; the non-null assertion operator; `any`; and the fact that object types are not sealed, so an object with extra properties may flow into a type that does not mention them (except for the *excess property check* on object literals written directly at an annotated site). Understanding these holes is not pedantry. In a large codebase, the places where TypeScript lies are exactly where the bugs that \"cannot happen\" happen, and a mature team knows to add runtime validation at those seams."},
    ],
  },
  {
    heading: "Configuration and the compiler",
    blocks: [
      {"kind":"p","text":"The compiler, `tsc`, is driven by `tsconfig.json`, and a few options matter enormously. `strict` turns on a family of checks (`strictNullChecks`, `noImplicitAny`, `strictFunctionTypes`, and others) that should be considered the baseline for any new project; the difference between strict and non-strict TypeScript is the difference between a type system and a suggestion. `noUncheckedIndexedAccess` and `exactOptionalPropertyTypes` tighten further. `target` and `module` control what JavaScript is emitted, and `moduleResolution` determines how imports are found, a subject of real complexity given the coexistence of CommonJS and ECMAScript modules in the Node ecosystem; the modern `bundler` and `node16`/`nodenext` settings exist to navigate that."},
      {"kind":"p","text":"*Declaration files*, with the `.d.ts` extension, contain types without implementations. They are how JavaScript libraries get types, either shipped alongside the library or community-maintained in the DefinitelyTyped repository, published under the `@types` scope. The `declare` keyword asserts the existence of something defined elsewhere. *Ambient declarations* and *module augmentation* let you extend the types of third-party code or the global scope without modifying it."},
    ],
  },
  {
    heading: "Working at scale",
    blocks: [
      {"kind":"p","text":"In a large codebase, TypeScript stops being primarily a bug catcher and becomes architecture. Several concerns dominate."},
      {"kind":"p","text":"*Project references* split a monolith into multiple `tsconfig` projects that compile independently and incrementally, with `tsc --build` orchestrating them. Combined with `incremental` and `composite` flags, this is the difference between a two-minute and a ten-second check in a monorepo. *Isolated modules* and the `verbatimModuleSyntax` option ensure that each file can be transpiled independently by fast tools like esbuild or SWC, which strip types without type-checking; the typical production setup is to transpile with a fast tool and run `tsc --noEmit` separately as a check. The `type` modifier on imports (`import type`) makes explicit that an import is erased, preventing accidental runtime dependencies and circular import problems."},
      {"kind":"p","text":"*Compiler performance* becomes a discipline of its own. Giant unions, deeply recursive conditional types, and large intersection chains can cause type-check times to balloon. The compiler offers diagnostics (`--extendedDiagnostics`, `--generateTrace`) to find hot spots. Preferring interfaces over type-alias intersections for object types is a known performance win because interfaces are cached by name. Annotating return types of exported functions speeds checking and prevents inference from leaking implementation details into public types."},
      {"kind":"p","text":"*API design* at the type level means thinking about what you expose. Public types should be stable, named, and documented; internal inference can be as clever as it likes. Overly clever types in a shared library impose their complexity on every consumer's error messages. A common mature pattern is to pair a runtime schema library (Zod, Valibot, io-ts, ArkType) with inferred types, so the validation code and the static type share a single definition, closing the erasure gap at system boundaries."},
      {"kind":"p","text":"*Migration* of JavaScript codebases is incremental by design: `allowJs` and `checkJs` let JavaScript files participate, JSDoc annotations provide types without syntax changes, and the strictness flags can be enabled one at a time. The practical sequence is usually to enable `noImplicitAny` and `strictNullChecks` first, quarantine the inevitable `any` with lint rules that forbid new ones, and ratchet upward."},
      {"kind":"p","text":"*Linting* complements the type checker. The compiler checks consistency; a linter (typescript-eslint) checks taste and risk, flagging floating promises, unsafe `any` usage, unnecessary conditions that the type system proves always true, and the like. Several of the most valuable rules require type information and are therefore slower, which again ties back to compiler performance."},
    ],
  },
  {
    heading: "How to think about all of this",
    blocks: [
      {"kind":"p","text":"Underneath every feature is one idea: a type is a set of values, and the compiler is checking that you never put a value where the set does not include it. Unions widen the set, intersections and narrowing shrink it, generics abstract over which set, conditional and mapped types compute new sets from old ones, and `never` is the empty set that signals a contradiction or a completed proof. Beginners should learn to write discriminated unions and lean on inference. Intermediate developers should learn to express relationships with generics and `keyof` rather than loosening types. Advanced practitioners should learn where the system is unsound, how to derive rather than duplicate, and how to keep the type-level program they are inevitably writing both correct and fast. At every level, the goal is the same as it has always been for static types: to make illegal states unrepresentable, so that the compiler, rather than your users, is the one to find out when you were wrong."},
    ],
  },
];;
