import type { LessonSection } from "../curriculum";

export const sections: readonly LessonSection[] = [
  {
    heading: null,
    blocks: [
      {"kind":"p","text":"The most useful way to understand TypeScript is to separate three things: what JavaScript does at runtime, what the type checker can establish before runtime, and what engineering practices make those static conclusions trustworthy."},
      {"kind":"p","text":"The most useful way to understand TypeScript is to separate three things: what JavaScript does at runtime, what the type checker can establish before runtime, and what engineering practices make those static conclusions trustworthy."},
      {"kind":"p","text":"TypeScript’s real power is not “putting types on variables.” It is expressing relationships: this key belongs to that object; this result depends on that argument; this state permits these operations; this module promises this contract."},
      {"kind":"p","text":"PART I — THE FOUNDATIONS"},
      {"kind":"list","ordered":true,"items":["TypeScript is JavaScript with a static reasoning layer"]},
      {"kind":"p","text":"JavaScript defines the runtime behavior: objects, functions, closures, prototypes, promises, exceptions, mutation, modules, and so on. TypeScript adds a language for describing values and checking how programs use them."},
      {"kind":"p","text":"“Static checking” means analyzing code without running it on its actual inputs. The checker can reject accessing a nonexistent property, supplying an incompatible argument, or forgetting to handle a possible state."},
      {"kind":"p","text":"Most TypeScript-specific syntax is erased before execution. An interface does not become a runtime validator. A generic parameter does not normally become a runtime object. An annotation saying that something is a number does not convert it into one."},
      {"kind":"p","text":"Some TypeScript constructs, such as conventional enums and constructor parameter properties, do generate JavaScript. Therefore, “all TypeScript syntax disappears” is slightly too strong. The important principle is that static types themselves do not enforce runtime contracts."},
      {"kind":"p","text":"A runtime that accepts TypeScript files may strip the types itself. That still does not mean the runtime validates those types."},
      {"kind":"p","text":"Type checking, transpilation, bundling, and execution are separate activities, even when a tool combines several of them."},
      {"kind":"list","ordered":true,"items":["Types, values, declarations, and assignability"]},
      {"kind":"p","text":"A value is something the running program can manipulate: a string, an object, a function, a promise. A type describes what the checker knows or permits about such values."},
      {"kind":"p","text":"A useful first approximation is to think of a type as a set of possible values. The type string contains strings; the literal type \"ready\" contains only that particular string; a union describes alternatives."},
      {"kind":"p","text":"This approximation is powerful, but not a complete mathematical model of TypeScript. Features such as any, mutation, and deliberately permissive compatibility rules complicate it."},
      {"kind":"p","text":"“Assignability” is the checker’s compatibility relation: may a value described by one type be used where another type is expected? Assignment, function arguments, return values, and generic constraints all involve assignability."},
      {"kind":"p","text":"TypeScript also distinguishes type-space names from value-space names. An interface exists only in type space. A variable exists in value space, although its static type can be queried. A class contributes both: an instance type and a runtime constructor."},
      {"kind":"p","text":"This distinction explains a common surprise: you cannot generally take an interface name and inspect it at runtime. There is no corresponding runtime object to inspect."},
      {"kind":"list","ordered":true,"items":["Primitive types and the special types"]},
      {"kind":"p","text":"The everyday primitive types include string, number, boolean, bigint, symbol, null, and undefined. TypeScript does not change their JavaScript semantics. In particular, number is not a mathematical integer type, and a number annotation does not establish finiteness, positivity, or freedom from NaN."},
      {"kind":"p","text":"A literal type identifies a particular value: \"open\", 200, or true. Literal types become especially useful when describing states, commands, event names, and configuration choices."},
      {"kind":"p","text":"The most important special types are any, unknown, never, and void."},
      {"kind":"p","text":"Any is an escape hatch. It suppresses many checks and allows unchecked assumptions to propagate through a program. It is not simply “a type that can contain anything”; unknown can also contain anything, but behaves much more safely."},
      {"kind":"p","text":"Unknown means that a value exists but its usable structure has not yet been established. Before calling it as a function or reading its properties, you must narrow it or validate it."},
      {"kind":"p","text":"Never represents an impossible value. It appears when a branch cannot occur, when a function cannot return normally, or when a type-level computation eliminates every possibility."},
      {"kind":"p","text":"Void usually means that a function’s return value is not intended to be used. It is not identical to undefined. In particular, a function returning a useful value can often be supplied where a callback returning void is expected: the caller is agreeing to ignore the result."},
      {"kind":"p","text":"With strictNullChecks enabled, null and undefined are distinct possibilities that must be accounted for rather than silently accepted almost everywhere."},
      {"kind":"list","ordered":true,"items":["Objects, properties, arrays, tuples, and readonly views"]},
      {"kind":"p","text":"An object type describes properties and their types. Some properties may be required; others may be optional."},
      {"kind":"p","text":"An optional property, written conceptually as name?: string, may be absent. Reading it can therefore produce undefined. Absence and explicit undefined are related but different runtime situations. The exactOptionalPropertyTypes option makes that distinction more precise when assigning properties."},
      {"kind":"p","text":"An array describes a sequence whose elements share a type. A tuple describes positions: for example, a string followed by a number. Tuples can also have optional positions, labels, and rest elements. At runtime, they are still JavaScript arrays."},
      {"kind":"p","text":"An index signature describes a family of properties whose names are not individually enumerated. Record<K, V> is a convenient type-level way to describe values of type V associated with keys K. When K is a finite union, it can require each named key. When K is string, it does not make every possible string property exist at runtime."},
      {"kind":"p","text":"Readonly means that a particular typed view does not permit certain writes. It does not imply that the underlying object is frozen or cannot change through another reference. Readonly transformations are also commonly shallow."},
      {"kind":"p","text":"Const is different again: it prevents rebinding a variable, not mutating every object reachable through it."},
      {"kind":"p","text":"Two terminology traps are worth remembering. Lowercase object excludes primitive values. The type {} does not mean “an object with no properties”; under strict null checking, it accepts non-nullish values, including primitives."},
      {"kind":"list","ordered":true,"items":["Structural typing, interfaces, type aliases, and classes"]},
      {"kind":"p","text":"TypeScript is primarily structurally typed. Compatibility usually depends on available members rather than the name of a declaration."},
      {"kind":"p","text":"If an operation requires an object with an id property of type string, many independently declared object types can satisfy that requirement. They need not explicitly announce that they implement the same interface."},
      {"kind":"p","text":"This is why object types are generally open rather than exact. Describing an object as having an id does not usually assert that id is its only property."},
      {"kind":"p","text":"Fresh object literals receive additional “excess property checks,” which catch likely mistakes such as misspelled configuration fields. These checks are useful, but they do not turn the entire type system into an exact-object system."},
      {"kind":"p","text":"An interface is a named structural contract, especially convenient for object and callable shapes. Interfaces can extend other interfaces and participate in declaration merging."},
      {"kind":"p","text":"A type alias names a type expression. It can describe an object, union, tuple, primitive, conditional type, or another composition. Unlike an interface, it cannot be reopened through declaration merging."},
      {"kind":"p","text":"Neither a type alias nor an ordinary interface automatically creates a distinct nominal identity. Two aliases of string are still compatible."},
      {"kind":"p","text":"Classes add runtime construction and behavior. Their instance compatibility is largely structural, although private and protected members introduce important nominal-like restrictions. TypeScript’s private modifier is primarily a checking restriction; JavaScript’s #private fields provide runtime-enforced private access."},
      {"kind":"p","text":"Enums deserve separate attention because conventional enums produce runtime objects. For many domain alternatives, literal unions are simpler. When runtime enumeration is needed, a constant object plus a derived union is another common design."},
      {"kind":"list","ordered":true,"items":["Unions, intersections, and modeling meaningful states"]},
      {"kind":"p","text":"A union, written A | B, means that a value may satisfy A or B. Until the checker knows which alternative applies, you can perform only operations safe for the possibilities that remain."},
      {"kind":"p","text":"An intersection, written A & B, requires both contracts simultaneously. It does not mean “merge these fields and let the second declaration win.” Conflicting requirements can produce impossible properties or an impossible overall type."},
      {"kind":"p","text":"The most valuable everyday application of unions is the discriminated union. Each variant has a common property whose literal value identifies it: perhaps status is \"loading\", \"success\", or \"failure\"."},
      {"kind":"p","text":"Each variant can then carry appropriate information. Success has data. Failure has an error. Loading has neither."},
      {"kind":"p","text":"This is better than several independent booleans and optional properties, which may allow contradictory combinations such as “loading, failed, and successfully loaded” at the same time."},
      {"kind":"p","text":"In programming-language terminology, discriminated unions are a practical form of sum types: one alternative or another. Records and tuples are product-like: several pieces of information together."},
      {"kind":"p","text":"“Make invalid states unrepresentable” means designing these combinations deliberately. It does not mean the type system can prevent malformed external input or every possible misuse."},
      {"kind":"list","ordered":true,"items":["Inference, widening, annotations, assertions, and satisfies"]},
      {"kind":"p","text":"Inference is the checker deriving a type without an explicit annotation. Contextual typing works in the other direction: an expected type helps determine the types inside an expression, such as the parameter of a callback."},
      {"kind":"p","text":"Literal widening explains why a value initialized with \"ready\" may acquire the broader type string. A mutable variable is often expected to hold other strings later. Even a const object can have mutable properties, so its properties may widen."},
      {"kind":"p","text":"An as const assertion preserves literal information and gives literal object properties or tuple positions readonly treatment. It does not freeze the runtime object, and it does not deeply transform separately created objects referenced by the literal."},
      {"kind":"p","text":"A type annotation states the type through which a declaration will be used."},
      {"kind":"p","text":"A type assertion, such as value as SomeType, asks the checker to accept a different static view. It performs no validation or conversion. Asserting that something is a number does not parse it."},
      {"kind":"p","text":"The satisfies operator checks compatibility with a target type while generally retaining more of the expression’s specific inferred structure than a broad annotation would. It is particularly useful for configuration objects. It still participates in contextual typing, so “it never affects inference” is too simplistic."},
      {"kind":"p","text":"The non-null assertion operator, !, tells the checker to disregard null or undefined. It inserts no runtime check. By contrast, optional chaining and nullish coalescing are real JavaScript operations with runtime effects."},
      {"kind":"p","text":"The important distinction is between establishing a fact and merely telling the compiler to assume it."},
      {"kind":"list","ordered":true,"items":["Functions, callbacks, overloads, and asynchronous results"]},
      {"kind":"p","text":"A function type describes a calling contract: parameter types, optional parameters, rest parameters, and a return type. Functions can also have properties, and object types can describe call signatures or constructor signatures."},
      {"kind":"p","text":"A callback is simply a function passed to another operation. Its types often come from context, which is why explicitly annotating every callback parameter is usually unnecessary."},
      {"kind":"p","text":"Overloads describe several public calling patterns for one implementation. They are useful when particular inputs correspond to particular outputs."},
      {"kind":"p","text":"The implementation signature is not an additional public overload. Its job is to accommodate the declared cases internally. Overloads can also become awkward when callers hold union-typed arguments; a union parameter or generic relationship may then be a better design."},
      {"kind":"p","text":"A useful distinction is this: a union says “these alternatives are accepted,” while a generic can preserve a relationship between the selected input and the resulting output."},
      {"kind":"p","text":"An async function produces a Promise. Promise<T> describes its successful resolution value; it does not describe every possible rejection or thrown exception. TypeScript does not have a general checked-exception system."},
      {"kind":"p","text":"When expected failure is part of an API contract, a discriminated result type can make success and failure explicit. That still does not establish that the implementation can never throw unexpectedly."},
      {"kind":"list","ordered":true,"items":["Narrowing, control-flow analysis, and exhaustiveness"]},
      {"kind":"p","text":"Narrowing is the checker refining a type as control flow establishes additional information."},
      {"kind":"p","text":"Checks involving typeof, instanceof, equality, property existence, and discriminant values can all narrow types. Early returns and thrown exceptions also matter: after an impossible case exits, the remaining code has stronger information."},
      {"kind":"p","text":"Truthiness checks require care. They do not merely remove null and undefined; they can also exclude values such as an empty string, zero, and false. A precise condition usually communicates a more precise invariant."},
      {"kind":"p","text":"A user-defined type guard returns a predicate such as value is User. This allows a function’s result to influence narrowing. However, the checker does not prove that the function correctly recognizes every User. An incorrect predicate can undermine otherwise well-typed code."},
      {"kind":"p","text":"An assertion function expresses a stronger postcondition: if the function returns normally, a certain fact should hold. Its implementation must actually check that fact, throw, or otherwise justify the promise."},
      {"kind":"p","text":"Exhaustiveness checking uses never to detect unhandled variants. After every member of a discriminated union has been handled, nothing should remain. Adding a new variant can then produce an error at incomplete consumers."},
      {"kind":"p","text":"This is one of TypeScript’s strongest architectural capabilities: turning certain forms of incomplete maintenance into compiler feedback."},
      {"kind":"list","ordered":true,"items":["Generics describe relationships, not vagueness"]},
      {"kind":"p","text":"A generic declaration is parameterized by types. In identity<T>, T connects the argument type with the return type: whatever type goes in is preserved coming out."},
      {"kind":"p","text":"Replacing T with any loses that relationship. Replacing it with unknown preserves safety but loses specific information about the result."},
      {"kind":"p","text":"A generic constraint, such as T extends HasId, states what the implementation may assume about T. It does not say that T is exactly HasId. T could contain additional required information."},
      {"kind":"p","text":"This distinction explains a frequent error: knowing that T has an id does not permit a function to manufacture an arbitrary T from an id alone. The caller’s T might also require a role, timestamp, or special invariant."},
      {"kind":"p","text":"Generic parameters can be inferred from arguments or supplied explicitly. Defaults make some parameters optional. Const type parameters can encourage literal-preserving inference for suitable inputs. NoInfer can prevent a particular position from contributing unwanted inference candidates."},
      {"kind":"p","text":"A good generic parameter connects meaningful parts of a contract. If it appears only in a return type that the caller can choose freely, ask where the evidence for that result comes from."},
      {"kind":"p","text":"For example, parse<T>(text) cannot verify arbitrary T merely because the caller supplied a type argument. Without a runtime schema or another trusted basis, such an API commonly conceals an assertion."},
      {"kind":"p","text":"PART II — ADVANCED TYPE-LEVEL REASONING"},
      {"kind":"list","ordered":true,"items":["Variance: how compatibility behaves through containers"]},
      {"kind":"p","text":"Variance asks how a relationship between types changes when those types appear inside another construction."},
      {"kind":"p","text":"Suppose Dog is assignable to Animal. A readonly collection of dogs can usually be treated as a readonly collection of animals: reading an element still produces an animal. This direction is covariance."},
      {"kind":"p","text":"Function inputs run in the opposite direction. A function capable of handling every animal can safely serve where a dog handler is required. A function that handles only dogs cannot safely replace an operation that might receive any animal. This reversal is contravariance."},
      {"kind":"p","text":"A structure that both consumes and produces T often needs invariance for full soundness. A writable container illustrates why: treating a dog container as an unrestricted animal container could allow inserting a cat."},
      {"kind":"p","text":"TypeScript is intentionally more permissive in some places. Mutable array compatibility and certain object rules sacrifice strict soundness for usability. Under strictFunctionTypes, ordinary function-type parameters receive stronger contravariant checking, while method declarations retain important bivariant behavior for compatibility."},
      {"kind":"p","text":"“Bivariant” means accepting compatibility in either direction, even where one direction may not be fully safe."},
      {"kind":"p","text":"Variance explains many apparently mysterious callback errors. The checker is not merely asking whether two names are related; it is asking whether substitution remains safe in the position where the type is used."},
      {"kind":"list","ordered":true,"items":["keyof, typeof, and indexed access"]},
      {"kind":"p","text":"Type-level programming begins with operators that inspect existing descriptions."},
      {"kind":"p","text":"Keyof T produces a type representing the permitted property keys of T. Those keys can include strings, numbers, or symbols."},
      {"kind":"p","text":"The type query typeof someValue extracts the static type known for a value. This differs from JavaScript’s runtime typeof expression, which returns a string such as \"object\" or \"number\"."},
      {"kind":"p","text":"An indexed access type, T[K], describes the property type selected by key K. If K represents several keys, the result can represent several property types. For an array-like type, T[number] is a common way to obtain its element type."},
      {"kind":"p","text":"These operators let APIs preserve relationships. A property accessor can accept an object of type T, a key K constrained to keyof T, and return T[K]. The return type now depends on which valid key was supplied."},
      {"kind":"p","text":"One subtlety: keyof a union gives the keys safely available across its members, not automatically every key appearing in any member."},
      {"kind":"p","text":"Another follows from open object types: Object.keys cannot generally promise that every runtime key belongs to keyof the object’s declared static type. The actual object may have additional properties that the narrower static view does not mention."},
      {"kind":"p","text":"Static knowledge is not necessarily an exhaustive inventory of runtime structure."},
      {"kind":"list","ordered":true,"items":["Mapped types and utility types"]},
      {"kind":"p","text":"A mapped type transforms properties by iterating over a key type. It can preserve each property’s value type, replace it, change its modifiers, or rename its key."},
      {"kind":"p","text":"This is the foundation of familiar utilities. Partial makes properties optional. Required makes them required. Readonly disallows writes through that view. Pick selects properties, while Omit describes a type without selected properties."},
      {"kind":"p","text":"Key remapping uses an as clause within a mapped type. It can rename properties or filter them out, often by mapping unwanted keys to never."},
      {"kind":"p","text":"These are computations over descriptions, not operations on runtime objects."},
      {"kind":"p","text":"That distinction has practical security consequences. Giving an object the type Omit<User, \"password\"> does not delete its password property. Returning or serializing the original object can still expose it. Actual redaction requires an actual runtime transformation."},
      {"kind":"p","text":"Most standard property utilities are shallow. Creating a recursive DeepReadonly or DeepPartial requires policy decisions about arrays, tuples, functions, maps, sets, promises, and class instances."},
      {"kind":"p","text":"A compact recursive definition can look mathematically elegant while having the wrong domain semantics. The hard question is not merely whether the compiler can transform every property, but whether those transformations mean the right thing."},
      {"kind":"list","ordered":true,"items":["Conditional types and distributivity"]},
      {"kind":"p","text":"A conditional type has the form T extends U ? X : Y. It selects a type according to an assignability relationship."},
      {"kind":"p","text":"It is a compile-time operation, not a runtime if statement. When generic parameters remain unresolved, the checker may retain the conditional symbolically rather than immediately selecting a branch."},
      {"kind":"p","text":"A central rule is distributivity. When the checked side is a “naked” type parameter, a conditional can operate separately on each union member."},
      {"kind":"p","text":"For example, T extends string ? T : never filters a union to its string-like members. Applied to string | number, it keeps string and removes number."},
      {"kind":"p","text":"Wrapping the sides, as in [T] extends [U], prevents that automatic distribution and asks about the union as a whole."},
      {"kind":"p","text":"This distinction is essential when writing reusable type utilities. “Does every possible value fit this category?” differs from “For each member, does that member fit?”"},
      {"kind":"p","text":"Exclude and Extract use this style of union filtering. They do not implement unrestricted mathematical set subtraction. Exclude<string, \"admin\"> remains string; TypeScript does not generally represent “all strings except this one literal.”"},
      {"kind":"p","text":"Never also interacts with distribution in surprising ways. As an empty union, it can cause a distributive conditional to produce no branches at all. Consequently, testing for never usually requires a non-distributive formulation."},
      {"kind":"p","text":"Any has special behavior that further complicates these clean algebraic intuitions. Advanced utilities should consider any, unknown, never, and unions deliberately."},
      {"kind":"list","ordered":true,"items":["Infer is structural pattern matching"]},
      {"kind":"p","text":"Infer introduces a type variable while matching a structure inside a conditional type."},
      {"kind":"p","text":"Conceptually, you can ask: if this type looks like an array of some element E, return E. If it looks like a function with some parameter tuple P and result R, extract P or R."},
      {"kind":"p","text":"This is type-level pattern matching. It does not execute a function or inspect a runtime object."},
      {"kind":"p","text":"Utilities such as Parameters and ReturnType expose parts of function types. Awaited models await-like unwrapping, including the relevant promise-like behavior, rather than merely removing one spelling of Promise."},
      {"kind":"p","text":"The result of inference depends on where a variable appears. Multiple candidates in output-like and input-like positions can combine differently, connecting infer directly to variance."},
      {"kind":"p","text":"Overloaded functions have another subtlety: inference from their callable type generally reflects the last signature rather than simulating overload resolution for some hypothetical argument list."},
      {"kind":"p","text":"Conditional types and infer together provide much of TypeScript’s type-level computational power. They let a library derive precise contracts from the structure of other contracts instead of requiring users to repeat the same information."},
      {"kind":"list","ordered":true,"items":["Template literal types, variadic tuples, and recursion"]},
      {"kind":"p","text":"Template literal types construct string types from other string-like types. They can describe event names, prefixes, naming conventions, and constrained string formats."},
      {"kind":"p","text":"If a key is \"name\", a template can derive \"nameChanged\". If a key type contains several alternatives, the result contains corresponding alternatives. Combining multiple unions can create a cross-product, which is useful but potentially expensive."},
      {"kind":"p","text":"Variadic tuple types preserve sequences of argument types. They support abstractions such as argument concatenation, partial application, wrappers, and APIs with a fixed prefix followed by a variable argument list."},
      {"kind":"p","text":"Recursive conditional types allow repeated structural processing. Common examples include flattening nested arrays, walking nested properties, or interpreting a restricted string format."},
      {"kind":"p","text":"These techniques can also encode arithmetic and elaborate parsers at the type level. That demonstrates expressive power, but does not establish engineering value."},
      {"kind":"p","text":"The compiler has finite budgets and implementation heuristics. A theoretically meaningful computation may still produce excessive-instantiation errors, slow editor interactions, or enormous error messages."},
      {"kind":"p","text":"TypeScript is also not a general dependent type system. It can express relationships involving statically known literals and structures, but it cannot freely reason about arbitrary future runtime computations."},
      {"kind":"p","text":"Once information has widened from a particular literal to string, a clever type utility cannot generally recover which string the program will produce."},
      {"kind":"list","ordered":true,"items":["Soundness, proof obligations, and the limits of checking"]},
      {"kind":"p","text":"A sound type system would ensure that accepted programs obey its intended safety guarantees. TypeScript deliberately does not pursue complete soundness."},
      {"kind":"p","text":"Assertions, any, trusted declarations, mutable aliases, permissive variance, and unchecked indexing can all create gaps between static descriptions and runtime reality."},
      {"kind":"p","text":"Control-flow reasoning also has limits. Narrowing one value does not necessarily establish every related generic constraint or resolve every conditional return type. A relationship obvious to a human may exceed what the checker tracks."},
      {"kind":"p","text":"The productive response is not automatically to add assertions until the error disappears. Sometimes the API needs a clearer discriminated union, a better generic relationship, a narrower abstraction, or a simpler implementation."},
      {"kind":"p","text":"Assertions are not inherently forbidden. They are best treated as localized proof obligations: places where the programmer accepts responsibility for a fact the checker cannot establish."},
      {"kind":"p","text":"Branding follows the same principle. A branded string can distinguish UserId from OrderId statically, often using an intersection and a unique symbol marker. The brand does not validate itself. A trusted constructor or parser must justify creating it."},
      {"kind":"p","text":"The professional question is not “Does this compile?” but “Which assumptions make its static claims true?”"},
      {"kind":"p","text":"PART III — LARGE CODEBASES AND PRODUCTION DESIGN"},
      {"kind":"list","ordered":true,"items":["Runtime boundaries are where trust must be established"]},
      {"kind":"p","text":"External input should be treated as untrusted regardless of the types you want it to have. This includes network responses, environment variables, database records, browser storage, files, and messages from other processes."},
      {"kind":"p","text":"A type annotation cannot establish that such data conforms to a contract. Runtime validation, decoding, or another trustworthy mechanism must do that work."},
      {"kind":"p","text":"Unknown is a useful boundary type because it prevents accidental use before refinement. Some APIs, notably JSON.parse, return any in standard declarations; placing the result behind unknown before validation helps prevent unchecked information from spreading."},
      {"kind":"p","text":"A schema can provide both runtime validation and a corresponding static type. Alternatively, declarations and validators can be generated from a shared contract. Either approach reduces the risk of separately maintained descriptions drifting apart."},
      {"kind":"p","text":"Validation should also be distinguished from domain truth. A string may be a correctly formatted UserId without identifying an existing user. A well-shaped request may still be unauthorized. Structural validation is one layer, not the whole correctness story."},
      {"kind":"p","text":"A robust pattern is: validate raw input, convert it into an appropriate domain representation, operate internally under stronger assumptions, and explicitly construct outbound data."},
      {"kind":"list","ordered":true,"items":["Modules, declarations, and package resolution"]},
      {"kind":"p","text":"A module provides an explicit boundary through imports and exports. TypeScript checks those boundaries, but the emitted program must still obey the module rules of its actual runtime or bundler."},
      {"kind":"p","text":"ES modules and CommonJS are different module systems. The module and moduleResolution settings should match the toolchain and deployment environment, not merely whichever configuration suppresses an error."},
      {"kind":"p","text":"Import type identifies an import needed only by the checker. This clarifies dependencies and avoids retaining a runtime import solely for a type."},
      {"kind":"p","text":"Declaration files, conventionally ending in .d.ts, describe the public types of JavaScript code. They contain promises about an implementation; they do not establish that the implementation exists or behaves correctly."},
      {"kind":"p","text":"Packages may ship their own declarations. Otherwise, a separate @types package may provide them. Ambient declarations and declare can describe globals or externally supplied values, but they do not create those values."},
      {"kind":"p","text":"Declaration merging and module augmentation can extend existing contracts. These mechanisms are useful for certain ecosystems, but excessive ambient modification creates hidden coupling."},
      {"kind":"p","text":"A frequent configuration trap is assuming that paths aliases rewrite emitted import specifiers. They generally do not. An alias understood by the checker must also be understood by the runtime, bundler, or another transformation step."},
      {"kind":"p","text":"For published packages, JavaScript entry points, declaration entry points, export conditions, and supported module formats must agree."},
      {"kind":"list","ordered":true,"items":["Compiler configuration is part of the contract"]},
      {"kind":"p","text":"A tsconfig.json is not just build decoration. Its options determine which assumptions are checked and which language or platform features are considered available."},
      {"kind":"p","text":"Strict is a strong baseline. Important checks under its umbrella include noImplicitAny, strictNullChecks, and strictFunctionTypes. It does not mean “enable every useful safety option.”"},
      {"kind":"p","text":"NoUncheckedIndexedAccess adds undefined to many indexed reads that might miss. ExactOptionalPropertyTypes distinguishes an absent optional property from an explicitly assigned undefined unless undefined is allowed. NoImplicitOverride makes overridden class members more explicit."},
      {"kind":"p","text":"Target controls aspects of emitted JavaScript syntax. Lib selects built-in API declarations available to the checker. Neither setting installs missing runtime features or supplies polyfills."},
      {"kind":"p","text":"IsolatedModules helps catch constructs incompatible with certain per-file transformation workflows. VerbatimModuleSyntax makes value-versus-type import and export intent more explicit."},
      {"kind":"p","text":"Many fast development tools strip types without performing full type checking. A successful development build therefore does not necessarily mean the program passed the checker. Run a dedicated checking step in continuous integration."},
      {"kind":"p","text":"The TypeScript compiler can also emit despite errors unless configured otherwise, so “files were generated” is not itself a correctness signal."},
      {"kind":"p","text":"SkipLibCheck can reduce declaration-checking cost, but it is a tradeoff: it skips checking declaration files themselves, not the use of their types throughout application code."},
      {"kind":"list","ordered":true,"items":["Architecture: stable boundaries, local inference, explicit meaning"]},
      {"kind":"p","text":"Large-codebase TypeScript works best when types reflect architectural meaning rather than merely the shape of today’s implementation."},
      {"kind":"p","text":"A database row, domain entity, public API response, and editable form may share fields while representing different contracts. Reusing one giant type everywhere creates accidental coupling: a storage change can become a client-facing change."},
      {"kind":"p","text":"Share types when they express a genuinely shared concept. Otherwise, separate the representations and make the transformations explicit."},
      {"kind":"p","text":"Within a small implementation, inference reduces noise and preserves useful detail. At public module boundaries, explicit parameter and return types often improve stability, documentation, and error locality."},
      {"kind":"p","text":"This is not an argument for annotating every variable. It is an argument for deciding where an inferred implementation detail should stop becoming a public promise."},
      {"kind":"p","text":"Prefer small contracts with meaningful names over universal “base” types containing dozens of optional fields. Optionality should represent real uncertainty or absence, not compensate for unclear architecture."},
      {"kind":"p","text":"Similarly, use generics to capture recurring relationships, not merely because several functions look superficially similar."},
      {"kind":"p","text":"A good abstraction reduces the knowledge required to use it. If callers must understand its entire conditional-type implementation to interpret an error, it may be saving code while increasing complexity."},
      {"kind":"list","ordered":true,"items":["Monorepos, project references, and compiler performance"]},
      {"kind":"p","text":"A monorepo contains multiple related packages or applications in one repository. It still needs genuine boundaries: explicit public APIs, dependency direction, and deliberate ownership of shared concepts."},
      {"kind":"p","text":"TypeScript project references allow separately configured projects to express compilation dependencies. Composite projects, declaration outputs, and incremental build information support more scalable checking and rebuilding."},
      {"kind":"p","text":"These mechanisms improve build structure, but they do not automatically enforce architectural rules. A project can still have an unhealthy dependency graph, leaky public types, or confusing runtime cycles."},
      {"kind":"p","text":"Compiler performance is also a type-design concern. Large unions, repeated distributive conditionals, deep recursive transformations, and enormous inferred public signatures can create substantial checking and editor costs."},
      {"kind":"p","text":"Naming intermediate concepts, simplifying relationships, and placing explicit types at strategic boundaries can help. Some interface-based compositions are easier for the compiler to handle than large repeated intersections, but actual performance should be measured rather than guessed."},
      {"kind":"p","text":"Use compiler diagnostics and traces to identify expensive work. Do not respond to every slowdown by disabling checks across the repository."},
      {"kind":"p","text":"The relevant budget includes human performance too: error-message readability, completion quality, refactoring confidence, and the time needed to understand a public API."},
      {"kind":"p","text":"A type-level trick that saves five implementation lines while generating incomprehensible diagnostics for hundreds of consumers is usually a poor trade."},
      {"kind":"list","ordered":true,"items":["Public type APIs, testing, and compatibility"]},
      {"kind":"p","text":"A library’s types are part of its public API."},
      {"kind":"p","text":"Changing a generic constraint, overload order, inferred literal, optional property, or return relationship can break consumers even when the emitted JavaScript barely changes."},
      {"kind":"p","text":"Adding a new member to a published union can break exhaustive consumers. Adding a required property can break producers. An inferred exported type can also accidentally expose dependencies or internal implementation details."},
      {"kind":"p","text":"Public declarations therefore deserve review just as runtime behavior does. Explicit signatures at package boundaries often make that review easier."},
      {"kind":"p","text":"Type-level tests check what the compiler accepts and rejects. Positive cases establish that intended usage compiles. Negative cases establish that invalid usage produces an error. @ts-expect-error can help because it reports a problem when the expected error disappears."},
      {"kind":"p","text":"These tests complement runtime tests; they do not replace them. A function can have a perfect signature and an incorrect implementation. A validator can claim a predicate while accepting malformed data."},
      {"kind":"p","text":"Libraries should also consider their supported TypeScript versions. Changes in inference and checking can affect users even without a runtime compatibility change."},
      {"kind":"p","text":"The goal is not merely a green checker run in the library’s own repository, but a stable and understandable contract for its consumers."},
      {"kind":"list","ordered":true,"items":["Migration strategy and the mature TypeScript mindset"]},
      {"kind":"p","text":"Existing JavaScript codebases can adopt TypeScript incrementally through allowJs, checkJs, JSDoc annotations, and gradual conversion. A useful migration establishes meaningful boundaries first instead of maximizing the number of renamed files."},
      {"kind":"p","text":"Contain unavoidable any values in adapters. Prefer unknown for untrusted input. Replace scattered assertions with named validators or constructors. Track suppressions rather than allowing them to become invisible infrastructure."},
      {"kind":"p","text":"A sensible learning progression is ordinary types and functions first, then unions and narrowing, then generics and structural relationships, then mapped and conditional types. Advanced type-level programming becomes easier when it is understood as composition of familiar ideas rather than a separate collection of tricks."},
      {"kind":"p","text":"The mature mindset has three parts."},
      {"kind":"p","text":"First, preserve information. Good inference, literal types, discriminated unions, and generics keep useful relationships from being discarded."},
      {"kind":"p","text":"Second, establish trust explicitly. External data, assertions, brands, ambient declarations, and third-party types all have assumptions that should be identifiable."},
      {"kind":"p","text":"Third, spend complexity carefully. Types are part of the software system, so they need maintainability, performance, testing, and coherent interfaces too."},
      {"kind":"p","text":"The goal is not to make the compiler admire a clever type. It is to make invalid states harder to express, valid code easier to understand, and the remaining assumptions easy to locate."},
    ],
  },
];;
