import type { LessonSection } from "../curriculum";

export const sections: readonly LessonSection[] = [
  {
    heading: null,
    blocks: [
      {"kind":"p","text":"*How to read this:* Each section starts with the intuitive picture and then goes deeper. Paragraphs marked **Going deeper** carry the technical content: equations, numbers, and open problems. Beginners can skip them without losing the thread. Specialists can skim the openings. Key vocabulary is in bold where it is first defined."},
    ],
  },
  {
    heading: "1. Scale: Learning to Think Big",
    blocks: [
      {"kind":"p","text":"The first obstacle to understanding the universe is its size, which exceeds intuition by dozens of orders of magnitude. Astronomers therefore use special units."},
      {"kind":"p","text":"The **astronomical unit (AU)** is the average Earth–Sun distance, about 150 million kilometres. A **light-year** is the distance light travels in a year, about 9.46 trillion kilometres. It is a distance, not a time. Professionals mostly use the **parsec (pc)**, about 3.26 light-years. It is defined as the distance at which one AU subtends one arcsecond of angle. Its multiples, the kiloparsec (kpc) and megaparsec (Mpc), are the working units of galactic and extragalactic astronomy."},
      {"kind":"p","text":"Because light travels at a finite speed, **looking far away is looking back in time**. You see the Sun as it was about 8 minutes ago, the nearest star system, Alpha Centauri, as it was about 4 years ago, and the Andromeda Galaxy as it was 2.5 million years ago. Telescopes are time machines. This is the central methodological fact of cosmology: we cannot watch the universe evolve, but we can see different epochs at different distances."},
      {"kind":"p","text":"The universe has a hierarchical structure:"},
      {"kind":"list","items":["**Planets** orbit **stars**.","Stars gather by the hundreds of billions into **galaxies**.","Galaxies cluster into **groups** (tens of members) and **clusters** (hundreds to thousands).","Clusters are knotted together in **superclusters**.","On the largest scales, matter forms the **cosmic web**: dense **nodes** (clusters) connected by **filaments** and **walls** (sheets), surrounding enormous, nearly empty **voids** tens of megaparsecs across."]},
      {"kind":"p","text":"Our address, in expanding order: Earth, the Solar System, the Orion Arm of the **Milky Way**, the **Local Group** (dominated by the Milky Way and Andromeda), the outskirts of the **Virgo Supercluster**, and the larger basin of galaxy flows called **Laniakea**."},
      {"kind":"p","text":"The **observable universe** is the region from which light has had time to reach us since the beginning. Its radius is about 46.5 billion light-years, even though the universe is only about 13.8 billion years old. The difference is not a paradox. Space has expanded while the light was in transit, so the objects that emitted the oldest light are now much farther away than 13.8 billion light-years. The universe as a whole may be vastly larger than the observable part, or infinite. We do not know."},
    ],
  },
  {
    heading: "2. The Expanding Universe",
    blocks: [
      {"kind":"p","text":"In the 1920s, Georges Lemaître and Edwin Hubble found that distant galaxies recede from us, with speeds proportional to their distance. This is the **Hubble–Lemaître law**, v = H₀d, where **H₀ (the Hubble constant)** is the present expansion rate."},
      {"kind":"p","text":"The crucial conceptual point is that galaxies are not flying *through* space away from a central point. **Space itself is expanding**, and every observer sees every distant galaxy receding. The standard analogy is dots on an inflating balloon's surface: no dot is the centre, and every dot sees the others move away. The balloon's two-dimensional surface is the analogy; its interior is irrelevant. Gravitationally bound systems like atoms, planets, and galaxies do not expand. Only the space *between* unbound systems grows."},
      {"kind":"p","text":"Expansion stretches light as it travels. Its wavelength lengthens and shifts toward the red end of the spectrum. This is **cosmological redshift**, measured by the number **z**, where 1 + z is the factor by which wavelengths have been stretched. A galaxy at z = 1 emitted its light when the universe was half its present linear size."},
      {"kind":"p","text":"Redshift has three distinct physical origins:"},
      {"kind":"list","items":["**Doppler redshift** comes from motion through space.","**Gravitational redshift** comes from light climbing out of a gravitational well.","**Cosmological redshift** comes from the expansion of space during transit."]},
      {"kind":"p","text":"**Going deeper.** Expansion is described by the **scale factor a(t)**, normalized so that a = 1 today. All cosmological distances scale with it: 1 + z = 1/a(t_emit). The **Hubble parameter** is H(t) = ȧ/a. It changes with time, and H₀ is simply its present value."},
      {"kind":"p","text":"Cosmologists distinguish several distance concepts:"},
      {"kind":"list","items":["**Proper distance** is the distance you would measure with rulers \"now\".","**Comoving distance** factors out expansion and stays fixed for objects moving with the cosmic flow.","**Luminosity distance** is inferred from apparent brightness.","**Angular diameter distance** is inferred from apparent size."]},
      {"kind":"p","text":"These coincide nearby but diverge dramatically at high z. The angular diameter distance even reaches a maximum around z ≈ 1.6, so more distant objects can appear *larger* on the sky."},
      {"kind":"p","text":"Several horizons also need separating:"},
      {"kind":"list","items":["The **Hubble radius**, c/H, is about 14.4 billion light-years, beyond which recession exceeds light speed. This does not violate relativity, because nothing moves *through* space faster than light.","The **particle horizon** is the boundary of the observable universe.","The **cosmological event horizon**, about 16–17 billion light-years, marks the limit beyond which light emitted *today* will never reach us, because of accelerating expansion."]},
      {"kind":"p","text":"We can see galaxies that are currently receding superluminally. Light they emitted long ago has been making headway against the stretching."},
    ],
  },
  {
    heading: "3. The Theoretical Framework: General Relativity and Cosmology",
    blocks: [
      {"kind":"p","text":"Newton described gravity as a force. Einstein's **general relativity (GR)** describes it as the **curvature of spacetime**, the four-dimensional union of space and time. John Wheeler's summary: *matter tells spacetime how to curve; spacetime tells matter how to move.* Planets orbit the Sun because they follow the straightest possible paths, called **geodesics**, through spacetime curved by the Sun's mass."},
      {"kind":"p","text":"Modern cosmology rests on the **cosmological principle**: on large enough scales (beyond a few hundred megaparsecs), the universe is **homogeneous** (the same everywhere) and **isotropic** (the same in every direction). This is not dogma. It is confirmed by galaxy surveys and spectacularly by the near-uniformity of the cosmic microwave background."},
      {"kind":"p","text":"**Going deeper.** GR's core is the **Einstein field equations**, G_μν + Λg_μν = (8πG/c⁴)T_μν. These relate spacetime geometry (the Einstein tensor G_μν, built from the metric g_μν) to energy and momentum content (the stress–energy tensor T_μν). Λ is the **cosmological constant**."},
      {"kind":"p","text":"Imposing homogeneity and isotropy forces the metric into the **Friedmann–Lemaître–Robertson–Walker (FLRW)** form. The whole cosmological dynamics then reduces to one function, a(t), and one number, the spatial curvature k. Space can be **flat** (k = 0, Euclidean), **closed** (k > 0, sphere-like, finite in volume), or **open** (k < 0, saddle-like)."},
      {"kind":"p","text":"The field equations then yield the **Friedmann equations**:"},
      {"kind":"p","text":"H² = (8πG/3)ρ − kc²/a² + Λc²/3"},
      {"kind":"p","text":"ä/a = −(4πG/3)(ρ + 3p/c²) + Λc²/3"},
      {"kind":"p","text":"The second equation contains a subtle insight: **pressure gravitates**. Ordinary matter and radiation decelerate expansion. A component with sufficiently *negative* pressure (p < −ρc²/3) accelerates it."},
      {"kind":"p","text":"Components are characterized by an **equation of state** w = p/(ρc²). Their densities dilute as ρ ∝ a^(−3(1+w)):"},
      {"kind":"list","items":["**Matter** (w = 0) dilutes as a⁻³, simply by volume.","**Radiation** (w = 1/3) dilutes as a⁻⁴, by volume plus redshift of each photon's energy.","**A cosmological constant** (w = −1) does not dilute at all."]},
      {"kind":"p","text":"This single fact explains the universe's history of eras: radiation dominated early, then matter, and now dark energy."},
      {"kind":"p","text":"The **critical density** ρ_c = 3H²/(8πG) is the density at which space is exactly flat, about 5 hydrogen atoms per cubic metre today. Densities are expressed as fractions of it, the **density parameters Ω**. Observations give total Ω ≈ 1 to better than about 0.5%. The universe is spatially flat, or very nearly so."},
    ],
  },
  {
    heading: "4. What the Universe Is Made Of",
    blocks: [
      {"kind":"p","text":"Everything familiar, including stars, planets, gas, and people, is made of **baryonic matter**: protons and neutrons, plus electrons, which cosmologists lump in by convention. It makes up only about **5%** of the universe's energy budget."},
      {"kind":"p","text":"About **27%** is **dark matter**, which exerts gravity but neither emits nor absorbs light. The remaining roughly **68%** is **dark energy**, a smooth component that causes the expansion to accelerate. The standard model built on these ingredients is called **ΛCDM** (\"Lambda Cold Dark Matter\")."},
      {"kind":"p","text":"**Dark matter: the evidence.** Dark matter is not a single anomaly but a convergence of independent lines of evidence:"},
      {"kind":"list","items":["In the 1930s, Fritz Zwicky found that galaxies in the Coma Cluster move too fast to be held together by visible mass.","In the 1970s, Vera Rubin and Kent Ford showed that spiral galaxies have flat **rotation curves**. Outer stars orbit as fast as inner ones, implying massive unseen **halos**.","**Gravitational lensing** maps mass directly through its bending of background light. It reveals far more mass than is visible.","In the **Bullet Cluster**, two colliding clusters, the lensing mass is cleanly separated from the hot gas that holds most of the ordinary matter.","Most decisively, the pattern of fluctuations in the cosmic microwave background, and the growth of cosmic structure, *require* a non-baryonic component that does not interact with light."]},
      {"kind":"p","text":"Without dark matter, the fluctuations imprinted in the early universe would not have had time to grow into the galaxies we see."},
      {"kind":"p","text":"**Going deeper on dark matter.** \"Cold\" means the particles were non-relativistic when structure began forming, which allows small structures to form first. **Hot dark matter**, such as light neutrinos, would erase small-scale structure and is ruled out as the dominant component. **Warm dark matter** is an intermediate possibility constrained by small-scale structure."},
      {"kind":"p","text":"Candidates include:"},
      {"kind":"list","items":["**WIMPs** (Weakly Interacting Massive Particles), motivated by the \"WIMP miracle\" that thermal relic abundances naturally match observations. They are increasingly constrained by null results from direct-detection experiments such as LZ and XENONnT.","**Axions**, very light particles originally proposed to solve QCD's strong CP problem.","**Sterile neutrinos**.","**Primordial black holes**.","Much more exotic proposals such as self-interacting or fuzzy dark matter."]},
      {"kind":"p","text":"**MOND** (Modified Newtonian Dynamics) proposes modifying gravity instead of adding matter. It fits galaxy rotation curves remarkably well, including the empirical **radial acceleration relation**, but struggles badly with clusters and the CMB."},
      {"kind":"p","text":"ΛCDM has persistent **small-scale tensions**: the \"cusp–core,\" \"missing satellites,\" and \"too-big-to-fail\" problems. Many of these have been eased by better modelling of baryonic feedback."},
      {"kind":"p","text":"**Dark energy.** In 1998, two teams using **Type Ia supernovae** as distance markers discovered that the expansion is **accelerating**. This earned the 2011 Nobel Prize. The simplest explanation is Einstein's cosmological constant, interpreted as the energy density of empty space itself."},
      {"kind":"p","text":"**Going deeper on dark energy.** Quantum field theory predicts a **vacuum energy**, but naive estimates exceed the observed value by roughly 10⁶⁰ to 10¹²⁰, depending on the cutoff. This is the **cosmological constant problem**, arguably the worst prediction in physics. A related puzzle is the **coincidence problem**: why are the dark energy and matter densities comparable *now*?"},
      {"kind":"p","text":"Alternatives include:"},
      {"kind":"list","items":["**Quintessence**, a slowly evolving scalar field with w varying over time.","**Modified gravity** theories, such as f(R) and Horndeski theories.","The **anthropic** explanation within a landscape of possible vacua."]},
      {"kind":"p","text":"The **deceleration parameter** q = −äa/ȧ² turned negative (acceleration began) around z ≈ 0.6–0.7, roughly 6 billion years ago. Recent baryon acoustic oscillation results from **DESI** (2024–2025), combined with supernovae and the CMB, show intriguing 2.8–4σ hints that dark energy *evolves* (w₀ > −1, wₐ < 0). If confirmed, this would overturn the pure cosmological constant."},
      {"kind":"p","text":"**Radiation and neutrinos.** Today the universe also contains photons, overwhelmingly those of the cosmic microwave background, outnumbering baryons about 1.6 billion to one. It also contains a **cosmic neutrino background** at about 1.95 K, predicted with confidence but not yet directly detected. Today, radiation contributes only about 0.01% of the energy budget, but it dominated the early universe."},
      {"kind":"p","text":"**Cosmological tensions.** The **Hubble tension** is currently the most prominent. Early-universe inference from the CMB (Planck, assuming ΛCDM) gives H₀ ≈ 67.4 km/s/Mpc. The local distance ladder (SH0ES, calibrated with Cepheids) gives about 73 km/s/Mpc, a discrepancy of roughly 5σ. Alternative calibrations, such as the tip of the red giant branch, give intermediate values, and the debate is active. It may reveal systematic errors or new physics, such as \"early dark energy\" or extra relativistic species."},
      {"kind":"p","text":"A milder **S₈ tension** concerns how clumpy matter is today. Weak lensing surveys have tended to find slightly less clustering than the CMB predicts, though recent analyses have reduced this."},
    ],
  },
  {
    heading: "5. Cosmic History: From the First Instant to Today",
    blocks: [
      {"kind":"p","text":"**What the \"Big Bang\" means.** The **Big Bang** is not an explosion at a point in pre-existing space. It is the hot, dense early phase of the universe, from which expansion and cooling proceeded *everywhere at once*. Extrapolating GR backward yields a **singularity** of infinite density. Nearly all physicists interpret this as a sign that GR breaks down, not as a literal physical event."},
      {"kind":"p","text":"The Big Bang theory rests on three classic pillars:"},
      {"kind":"list","ordered":true,"items":["The expansion of the universe.","The **cosmic microwave background**.","The abundances of the light elements."]},
      {"kind":"p","text":"**The Planck epoch (t < 10⁻⁴³ s).** At the **Planck time** (about 5.4 × 10⁻⁴⁴ s), quantum effects of gravity become important, and no established theory applies. Everything earlier is speculation."},
      {"kind":"p","text":"**Grand unification and inflation.** It is hypothesized that the strong, weak, and electromagnetic forces were unified at very high energies. This is the idea of **Grand Unified Theories (GUTs)**."},
      {"kind":"p","text":"Around 10⁻³⁶ to 10⁻³² s (the timing is model-dependent), the universe is thought to have undergone **cosmic inflation**: an episode of exponential expansion that grew distances by a factor of at least about e⁶⁰ (roughly 10²⁶)."},
      {"kind":"p","text":"Inflation was proposed by Alan Guth, Andrei Linde, Andreas Albrecht, Paul Steinhardt, and Alexei Starobinsky in the early 1980s. It solves three puzzles:"},
      {"kind":"list","items":["**The horizon problem.** Why is the CMB the same temperature in regions that should never have been in causal contact?","**The flatness problem.** Why is Ω so finely tuned to 1?","**The monopole problem.** Why don't we see relic magnetic monopoles predicted by GUTs?"]},
      {"kind":"p","text":"Its most powerful achievement is explaining the *origin of structure*. **Quantum fluctuations** in the field driving inflation, the **inflaton**, were stretched to cosmic scales and became the seeds of all galaxies. Every galaxy is a magnified quantum fluctuation."},
      {"kind":"p","text":"**Going deeper on inflation.** In **slow-roll inflation**, the inflaton's potential energy dominates its kinetic energy, mimicking a cosmological constant (w ≈ −1). Inflation predicts:"},
      {"kind":"list","items":["Nearly **Gaussian**, **adiabatic** perturbations.","A spatially flat universe.","A nearly (but not exactly) **scale-invariant** spectrum. Planck measures the **scalar spectral index** n_s ≈ 0.965, a detected ~8σ deviation from n_s = 1 that is consistent with slow roll.","**Primordial gravitational waves**, parametrized by the **tensor-to-scalar ratio r**. The current bound is r < 0.036 (BICEP/Keck), which has already disfavoured simple models such as m²φ² inflation. Starobinsky-like \"plateau\" potentials are favoured."]},
      {"kind":"p","text":"Detecting primordial **B-mode polarization** in the CMB would be near-direct evidence of quantum gravity at work. Many models imply **eternal inflation**, in which inflation ends in some regions while continuing in others, producing \"pocket universes.\" This feeds multiverse speculation and a serious **measure problem**."},
      {"kind":"p","text":"Inflation has alternatives and critics, including bouncing cosmologies, ekpyrotic models, and string gas cosmology. Critics argue that its flexibility compromises its predictiveness."},
      {"kind":"p","text":"**Reheating.** Inflation ended when the inflaton decayed, filling the universe with hot particles. This process is called **reheating**."},
      {"kind":"p","text":"**Baryogenesis.** The universe contains matter but almost no antimatter, with a baryon-to-photon ratio η ≈ 6 × 10⁻¹⁰. For every billion antiquarks there were roughly a billion and one quarks. The survivors of the mutual annihilation make up everything we see."},
      {"kind":"p","text":"Andrei Sakharov identified three necessary conditions for generating this asymmetry:"},
      {"kind":"list","ordered":true,"items":["Baryon number violation.","C and CP violation.","Departure from thermal equilibrium."]},
      {"kind":"p","text":"The Standard Model's CP violation is far too small. **Leptogenesis**, via heavy right-handed neutrinos, is a leading explanation."},
      {"kind":"p","text":"**Electroweak and QCD transitions.** At about 10⁻¹² s, the **electroweak symmetry breaking** transition occurred. The Higgs field acquired its vacuum value, and fundamental particles gained mass. In the Standard Model this was a smooth crossover rather than a sharp transition."},
      {"kind":"p","text":"At about 10⁻⁵ s, the **quark–hadron (QCD) transition** confined free quarks and gluons (the **quark–gluon plasma**) into protons and neutrons."},
      {"kind":"p","text":"**Neutrino decoupling and nucleosynthesis (1 second to 20 minutes).** At about 1 second, neutrinos stopped interacting and began free-streaming. They formed the neutrino background. Shortly afterward, electron–positron annihilation heated the photons relative to the neutrinos."},
      {"kind":"p","text":"Between about 3 and 20 minutes, **Big Bang nucleosynthesis (BBN)** forged the light nuclei:"},
      {"kind":"list","items":["About 75% hydrogen and 25% helium-4 by mass.","Traces of deuterium, helium-3, and lithium-7."]},
      {"kind":"p","text":"The predicted abundances depend on η and agree impressively with observation, except for the **cosmological lithium problem**: observed primordial lithium is about 3 times lower than predicted. Nearly every heavier element came later, from stars."},
      {"kind":"p","text":"**Matter–radiation equality (~50,000 years, z ≈ 3400).** The density of matter overtook that of radiation. After this point, dark matter perturbations could grow efficiently."},
      {"kind":"p","text":"**Recombination and the CMB (~380,000 years, z ≈ 1100).** Until this point, the universe was an opaque **plasma**. Free electrons scattered photons constantly, like fog."},
      {"kind":"p","text":"When the temperature fell to about 3000 K, electrons combined with nuclei to form neutral atoms. This is **recombination**, a misnomer, since they had never been combined before. Photons **decoupled** and have streamed freely ever since. Their point of origin is called the **surface of last scattering**."},
      {"kind":"p","text":"This light, redshifted by a factor of about 1100, is the **cosmic microwave background (CMB)**. It is a nearly perfect **blackbody** at 2.7255 K, discovered accidentally by Arno Penzias and Robert Wilson in 1965. It is the oldest light we can see."},
      {"kind":"p","text":"**Going deeper on the CMB.** The CMB's temperature **anisotropies** are about 1 part in 100,000. They are mapped by COBE, WMAP, Planck, ACT, and SPT, and they are cosmology's richest dataset."},
      {"kind":"p","text":"Before decoupling, gravity (dominated by dark matter) pulled the photon–baryon fluid into potential wells, while photon pressure pushed back. This produced sound waves: **acoustic oscillations**. Their snapshot at decoupling appears in the **angular power spectrum** as a series of **acoustic peaks**:"},
      {"kind":"list","items":["The first peak, at about 1°, measures spatial curvature and confirms flatness.","The ratio of the odd and even peaks measures baryon density.","The overall pattern measures dark matter density and much more."]},
      {"kind":"p","text":"The six-parameter ΛCDM fit to this spectrum is one of the great quantitative triumphs of science."},
      {"kind":"p","text":"CMB **polarization** also carries information:"},
      {"kind":"list","items":["**E-modes** arise from scalar density perturbations.","**B-modes** arise from gravitational lensing and, potentially, primordial gravitational waves."]},
      {"kind":"p","text":"Secondary effects add further information. **CMB lensing** probes intervening mass. The **Sunyaev–Zel'dovich effect** occurs when hot cluster gas scatters CMB photons to higher energies. The **integrated Sachs–Wolfe effect** arises when photons cross evolving potential wells, which is a probe of dark energy."},
      {"kind":"p","text":"**The dark ages and cosmic dawn.** After recombination came the **cosmic dark ages**: neutral hydrogen and no stars."},
      {"kind":"p","text":"Within roughly 100–200 million years, gas collapsing inside dark matter **halos** ignited the first stars, known as **Population III** stars. They were probably massive and metal-free, and none has yet been confirmed directly. This was **cosmic dawn**."},
      {"kind":"p","text":"Ultraviolet light from the first stars and galaxies gradually re-ionized the intergalactic hydrogen. This was the **epoch of reionization**, roughly z ≈ 15 to 6, with its midpoint near z ≈ 7–8. The 21-cm line of neutral hydrogen is the key future probe of this era."},
      {"kind":"p","text":"The **James Webb Space Telescope (JWST)** is now finding surprisingly bright, massive, and mature galaxies within the first 300–500 million years. It has also found unexpectedly abundant early **supermassive black holes** and compact red sources nicknamed \"little red dots.\" These findings are pressing on galaxy formation models, though not, on current evidence, on ΛCDM itself."},
      {"kind":"p","text":"**The present.** Around 9 billion years after the Big Bang, the Sun formed, about 4.6 billion years ago. Around the same epoch, dark energy began to dominate the expansion. Today, 13.8 billion years after the Big Bang, galaxy formation is winding down. The peak of cosmic star formation, \"**cosmic noon**,\" was about 10 billion years ago (z ≈ 2)."},
    ],
  },
  {
    heading: "6. How Structure Forms",
    blocks: [
      {"kind":"p","text":"The early universe was smooth to 1 part in 100,000. The present universe is lumpy on every scale. The link is **gravitational instability**: slightly overdense regions attract more matter, becoming denser still."},
      {"kind":"p","text":"In ΛCDM, structure forms **hierarchically**, or \"bottom-up.\" Small dark matter halos form first, then merge into ever-larger ones. Gas cools and sinks into halos, forming galaxies at their centres. Massive clusters are the youngest bound structures."},
      {"kind":"p","text":"**Going deeper.** Perturbations are described by the **density contrast** δ = (ρ − ρ̄)/ρ̄. They are characterized statistically by the **matter power spectrum P(k)** and its amplitude parameter **σ₈** (or S₈). While δ ≪ 1, perturbations grow linearly (δ ∝ a in the matter era). Growth is suppressed during radiation domination (the **Mészáros effect**) and during dark energy domination."},
      {"kind":"p","text":"The **Jeans instability** criterion determines which scales can collapse against pressure. Nonlinear collapse is modelled analytically with **spherical collapse** (a halo virializes at about 200 times the background density) and **Press–Schechter**-type **halo mass functions**. It is modelled numerically with **N-body** and **hydrodynamical simulations** such as Millennium, IllustrisTNG, EAGLE, and FLAMINGO."},
      {"kind":"p","text":"The acoustic oscillations seen in the CMB also left a faint imprint on the distribution of galaxies. This is the **baryon acoustic oscillation (BAO)** scale of about 150 comoving Mpc, which serves as a **standard ruler** for measuring the expansion history."},
      {"kind":"p","text":"**Redshift-space distortions** (galaxy peculiar velocities) measure the growth rate of structure and so test gravity itself."},
      {"kind":"p","text":"Galaxy formation depends heavily on **feedback**: supernovae and active black holes inject energy that regulates star formation. The ratio of stellar mass to halo mass peaks near Milky Way-sized halos, and even there only about 20% of the available baryons become stars."},
    ],
  },
  {
    heading: "7. Stars: The Engines of Cosmic Chemistry",
    blocks: [
      {"kind":"p","text":"**Birth.** Stars form in cold, dense **molecular clouds**. They are often triggered by shock waves or spiral density waves. A collapsing core becomes a **protostar**, often surrounded by a **protoplanetary disk**, the birthplace of planets."},
      {"kind":"p","text":"A star is a balance between gravity pulling inward and pressure pushing outward. This is **hydrostatic equilibrium**. When the core reaches about 10 million K, **nuclear fusion** begins: hydrogen fuses into helium, converting about 0.7% of the mass into energy (E = mc²). The star has entered the **main sequence**, where it spends about 90% of its life."},
      {"kind":"p","text":"**Going deeper on fusion.** Sun-like and smaller stars fuse hydrogen mainly via the **proton–proton chain**. More massive stars use the **CNO cycle**, in which carbon, nitrogen, and oxygen act as catalysts. Fusion at solar core temperatures is only possible through **quantum tunnelling** through the Coulomb barrier, described by the **Gamow peak**."},
      {"kind":"p","text":"Energy escapes the core through **radiative transport** and **convection**. It takes a photon tens of thousands to hundreds of thousands of years to random-walk out of the Sun."},
      {"kind":"p","text":"Main-sequence lifetime scales steeply with mass, roughly t ∝ M^(−2.5):"},
      {"kind":"list","items":["The Sun lasts about 10 billion years.","A 20-solar-mass star lasts about 10 million years.","A red dwarf can last trillions of years, longer than the current age of the universe."]},
      {"kind":"p","text":"**Classifying stars.** The **Hertzsprung–Russell (HR) diagram** plots **luminosity** (intrinsic power output) against surface temperature. It is the periodic table of stellar astrophysics. Stars appear in distinct regions: the main sequence, **giants**, **supergiants**, and **white dwarfs**."},
      {"kind":"p","text":"Stars are classified by spectral type, from hot to cool: **O, B, A, F, G, K, M**. The Sun is a G2 star."},
      {"kind":"p","text":"Brightness is measured in **magnitudes**, a logarithmic and inverted scale in which smaller numbers mean brighter:"},
      {"kind":"list","items":["**Apparent magnitude** is how bright a star looks from Earth.","**Absolute magnitude** is how bright it would look from 10 parsecs."]},
      {"kind":"p","text":"Astronomers call every element heavier than helium a \"**metal**.\" **Metallicity** records a star's generation: **Population I** stars (like the Sun) are young and metal-rich, while **Population II** stars are old and metal-poor."},
      {"kind":"p","text":"**Death: it depends on mass.**"},
      {"kind":"list","items":["**Low- and intermediate-mass stars** (below about 8 solar masses) swell into **red giants** when core hydrogen runs out. They fuse helium into carbon and oxygen, then puff off their outer layers as a glowing **planetary nebula**. This is another misnomer, unrelated to planets. The exposed core is a **white dwarf**: an Earth-sized ember supported by **electron degeneracy pressure**, a quantum effect arising from the Pauli exclusion principle. White dwarfs cannot exceed the **Chandrasekhar limit** of about 1.4 solar masses."]},
      {"kind":"list","items":["**Massive stars** fuse progressively heavier elements in onion-like shells, up to iron. Fusing iron consumes energy rather than releasing it, so the iron core collapses in under a second. This triggers a **core-collapse supernova** (Type II, Ib, or Ic), briefly outshining an entire galaxy. The remnant is either a **neutron star** or a **black hole**."]},
      {"kind":"list","items":["**Neutron stars** are city-sized objects, about 20 km across, with more mass than the Sun. A teaspoon of their material weighs about a billion tonnes. They are supported by **neutron degeneracy pressure** and nuclear forces, up to the **Tolman–Oppenheimer–Volkoff limit** of about 2–2.3 solar masses. Rotating neutron stars with beamed radiation are **pulsars**, some rotating hundreds of times per second with clock-like precision. **Magnetars** carry magnetic fields up to about 10¹⁵ gauss."]},
      {"kind":"list","items":["**Type Ia supernovae** are thermonuclear explosions of white dwarfs in binary systems, triggered near the Chandrasekhar limit. Their fairly uniform (and calibratable) peak brightness makes them **standard candles**, the tool that revealed cosmic acceleration."]},
      {"kind":"p","text":"**Stellar nucleosynthesis: \"we are star stuff.\"** Stars forged the carbon in your cells, the oxygen you breathe, and the calcium in your bones. Nuclei heavier than iron are built by neutron capture:"},
      {"kind":"list","items":["The **s-process** (slow neutron capture) occurs in aging giant stars.","The **r-process** (rapid neutron capture) occurs in extreme events. **Neutron star mergers**, whose explosions are called **kilonovae**, were confirmed as a major r-process site in 2017. Much of the universe's gold and platinum was likely made this way."]},
    ],
  },
  {
    heading: "8. Black Holes",
    blocks: [
      {"kind":"p","text":"A **black hole** is a region where spacetime is so curved that nothing, not even light, can escape. Its boundary is the **event horizon**. For a non-rotating black hole, the horizon lies at the **Schwarzschild radius** r_s = 2GM/c², about 3 km per solar mass. Crossing the horizon is locally unremarkable for a large black hole, but it is a one-way trip."},
      {"kind":"p","text":"Black holes come in several classes:"},
      {"kind":"list","items":["**Stellar-mass black holes**, a few to about 100 solar masses, are the remnants of massive stars or of mergers.","**Intermediate-mass black holes**, hundreds to hundreds of thousands of solar masses, are elusive but increasingly evidenced.","**Supermassive black holes**, millions to billions of solar masses, sit at the centres of most large galaxies. The Milky Way's, **Sagittarius A\\***, has about 4.3 million solar masses. Its existence was established by decades of tracking stellar orbits (Nobel Prize 2020). The **Event Horizon Telescope** imaged the shadows of M87\\* (2019) and Sgr A\\* (2022)."]},
      {"kind":"p","text":"Matter falling into a black hole forms a hot, luminous **accretion disk**. Accretion is the most efficient energy source known, converting up to tens of percent of rest mass to radiation, compared with 0.7% for fusion. Actively feeding supermassive black holes are **active galactic nuclei (AGN)**. The most luminous are **quasars**, which can outshine their host galaxies a thousandfold and often launch **relativistic jets**."},
      {"kind":"p","text":"**Going deeper.** Realistic astrophysical black holes rotate and are described by the **Kerr metric**. Outside the horizon of a rotating hole lies the **ergosphere**, where spacetime is dragged so strongly that nothing can remain stationary. Rotational energy can be extracted there through the **Penrose process** and, magnetically, through the **Blandford–Znajek mechanism**, which likely powers jets."},
      {"kind":"p","text":"Key features of black hole physics:"},
      {"kind":"list","items":["**The no-hair theorem.** Classically, black holes are characterized only by mass, spin, and charge.","**The ISCO.** The **innermost stable circular orbit** sets the inner edge of the accretion disk and the efficiency of accretion.","**The singularity.** It is hidden behind the horizon, per the unproven **cosmic censorship conjecture**. It signals the breakdown of GR.","**Hawking radiation.** In 1974, Stephen Hawking showed that quantum effects make black holes radiate thermally, with a temperature of about 6 × 10⁻⁸ K × (M_sun/M). Isolated black holes therefore slowly evaporate, over roughly 10⁶⁷ years for a solar-mass black hole. That is unobservably cold, but conceptually seismic.","**Black hole entropy.** Black holes have **Bekenstein–Hawking entropy** S = k_B c³A/(4Għ), proportional to horizon *area* rather than volume. This inspired the **holographic principle**.","**The information paradox.** If evaporation is exactly thermal, information about what fell in is destroyed, violating quantum unitarity. This is the **black hole information paradox**. Recent work on the **Page curve**, **quantum extremal surfaces**, and \"**islands**\" suggests information is preserved, though the mechanism is debated. The related **firewall** paradox remains a live controversy."]},
    ],
  },
  {
    heading: "9. Galaxies",
    blocks: [
      {"kind":"p","text":"Galaxies come in several main types, organized historically by the **Hubble sequence**:"},
      {"kind":"list","items":["**Spiral galaxies**, like the Milky Way, have rotating disks, spiral arms, and ongoing star formation. Many, including ours, have a central **bar**.","**Elliptical galaxies** are smooth, reddish, gas-poor, and dominated by old stars on random orbits. The largest giant ellipticals sit at cluster centres.","**Lenticular galaxies** are intermediate: disks without prominent arms.","**Irregular** and **dwarf galaxies** are the most numerous type. The **Large and Small Magellanic Clouds**, satellites of the Milky Way, are examples."]},
      {"kind":"p","text":"Galaxies also split into a star-forming \"**blue cloud**\" and a quenched \"**red sequence**,\" with a sparsely populated \"**green valley**\" of transitioning systems between them. **Quenching**, the shutdown of star formation, is driven by processes such as AGN feedback and environmental stripping."},
      {"kind":"p","text":"**The Milky Way.** Our galaxy is a barred spiral about 100,000 light-years across, containing 100–400 billion stars. The Sun sits about 26,000 light-years from the centre and orbits it every 230 million years or so."},
      {"kind":"p","text":"The Milky Way has four main components:"},
      {"kind":"list","items":["A thin disk.","A thick disk.","A central **bulge**.","A sparse **stellar halo**."]},
      {"kind":"p","text":"All of these are embedded in a much larger dark matter halo. The **Gaia** mission has revealed that the Milky Way grew by cannibalizing smaller galaxies, notably the **Gaia–Enceladus/Sausage** merger roughly 8–11 billion years ago. This field is called **galactic archaeology**."},
      {"kind":"p","text":"Andromeda approaches at about 110 km/s. The traditional prediction was a merger in about 4.5 billion years, but recent analyses using Gaia and Hubble data put the odds of a merger within 10 billion years at only about 50%."},
      {"kind":"p","text":"**Clusters.** Galaxy clusters are the largest gravitationally bound objects, reaching about 10¹⁵ solar masses. Most of their baryons are not in galaxies but in the **intracluster medium**: gas at 10–100 million K that glows in X-rays."},
      {"kind":"p","text":"**Going deeper.** Galaxies obey tight **scaling relations**, which constrain formation models:"},
      {"kind":"list","items":["The **Tully–Fisher relation** links luminosity (or baryonic mass) to rotation speed in spirals.","The **Faber–Jackson relation** and the **fundamental plane** apply to ellipticals.","The **M–σ relation** links the mass of the central black hole to the velocity dispersion of the bulge. It is evidence that black holes and galaxies **co-evolve**."]},
      {"kind":"p","text":"Clusters are also cosmological probes. Their abundance as a function of mass and redshift is sensitive to σ₈ and dark energy. Their masses can be measured by lensing, X-rays, the Sunyaev–Zel'dovich effect, and galaxy dynamics."},
    ],
  },
  {
    heading: "10. How We Know: Messengers and Methods",
    blocks: [
      {"kind":"p","text":"**Light across the electromagnetic spectrum.** Each band of the spectrum reveals different physics:"},
      {"kind":"list","items":["**Radio** shows cold gas, pulsars, and jets.","**Microwave** shows the CMB.","**Infrared** shows dust, star formation, and high-redshift galaxies.","**Optical** shows stars.","**Ultraviolet** shows hot young stars.","**X-ray** shows hot gas and accretion.","**Gamma-ray** shows the most violent events, such as **gamma-ray bursts**."]},
      {"kind":"p","text":"**Spectroscopy** is arguably astronomy's most powerful tool. It splits light into its component wavelengths, revealing an object's chemical composition, temperature, density, velocity, and redshift from its **emission lines** and **absorption lines**."},
      {"kind":"p","text":"**The cosmic distance ladder.** Distances are measured in overlapping steps, each calibrating the next:"},
      {"kind":"list","ordered":true,"items":["**Parallax**: the apparent shift of nearby stars as Earth orbits the Sun. Gaia measures this for more than a billion stars.","**Standard candles** of known luminosity: **Cepheid variables**, whose pulsation period predicts luminosity (Henrietta Leavitt's law), and the **tip of the red giant branch**.","**Type Ia supernovae** for cosmological distances."]},
      {"kind":"p","text":"Independent routes include:"},
      {"kind":"list","items":["**Strong-lensing time delays**.","**Megamasers**.","**Gravitational-wave \"standard sirens,\"** whose waveforms encode their distance directly."]},
      {"kind":"p","text":"**Gravitational lensing.** Mass bends light, a GR prediction first confirmed in 1919. Lensing comes in three regimes:"},
      {"kind":"list","items":["**Strong lensing** produces arcs, multiple images, and **Einstein rings**.","**Weak lensing** produces subtle statistical distortions of galaxy shapes. This is **cosmic shear**, which maps dark matter on large scales.","**Microlensing** produces the temporary brightening of a background star. It is used to find exoplanets and to constrain compact dark matter."]},
      {"kind":"p","text":"Massive clusters also act as natural telescopes, magnifying the most distant galaxies."},
      {"kind":"p","text":"**Gravitational waves.** Accelerating masses create ripples in spacetime, predicted by Einstein in 1916. In 2015, **LIGO** detected the waves from two merging black holes about 1.3 billion light-years away. The signal was a characteristic rising \"**chirp**\" that stretched the 4-km detector arms by less than a thousandth of a proton's width. This earned the 2017 Nobel Prize."},
      {"kind":"p","text":"Hundreds of mergers have since been catalogued by LIGO, **Virgo**, and **KAGRA**. In 2023, **pulsar timing arrays** such as NANOGrav reported evidence for a low-frequency **gravitational-wave background**, likely from supermassive black hole binaries. The space-based detector **LISA** is planned for the 2030s."},
      {"kind":"p","text":"**Multi-messenger astronomy.** In 2017, the neutron star merger **GW170817** was seen in gravitational waves, gamma rays, and across the electromagnetic spectrum. This single event:"},
      {"kind":"list","items":["Confirmed kilonovae as an r-process site.","Showed that gravitational waves travel at light speed to about 1 part in 10¹⁵, eliminating many modified-gravity theories.","Gave an independent measurement of H₀."]},
      {"kind":"p","text":"**Neutrinos** (from supernova 1987A, the Sun, and IceCube's high-energy events) and **cosmic rays** complete the set of cosmic messengers."},
    ],
  },
  {
    heading: "11. Planets and Life",
    blocks: [
      {"kind":"p","text":"Since 1995, more than 5,000 **exoplanets** have been confirmed. They are found by several methods:"},
      {"kind":"list","items":["**Transits**: the dimming of a star as a planet crosses in front of it (Kepler, TESS).","**Radial velocity**: the star's wobble, detected through Doppler shifts.","**Microlensing**.","**Direct imaging**."]},
      {"kind":"p","text":"The census includes types absent from our Solar System, such as **hot Jupiters** and **super-Earths** or **sub-Neptunes**. The **habitable zone** is the orbital range where liquid water could exist on a planet's surface. JWST now analyses exoplanet atmospheres through **transmission spectroscopy**, searching for **biosignatures**. Claims so far remain unconfirmed and contested."},
      {"kind":"p","text":"The **Drake equation** frames the estimation of how many communicating civilizations might exist. The **Fermi paradox** asks why, given the universe's size and age, we see no evidence of any. Proposed answers range from rare-Earth reasoning to a \"**Great Filter**.\" This remains one of the deepest open questions, and it sits at the boundary of astrophysics, biology, and philosophy."},
    ],
  },
  {
    heading: "12. The Fate of the Universe",
    blocks: [
      {"kind":"p","text":"The universe's future depends on dark energy."},
      {"kind":"p","text":"**If dark energy is a true cosmological constant,** expansion accelerates forever. Galaxies beyond the Local Group will redshift beyond the cosmic event horizon, in roughly 100 billion years. Future astronomers in a merged \"Milkomeda\" galaxy would see no evidence of cosmic expansion or the CMB."},
      {"kind":"p","text":"Star formation ends in about 10¹⁴ years. The **degenerate era** follows, an era of white dwarfs, neutron stars, and black holes. If protons decay, as many GUTs predict (lifetime above 10³⁴ years), ordinary matter eventually dissolves."},
      {"kind":"p","text":"Black holes evaporate by roughly 10¹⁰⁰ years. What remains is a cold, dilute, near-maximum-entropy state: the **heat death**, or **Big Freeze**. Even then, de Sitter space retains a faint **horizon temperature** of about 10⁻³⁰ K."},
      {"kind":"p","text":"**Other possibilities:**"},
      {"kind":"list","items":["**Big Rip.** If w < −1 (\"**phantom energy**\"), dark energy's density grows. It tears apart clusters, galaxies, planets, and finally atoms in finite time.","**Big Crunch.** If dark energy weakens and turns negative, recollapse is possible. The DESI hints of evolving dark energy have revived interest in this scenario.","**Vacuum decay.** The measured Higgs and top quark masses suggest our electroweak vacuum may be **metastable**. A bubble of \"true vacuum\" could nucleate by quantum tunnelling and expand at nearly light speed, rewriting physics. The expected timescale vastly exceeds 10¹⁰⁰ years.","**Cyclic models.** Proposals such as Roger Penrose's **conformal cyclic cosmology** or ekpyrotic cycles posit repeated aeons. They remain speculative and are observationally disputed."]},
    ],
  },
  {
    heading: "13. The Frontier: Open Questions",
    blocks: [
      {"kind":"p","text":"**Quantum gravity.** GR and quantum mechanics are each superbly confirmed but mutually incompatible at the Planck scale (about 1.6 × 10⁻³⁵ m). Leading approaches include:"},
      {"kind":"list","items":["**String theory**: fundamental strings, extra dimensions, and a vast \"**landscape**\" of perhaps 10⁵⁰⁰ vacua.","**Loop quantum gravity**: quantized spacetime geometry, and in cosmology, a \"**Big Bounce**\" replacing the singularity.","**Asymptotic safety**.","**Causal dynamical triangulations** and **causal sets**."]},
      {"kind":"p","text":"The **AdS/CFT correspondence** is a concrete realization of holography. It shows that a gravitational theory in a volume can be exactly equivalent to a non-gravitational quantum theory on its boundary. It has led to the striking proposal that **spacetime emerges from quantum entanglement**, sometimes summarized as \"ER = EPR.\""},
      {"kind":"p","text":"**The origin question.** What, if anything, came \"before\" the Big Bang? Was there a beginning? Proposals include:"},
      {"kind":"list","items":["The Hartle–Hawking **no-boundary proposal**.","Vilenkin's **tunnelling from nothing**.","Bouncing cosmologies.","Eternal inflation."]},
      {"kind":"p","text":"No proposal is observationally established. Theorems such as Borde–Guth–Vilenkin suggest that inflating spacetimes are past-incomplete, although their interpretation is debated."},
      {"kind":"p","text":"**The arrow of time.** The **second law of thermodynamics** says entropy increases. This requires the early universe to have had extraordinarily *low* entropy. Although the early universe's matter was near thermal equilibrium, its *gravitational* degrees of freedom were exceedingly smooth, a highly improbable state. Why the universe began this way is the \"**past hypothesis**.\" Penrose estimated the improbability as 1 in 10^(10¹²³)."},
      {"kind":"p","text":"**Fine-tuning and the anthropic principle.** Several constants appear tuned for complexity: the cosmological constant, the Higgs mass (the **hierarchy problem**), and the strength of the strong force. Responses include:"},
      {"kind":"list","items":["Deeper laws not yet discovered.","The **anthropic principle**: observers necessarily find themselves in life-permitting regions of a possible multiverse.","The view that the question is ill-posed."]},
      {"kind":"p","text":"Whether multiverse explanations are testable science is itself contested."},
      {"kind":"p","text":"**The standing empirical puzzles:**"},
      {"kind":"list","items":["What is dark matter?","What is dark energy, and does it evolve?","What resolves the Hubble tension?","What are the neutrino masses? Cosmology now caps their sum below about 0.07–0.12 eV, which is itself creating tension with oscillation experiments.","Did inflation happen, and what was the inflaton?","Why is there matter rather than antimatter?","How did supermassive black holes grow so fast?","Is ΛCDM the final word or a very good effective description?"]},
    ],
  },
  {
    heading: "Quick Reference: The Universe in Numbers",
    blocks: [
      {"kind":"list","items":["**Age:** 13.79 billion years","**Hubble constant:** 67–73 km/s/Mpc (in tension)","**Composition:** about 68% dark energy, 27% dark matter, 5% baryons; radiation about 0.01% today","**Spatial curvature:** flat to within about 0.5%","**CMB temperature:** 2.7255 K; last scattering at z ≈ 1100, about 380,000 years after the Big Bang","**Primordial helium mass fraction:** about 24.5%","**Radius of the observable universe:** about 46.5 billion light-years (comoving)","**Number of galaxies in the observable universe:** roughly hundreds of billions to about 2 trillion, depending on how faint dwarfs are counted","**Scalar spectral index:** n_s ≈ 0.965; tensor-to-scalar ratio r < 0.036","**Dark energy equation of state:** w ≈ −1, with hints of evolution","**Planck time:** 5.4 × 10⁻⁴⁴ s; **Planck length:** 1.6 × 10⁻³⁵ m"]},
    ],
  },
  {
    heading: "A Closing Thought",
    blocks: [
      {"kind":"p","text":"The deepest lesson of modern cosmology may be how much a few principles explain: general relativity, quantum mechanics, the Standard Model of particle physics, and the cosmological principle. From these, plus six measured parameters, one can compute the pattern of spots in the oldest light, the helium in a distant cloud, and the web of galaxies spanning billions of light-years."},
      {"kind":"p","text":"The second lesson is humility. About 95% of the cosmos consists of things we can name but not explain."},
    ],
  },
];;
