import type { LessonSection } from "../curriculum";

export const sections: readonly LessonSection[] = [
  {
    heading: null,
    blocks: [
      {"kind":"p","text":"Zero Trust is best understood not as a product you buy but as a change in the default assumption a security system makes about any request it receives. For most of computing's history, networks were built like medieval cities: a hard wall at the edge, a gate with guards, and relative freedom of movement once you were inside. This is the *perimeter model*, and its implicit rule was \"trust by location.\" If a packet came from an internal IP address, it was presumed friendly. Zero Trust inverts that rule. Its founding slogan, coined by John Kindervag at Forrester in 2010, is \"never trust, always verify,\" which in practice means that no request is granted access merely because of where it originates, what network it sits on, or what it was allowed to do a moment ago. Every access decision is made freshly, on evidence, and as narrowly as possible."},
      {"kind":"p","text":"The reason this shift became necessary is historical and architectural at once. The perimeter dissolved: employees work from home, data lives in multiple clouds, partners connect through APIs, and the device touching your database may be a personal phone. Simultaneously, attackers learned that the easiest path into a hardened network is through a trusted insider's credentials, after which they move laterally from a low-value foothold to a high-value target. The perimeter model offered almost no resistance to that second phase. Zero Trust is, at its heart, a design philosophy for making lateral movement expensive."},
    ],
  },
  {
    heading: "The Vocabulary of Trust Decisions",
    blocks: [
      {"kind":"p","text":"To talk about Zero Trust precisely, you need a small set of terms that recur in every framework, most canonically in NIST Special Publication 800-207, which is the closest thing the field has to a shared grammar."},
      {"kind":"p","text":"A *subject* is the entity requesting access: a human user, a service account, a workload, a device acting on its own. A *resource* is the thing being accessed: an application, a file, an API endpoint, a database row. Zero Trust deliberately speaks of \"resources\" rather than \"networks,\" because the unit of protection is the asset, not the segment it lives in."},
      {"kind":"p","text":"The *Policy Decision Point* (PDP) is the logical brain that evaluates whether a given subject may access a given resource under current conditions. NIST splits this further into a *Policy Engine*, which computes the decision, and a *Policy Administrator*, which translates that decision into the configuration that actually opens or closes a path. The *Policy Enforcement Point* (PEP) is the gatekeeper that sits in the data path and does what the PDP tells it. The PEP might be a reverse proxy, an identity-aware gateway, a host-based agent, a service mesh sidecar, or a firewall rule. The architectural insight is the separation of these roles: enforcement is distributed everywhere, but decision-making is centralized and informed by many signals."},
      {"kind":"p","text":"Those signals come from what NIST calls the *control plane* feeding the PDP: identity providers, device management systems, threat intelligence feeds, security information and event management (SIEM) systems, data classification tags, and activity logs. The *data plane* is where actual traffic flows between subject and resource once a PEP permits it. Keeping these planes distinct is what allows policy to be rich and context-aware without slowing the traffic itself."},
    ],
  },
  {
    heading: "Identity as the New Perimeter",
    blocks: [
      {"kind":"p","text":"If location no longer confers trust, something must. In Zero Trust, the primary anchor is *identity*, which is why the phrase \"identity is the new perimeter\" became a cliché almost as soon as it was uttered. Identity here is broader than a username. It encompasses *authentication* (proving you are who you claim), *authorization* (determining what that proven identity may do), and increasingly *continuous authentication*, where confidence in the identity is reassessed throughout a session rather than only at login."},
      {"kind":"p","text":"*Multi-factor authentication* (MFA) is the entry-level control, but the field has moved toward *phishing-resistant* MFA, meaning methods such as FIDO2/WebAuthn hardware keys and passkeys that bind the credential cryptographically to the legitimate origin so a fake login page cannot harvest it. Push-notification MFA, by contrast, has proven vulnerable to \"MFA fatigue\" attacks where users are bombarded until they approve one out of exasperation, so mature Zero Trust programs treat the *strength* of the factor as a policy input, not a checkbox."},
      {"kind":"p","text":"Beneath human identity lies *workload identity* and *machine identity*. Services calling other services need credentials too, and here the modern answer is short-lived, automatically rotated, cryptographically verifiable identities rather than static API keys buried in configuration files. The SPIFFE/SPIRE standard, for instance, issues each workload an X.509 SVID (SPIFFE Verifiable Identity Document) tied to attestable properties of where and how it runs, so that a service can prove \"I am the billing service running in this cluster, launched from this signed image\" rather than merely \"I possess this secret.\""},
    ],
  },
  {
    heading: "Device Posture and the Idea of Health",
    blocks: [
      {"kind":"p","text":"A verified user on a compromised laptop is still a compromised request. Zero Trust therefore treats the *device* as a first-class subject whose *posture* is evaluated: is the disk encrypted, is the operating system patched, is endpoint detection running, is the device enrolled in management, has it been jailbroken, when did it last check in. This information is gathered by *Mobile Device Management* (MDM), *Endpoint Detection and Response* (EDR), or lighter-weight agents, and surfaced to the PDP as attributes. A policy might then say that finance applications are reachable only from managed, compliant devices, while a webmail interface tolerates a wider range."},
      {"kind":"p","text":"At the advanced end, posture becomes *attestation*: using a hardware root of trust such as a Trusted Platform Module (TPM) to produce a signed measurement of the boot chain, so the device can prove cryptographically that it booted untampered firmware and an unmodified kernel. This is a meaningful step up, because self-reported posture from a compromised host is exactly what an attacker would falsify. *Remote attestation* closes that gap by anchoring the claim in silicon."},
    ],
  },
  {
    heading: "Context, Risk, and Adaptive Access",
    blocks: [
      {"kind":"p","text":"The real power of Zero Trust emerges when identity and device signals are combined with *context*: time of day, geolocation, impossible travel (a login from Tokyo ten minutes after one from Toronto), the sensitivity of the data, the behavior of the session so far. This is *risk-based* or *adaptive* access control. Rather than a binary allow/deny, the PDP computes a *confidence level* or *risk score* and selects a response proportionate to it: allow silently, allow but require step-up authentication, allow read-only, allow but record the session, or deny and alert."},
      {"kind":"p","text":"The models that formalize this are *Attribute-Based Access Control* (ABAC), which expresses policy as predicates over attributes of subject, resource, action, and environment, and its more expressive cousin *Policy-Based Access Control*. These supersede classic *Role-Based Access Control* (RBAC), not by abolishing roles but by treating role as one attribute among many. The practical consequence is that policy becomes code, authored in languages such as Rego (used by Open Policy Agent) or Cedar, version-controlled, tested, and auditable. A PhD-level observation here is that this converts security from a configuration problem into a software-engineering problem, with all the benefits and all the discipline that implies."},
      {"kind":"p","text":"The principle of *least privilege* is the normative goal all this machinery serves: a subject should hold exactly the permissions its current task requires and no more. *Just-in-Time* (JIT) access operationalizes this by granting elevated rights only for a bounded window upon request and approval, and *Just-Enough-Access* narrows the scope of what is granted. *Privileged Access Management* (PAM) systems broker these elevations, vault the credentials, and record what was done with them. The aspiration, sometimes called *zero standing privileges*, is that nobody permanently holds administrative power; it is checked out, used, and returned."},
    ],
  },
  {
    heading: "Segmentation and the Containment of Blast Radius",
    blocks: [
      {"kind":"p","text":"The network does not disappear in Zero Trust; it is simply demoted from a trust boundary to one enforcement surface among several. *Microsegmentation* is the practice of dividing the environment into very small zones, often down to the individual workload, with explicit policy governing which may talk to which on what ports. Where a traditional network might have a flat internal subnet where any server could reach any other, a microsegmented one has a *default-deny* posture everywhere: if a flow is not explicitly permitted, it is dropped. This is what makes lateral movement expensive. An attacker who compromises a web server discovers it can reach only the specific application server it legitimately needs, on the one port it uses, and nothing else."},
      {"kind":"p","text":"The relevant metric is *blast radius*: the extent of damage a single compromised component can cause. Zero Trust is, measured this way, a program for minimizing blast radius, and the assumption that drives it is *assume breach*, the posture of designing every control as though an adversary is already inside. This is the second of the field's three canonical maxims, alongside \"verify explicitly\" and \"use least privilege.\""},
      {"kind":"p","text":"Segmentation is implemented through several mechanisms. Host-based firewalls and agents enforce it at the endpoint. *Software-Defined Perimeters* (SDP), descending from the Defense Information Systems Agency's work, make resources invisible until a subject has authenticated to a controller, a pattern sometimes called *dark cloud* or *single-packet authorization*, where the server does not even respond to unauthenticated probes. In cloud-native systems, a *service mesh* such as Istio or Linkerd injects a sidecar proxy beside each workload, establishing *mutual TLS* (mTLS) between every pair of services so each connection is both encrypted and authenticated in both directions, with the mesh's control plane distributing identity-based authorization policies."},
    ],
  },
  {
    heading: "Zero Trust Network Access and the Death of the VPN",
    blocks: [
      {"kind":"p","text":"The most visible consumer-facing form of Zero Trust is *Zero Trust Network Access* (ZTNA), the technology that replaces the traditional VPN. A VPN, once connected, typically places the remote device on the internal network as though it were physically present, which is precisely the location-based trust Zero Trust rejects. ZTNA instead brokers access per application: the user authenticates to an identity-aware proxy, device posture is checked, policy is evaluated, and if permitted a connection is established to that single application only. The user never gets a network address inside the data center and never sees applications they are not authorized for. Google's BeyondCorp, the first large-scale public implementation, demonstrated that an entire enterprise could operate this way with employees working from untrusted networks indefinitely, and it is the lineage from which most commercial ZTNA products descend."},
      {"kind":"p","text":"ZTNA is frequently bundled with secure web gateways, cloud access security brokers (CASB), and data loss prevention into what Gartner termed *Secure Access Service Edge* (SASE, pronounced \"sassy\") when combined with SD-WAN networking, or *Security Service Edge* (SSE) when the networking piece is omitted. These terms are marketing taxonomies more than architectural ones, but they describe a real convergence: enforcement points moving from on-premises appliances to globally distributed cloud points of presence through which all traffic is routed."},
    ],
  },
  {
    heading: "Data-Centric Zero Trust",
    blocks: [
      {"kind":"p","text":"A sophisticated Zero Trust program eventually recognizes that the ultimate resource is data, and that network and application controls are proxies for protecting it. *Data classification* assigns sensitivity labels, *data discovery* finds where regulated or valuable data actually resides (usually in more places than anyone expected), and these labels become attributes the PDP can reason about. *Encryption at rest and in transit* is table stakes, but Zero Trust pushes toward *encryption in use* via confidential computing, where data is processed inside hardware-isolated enclaves (Intel SGX, AMD SEV, ARM CCA) such that even the cloud operator or a compromised hypervisor cannot read it. *Rights management* and *tokenization* extend protection to the data object itself so that exfiltration yields ciphertext. The theoretical endpoint is that trust decisions attach to data wherever it travels, independent of the system holding it."},
    ],
  },
  {
    heading: "Visibility, Analytics, and the Feedback Loop",
    blocks: [
      {"kind":"p","text":"Zero Trust is sometimes described as a verb rather than a noun, and the reason is that policy must be continuously tuned against observed reality. *Telemetry* from every PEP, every authentication, every denied flow, feeds analytics systems. *User and Entity Behavior Analytics* (UEBA) builds baselines of normal activity and flags deviations, which in turn adjust risk scores in near real time. *Extended Detection and Response* (XDR) correlates signals across endpoints, identities, email, and cloud. The feedback loop closes when a detection automatically triggers a policy change: a user whose account shows signs of compromise is forced to re-authenticate, has sessions revoked, or is quarantined to a restricted policy tier without a human touching a console. This is what makes authentication *continuous* rather than episodic, and it is where Zero Trust most clearly departs from static access control."},
    ],
  },
  {
    heading: "Maturity, Governance, and the Hard Parts",
    blocks: [
      {"kind":"p","text":"Because Zero Trust is a journey rather than a destination, several maturity models exist to chart it. The U.S. Cybersecurity and Infrastructure Security Agency's Zero Trust Maturity Model defines five pillars (Identity, Devices, Networks, Applications and Workloads, Data) spanned by three cross-cutting capabilities (Visibility and Analytics, Automation and Orchestration, Governance), and grades each from Traditional through Initial and Advanced to Optimal. The U.S. Department of Defense publishes a parallel model with seven pillars. These exist because organizations need a vocabulary for \"how far along are we,\" and because an Executive Order in 2021 mandated Zero Trust adoption across the U.S. federal government, forcing the abstractions to become auditable commitments."},
      {"kind":"p","text":"The honest difficulties deserve naming. Legacy systems that cannot speak modern identity protocols must be wrapped in proxies or isolated behind compensating controls. Policy sprawl is real: thousands of fine-grained rules can become as unmaintainable as the flat network they replaced, which is why *policy as code* with testing and *intent-based* abstractions matter. Availability becomes coupled to the identity provider and policy engine, so these must be engineered for resilience; a Zero Trust system whose PDP is down is a system where nothing works, and designers must decide deliberately between *fail-closed* (secure but unavailable) and *fail-open* (available but exposed) for each enforcement point. User experience must be protected, because friction drives workarounds, and a workaround is an unmonitored path. And there is a subtle epistemological point that researchers emphasize: Zero Trust does not actually eliminate trust, it relocates and makes explicit the trust you place in your identity provider, your device attestation chain, your policy engine, and the integrity of the signals feeding it. A mature practitioner knows exactly where those trust anchors are, how they could be subverted, and what would happen if they were."},
    ],
  },
  {
    heading: "The Essential Idea",
    blocks: [
      {"kind":"p","text":"Strip away the acronyms and the vendors and Zero Trust reduces to a handful of commitments. Authenticate and authorize every request, every time, using the strongest evidence available. Grant the smallest permission for the shortest duration that accomplishes the task. Assume the adversary is already inside and design so that any single compromise is contained. Observe everything and let what you observe change what you permit. Treat the network as a transport, identity as the anchor, the device as a witness, and data as the thing that actually matters. Everything else, from service meshes to attestation to SASE, is the engineering of those commitments at scale."},
    ],
  },
];;
