import type { ProjectModule } from "../../contracts/project-module";

const raftCluster: ProjectModule = {
  id: "raft-cluster",
  title: "Raft Cluster",
  tag: "distributed systems",
  eyebrow: "live consensus · Rust → WebAssembly",
  description:
    "Live Raft consensus in the browser — crash the leader and watch elections answer.",
  technologies: ["Rust", "WebAssembly", "TypeScript", "Canvas 2D"],
  status: "available",
  accent: "azure",
  presentation: {
    className: "presentation-raft-cluster",
    motion: "network",
    centerLabel: "R / C",
    centerMark: "raft",
    note: "the leader holds quorum",
    motionLabel: "the cluster elects",
    instruction: "crash the leader or cut a link, watch a new term elect",
    parts: [
      {
        id: "quorum-field",
        label: "Quorum field",
        className: "presentation-part-quorum-field",
        anchorX: -6,
        anchorY: -2,
        mark: "contours",
        scatterX: -80,
        scatterY: -40,
        scatterZ: 70,
        baseZ: 12,
        rotation: -4,
      },
      {
        id: "replicated-log",
        label: "Replicated log",
        className: "presentation-part-replicated-log",
        anchorX: -60,
        anchorY: 44,
        mark: "nodes",
        scatterX: -70,
        scatterY: 60,
        scatterZ: 60,
        baseZ: 28,
        rotation: -6,
      },
      {
        id: "current-term",
        label: "Current term",
        className: "presentation-part-current-term",
        anchorX: -72,
        anchorY: -46,
        mark: "type",
        markLabel: "term 4",
        scatterX: -64,
        scatterY: -70,
        scatterZ: 84,
        baseZ: 42,
        rotation: -5,
      },
    ],
  },
  loadPage: () => import("./web/RaftPage"),
};

export default raftCluster;
