import type { ProjectModule } from "../../contracts/project-module";

const codeLayout: ProjectModule = {
  id: "code-layout",
  title: "Code Layout",
  eyebrow: "A source structure tool",
  description: "Paste a source file and get a compact layout of its declarations, dependencies, and architecture for an LLM.",
  technologies: ["React", "TypeScript", "Go"],
  status: "available",
  accent: "blue",
  presentation: {
    className: "presentation-code-layout",
    motion: "network",
    centerLabel: "C / L",
    centerMark: "graph",
    note: "Structure map",
    motionLabel: "connections appear",
    instruction: "Move through the structure and let the relationships become legible.",
    parts: [
      {
        id: "nodes",
        label: "Declaration nodes",
        className: "presentation-part-nodes",
        anchorX: -54,
        anchorY: -18,
        mark: "nodes",
        scatterX: -88,
        scatterY: -38,
        scatterZ: 72,
        baseZ: 18,
        rotation: -7,
      },
      {
        id: "branches",
        label: "Dependency branches",
        className: "presentation-part-branches",
        anchorX: 54,
        anchorY: -10,
        mark: "branches",
        scatterX: 86,
        scatterY: -30,
        scatterZ: 54,
        baseZ: 28,
        rotation: 5,
      },
      {
        id: "source",
        label: "Source block",
        className: "presentation-part-sheet",
        anchorX: 18,
        anchorY: 40,
        mark: "stack",
        scatterX: 20,
        scatterY: 88,
        scatterZ: 92,
        baseZ: 42,
        rotation: -3,
      },
      {
        id: "entry",
        label: "Entry point",
        className: "presentation-part-entry",
        anchorX: -82,
        anchorY: 42,
        mark: "type",
        markLabel: "fn",
        scatterX: -110,
        scatterY: 72,
        scatterZ: 64,
        baseZ: 36,
        rotation: 12,
      },
    ],
  },
  loadPage: () => import("./web/CodeLayoutPage"),
};

export default codeLayout;
